/****** Object:  Table [L0].[L0_MI_COUNTRY_GROUP]    Script Date: 13/10/2025 11:42:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [L0].[L0_MI_COUNTRY_GROUP]
(
	[COUNTRY] [nvarchar](5) NULL,
	[COUNTRYGROUP] [nvarchar](5) NULL,
	[LOAD_TIMESTAMP] [datetime2](7) NULL,
	[CANCELLATION_RATE_COUNTRY_GROUP] [varchar](50) NULL
)
WITH
(
	DISTRIBUTION = REPLICATE,
	HEAP
)
GO


