/****** Object:  Table [L0].[L0_MI_SM_FIX_COST_ESTIMATE]    Script Date: 13/10/2025 11:50:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [L0].[L0_MI_SM_FIX_COST_ESTIMATE]
(
	[DATE] [date] NULL,
	[POSITION] [varchar](50) NULL,
	[SUBITEM] [varchar](50) NULL,
	[STORAGELOCATIONCODE] [varchar](10) NULL,
	[COMMEMNT] [varchar](150) NULL,
	[VALUE] [decimal](19, 4) NULL,
	[ADDEDON] [date] NULL,
	[LOAD_TIMESTAMP] [datetime2](7) NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO


