/****** Object:  Table [L1].[L1_FACT_A_SALES_TRANSACTION_MKT_KPI_SM]    Script Date: 13/10/2025 11:44:47 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [L1].[L1_FACT_A_SALES_TRANSACTION_MKT_KPI_SM]
(
	[ID_SALES_TRANSACTION] [int] NULL,
	[CD_SALES_TRANSACTION] [varchar](250) NULL,
	[CD_SOURCE_SYSTEM] [varchar](10) NULL,
	[D_CREATED] [date] NULL,
	[ID_ITEM] [int] NULL,
	[T_PRODUCT_HIERARCHY_4] [varchar](150) NULL,
	[CD_CHANNEL_GROUP_3] [varchar](50) NULL,
	[ID_SALES_CHANNEL] [int] NULL,
	[CD_COUNTRY_GROUP] [varchar](10) NULL,
	[AMT_MKT_COST_EUR] [decimal](19, 4) NULL,
	[DT_DWH_CREATED] [smalldatetime] NOT NULL,
	[DT_DWH_UPDATED] [smalldatetime] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH ( [CD_SOURCE_SYSTEM] ),
	CLUSTERED COLUMNSTORE INDEX
)
GO


