; with cte_amazon_orders as (

	SELECT CD_SALES_CHANNEL,CD_AMAZON_ORDER,CD_ORDER_STATUS, ISNULL(CD_ITEM,'')CD_ITEM,CD_SKU,CD_ASIN,D_ORDER,CD_ITEM_STATUS,
			SUM(AMT_ECOMMERCE_ITEM_TURNOVER_EUR) TURNOVER_EUR,
			SUM(AMT_ECOMMERCE_ITEM_TURNOVER_DISCOUNT_EUR) TURNOVER_DISCOUNT_EUR,
			SUM(AMT_ECOMMERCE_ITEM_VAT_EUR) ITEM_VAT_EUR,
			SUM(AMT_ECOMMERCE_GROSS_ITEM_VALUE_EUR) GROSS_PRICE_EUR
	FROM l1.L1_FACT_A_AMAZON_ORDER_DAILY amz
	LEFT JOIN  L1.L1_DIM_A_MARKETING_ACCOUNT acc
		on amz.ID_MARKETING_ACCOUNT = acc.ID_MARKETING_ACCOUNT
	WHERE
		MONTH(D_ORDER) = 3 and YEAR(D_ORDER) = 2024
	GROUP BY CD_AMAZON_ORDER, ISNULL(CD_ITEM,''),CD_SKU,D_ORDER,CD_ITEM_STATUS,CD_SALES_CHANNEL,CD_ASIN,CD_ORDER_STATUS

),
SALES_ORDERS AS (
SELECT  kpi.CD_MARKET_ORDER_ID,NUM_ITEM,
		SUM(AMT_NET_PRICE_EUR)AMT_NET_PRICE_EUR,
		SUM(AMT_GROSS_PRICE_EUR)AMT_GROSS_PRICE_EUR,
		SUM(AMT_TAX_PRICE_EUR)AMT_TAX_PRICE_EUR,
		SUM(AMT_NET_DISCOUNT_EUR)AMT_NET_DISCOUNT_EUR,
		SUM(AMT_TURNOVER_EUR)AMT_TURNOVER_EUR,
		SUM(AMT_VALUE_ADDED_TAX_EUR)AMT_VALUE_ADDED_TAX_EUR,
		SUM(AMT_ORDER_DISCOUNTS_EUR)AMT_ORDER_DISCOUNTS_EUR,
		SUM(AMT_ORDER_CHARGES_EUR)AMT_ORDER_CHARGES_EUR,
		SUM(AMT_GROSS_ORDER_VALUE_EUR)AMT_GROSS_ORDER_VALUE_EUR
FROM L1.L1_FACT_A_SALES_TRANSACTION_KPI kpi
INNER JOIN L1.L1_DIM_A_ITEM it on it.ID_ITEM = kpi.ID_ITEM
LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL ch
	on ch.ID_SALES_CHANNEL = kpi.ID_SALES_CHANNEL
WHERE 
	MONTH(kpi.D_CREATED) = 3 and YEAR(kpi.D_CREATED) = 2024
	AND CD_TYPE IN ('ZAA','ZKE','ZAZ')
	AND [CD_CHANNEL_GROUP_1] = 'AMAZON'
GROUP BY CD_MARKET_ORDER_ID,NUM_ITEM

)

SELECT amz.*, 
		sales.AMT_TURNOVER_EUR,
		sales.AMT_VALUE_ADDED_TAX_EUR,
		sales.AMT_ORDER_DISCOUNTS_EUR,
		sales.AMT_ORDER_CHARGES_EUR,
		sales.AMT_GROSS_ORDER_VALUE_EUR
FROM cte_amazon_orders amz
LEFT JOIN SALES_ORDERS sales
	on sales.CD_MARKET_ORDER_ID like ('%'+amz.CD_AMAZON_ORDER)
		AND sales.NUM_ITEM = amz.CD_ITEM
where 
	sales.CD_MARKET_ORDER_ID is null




--select top 10 *
--FROM l1.L1_FACT_A_AMAZON_ORDER_DAILY amz
--where CD_AMAZON_ORDER ='026-0109766-7784369'