/****** Object:  Table [L1].[L1_FACT_F_BOTTOM_LINE_FORECAST]    Script Date: 12/03/2025 10:47:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [L1].[L1_FACT_F_BOTTOM_LINE_FORECAST]
(
	[D_TARGET] [date] NULL,
	[ID_ITEM] [int] NULL,
	[NUM_ITEM] [int] NULL,
	[CD_CHANNEL_GROUP_3] [varchar](50) NULL,
	[CD_CHANNEL_GROUP_1] [varchar](50) NULL,
	[CD_COUNTRY_GROUP] [varchar](50) NULL,
	[AMT_PLAN_PRICE_EUR] [decimal](19, 6) NULL,
	[VL_ITEM_QUANTITY] [decimal](19, 6) NULL,
	[AMT_TARGET_NET_ORDER_VALUE_EUR] [decimal](19, 6) NULL,
	[DT_DWH_CREATED] [smalldatetime] NOT NULL,
	[DT_DWH_UPDATED] [smalldatetime] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH ( [D_TARGET] ),
	CLUSTERED COLUMNSTORE INDEX
)
GO


