USE [CT dwh 02 Data]
GO
/****** Object:  StoredProcedure [dbo].[spLoadFactBaseDataToIntelligence]    Script Date: 18/03/2025 16:22:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[spLoadFactBaseDataToIntelligence]
AS BEGIN
PRINT LTRIM(GETDATE()) + ' Starting';
DECLARE @start_time DATETIME = GETDATE()
DECLARE @total_rows_affected INT = 0;
	/*
	16.11.2021/FT: Umstellung von Data-Layer auf Stage-Layer
	20.10.2021/FT: Kitting-Abfrage von Left join auf INNER JOIN gedreht, da immer wieder der Mandant teilweise nicht ausgefüllt ist

	-- select * from [CT dwh 03 Intelligence].[dbo].[tItemMasterData]
	-- at first, we truncate the whole table
	TRUNCATE TABLE [CT dwh 03 Intelligence].[dbo].[tItemMasterData]

	-- after that, we copy all rows from Stage Layer MARA-Table to Intelligence
	INSERT INTO [CT dwh 03 Intelligence].[dbo].[tItemMasterData]
	(
		   [MANDT]
		  ,[Material_MATNR]
		  ,[Created On]
		  ,[Created by]
		  ,[Last Change]
		  ,[Changed by]
		  ,[Compl. maint. status]
		  ,[Maintenance status]
		  ,[DF at client level]
		  ,[Material type]
		  ,[Industry Sector]
		  ,[Material Group]
		  ,[Old material number]
		  ,[Base Unit of Measure]
		  ,[Order Unit]
		  ,[Document]
		  ,[Document type]
		  ,[Doc. Version]
		  ,[Page format_ZEIFO]
		  ,[Document change no.]
		  ,[Page number]
		  ,[Number of sheets]
		  ,[Prod./insp. memo]
		  ,[Page format_FORMT]
		  ,[Size/dimensions]
		  ,[Basic material]
		  ,[Industry Std Desc.]
		  ,[Lab/Office]
		  ,[Purchasing value key]
		  ,[Gross weight]
		  ,[Net weight]
		  ,[Weight unit]
		  ,[Volume]
		  ,[Volume unit_VOLEH]
		  ,[Container reqmts]
		  ,[Storage conditions]
		  ,[Temp. conditions]
		  ,[Low-Level Code]
		  ,[Transportation Group]
		  ,[Haz. material number]
		  ,[Division]
		  ,[Competitor]
		  ,[EAN Number]
		  ,[Number of GR slips]
		  ,[Procurement rule]
		  ,[Source of supply]
		  ,[Season]
		  ,[Label type]
		  ,[Label form]
		  ,[Field deactivated]
		  ,[EAN/UPC]
		  ,[EAN category]
		  ,[Length]
		  ,[Width]
		  ,[Height]
		  ,[Unit of Dimension]
		  ,[Product hierarchy]
		  ,[Stock Transfer Net Change Costing]
		  ,[CAD Indicator]
		  ,[QM proc. active]
		  ,[Allowed pkg weight]
		  ,[Unit of weight]
		  ,[Allowed pkg volume]
		  ,[Volume unit_ERVOE]
		  ,[Excess wt tolerance]
		  ,[Excess volume tol.]
		  ,[Variable Purchase Order Unit]
		  ,[Revision Level Assgd]
		  ,[Material is configurable]
		  ,[Batch management]
		  ,[Packaging Mat. Type]
		  ,[Maximum level]
		  ,[Stackability factor]
		  ,[Matl Grp Pack.Matls]
		  ,[Authorization Group]
		  ,[Valid From_DATAB]
		  ,[Valid to]
		  ,[Season Year]
		  ,[Price Band Category]
		  ,[With empties BOM]
		  ,[Ext. Material Group]
		  ,[Cross-plant CM]
		  ,[Material Category]
		  ,[Co-product]
		  ,[Follow-up material]
		  ,[Pricing Ref. Matl]
		  ,[X-Plant Matl Status]
		  ,[X-distr.chain status]
		  ,[Valid from_MSTDE]
		  ,[Valid from_MSTDV]
		  ,[Tax classification]
		  ,[Catalog Profile]
		  ,[Min. Rem. Shelf Life]
		  ,[Total shelf life]
		  ,[Storage percentage]
		  ,[Content unit]
		  ,[Net contents]
		  ,[ComparisonPriceUnit]
		  ,[Labeling matl grpg]
		  ,[Gross contents]
		  ,[Conversion Method]
		  ,[Internal object no.]
		  ,[Environmentally rlvt]
		  ,[Product allocation]
		  ,[Pricing profile]
		  ,[Qual.f.FreeGoodsDis.]
		  ,[Manufacturer Part No.]
		  ,[Manufacturer]
		  ,[Int. material number]
		  ,[Mfr part profile]
		  ,[Units of meas. usage]
		  ,[Rollout]
		  ,[DG indicator profile]
		  ,[Highly viscous]
		  ,[In bulk/liquid]
		  ,[Serialization level]
		  ,[Closed]
		  ,[Appr.Batch Recd Req.]
		  ,[Assign effect. vals]
		  ,[Material completion level]
		  ,[Period Ind. for SLED]
		  ,[Rounding rule SLED]
		  ,[Product Composition]
		  ,[Gen. item cat. grp]
		  ,[Logistical variants]
		  ,[Material is locked]
		  ,[Indicator for relevance in CM]
		  ,[Assortment List Type]
		  ,[Expiration Date]
		  ,[EAN Variant]
		  ,[Generic Material]
		  ,[Reference matl for packing]
		  ,[GDS-Relevant]
		  ,[Origin Acceptance]
		  ,[Standard HU Type]
		  ,[Pilferable]
		  ,[WH Storage Condition]
		  ,[WH Material Group]
		  ,[Handling Indicator]
		  ,[Relevant for HS]
		  ,[Handling Unit Type]
		  ,[Varb. Tare Weight]
		  ,[Maximum Capacity]
		  ,[Overcapacity Toler.]
		  ,[Max. Pack. Length]
		  ,[Max. Pack. Width]
		  ,[Max. Pack. Height]
		  ,[Unit of Measurement]
		  ,[Country of origin]
		  ,[Material freight grp]
		  ,[Quarant. Per.]
		  ,[Quarantine Time Unit]
		  ,[Quality Inspection Group]
		  ,[Serial No. Profile]
		  ,[Form Name]
		  ,[Logistics Unit of Measure]
		  ,[Material Is a CW Material]
		  ,[CW Profile for CW Quantity]
		  ,[Catch Weight Tolerance Group]
		  ,[Adjustment Profile (Merchandise Distr.)]
		  ,[Intellectual Property]
		  ,[Variant Price Allowed]
		  ,[Medium]
		  ,[Commodity]
		  ,[Cont. Non-Textile Parts of Animal Origin]
		  ,[Textile Composition Maintenance Active]
		  ,[Last Changed Time]
		  ,[Material_MATNR_EXTERNAL]
		  ,[Category of a Logistical Material]
		  ,[Material Number of Sales Material]
		  ,[Identification Tag Type]
		  ,[Segmentation Structure]
		  ,[Segmentation Strategy]
		  ,[Segmentation Status]
		  ,[Segmentation Strategy Scope]
		  ,[Segmentation Relevant]
		  ,[ANP Code]
		  ,[Protected Species Management Code]
		  ,[Fashion Attribute 1]
		  ,[Fashion Attribute 2]
		  ,[Fashion Attribute 3]
		  ,[Season Usage]
		  ,[Season Active in Inventory Management]
		  ,[Material Conv. ID]
		  ,[Dummy Field]
		  ,[Product]
		  ,[Product ID]
		  ,[Maturation Time]
		  ,[Reqd Min. Shelf Life]
		  ,[Reqd Max. Shelf Life]
		  ,[Preferred Unit of Measure]
		  ,[Reference Product for Package Building]
		  ,[Product Shape]
		  ,[Product Orientation Profile]
		  ,[Overhang Threshold %]
		  ,[Bridge Threshold %]
		  ,[Maximum Slope for Bridges °]
		  ,[Absolute Height Threshold]
		  ,[UoM of Absolute Height Threshold]
		  ,[Material Is Activated for CW]
		  ,[Valuation UoM]
		  ,[CW Tolerance Group]
		  ,[Fixed Tare]
		  ,[Ref.Unit of Measure TARE Calculation]
		  ,[Loading Units]
		  ,[Loading Unit Group]
		  ,[Structure Category]
		  ,[Tolerance Type ID]
		  ,[Counting Group]
		  ,[DSD Grouping]
		  ,[Cable Diameter]
		  ,[Unit for Dimensions]
		  ,[Cable Diameter Allowance in Percent]
		  ,[Bending Factor]
		  ,[Inner Width]
		  ,[Outer Diameter]
		  ,[Core Diameter]
		  ,[Load Capacity]
		  ,[R-O Flange Thick.]
		  ,[R-O Flange Height]
		  ,[Coil Delivery]
		  ,[Run-Out Flange]
		  ,[No. Vertical Layers]
		  ,[Smallest Permitted Clearance]
		  ,[Serialization Type]
		  ,[Synchronization Active]
		  ,[Last Synchronization Time]
		  ,[Indicator Changed Since Integration]
		  ,[Profile Relevant Country]
		  ,[Product Category]
		  ,[Tilting Allowed]
		  ,[No Stacking]
		  ,[Only Bottom Layer]
		  ,[Only Top Layer]
		  ,[Stacking Factor]
		  ,[Load without PKM]
		  ,[PKM Overhang Depth]
		  ,[PKM Overhang Width]
		  ,[Max. Stacking Height]
		  ,[Min. Stacking Height]
		  ,[Max.StackH Tolerance]
		  ,[No. Mat / Closed PKM]
		  ,[VSO Unit of Measure]
		  ,[Closed PKM Required]
		  ,[Packaging Code]
		  ,[DG Packaging Status]
		  ,[Material Condition Mgmt]
		  ,[Return Code]
		  ,[Return to Logistics Level]
		  ,[NATO Stock Number]
		  ,[Overlength Part Number]
		  ,[Spare Part Class Code]
		  ,[Variable ObjectID]
		  ,[MS Book Part Number]
		  ,[SU Batch Default Value]
		  ,[Goods Rcpt to Posted Single-Unit Bch]
		  ,[Form-Fit-Function class]
		  ,[Supersession chain number]
		  ,[Creation Status]
		  ,[Int. Char. Number_COLOR_ATINN]
		  ,[Int. Char. Number_SIZE1_ATINN]
		  ,[Int. Char. Number_SIZE2_ATINN]
		  ,[Color]
		  ,[Main Size]
		  ,[Second Size]
		  ,[Free Charact. Value]
		  ,[Care Code]
		  ,[Brand]
		  ,[Component 1]
		  ,[Percentage Share 1]
		  ,[Component 2]
		  ,[Percentage Share 2]
		  ,[Component 3]
		  ,[Percentage Share 3]
		  ,[Component 4]
		  ,[Percentage Share 4]
		  ,[Component 5]
		  ,[Percentage Share 5]
		  ,[Fashion Grade]
	)
	SELECT [MANDT]
		  ,[MATNR]
		  ,[ERSDA]
		  ,[ERNAM]
		  ,[LAEDA]
		  ,[AENAM]
		  ,[VPSTA]
		  ,[PSTAT]
		  ,[LVORM]
		  ,[MTART]
		  ,[MBRSH]
		  ,[MATKL]
		  ,[BISMT]
		  ,[MEINS]
		  ,[BSTME]
		  ,[ZEINR]
		  ,[ZEIAR]
		  ,[ZEIVR]
		  ,[ZEIFO]
		  ,[AESZN]
		  ,[BLATT]
		  ,[BLANZ]
		  ,[FERTH]
		  ,[FORMT]
		  ,[GROES]
		  ,[WRKST]
		  ,[NORMT]
		  ,[LABOR]
		  ,[EKWSL]
		  ,[BRGEW]
		  ,[NTGEW]
		  ,[GEWEI]
		  ,[VOLUM]
		  ,[VOLEH]
		  ,[BEHVO]
		  ,[RAUBE]
		  ,[TEMPB]
		  ,[DISST]
		  ,[TRAGR]
		  ,[STOFF]
		  ,[SPART]
		  ,[KUNNR]
		  ,[EANNR]
		  ,[WESCH]
		  ,[BWVOR]
		  ,[BWSCL]
		  ,[SAISO]
		  ,[ETIAR]
		  ,[ETIFO]
		  ,[ENTAR]
		  ,[EAN11]
		  ,[NUMTP]
		  ,[LAENG]
		  ,[BREIT]
		  ,[HOEHE]
		  ,[MEABM]
		  ,[PRDHA]
		  ,[AEKLK]
		  ,[CADKZ]
		  ,[QMPUR]
		  ,[ERGEW]
		  ,[ERGEI]
		  ,[ERVOL]
		  ,[ERVOE]
		  ,[GEWTO]
		  ,[VOLTO]
		  ,[VABME]
		  ,[KZREV]
		  ,[KZKFG]
		  ,[XCHPF]
		  ,[VHART]
		  ,[FUELG]
		  ,[STFAK]
		  ,[MAGRV]
		  ,[BEGRU]
		  ,[DATAB]
		  ,[LIQDT]
		  ,[SAISJ]
		  ,[PLGTP]
		  ,[MLGUT]
		  ,[EXTWG]
		  ,[SATNR]
		  ,[ATTYP]
		  ,[KZKUP]
		  ,[KZNFM]
		  ,[PMATA]
		  ,[MSTAE]
		  ,[MSTAV]
		  ,[MSTDE]
		  ,[MSTDV]
		  ,[TAKLV]
		  ,[RBNRM]
		  ,[MHDRZ]
		  ,[MHDHB]
		  ,[MHDLP]
		  ,[INHME]
		  ,[INHAL]
		  ,[VPREH]
		  ,[ETIAG]
		  ,[INHBR]
		  ,[CMETH]
		  ,[CUOBF]
		  ,[KZUMW]
		  ,[KOSCH]
		  ,[SPROF]
		  ,[NRFHG]
		  ,[MFRPN]
		  ,[MFRNR]
		  ,[BMATN]
		  ,[MPROF]
		  ,[KZWSM]
		  ,[SAITY]
		  ,[PROFL]
		  ,[IHIVI]
		  ,[ILOOS]
		  ,[SERLV]
		  ,[KZGVH]
		  ,[XGCHP]
		  ,[KZEFF]
		  ,[COMPL]
		  ,[IPRKZ]
		  ,[RDMHD]
		  ,[PRZUS]
		  ,[MTPOS_MARA]
		  ,[BFLME]
		  ,[MATFI]
		  ,[CMREL]
		  ,[BBTYP]
		  ,[SLED_BBD]
		  ,[GTIN_VARIANT]
		  ,[GENNR]
		  ,[RMATP]
		  ,[GDS_RELEVANT]
		  ,[WEORA]
		  ,[HUTYP_DFLT]
		  ,[PILFERABLE]
		  ,[WHSTC]
		  ,[WHMATGR]
		  ,[HNDLCODE]
		  ,[HAZMAT]
		  ,[HUTYP]
		  ,[TARE_VAR]
		  ,[MAXC]
		  ,[MAXC_TOL]
		  ,[MAXL]
		  ,[MAXB]
		  ,[MAXH]
		  ,[MAXDIM_UOM]
		  ,[HERKL]
		  ,[MFRGR]
		  ,[QQTIME]
		  ,[QQTIMEUOM]
		  ,[QGRP]
		  ,[SERIAL]
		  ,[PS_SMARTFORM]
		  ,[LOGUNIT]
		  ,[CWQREL]
		  ,[CWQPROC]
		  ,[CWQTOLGR]
		  ,[ADPROF]
		  ,[IPMIPPRODUCT]
		  ,[ALLOW_PMAT_IGNO]
		  ,[MEDIUM]
		  ,[COMMODITY]
		  ,[ANIMAL_ORIGIN]
		  ,[TEXTILE_COMP_IND]
		  ,[LAST_CHANGED_TIME]
		  ,[MATNR_EXTERNAL]
		  ,[LOGISTICAL_MAT_CATEGORY]
		  ,[SALES_MATERIAL]
		  ,[IDENTIFICATION_TAG_TYPE]
		  ,[SGT_CSGR]
		  ,[SGT_COVSA]
		  ,[SGT_STAT]
		  ,[SGT_SCOPE]
		  ,[SGT_REL]
		  ,[ANP]
		  ,[PSM_CODE]
		  ,[FSH_MG_AT1]
		  ,[FSH_MG_AT2]
		  ,[FSH_MG_AT3]
		  ,[FSH_SEALV]
		  ,[FSH_SEAIM]
		  ,[FSH_SC_MID]
		  ,[DUMMY_PRD_INCL_EEW_PS]
		  ,[SCM_MATID_GUID16]
		  ,[SCM_MATID_GUID22]
		  ,[SCM_MATURITY_DUR]
		  ,[SCM_SHLF_LFE_REQ_MIN]
		  ,[SCM_SHLF_LFE_REQ_MAX]
		  ,[SCM_PUOM]
		  ,[RMATP_PB]
		  ,[PROD_SHAPE]
		  ,[MO_PROFILE_ID]
		  ,[OVERHANG_TRESH]
		  ,[BRIDGE_TRESH]
		  ,[BRIDGE_MAX_SLOPE]
		  ,[HEIGHT_NONFLAT]
		  ,[HEIGHT_NONFLAT_UOM]
		  ,[/CWM/XCWMAT]
		  ,[/CWM/VALUM]
		  ,[/CWM/TOLGR]
		  ,[/CWM/TARA]
		  ,[/CWM/TARUM]
		  ,[/BEV1/LULEINH]
		  ,[/BEV1/LULDEGRP]
		  ,[/BEV1/NESTRUCCAT]
		  ,[/DSD/SL_TOLTYP]
		  ,[/DSD/SV_CNT_GRP]
		  ,[/DSD/VC_GROUP]
		  ,[/SAPMP/KADU]
		  ,[/SAPMP/ABMEIN]
		  ,[/SAPMP/KADP]
		  ,[/SAPMP/BRAD]
		  ,[/SAPMP/SPBI]
		  ,[/SAPMP/TRAD]
		  ,[/SAPMP/KEDU]
		  ,[/SAPMP/SPTR]
		  ,[/SAPMP/FBDK]
		  ,[/SAPMP/FBHK]
		  ,[/SAPMP/RILI]
		  ,[/SAPMP/FBAK]
		  ,[/SAPMP/AHO]
		  ,[/SAPMP/MIFRR]
		  ,[/STTPEC/SERTYPE]
		  ,[/STTPEC/SYNCACT]
		  ,[/STTPEC/SYNCTIME]
		  ,[/STTPEC/SYNCCHG]
		  ,[/STTPEC/COUNTRY_REF]
		  ,[/STTPEC/PRDCAT]
		  ,[/VSO/R_TILT_IND]
		  ,[/VSO/R_STACK_IND]
		  ,[/VSO/R_BOT_IND]
		  ,[/VSO/R_TOP_IND]
		  ,[/VSO/R_STACK_NO]
		  ,[/VSO/R_PAL_IND]
		  ,[/VSO/R_PAL_OVR_D]
		  ,[/VSO/R_PAL_OVR_W]
		  ,[/VSO/R_PAL_B_HT]
		  ,[/VSO/R_PAL_MIN_H]
		  ,[/VSO/R_TOL_B_HT]
		  ,[/VSO/R_NO_P_GVH]
		  ,[/VSO/R_QUAN_UNIT]
		  ,[/VSO/R_KZGVH_IND]
		  ,[PACKCODE]
		  ,[DG_PACK_STATUS]
		  ,[MCOND]
		  ,[RETDELC]
		  ,[LOGLEV_RETO]
		  ,[NSNID]
		  ,[OVLPN]
		  ,[ADSPC_SPC]
		  ,[VARID]
		  ,[MSBOOKPARTNO]
		  ,[DPCBT]
		  ,[XGRDT]
		  ,[IMATN]
		  ,[PICNUM]
		  ,[BSTAT]
		  ,[COLOR_ATINN]
		  ,[SIZE1_ATINN]
		  ,[SIZE2_ATINN]
		  ,[COLOR]
		  ,[SIZE1]
		  ,[SIZE2]
		  ,[FREE_CHAR]
		  ,[CARE_CODE]
		  ,[BRAND_ID]
		  ,[FIBER_CODE1]
		  ,[FIBER_PART1]
		  ,[FIBER_CODE2]
		  ,[FIBER_PART2]
		  ,[FIBER_CODE3]
		  ,[FIBER_PART3]
		  ,[FIBER_CODE4]
		  ,[FIBER_PART4]
		  ,[FIBER_CODE5]
		  ,[FIBER_PART5]
		  ,[FASHGRD]
	  FROM [CT dwh 01 Stage].[dbo].[tSAP_MARA]
	  WITH (NOLOCK)
	  */
	  /*
	  -- WORKING with Spoon generated table data

	  INSERT INTO [CT dwh 03 Intelligence].[dbo].[tItemMasterData]
	(
		   [MANDT]
		  ,[Loading Unit Group]
		  ,[Loading Units]
		  ,[Structure Category]
		  ,[Fixed Tare]
		  ,[Ref.Unit of Measure TARE Calculation]
		  ,[CW Tolerance Group]
		  ,[Valuation UoM]
		  ,[Material Is Activated for CW]
		  ,[Tolerance Type ID]
		  ,[Counting Group]
		  ,[DSD Grouping]
		  ,[Unit for Dimensions]
		  ,[No. Vertical Layers]
		  ,[Bending Factor]
		  ,[Run-Out Flange]
		  ,[R-O Flange Thick.]
		  ,[R-O Flange Height]
		  ,[Cable Diameter Allowance in Percent]
		  ,[Cable Diameter]
		  ,[Core Diameter]
		  ,[Smallest Permitted Clearance]
		  ,[Coil Delivery]
		  ,[Inner Width]
		  ,[Load Capacity]
		  ,[Outer Diameter]
		  ,[Profile Relevant Country]
		  ,[Product Category]
		  ,[Serialization Type]
		  ,[Synchronization Active]
		  ,[Indicator Changed Since Integration]
		  ,[Last Synchronization Time]
		  ,[Only Bottom Layer]
		  ,[Closed PKM Required]
		  ,[No. Mat / Closed PKM]
		  ,[Max. Stacking Height]
		  ,[Load without PKM]
		  ,[Min. Stacking Height]
		  ,[PKM Overhang Depth]
		  ,[PKM Overhang Width]
		  ,[VSO Unit of Measure]
		  ,[No Stacking]
		  ,[Stacking Factor]
		  ,[Tilting Allowed]
		  ,[Max.StackH Tolerance]
		  ,[Only Top Layer]
		  ,[Adjustment Profile (Merchandise Distr.)]
		  ,[Spare Part Class Code]
		  ,[Stock Transfer Net Change Costing]
		  ,[Changed by]
		  ,[Document change no.]
		  ,[Variant Price Allowed]
		  ,[Cont. Non-Textile Parts of Animal Origin]
		  ,[ANP Code]
		  ,[Material Category]
		  ,[Assortment List Type]
		  ,[Authorization Group]
		  ,[Container reqmts]
		  ,[Logistical variants]
		  ,[Old material number]
		  ,[Number of sheets]
		  ,[Page number]
		  ,[Int. material number]
		  ,[Brand]
		  ,[Width]
		  ,[Gross weight]
		  ,[Maximum Slope for Bridges °]
		  ,[Bridge Threshold %]
		  ,[Creation Status]
		  ,[Order Unit]
		  ,[Source of supply]
		  ,[Procurement rule]
		  ,[CAD Indicator]
		  ,[Care Code]
		  ,[Conversion Method]
		  ,[Indicator for relevance in CM]
		  ,[Color]
		  ,[Int. Char. Number_COLOR_ATINN]
		  ,[Commodity]
		  ,[Material completion level]
		  ,[Internal object no.]
		  ,[CW Profile for CW Quantity]
		  ,[Material Is a CW Material]
		  ,[Catch Weight Tolerance Group]
		  ,[Valid From_DATAB]
		  ,[DG Packaging Status]
		  ,[Low-Level Code]
		  ,[SU Batch Default Value]
		  ,[Dummy Field]
		  ,[EAN/UPC]
		  ,[EAN Number]
		  ,[Purchasing value key]
		  ,[Field deactivated]
		  ,[Unit of weight]
		  ,[Allowed pkg weight]
		  ,[Created by]
		  ,[Created On]
		  ,[Volume unit_ERVOE]
		  ,[Allowed pkg volume]
		  ,[Labeling matl grpg]
		  ,[Label type]
		  ,[Label form]
		  ,[Ext. Material Group]
		  ,[Fashion Grade]
		  ,[Prod./insp. memo]
		  ,[Component 1]
		  ,[Component 2]
		  ,[Component 3]
		  ,[Component 4]
		  ,[Component 5]
		  ,[Percentage Share 1]
		  ,[Percentage Share 2]
		  ,[Percentage Share 3]
		  ,[Percentage Share 4]
		  ,[Percentage Share 5]
		  ,[Page format_FORMT]
		  ,[Free Charact. Value]
		  ,[Fashion Attribute 1]
		  ,[Fashion Attribute 2]
		  ,[Fashion Attribute 3]
		  ,[Material Conv. ID]
		  ,[Season Active in Inventory Management]
		  ,[Season Usage]
		  ,[Maximum level]
		  ,[GDS-Relevant]
		  ,[Generic Material]
		  ,[Weight unit]
		  ,[Excess wt tolerance]
		  ,[Size/dimensions]
		  ,[EAN Variant]
		  ,[Relevant for HS]
		  ,[Absolute Height Threshold]
		  ,[UoM of Absolute Height Threshold]
		  ,[Country of origin]
		  ,[Handling Indicator]
		  ,[Height]
		  ,[Handling Unit Type]
		  ,[Standard HU Type]
		  ,[Identification Tag Type]
		  ,[Highly viscous]
		  ,[In bulk/liquid]
		  ,[Form-Fit-Function class]
		  ,[Net contents]
		  ,[Gross contents]
		  ,[Content unit]
		  ,[Intellectual Property]
		  ,[Period Ind. for SLED]
		  ,[Product allocation]
		  ,[Competitor]
		  ,[Assign effect. vals]
		  ,[Closed]
		  ,[Material is configurable]
		  ,[Co-product]
		  ,[Follow-up material]
		  ,[Revision Level Assgd]
		  ,[Environmentally rlvt]
		  ,[Units of meas. usage]
		  ,[Lab/Office]
		  ,[Last Change]
		  ,[Length]
		  ,[Last Changed Time]
		  ,[Valid to]
		  ,[Category of a Logistical Material]
		  ,[Return to Logistics Level]
		  ,[Logistics Unit of Measure]
		  ,[DF at client level]
		  ,[Matl Grp Pack.Matls]
		  ,[Material is locked]
		  ,[Material Group]
		  ,[Material_MATNR]
		  ,[Material_MATNR_EXTERNAL]
		  ,[Max. Pack. Width]
		  ,[Maximum Capacity]
		  ,[Overcapacity Toler.]
		  ,[Unit of Measurement]
		  ,[Max. Pack. Height]
		  ,[Max. Pack. Length]
		  ,[Industry Sector]
		  ,[Material Condition Mgmt]
		  ,[Unit of Dimension]
		  ,[Medium]
		  ,[Base Unit of Measure]
		  ,[Material freight grp]
		  ,[Manufacturer]
		  ,[Manufacturer Part No.]
		  ,[Total shelf life]
		  ,[Storage percentage]
		  ,[Min. Rem. Shelf Life]
		  ,[With empties BOM]
		  ,[Product Orientation Profile]
		  ,[Mfr part profile]
		  ,[MS Book Part Number]
		  ,[X-Plant Matl Status]
		  ,[X-distr.chain status]
		  ,[Valid from_MSTDE]
		  ,[Valid from_MSTDV]
		  ,[Material type]
		  ,[Gen. item cat. grp]
		  ,[Industry Std Desc.]
		  ,[Qual.f.FreeGoodsDis.]
		  ,[NATO Stock Number]
		  ,[Net weight]
		  ,[EAN category]
		  ,[Overhang Threshold %]
		  ,[Overlength Part Number]
		  ,[Packaging Code]
		  ,[Supersession chain number]
		  ,[Pilferable]
		  ,[Price Band Category]
		  ,[Pricing Ref. Matl]
		  ,[Product hierarchy]
		  ,[Product Shape]
		  ,[DG indicator profile]
		  ,[Product Composition]
		  ,[Form Name]
		  ,[Protected Species Management Code]
		  ,[Maintenance status]
		  ,[Quality Inspection Group]
		  ,[QM proc. active]
		  ,[Quarant. Per.]
		  ,[Quarantine Time Unit]
		  ,[Storage conditions]
		  ,[Catalog Profile]
		  ,[Rounding rule SLED]
		  ,[Return Code]
		  ,[Reference matl for packing]
		  ,[Reference Product for Package Building]
		  ,[Season Year]
		  ,[Season]
		  ,[Rollout]
		  ,[Material Number of Sales Material]
		  ,[Cross-plant CM]
		  ,[Product]
		  ,[Product ID]
		  ,[Maturation Time]
		  ,[Preferred Unit of Measure]
		  ,[Reqd Max. Shelf Life]
		  ,[Reqd Min. Shelf Life]
		  ,[Serial No. Profile]
		  ,[Serialization level]
		  ,[Segmentation Strategy]
		  ,[Segmentation Structure]
		  ,[Segmentation Relevant]
		  ,[Segmentation Strategy Scope]
		  ,[Segmentation Status]
		  ,[Main Size]
		  ,[Int. Char. Number_SIZE1_ATINN]
		  ,[Second Size]
		  ,[Int. Char. Number_SIZE2_ATINN]
		  ,[Expiration Date]
		  ,[Division]
		  ,[Pricing profile]
		  ,[Stackability factor]
		  ,[Haz. material number]
		  ,[Tax classification]
		  ,[Varb. Tare Weight]
		  ,[Temp. conditions]
		  ,[Textile Composition Maintenance Active]
		  ,[Transportation Group]
		  ,[Variable Purchase Order Unit]
		  ,[Variable ObjectID]
		  ,[Packaging Mat. Type]
		  ,[Volume unit_VOLEH]
		  ,[Excess volume tol.]
		  ,[Volume]
		  ,[ComparisonPriceUnit]
		  ,[Compl. maint. status]
		  ,[Origin Acceptance]
		  ,[Number of GR slips]
		  ,[WH Material Group]
		  ,[WH Storage Condition]
		  ,[Basic material]
		  ,[Batch management]
		  ,[Appr.Batch Recd Req.]
		  ,[Goods Rcpt to Posted Single-Unit Bch]
		  ,[Document type]
		  ,[Page format_ZEIFO]
		  ,[Document]
		  ,[Doc. Version]
	)
	SELECT
		   [MANDT]
		  ,[/BEV1/LULDEGRP]
		  ,[/BEV1/LULEINH]
		  ,[/BEV1/NESTRUCCAT]
		  ,[/CWM/TARA]
		  ,[/CWM/TARUM]
		  ,[/CWM/TOLGR]
		  ,[/CWM/VALUM]
		  ,[/CWM/XCWMAT]
		  ,[/DSD/SL_TOLTYP]
		  ,[/DSD/SV_CNT_GRP]
		  ,[/DSD/VC_GROUP]
		  ,[/SAPMP/ABMEIN]
		  ,[/SAPMP/AHO]
		  ,[/SAPMP/BRAD]
		  ,[/SAPMP/FBAK]
		  ,[/SAPMP/FBDK]
		  ,[/SAPMP/FBHK]
		  ,[/SAPMP/KADP]
		  ,[/SAPMP/KADU]
		  ,[/SAPMP/KEDU]
		  ,[/SAPMP/MIFRR]
		  ,[/SAPMP/RILI]
		  ,[/SAPMP/SPBI]
		  ,[/SAPMP/SPTR]
		  ,[/SAPMP/TRAD]
		  ,[/STTPEC/COUNTRY_REF]
		  ,[/STTPEC/PRDCAT]
		  ,[/STTPEC/SERTYPE]
		  ,[/STTPEC/SYNCACT]
		  ,[/STTPEC/SYNCCHG]
		  ,[/STTPEC/SYNCTIME]
		  ,[/VSO/R_BOT_IND]
		  ,[/VSO/R_KZGVH_IND]
		  ,[/VSO/R_NO_P_GVH]
		  ,[/VSO/R_PAL_B_HT]
		  ,[/VSO/R_PAL_IND]
		  ,[/VSO/R_PAL_MIN_H]
		  ,[/VSO/R_PAL_OVR_D]
		  ,[/VSO/R_PAL_OVR_W]
		  ,[/VSO/R_QUAN_UNIT]
		  ,[/VSO/R_STACK_IND]
		  ,[/VSO/R_STACK_NO]
		  ,[/VSO/R_TILT_IND]
		  ,[/VSO/R_TOL_B_HT]
		  ,[/VSO/R_TOP_IND]
		  ,[ADPROF]
		  ,[ADSPC_SPC]
		  ,[AEKLK]
		  ,[AENAM]
		  ,[AESZN]
		  ,[ALLOW_PMAT_IGNO]
		  ,[ANIMAL_ORIGIN]
		  ,[ANP]
		  ,[ATTYP]
		  ,[BBTYP]
		  ,[BEGRU]
		  ,[BEHVO]
		  ,[BFLME]
		  ,[BISMT]
		  ,[BLANZ]
		  ,[BLATT]
		  ,[BMATN]
		  ,[BRAND_ID]
		  ,[BREIT]
		  ,[BRGEW]
		  ,[BRIDGE_MAX_SLOPE]
		  ,[BRIDGE_TRESH]
		  ,[BSTAT]
		  ,[BSTME]
		  ,[BWSCL]
		  ,[BWVOR]
		  ,[CADKZ]
		  ,[CARE_CODE]
		  ,[CMETH]
		  ,[CMREL]
		  ,[COLOR]
		  ,[COLOR_ATINN]
		  ,[COMMODITY]
		  ,[COMPL]
		  ,[CUOBF]
		  ,[CWQPROC]
		  ,[CWQREL]
		  ,[CWQTOLGR]
		  ,[DATAB]
		  ,[DG_PACK_STATUS]
		  ,[DISST]
		  ,[DPCBT]
		  ,[DUMMY_PRD_INCL_EEW_PS]
		  ,[EAN11]
		  ,[EANNR]
		  ,[EKWSL]
		  ,[ENTAR]
		  ,[ERGEI]
		  ,[ERGEW]
		  ,[ERNAM]
		  ,[ERSDA]
		  ,[ERVOE]
		  ,[ERVOL]
		  ,[ETIAG]
		  ,[ETIAR]
		  ,[ETIFO]
		  ,[EXTWG]
		  ,[FASHGRD]
		  ,[FERTH]
		  ,[FIBER_CODE1]
		  ,[FIBER_CODE2]
		  ,[FIBER_CODE3]
		  ,[FIBER_CODE4]
		  ,[FIBER_CODE5]
		  ,[FIBER_PART1]
		  ,[FIBER_PART2]
		  ,[FIBER_PART3]
		  ,[FIBER_PART4]
		  ,[FIBER_PART5]
		  ,[FORMT]
		  ,[FREE_CHAR]
		  ,[FSH_MG_AT1]
		  ,[FSH_MG_AT2]
		  ,[FSH_MG_AT3]
		  ,[FSH_SC_MID]
		  ,[FSH_SEAIM]
		  ,[FSH_SEALV]
		  ,[FUELG]
		  ,[GDS_RELEVANT]
		  ,[GENNR]
		  ,[GEWEI]
		  ,[GEWTO]
		  ,[GROES]
		  ,[GTIN_VARIANT]
		  ,[HAZMAT]
		  ,[HEIGHT_NONFLAT]
		  ,[HEIGHT_NONFLAT_UOM]
		  ,[HERKL]
		  ,[HNDLCODE]
		  ,[HOEHE]
		  ,[HUTYP]
		  ,[HUTYP_DFLT]
		  ,[IDENTIFICATION_TAG_TYPE]
		  ,[IHIVI]
		  ,[ILOOS]
		  ,[IMATN]
		  ,[INHAL]
		  ,[INHBR]
		  ,[INHME]
		  ,[IPMIPPRODUCT]
		  ,[IPRKZ]
		  ,[KOSCH]
		  ,[KUNNR]
		  ,[KZEFF]
		  ,[KZGVH]
		  ,[KZKFG]
		  ,[KZKUP]
		  ,[KZNFM]
		  ,[KZREV]
		  ,[KZUMW]
		  ,[KZWSM]
		  ,[LABOR]
		  ,[LAEDA]
		  ,[LAENG]
		  ,[LAST_CHANGED_TIME]
		  ,[LIQDT]
		  ,[LOGISTICAL_MAT_CATEGORY]
		  ,[LOGLEV_RETO]
		  ,[LOGUNIT]
		  ,[LVORM]
		  ,[MAGRV]
		  ,[MATFI]
		  ,[MATKL]
		  ,[MATNR]
		  ,[MATNR_EXTERNAL]
		  ,[MAXB]
		  ,[MAXC]
		  ,[MAXC_TOL]
		  ,[MAXDIM_UOM]
		  ,[MAXH]
		  ,[MAXL]
		  ,[MBRSH]
		  ,[MCOND]
		  ,[MEABM]
		  ,[MEDIUM]
		  ,[MEINS]
		  ,[MFRGR]
		  ,[MFRNR]
		  ,[MFRPN]
		  ,[MHDHB]
		  ,[MHDLP]
		  ,[MHDRZ]
		  ,[MLGUT]
		  ,[MO_PROFILE_ID]
		  ,[MPROF]
		  ,[MSBOOKPARTNO]
		  ,[MSTAE]
		  ,[MSTAV]
		  ,[MSTDE]
		  ,[MSTDV]
		  ,[MTART]
		  ,[MTPOS_MARA]
		  ,[NORMT]
		  ,[NRFHG]
		  ,[NSNID]
		  ,[NTGEW]
		  ,[NUMTP]
		  ,[OVERHANG_TRESH]
		  ,[OVLPN]
		  ,[PACKCODE]
		  ,[PICNUM]
		  ,[PILFERABLE]
		  ,[PLGTP]
		  ,[PMATA]
		  ,[PRDHA]
		  ,[PROD_SHAPE]
		  ,[PROFL]
		  ,[PRZUS]
		  ,[PS_SMARTFORM]
		  ,[PSM_CODE]
		  ,[PSTAT]
		  ,[QGRP]
		  ,[QMPUR]
		  ,[QQTIME]
		  ,[QQTIMEUOM]
		  ,[RAUBE]
		  ,[RBNRM]
		  ,[RDMHD]
		  ,[RETDELC]
		  ,[RMATP]
		  ,[RMATP_PB]
		  ,[SAISJ]
		  ,[SAISO]
		  ,[SAITY]
		  ,[SALES_MATERIAL]
		  ,[SATNR]
		  ,[SCM_MATID_GUID16]
		  ,[SCM_MATID_GUID22]
		  ,[SCM_MATURITY_DUR]
		  ,[SCM_PUOM]
		  ,[SCM_SHLF_LFE_REQ_MAX]
		  ,[SCM_SHLF_LFE_REQ_MIN]
		  ,[SERIAL]
		  ,[SERLV]
		  ,[SGT_COVSA]
		  ,[SGT_CSGR]
		  ,[SGT_REL]
		  ,[SGT_SCOPE]
		  ,[SGT_STAT]
		  ,[SIZE1]
		  ,[SIZE1_ATINN]
		  ,[SIZE2]
		  ,[SIZE2_ATINN]
		  ,[SLED_BBD]
		  ,[SPART]
		  ,[SPROF]
		  ,[STFAK]
		  ,[STOFF]
		  ,[TAKLV]
		  ,[TARE_VAR]
		  ,[TEMPB]
		  ,[TEXTILE_COMP_IND]
		  ,[TRAGR]
		  ,[VABME]
		  ,[VARID]
		  ,[VHART]
		  ,[VOLEH]
		  ,[VOLTO]
		  ,[VOLUM]
		  ,[VPREH]
		  ,[VPSTA]
		  ,[WEORA]
		  ,[WESCH]
		  ,[WHMATGR]
		  ,[WHSTC]
		  ,[WRKST]
		  ,[XCHPF]
		  ,[XGCHP]
		  ,[XGRDT]
		  ,[ZEIAR]
		  ,[ZEIFO]
		  ,[ZEINR]
		  ,[ZEIVR]
	FROM [CT dwh 02 Data].[dbo].[tSAP_MARA]
	WITH (NOLOCK)
	WHERE valid_to = '2200-01-01' and is_deleted = 0
	  */

	-- 28.10.2020/FT -> https://jira.chal-tec.com/browse/DEVTCK-17601
	-- delete all
	TRUNCATE TABLE [CT dwh 03 Intelligence].[dbo].[tStorageLocationDataForMaterial]

	INSERT INTO [CT dwh 03 Intelligence].[dbo].[tStorageLocationDataForMaterial]
	(
	   [MANDT]
      ,[Material]
      ,[Plant]
      ,[Storage location]
      ,[Maintenance status]
      ,[DF stor. loc. level]
      ,[Year current period]
      ,[Current period]
      ,[Phys. Inv. Block]
      ,[Unrestricted_LABST]
      ,[Stock in transfer_UMLME]
      ,[Quality Inspection_INSME]
      ,[Restricted-Use Stock_EINME]
      ,[Blocked_SPEME]
      ,[Returns_RETME]
      ,[Unrestr.-use stock_VMLAB]
      ,[Stock in transfer_VMUML]
      ,[In quality insp._VMINS]
      ,[Restricted-use stock_VMEIN]
      ,[Blocked_VMSPE]
      ,[Returns_VMRET]
      ,[Warehouse stock CY]
      ,[Qual. insp. stock CY]
      ,[Restricted-use stock_KZILE]
      ,[Blocked stock]
      ,[Warehouse stock PY]
      ,[QuallnspStock prv.pd]
      ,[Restricted use, PP]
      ,[Blocked stock prev.pd]
      ,[Sloc MRP indicator]
      ,[Spec.proc.type: SLoc]
      ,[Reorder point]
      ,[Replenishment qty]
      ,[Country of origin]
      ,[Preference indicator]
      ,[Export indicator]
      ,[Storage bin]
      ,[Unrestr. Consignment_KLABS]
      ,[Cnsgt in Inspection_KINSM]
      ,[Restr. Consignment_KEINM]
      ,[Blocked Consignment_KSPEM]
      ,[Date of Last Count]
      ,[Profit Center]
      ,[Created On]
      ,[SP stock value]
      ,[St.trnsfr/SP (SLoc)]
      ,[Picking area]
      ,[Invent. corr. factor]
      ,[MARDH rec. already exists for per. befor]
      ,[Fiscal year of current physical inventor]
      ,[MD PRODUCT Storage location]
      ,[Allocated Stock Quantity]
      ,[Unrestricted_/CWM/LABST]
      ,[Quality Inspection_/CWM/INSME]
      ,[Restricted-Use Stock_/CWM/EINME]
      ,[Blocked_/CWM/SPEME]
      ,[Returns_/CWM/RETME]
      ,[Stock in transfer_/CWM/UMLME]
      ,[Unrestr. Consignment_/CWM/KLABS]
      ,[Cnsgt in Inspection_/CWM/KINSM]
      ,[Restr. Consignment_/CWM/KEINM]
      ,[Blocked Consignment_/CWM/KSPEM]
      ,[Unrestr.-use stock_/CWM/VMLAB]
      ,[In quality insp._/CWM/VMINS]
      ,[Restricted-Use Stock/CWM/VMEIN]
      ,[Blocked_/CWM/VMSPE]
      ,[Returns_/CWM/VMRET]
      ,[Stock in transfer_/CWM/VMUML]
	)
	SELECT [MANDT]
      ,RIGHT([MATNR],LEN([MATNR])-CHARINDEX(LEFT(REPLACE([MATNR],'0',''),1),[MATNR])+1) --DEVTCK-17779
      ,[WERKS]
      ,[LGORT]
      ,[PSTAT]
      ,[LVORM]
      ,[LFGJA]
      ,[LFMON]
      ,[SPERR]
      ,[LABST]
      ,[UMLME]
      ,[INSME]
      ,[EINME]
      ,[SPEME]
      ,[RETME]
      ,[VMLAB]
      ,[VMUML]
      ,[VMINS]
      ,[VMEIN]
      ,[VMSPE]
      ,[VMRET]
      ,[KZILL]
      ,[KZILQ]
      ,[KZILE]
      ,[KZILS]
      ,[KZVLL]
      ,[KZVLQ]
      ,[KZVLE]
      ,[KZVLS]
      ,[DISKZ]
      ,[LSOBS]
      ,[LMINB]
      ,[LBSTF]
      ,[HERKL]
      ,[EXPPG]
      ,[EXVER]
      ,[LGPBE]
      ,[KLABS]
      ,[KINSM]
      ,[KEINM]
      ,[KSPEM]
      ,[DLINL]
      ,[PRCTL]
      ,[ERSDA]
      ,[VKLAB]
      ,[VKUML]
      ,[LWMKB]
      ,[BSKRF]
      ,[MDRUE]
      ,[MDJIN]
      ,[DUMMY_STL_INCL_EEW_PS]
      ,[FSH_SALLOC_QTY_S]
      ,[/CWM/LABST]
      ,[/CWM/INSME]
      ,[/CWM/EINME]
      ,[/CWM/SPEME]
      ,[/CWM/RETME]
      ,[/CWM/UMLME]
      ,[/CWM/KLABS]
      ,[/CWM/KINSM]
      ,[/CWM/KEINM]
      ,[/CWM/KSPEM]
      ,[/CWM/VMLAB]
      ,[/CWM/VMINS]
      ,[/CWM/VMEIN]
      ,[/CWM/VMSPE]
      ,[/CWM/VMRET]
      ,[/CWM/VMUML]
  FROM [CT dwh 01 Stage].[dbo].[tSAP_MARD]
  WITH (NOLOCK)
PRINT LTRIM(GETDATE()) + ' Finished tStorageLocationDataForMaterial' + '; rows affected: ' + cast(@@ROWCOUNT as varchar);
SET @total_rows_affected = @total_rows_affected + @@rowcount;

  --> 12.11.2020/FT: https://jira.chal-tec.com/browse/DEVTCK-17731
  -- delete all data
  TRUNCATE TABLE [CT dwh 03 Intelligence].[dbo].[tPurchasingInfoRecordGeneralData]
  /*
  -- 16.12.2020/FT: Umstellung auf die Spoon Tabelle -> https://jira.chal-tec.com/browse/DEVTCK-18053
  INSERT INTO [CT dwh 03 Intelligence].[dbo].[tPurchasingInfoRecordGeneralData]
           ([MANDT]
           ,[Purchasing info rec.]
           ,[Material]
           ,[Material Group]
           ,[Vendor]
           ,[Complete info record]
           ,[Created on]
           ,[Created by]
           ,[Info Short Text]
           ,[Sort Term]
           ,[Order Unit]
           ,[Equal To]
           ,[Denominator]
           ,[Supplier Material Number]
           ,[Salesperson]
           ,[Telephone]
           ,[1st Reminder/Exped.]
           ,[2nd Reminder/Exped.]
           ,[3rd Reminder/Exped.]
           ,[Certificate Number]
           ,[Valid to]
           ,[Country of Origin]
           ,[Certificate Category]
           ,[Number]
           ,[Base Unit of Measure]
           ,[Region]
           ,[Variable Purchase Order Unit]
           ,[Supplier Subrange]
           ,[SSR Sort Seq. Number]
           ,[Supplier Mat. Group]
           ,[Return Agreement]
           ,[Available from]
           ,[Available to]
           ,[Prior Supplier]
           ,[Points]
           ,[Points unit]
           ,[Regular Supplier]
           ,[Manufacturer]
           ,[Ext. Include]
           ,[Time Stamp]
           ,[Business Purpose Completed])
  
	SELECT [MANDT]
      ,[INFNR]
      ,[MATNR]
      ,[MATKL]
      ,[LIFNR]
      ,[LOEKZ]
      ,[ERDAT]
      ,[ERNAM]
      ,[TXZ01]
      ,[SORTL]
      ,[MEINS]
      ,[UMREZ]
      ,[UMREN]
      ,[IDNLF]
      ,[VERKF]
      ,[TELF1]
      ,[MAHN1]
      ,[MAHN2]
      ,[MAHN3]
      ,[URZNR]
      ,[URZDT]
      ,[URZLA]
      ,[URZTP]
      ,[URZZT]
      ,[LMEIN]
      ,[REGIO]
      ,[VABME]
      ,[LTSNR]
      ,[LTSSF]
      ,[WGLIF]
      ,[RUECK]
      ,[LIFAB]
      ,[LIFBI]
      ,[KOLIF]
      ,[ANZPU]
      ,[PUNEI]
      ,[RELIF]
      ,[MFRNR]
      ,[DUMMY_EINA_INCL_EEW_PS]
      ,[LASTCHANGEDATETIME]
      ,[ISEOPBLOCKED]
  FROM [CT dwh 01 Stage].[dbo].[tSAP_EINA]
  WITH (NOLOCK)
  */
  
  -- WORKING with Spoon generated table data
  INSERT INTO [CT dwh 03 Intelligence].[dbo].[tPurchasingInfoRecordGeneralData]
           (
		   [Row_ID]
		   ,[MANDT]
           ,[Purchasing info rec.]
		   ,[Points]
		   ,[Ext. Include]
           ,[Created on]
		   ,[Created by]
		   ,[Supplier Material Number]
		   ,[Business Purpose Completed]
		   ,[Prior Supplier]
		   ,[Time Stamp]
		   ,[Available from]
		   ,[Available to]
		   ,[Vendor]
		   ,[Base Unit of Measure]
		   ,[Complete info record]
		   ,[Supplier Subrange]
		   ,[SSR Sort Seq. Number]
		   ,[1st Reminder/Exped.]
           ,[2nd Reminder/Exped.]
           ,[3rd Reminder/Exped.]
		   ,[Material Group]   
		   ,[Material]       
		   ,[Order Unit]
		   ,[Manufacturer]
		   ,[Points unit]
		   ,[Region]
		   ,[Regular Supplier]
		   ,[Return Agreement]
           ,[Sort Term]
		   ,[Telephone]
		   ,[Info Short Text]
		   ,[Denominator]
		   ,[Equal To]
           ,[Valid to]
		   ,[Country of Origin]
		   ,[Certificate Number]
		   ,[Certificate Category]
           ,[Number]
		   ,[Variable Purchase Order Unit]
		   ,[Salesperson]
           ,[Supplier Mat. Group]
		   ,[Valid_From]
		   ,[Valid_To]
		   )
		   
  SELECT 
      --[row_id]
	  NULL as row_id
	  ,[MANDT]
	  ,[INFNR]
      ,[ANZPU]
      ,[DUMMY_EINA_INCL_EEW_PS]
      ,[ERDAT]
      ,[ERNAM]
      ,[IDNLF]
      ,[ISEOPBLOCKED]
      ,[KOLIF]
      ,[LASTCHANGEDATETIME]
      ,[LIFAB]
      ,[LIFBI]
      ,[LIFNR]
      ,[LMEIN]
      ,[LOEKZ]
      ,[LTSNR]
      ,[LTSSF]
      ,[MAHN1]
      ,[MAHN2]
      ,[MAHN3]
      ,[MATKL]
      ,[MATNR]
      ,[MEINS]
      ,[MFRNR]
      ,[PUNEI]
      ,[REGIO]
      ,[RELIF]
      ,[RUECK]
      ,[SORTL]
      ,[TELF1]
      ,[TXZ01]
      ,[UMREN]
      ,[UMREZ]
      ,[URZDT]
      ,[URZLA]
      ,[URZNR]
      ,[URZTP]
      ,[URZZT]
      ,[VABME]
      ,[VERKF]
      ,[WGLIF]
	  --,[Valid_From]
	  ,NULL as Valid_From
	  --,[Valid_To]
	  ,NULL as Valid_To
	--FROM [CT dwh 02 Data].[dbo].[tSAPEINA]
	FROM [CT dwh 01 Stage].[dbo].[tSAP_EINA]
	WITH (NOLOCK)
	where MANDT is not null
	-- 16.11.2021/FT: Umstellung von Data auf Stage
	--and valid_to = '2200-01-01' and is_deleted = 0
PRINT LTRIM(GETDATE()) + ' Finished tPurchasingInfoRecordGeneralData' + '; rows affected: ' + cast(@@ROWCOUNT as varchar);
SET @total_rows_affected = @total_rows_affected + @@rowcount;
	

	TRUNCATE TABLE [CT dwh 03 Intelligence].[dbo].[tPurchasingInfoRecordPurchasingOrganizationData]

	INSERT INTO [CT dwh 03 Intelligence].[dbo].[tPurchasingInfoRecordPurchasingOrganizationData]
	(
			--[Row_ID]
		   --,
		   [MANDT]
           ,[Purchasing info rec.]
           ,[Purch. organization]
           ,[Info record category]
           ,[Plant]
           ,[Purch. org. data]
           ,[Created on]
           ,[Created by]
           ,[Purchasing Group]
           ,[Currency]
           ,[Volume Rebate Ind.]
           ,[Quantity Rebate Ind.]
           ,[Minimum Order Qty]
           ,[Standard PO Quantity]
           ,[Planned Deliv. Time]
           ,[Overdeliv. Tolerance]
           ,[Unltd Overdelivery]
           ,[Underdel. Tolerance]
           ,[Quotation]
           ,[Quotation Valid from]
           ,[RFQ]
           ,[Item_ANFPS]
           ,[Rejection Indicator]
           ,[Amort. period from]
           ,[Amort. period to]
           ,[Amortized plan qty.]
           ,[Amortized plan value]
           ,[Amortized actual qty]
           ,[Amortized act. value]
           ,[Amortization reset]
           ,[Purch. Doc. Category]
           ,[Purchasing Document]
           ,[Item_EBELP]
           ,[Date of Document]
           ,[Net Price]
           ,[Price unit]
           ,[Order Price Unit]
           ,[Valid to]
           ,[Quantity Conversion_BPUMZ]
           ,[Quantity Conversion_BPUMN]
           ,[No Material Text]
           ,[GR-Based Inv. Verif.]
           ,[Effective Price]
           ,[Condition Group]
           ,[No Cash Discount]
           ,[Acknowledgment Reqd]
           ,[Tax Code]
           ,[Valuation Type]
           ,[Settlement Group 1]
           ,[Shipping Instr.]
           ,[Procedure]
           ,[Confirmation Control]
           ,[Pricing Date Control]
           ,[Incoterms]
           ,[Incoterms (Part 2)]
           ,[No ERS]
           ,[Settlement Group 2]
           ,[Settlement Group 3]
           ,[No Subsequent Sett.]
           ,[Min. Rem. Shelf Life]
           ,[Production Version]
           ,[Max. Order Quantity]
           ,[Rounding Profile]
           ,[Unit of Measure Grp]
           ,[NCM Code]
           ,[New PO for inc. Del.]
           ,[Period Ind. for SLED]
           ,[Real-Time Cons.Post.]
           ,[Supplier RMA Number Required]
           ,[Differential Invoicing]
           ,[Incoterms Version]
           ,[Incoterms Location 1]
           ,[Incoterms Location 2]
           ,[Automatic Sourcing]
           ,[Ext. Include]
           ,[Business Purpose Completed]
           ,[Correlate DCI indicator]
           ,[Replenishment Lead Time for Raw Material]
           ,[Manufacturing Lead Time]
           ,[Packing Lead Time]
           ,[Transportation Lead Time]
           ,[Max Retail Price  Relevance]
           ,[Stock Segment Relevant Indicator]
           ,[Transportation Chain]
           ,[Staging Time]
		  -- ,[ValidFrom]
		  -- ,[ValidTo]
	)
	SELECT 
	   --[row_id]
	  --,
	  [MANDT]
      ,[INFNR]
      ,[EKORG]
      ,[ESOKZ]
      ,[WERKS]
      ,[LOEKZ]
      ,[ERDAT]
      ,[ERNAM]
      ,[EKGRP]
      ,[WAERS]
      ,[BONUS]
      ,[MGBON]
      ,[MINBM]
      ,[NORBM]
      ,[APLFZ]
      ,[UEBTO]
      ,[UEBTK]
      ,[UNTTO]
      ,[ANGNR]
      ,[ANGDT]
      ,[ANFNR]
      ,[ANFPS]
      ,[ABSKZ]
      ,[AMODV]
      ,[AMODB]
      ,[AMOBM]
      ,[AMOBW]
      ,[AMOAM]
      ,[AMOAW]
      ,[AMORS]
      ,[BSTYP]
      ,[EBELN]
      ,[EBELP]
      ,[DATLB]
      ,[NETPR]
      ,[PEINH]
      ,[BPRME]
      ,[PRDAT]
      ,[BPUMZ]
      ,[BPUMN]
      ,[MTXNO]
      ,[WEBRE]
      ,[EFFPR]
      ,[EKKOL]
      ,[SKTOF]
      ,[KZABS]
      ,[MWSKZ]
      ,[BWTAR]
      ,[EBONU]
      ,[EVERS]
      ,[EXPRF]
      ,[BSTAE]
      ,[MEPRF]
      ,[INCO1]
      ,[INCO2]
      ,[XERSN]
      ,[EBON2]
      ,[EBON3]
      ,[EBONF]
      ,[MHDRZ]
      ,[VERID]
      ,[BSTMA]
      ,[RDPRF]
      ,[MEGRU]
      ,[J_1BNBM]
      ,[SPE_CRE_REF_DOC]
      ,[IPRKZ]
      ,[CO_ORDER]
      ,[VENDOR_RMA_REQ]
      ,[DIFF_INVOICE]
      ,[INCOV]
      ,[INCO2_L]
      ,[INCO3_L]
      ,[AUT_SOURCE]
      ,[DUMMY_EINE_INCL_EEW_PS]
      ,[ISEOPBLOCKED]
      ,[FSH_DCI_CORR]
      ,[FSH_RLT]
      ,[FSH_MLT]
      ,[FSH_PLT]
      ,[FSH_TLT]
      ,[MRPIND]
      ,[SGT_SSREL]
      ,[TRANSPORT_CHAIN]
      ,[STAGING_TIME]
	  --,[Valid_From]
	 -- ,[Valid_To]
  FROM [CT dwh 01 Stage].[dbo].[tSAP_EINE]
  WITH (NOLOCK)
PRINT LTRIM(GETDATE()) + ' Finished tPurchasingInfoRecordPurchasingOrganizationData' + '; rows affected: ' + cast(@@ROWCOUNT as varchar);
SET @total_rows_affected = @total_rows_affected + @@rowcount;

	-- ArticleMasterData // 16.12.2020 -> https://jira.chal-tec.com/browse/DEVTCK-18055
	TRUNCATE TABLE [CT dwh 03 Intelligence].[dbo].[tArticleMasterData]

	INSERT INTO [CT dwh 03 Intelligence].[dbo].[tArticleMasterData]
	(
			[MANDT]
		  -- MARC
		  ,[Material]
		  ,[Plant]
		 -- ,[Maintenance status]
		  ,[Valuation Category]
		  ,[Batch Management]
		  ,[Plant-sp.matl status]
		  ,[Purchasing Group]
		  ,[MRP Type]
		  ,[MRP Controller]
		  ,[Planned Deliv. Time]
		  ,[GR processing time]
		  ,[Period Indicator]
		  ,[Assembly scrap (%)]
		  ,[Lot Sizing Procedure]
		  ,[Procurement type]
		  ,[Minimum Lot Size]
		  ,[Loading Group]
		  ,[Availability check]
		  ,[Base quantity]
		  ,[Processing time]
		  ,[Commodity Code]
		  ,[Country of origin]
		  ,[Profit Center]
		  ,[Planning Strategy Group]
		  ,[Internal object no.]
		  ,[Storage loc. for EP]
		  ,[Current period]
		  ,[Year current period]
		  ,[Valuated Goods Receipt Blocked Stock]
		  ,[Segmentation Strategy]
		  ,[Seg. Status MRP]
		  --,[Segmentation Strategy Scope]
		  --,[Product]
		  ,[Location Product ID]
		  -- 33 + MANDT
		  -- MARA
		  ,[Created On]
		  ,[Created by]
		  ,[Last Change]
		  ,[Changed by]
		  ,[Compl. maint. status]
		  ,[Maintenance status]
		  ,[DF at client level]
		  ,[Material type]
		  ,[Industry Sector]
		  ,[Material Group]
		  ,[Old material number]
		  ,[Base Unit of Measure]
		  ,[Gross weight]
		  ,[Weight unit]
		  ,[Volume]
		  ,[Volume Unit]
		  ,[Transportation Group]
		  ,[EAN/UPC]
		  ,[EAN category]
		  ,[Length]
		  ,[Width]
		  ,[Height]
		  ,[Unit of Dimension]
		  ,[Product hierarchy]
		  ,[Allowed pkg weight]
		  ,[Allowed pkg volume]
		  ,[X-Plant Matl Status]
		  ,[Qual.f.FreeGoodsDis.]
		  ,[Gen. item cat. grp]
		  ,[Last Changed Time]
		  ,[Segmentation Status]
		  ,[Segmentation Strategy Scope]
		  ,[Segmentation Relevant]
		  ,[Product]
		  ,[Product ID]
		  )
	select 
		 MARC.MANDT
		-- MARC
		,MARC.MATNR	
		,MARC.WERKS	
		--,MARC.PSTAT	
		,MARC.BWTTY	
		,MARC.XCHAR	
		,MARC.MMSTA	
		,MARC.EKGRP	
		,MARC.DISMM	
		,MARC.DISPO	
		,MARC.PLIFZ	
		,MARC.WEBAZ	
		,MARC.PERKZ	
		,MARC.AUSSS	
		,MARC.DISLS	
		,MARC.BESKZ	
		,MARC.BSTMI	
		,MARC.LADGR	
		,MARC.MTVFP	
		,MARC.VBAMG	
		,MARC.VBEAZ	
		,MARC.STAWN	
		,MARC.HERKL	
		,MARC.PRCTR	
		,MARC.STRGR	
		,MARC.CUOBV	
		,MARC.LGFSB	
		,MARC.LFMON	
		,MARC.LFGJA	
		,MARC.BWESB	
		,MARC.SGT_COVS	
		,MARC.SGT_STATC	
		--,MARC.SGT_SCOPE	
		--,MARC.SCM_MATLOCID_GUID16	
		,MARC.SCM_MATLOCID_GUID22
		-- 33 + MANDT
		-- MARA
		,MARA.ERSDA	
		,MARA.ERNAM	
		,MARA.LAEDA	
		,MARA.AENAM	
		,MARA.VPSTA	
		,MARA.PSTAT	
		,MARA.LVORM	
		,MARA.MTART	
		,MARA.MBRSH	
		,MARA.MATKL	
		,MARA.BISMT	
		,MARA.MEINS	
		,MARA.BRGEW	
		,MARA.GEWEI	
		,MARA.VOLUM	
		,MARA.VOLEH	
		,MARA.TRAGR	
		,MARA.EAN11	
		,MARA.NUMTP	
		,MARA.LAENG	
		,MARA.BREIT	
		,MARA.HOEHE	
		,MARA.MEABM	
		,MARA.PRDHA	
		,MARA.ERGEW	
		,MARA.ERVOL	
		,MARA.MSTAE	
		,MARA.NRFHG	
		,MARA.MTPOS_MARA	
		,MARA.LAST_CHANGED_TIME	
		,MARA.SGT_STAT	
		,MARA.SGT_SCOPE	
		,MARA.SGT_REL
		,MARA.SCM_MATID_GUID16
		,MARA.SCM_MATID_GUID22
		-- 35
	from 
		[CT dwh 01 Stage].[dbo].[tSAP_MARC] marc with (nolock)
	inner join 
		[CT dwh 01 Stage].[dbo].[tSAP_MARA] mara with (nolock) 
	on marc.MATNR = mara.MATNR
PRINT LTRIM(GETDATE()) + ' Finished tArticleMasterData' + '; rows affected: ' + cast(@@ROWCOUNT as varchar);
SET @total_rows_affected = @total_rows_affected + @@rowcount;

	-- 16.12.2020/FT: new Kitting Table -> https://jira.chal-tec.com/browse/DEVTCK-18017
	TRUNCATE TABLE [CT dwh 03 Intelligence].[dbo].[tDeliveryNotesKittingTemp]

	;with cte as (
	select OutboundDeliveryNoteDocumentNo as Bel from [CT dwh 03 Intelligence].dbo.vFactPurchasingOrdersTransactions with (nolock) where OutboundDeliveryNoteDocumentType = 'OutboundDeliveryNote' and OutboundDeliveryNoteDocumentNo is not null and [source] = 'SAP'
	union
	select DeliveryNoteDocumentNo as Bel from [CT dwh 03 Intelligence].dbo.vFactPurchasingOrdersTransactions with (nolock) where DeliveryNoteDocumentType = 'DeliveryNote' and DeliveryNoteDocumentNo is not null and [source] = 'SAP'
	)
	INSERT INTO [CT dwh 03 Intelligence].[dbo].[tDeliveryNotesKittingTemp] (
		  [MANDT]
		  ,[Actual_Goods_Movement_Date]
		  ,[Bill_of_Lading_(BOLNR)]
		  ,[Bill_of_Lading_(ZZ_LIEFNR)]
		  ,[Document_Changed_by]
		  ,[Document_Changed_on]
		  ,[Company_ID]
		  ,[Document_created_by]
		  ,[Document_created_on]
		  ,[customer_intercompany_billing_nb]
		  ,[Date_of_unloading]
		  ,[Delivery_Location_Time_Zone]
		  ,[Delivery]
		  ,[Delivery_Date]
		  ,[Delivery_Type]
		  ,[Depreciation_percentage]
		  ,[Distribution_Channel]
		  ,[Document_Currency]
		  ,[Document_Date]
		  ,[ETA_Port]
		  ,[Exchange_rate_stats]
		  ,[External_Delivery_ID]
		  ,[Forwarder_Reference]
		  ,[ID:_Delivery_Split,_Warehouse_No.]
		  ,[Incoterms]
		  ,[Incoterms_(Part_2)]
		  ,[Incoterms_Location_1]
		  ,[Incoterms_Version]
		  ,[Division_for_intercompany_billing]
		  ,[Intercompany_billing_type]
		  ,[Containernumber]
		  ,[Containertype]
		  ,[Net_weight]
		  ,[Order_Combination]
		  ,[Original_document]
		  ,[POD_Confirmation_Time]
		  ,[Procedure]
		  ,[Proof_of_Delivery_Date]
		  ,[Time_zone_of_recipient_location]
		  ,[Receiving_Plant]
		  ,[Sales_organization]
		  ,[Sales_Organization_for_intercmopany_billing]
		  ,[SD_Document_Category]
		  ,[Shipping_Point/Receiving_Pt]
		  ,[Ship-to_party]
		  ,[Statistics_Currency]
		  ,[Status_of_delivery_note]
		  ,[Telex_release]
		  ,[Document_creation_time]
		  ,[Total_Weight]
		  ,[Vendor]
		  ,[Vessel]
		  ,[Total_Volume]
		  ,[Total_Volume_Unit]
		  ,[Warehouse_Number]
		  ,[Total_Weight_Unit]
		  -- LIPS
		  ,[Actual_Delivery_QTY_in_packaging_unit_of_measure]
		  ,[Base_Unit_of_Measure]
		  ,[Batch]
		  ,[Item_changed_on]
		  ,[Item_created_by]
		  ,[Item_created_on]
		  ,[Actual_Delivery_QTY_in_storage_unit]
		  ,[original_delivery_QTY]
		  ,[EAN/UPC]
		  ,[Item_gross_weight]
		  ,[Item]
		  ,[Item_Category]
		  ,[Item_Description]
		  ,[Material]
		  ,[Material_Group]
		  ,[Movement_type]
		  ,[Production_Order]
		  ,[Production_Order_Item_Nb]
		  ,[Plant]
		  ,[Product_hierarchy]
		  ,[Profit_Center]
		  ,[Reference_document]
		  ,[Reference_Item]
		  ,[Storage_location]
		  ,[Item_creation_time]
		  ,[Item_Volume]
		  ,[Item_Volume_Unit]
		  ,[Item_Weight_Unit]
	 )
	SELECT
		 LIKP.MANDT
		,LIKP.WADAT_IST
		,LIKP.BOLNR
		,LIKP.ZZ_LIEFNR
		,LIKP.AENAM
		,LIKP.AEDAT
		,LIKP.VBUND
		,LIKP.ERNAM
		,LIKP.ERDAT
		,LIKP.KUNIV
		,LIKP.ZZ_LOESCHDATE
		,LIKP.TZONIS
		,LIKP.VBELN
		,LIKP.LFDAT
		,LIKP.LFART
		,LIKP.AKPRZ
		,LIKP.VTWIV
		,LIKP.WAERK
		,LIKP.BLDAT
		,LIKP.ZZ_ETAPORT
		,LIKP.STCUR
		,LIKP.LIFEX
		,LIKP.ZZ_SPEDIREFERENZ
		,LIKP.LISPL
		,LIKP.INCO1
		,LIKP.INCO2
		,LIKP.INCO2_L
		,LIKP.INCOV
		,LIKP.SPAIV
		,LIKP.FKAIV
		,LIKP.TRAID
		,LIKP.TRATY
		,LIKP.NTGEW
		,LIKP.KZAZU
		,LIKP.VERUR
		,LIKP.POTIM
		,LIKP.KALSM
		,LIKP.PODAT
		,LIKP.TZONRC
		,LIKP.WERKS
		,LIKP.VKORG
		,LIKP.VKOIV
		,LIKP.VBTYP
		,LIKP.VSTEL
		,LIKP.KUNNR
		,LIKP.STWAE
		,LIKP.VLSTK
		,LIKP.ZZ_TELEXREL
		,LIKP.ERZET
		,LIKP.BTGEW
		,LIKP.LIFNR
		,LIKP.ZZ_SCHIFF
		,LIKP.VOLUM
		,LIKP.VOLEH
		,LIKP.LGNUM
		,LIKP.GEWEI
		-- LIPS
		,LIPS.LGMNG
		,LIPS.MEINS
		,LIPS.CHARG
		,LIPS.AEDAT
		,LIPS.ERNAM
		,LIPS.ERDAT
		,LIPS.LFIMG
		,LIPS.ORMNG
		,LIPS.EAN11
		,LIPS.BRGEW
		,LIPS.POSNR
		,LIPS.PSTYV
		,LIPS.ARKTX
		,LIPS.MATNR
		,LIPS.MATKL
		,LIPS.BWART
		,LIPS.AUFNR
		,LIPS.POSNR_PP
		,LIPS.WERKS
		,LIPS.PRODH
		,LIPS.PRCTR
		,LIPS.VGBEL
		,LIPS.VGPOS
		,LIPS.LGORT
		,LIPS.ERZET
		,LIPS.VOLUM
		,LIPS.VOLEH
		,LIPS.GEWEI
	from 
		[CT dwh 01 Stage].[dbo].[tSAP_LIPS] LIPS WITH (NOLOCK)
	INNER JOIN
		[CT dwh 01 Stage].[dbo].[tSAP_LIKP] AS LIKP WITH (NOLOCK)
	ON
		LIPS.MANDT     = LIKP.MANDT
		AND LIPS.VBELN = LIKP.VBELN
	left outer join
		cte on cte.Bel = LIPS.VBELN
	where 
		lips.MATNR like '00000000007%'
	-- only show datasets without information in vFactPurchasingOrdersTransactions
	and cte.bel is null
PRINT LTRIM(GETDATE()) + ' Finished tDeliveryNotesKittingTemp' + '; rows affected: ' + cast(@@ROWCOUNT as varchar);
SET @total_rows_affected = @total_rows_affected + @@rowcount;


	--###################
	-- 13.01.2021/FT: https://jira.chal-tec.com/browse/DEVTCK-18139
	TRUNCATE TABLE [CT dwh 03 Intelligence].[dbo].tContract
	
	INSERT INTO [CT dwh 03 Intelligence].[dbo].[tContract]
           ([PurchasingDocument]
           ,[Item]
           ,[EffectiveValue]
           ,[PurchOrganization]
           ,[Incoterms]
           ,[IncotermsPart2]
           ,[IncotermsLocation1]
           ,[IncotermsLocation2]
           ,[IncotermsVersion]
           ,[PurchasingInfoRec]
           ,[DocConditionNo]
           ,[ProfitCenter]
           ,[StorageLocation]
           ,[Vendor]
           ,[MaterialGroup]
           ,[Material]
           ,[NetOrderPrice]
           ,[SupplyingPlant]
           ,[CommodityCode]
           ,[DocumentItem]
           ,[VolumeUnit]
           ,[Volume]
           ,[Currency]
           ,[GRMessage]
           ,[Plant]
           ,[ExchangeRate]
           ,[PaymentIn]
           ,[Discpercent2]
           ,[PaymentTerms]
           ,[Kontraktnummer]
           ,[GrossWeight]
           ,[GrossOrderValue]
           ,[PurchDocCategory]
           ,[CompanyCode])
	select 
		 EKPO.EBELN		as PurchasingDocument
		,EKPO.EBELP		as Item
		,EKPO.EFFWR		as EffectiveValue
		,EKKO.EKORG		as PurchOrganization
		,EKPO.INCO1		as Incoterms
		,EKKO.INCO2		as IncotermsPart2
		,EKKO.INCO2_L	as IncotermsLocation1
		,EKKO.INCO3_L	as IncotermsLocation2
		,EKKO.INCOV		as IncotermsVersion
		,EKPO.INFNR		as PurchasingInfoRec
		,EKKO.KNUMV		as DocConditionNo
		,EKPO.KO_PRCTR	as ProfitCenter
		,EKPO.LGORT		as StorageLocation
		,EKKO.LIFNR		as Vendor
		,EKPO.MATKL		as MaterialGroup
		,EKPO.MATNR		as Material
		,EKPO.NETPR		as NetOrderPrice
		,EKKO.RESWK		as SupplyingPlant
		,EKPO.STAWN		as CommodityCode
		,EKPO.UNIQUEID	as DocumentItem
		,EKPO.VOLEH		as VolumeUnit
		,EKPO.VOLUM		as Volume
		,EKKO.WAERS		as Currency
		,EKKO.WEAKT		as GRMessage
		,EKPO.WERKS		as Plant
		,EKKO.WKURS		as ExchangeRate
		,EKKO.ZBD1T		as PaymentIn
		,EKKO.ZBD2P		as Discpercent2
		,EKKO.ZTERM		as PaymentTerms
		,EKKO.ZZKONNR	as Kontraktnummer
		,EKPO.BRGEW		as GrossWeight
		,EKPO.BRTWR		as GrossOrderValue
		,EKKO.BSTYP		as PurchDocCategory
		,EKPO.BUKRS		as CompanyCode 
	from 
		[CT dwh 01 Stage].dbo.tSAP_EKPO ekpo with (nolock)
	join 
		[CT dwh 01 Stage].dbo.tSAP_EKKO ekko with (nolock) 
	on 
		ekko.EBELN = ekpo.EBELN
	where 
		ekpo.LOEKZ = '' 
	and ekko.LOEKZ = ''
	and ekko.BSTYP = 'K'
	-- 16.11.2021/FT: Umstellung von Data auf Stage
	--and ekpo.valid_to = '22000101'
	--and ekpo.is_deleted = 0
	--and ekko.valid_to = '22000101'
	--and ekko.is_deleted = 0
PRINT LTRIM(GETDATE()) + ' Finished tContract' + '; rows affected: ' + cast(@@ROWCOUNT as varchar);
SET @total_rows_affected = @total_rows_affected + @@rowcount;

DECLARE @db_id INT = DB_ID()
EXEC [CT dwh 00 Meta]..sp_Log_ProcedureCall
    @object_id = @@PROCID,
    @database_id = @db_id,
    @total_rows_affected = @total_rows_affected,
    @start_time = @start_time
    -- @log_message = '';

END

