/****** Object:  Table [L1].[L1_FACT_F_BUSINESS_PLAN_KPI]    Script Date: 16/10/2024 12:14:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [L1].[L1_FACT_F_BUSINESS_PLAN_KPI_CALCULATION]
(
	[D_SNAPSHOT] [date] NULL,
	[ID_COMPANY] [int] NULL,
	[D_TARGET] [date] NULL,
	[PCT_QTY]	decimal(19,2),
	[PCT_PRICE]	decimal(19,2),
	[CD_SOURCE] [varchar](50) NULL,
	[ID_ITEM] [int] NULL,
	[ID_ITEM_BUSINESS_PLAN] [int] NULL,
	[CD_FULFILLMENT] [varchar](5) NULL,
	[T_REVISED_LOCATION] [varchar](50) NULL,
	[CD_COUNTRY_GROUP] [varchar](50) NULL,
	[CD_CHANNEL_GROUP_3] [varchar](50) NULL,
	[CD_CURRENCY] [varchar](5) NULL,
	[VL_ITEM_QUANTITY] [decimal](19, 2) NULL,
	[VL_BASE_ITEM_QUANTITY] [decimal](19, 2) NULL,
	[AMT_PLAN_PRICE_EUR] [decimal](19, 2) NULL,
	[AMT_BASE_PLAN_PRICE_EUR] [decimal](19, 2) NULL,
	[AMT_SHIPPING_COST_EST_EUR] [decimal](19, 2) NULL,
	[AMT_MEK_HEDGING_EUR] [decimal](19, 2) NULL,
	[AMT_GTS_MARKUP_EUR] [decimal](19, 2) NULL,
	[VL_CANCELLED_ORDERS_QUANTITY_EST] [decimal](19, 2) NULL,
	[VL_NET_ORDER_QUANTITY] [decimal](19, 2) NULL,
	[VL_REFUNDED_QUANTITY_EST] [decimal](19, 2) NULL,
	[VL_RETURNED_QUANTITY_EST] [decimal](19, 2) NULL,
	[VL_REPLACEMENT_ORDER_QUANTITY_EST] [decimal](19, 2) NULL,
	[AMT_GROSS_ORDER_VALUE_EUR] [decimal](19, 2) NULL,
	[AMT_CANCELLED_ORDER_VALUE_EST_EUR] [decimal](19, 2) NULL,
	[AMT_BASE_NET_ORDER_VALUE_EST_EUR] [decimal](19, 2) NULL,
	[AMT_NET_ORDER_VALUE_EST_EUR] [decimal](19, 2) NULL,
	[AMT_REFUNDED_ORDER_VALUE_EST_EUR] [decimal](19, 2) NULL,
	[AMT_REVENUE_EST_EUR] [decimal](19, 2) NULL,
	[AMT_DEPRECIATION_EST_EUR] [decimal](19, 2) NULL,
	[AMT_NET_PRODUCT_COST_EST_EUR] [decimal](19, 2) NULL,
	[AMT_PC0_EST_EUR] [decimal](19, 2) NULL,
	[AMT_DEMURRAGE_DETENTION_EUR] [decimal](19, 2) NULL,
	[AMT_DEADFREIGHT_EUR] [decimal](19, 2) NULL,
	[AMT_KICKBACKS_EUR] [decimal](19, 2) NULL,
	[AMT_3RD_PARTY_SERVICES_EUR] [decimal](19, 2) NULL,
	[AMT_RETURN_MERCHANDISE_AUTHORIZATION_EUR] [decimal](19, 2) NULL,
	[AMT_SAMPLES_EUR] [decimal](19, 2) NULL,
	[AMT_OTHER_COGS_EFFECT_EST_EUR] [decimal](19, 2) NULL,
	[AMT_DROPSHIPMENT_CEOTRA9ER_EST_EUR] [decimal](19, 2) NULL,
	[AMT_INBOUND_FREIGHT_COST_EST_EUR] [decimal](19, 2) NULL,
	[AMT_PO_CANCELLATION_EUR] [decimal](19, 2) NULL,
	[AMT_STOCK_ADJUSTMENT_EUR] [decimal](19, 2) NULL,
	[AMT_FX_HEDGING_IMPACT_EST_EUR] [decimal](19, 2) NULL,
	[AMT_COGS_STOCK_VALUE_ADJUSTMENT_EST_EUR] [decimal](19, 2) NULL,
	[AMT_COGS_OPERATIONS_EST] [decimal](19, 2) NULL,
	[AMT_PC1_EST_EUR] [decimal](19, 2) NULL,
	[AMT_PACKAGING_EUR] [decimal](19, 2) NULL,
	[AMT_HANDLING_ORDERS_EST_EUR] [decimal](19, 2) NULL,
	[AMT_HANDLING_INBOUND_EST_EUR] [decimal](19, 2) NULL,
	[AMT_HANDLING_TRANS_SHIPPMENT_EST_EUR] [decimal](19, 2) NULL,
	[AMT_TRUCKING_TRANS_SHIPMENT_EST_EUR] [decimal](19, 2) NULL,
	[AMT_HANDLING_RETURNS_EST_EUR] [decimal](19, 2) NULL,
	[AMT_WAREHOUSING_FBA_EUR] [decimal](19, 2) NULL,
	[AMT_FULFILLMENT_OUTBOUND_EST_EUR] [decimal](19, 2) NULL,
	[AMT_COMMISSIONS_MARKETPLACES_EUR] [decimal](19, 2) NULL,
	[AMT_COMMISSIONS_MARKETPLACES_REFUNDS_EUR] [decimal](19, 2) NULL,
	[AMT_MARKETING_MARKETPLACES_EST_EUR] [decimal](19, 2) NULL,
	[AMT_COMMISSIONS_AMAZON_EUR] [decimal](19, 2) NULL,
	[AMT_COMMISSIONS_AMAZON_REFUNDS_EUR] [decimal](19, 2) NULL,
	[AMT_SHOP_MARKETING_EUR] [decimal](19, 2) NULL,
	[AMT_CS_HANDLING_CLAIMS_EUR] [decimal](19, 2) NULL,
	[AMT_PAYMENTS_EUR] [decimal](19, 2) NULL,
	[AMT_AMAZON_MARKETING_COSTS_EUR] [decimal](19, 2) NULL,
	[AMT_ENVIRO_AND_LICENSE_COST_EST_EUR] [decimal](19, 2) NULL,
	[AMT_PC2_EST_EUR] [decimal](19, 2) NULL,
	[AMT_WAREHOUSING_RENT_EST_EUR] [decimal](19, 2) NULL,
	[AMT_WAREHOUSING_OPEX_EST_EUR] [decimal](19, 2) NULL,
	[AMT_CS_MANAGEMENT_EST_EUR] [decimal](19, 2) NULL,
	[AMT_MARKETING_FIXED_COST_EST_EUR] [decimal](19, 2) NULL,
	[AMT_NET_ORDER_CONTRIBUTION_EST_EUR] [decimal](19, 2) NULL,
	[AMT_PC3_EST_EUR] [decimal](19, 2) NULL,
	[DT_DWH_CREATED] [smalldatetime] NOT NULL,
	[DT_DWH_UPDATED] [smalldatetime] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH ( [D_SNAPSHOT] ),
	CLUSTERED COLUMNSTORE INDEX
)
GO


