CREATE TABLE [L0].[L0_S4HANA_2LIS_02_HDR]
(
	[ROCANCEL] VARCHAR(250) NULL,
	[HDRVORG] VARCHAR(250) NULL,
	[ALIEF] [numeric](9, 0) NULL,
	[ARECH] [int] NULL,
	[BEDAT] VARCHAR(250) NULL,
	[BSART] VARCHAR(250) NULL,
	[BSTYP] VARCHAR(250) NULL,
	[BUDAT] VARCHAR(250) NULL,
	[EBELN] VARCHAR(250) NULL,
	[EKGRP] VARCHAR(250) NULL,
	[EKORG] VARCHAR(250) NULL,
	[KDATB] VARCHAR(250) NULL,
	[KDATE] VARCHAR(250) NULL,
	[LBLIF] VARCHAR(250) NULL,
	[LIFNR] VARCHAR(250) NULL,
	[LIFRE] VARCHAR(250) NULL,
	[LLIEF] VARCHAR(250) NULL,
	[LOGSY] VARCHAR(250) NULL,
	[ORGLOGSY] VARCHAR(250) NULL,
	[RESWK] VARCHAR(250) NULL,
	[STATU] VARCHAR(250) NULL,
	[SYDAT] VARCHAR(250) NULL,
	[WAERS] VARCHAR(250) NULL,
	[WKURS] [numeric](9, 5) NULL,
	[BRESWK] VARCHAR(250) NULL,
	[BSAKZ] VARCHAR(250) NULL,
	[BUKRS] VARCHAR(250) NULL,
	[FRGRL] VARCHAR(250) NULL,
	[FSH_ITEM_GROUP] VARCHAR(250) NULL,
	[HWAER] VARCHAR(250) NULL,
	[KALSM] VARCHAR(250) NULL,
	[KNUMV] VARCHAR(250) NULL,
	[KONZS] VARCHAR(250) NULL,
	[KORNR] VARCHAR(250) NULL,
	[KTWRT] [numeric](15, 2) NULL,
	[KUFIX] VARCHAR(250) NULL,
	[KUNNR] VARCHAR(250) NULL,
	[KZKPF] VARCHAR(250) NULL,
	[LAND1] VARCHAR(250) NULL,
	[LOEKZ] VARCHAR(250) NULL,
	[MEMORY] VARCHAR(250) NULL,
	[REVNO] VARCHAR(250) NULL,
	[STAFO] VARCHAR(250) NULL,
	[STAKO] VARCHAR(250) NULL,
	[SUBMI] VARCHAR(250) NULL,
	[ZZ_DPAMT] [numeric](23, 2) NULL,
	[ZZ_DPPCT] [numeric](5, 2) NULL,
	[ZZ_DPTYP] VARCHAR(250) NULL,
	[ZZ_FRGGR] VARCHAR(250) NULL,
	[ZZ_FRGKE] VARCHAR(250) NULL,
	[ZZ_INCO2] VARCHAR(250) NULL,
	[ZZ_INCOV] VARCHAR(250) NULL,
	[ZZ_LASTCHANGEDATETIME] [numeric](21, 7) NULL,
	[NOHDR] [numeric](7, 0) NULL,
	[PWLIF] VARCHAR(250) NULL,
	[PREST] VARCHAR(250) NULL,
	[PLIWK] VARCHAR(250) NULL,
	[PLIEF] VARCHAR(250) NULL,
	[PBEST] VARCHAR(250) NULL,
	[PERIV] VARCHAR(250) NULL,
	[ZZDPTYP] VARCHAR(250) NULL,
	[ZZDPPER] [numeric](5, 2) NULL,
	[ZZDPFIX] [numeric](11, 2) NULL,
	[ZZDPDAT] VARCHAR(250) NULL,
	[ZZKONNR] VARCHAR(250) NULL,
	[ZZPRQNO] VARCHAR(250) NULL,
	[ZZSUPPLIER_REF] VARCHAR(250) NULL,
	[ZZFORWARDER_REF] VARCHAR(250) NULL,
	[ZZETD] VARCHAR(250) NULL,
	[ZZCONTRACT_REFERENCE] VARCHAR(250) NULL,
	[ZZTRANSPORT_MODE] VARCHAR(250) NULL,
	[ZZETA] VARCHAR(250) NULL,
	[ZZPORT_OF_LOADING] VARCHAR(250) NULL,
	[ZZPORT_OF_DISCHARG] VARCHAR(250) NULL,
	[ZZ_ZTERM] VARCHAR(250) NULL,
	[ZZ_ZBD1T] [numeric](3, 0) NULL,
	[ZZ_AEDAT] VARCHAR(250) NULL,
	[ZZ_WEAKT] VARCHAR(250) NULL,
	[LOAD_TIMESTAMP] [datetime] NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO


INSERT INTO [MD].[MD_L0_LOAD_LIST]
           ([TableName]
           ,[SchemaName]
           ,[FolderPath]
           ,[Is_Active]
           ,[EntityName]
           ,[KeyColumns]
           ,[PipelineLastRun])
     VALUES
           ('L0_S4HANA_2LIS_02_HDR_FULL'
           ,'TEST'
           ,'curated/s4hana_theobald/cbp/2lis_02_hdr_temp'
           ,0
           ,'SAP'
           ,'EBELN'
           ,'2024-01-01')

--select * from [MD].[MD_L0_LOAD_LIST] where tablename Like'L0_S4HANA_2LIS_02_ITM%'

update [MD].[MD_L0_LOAD_LIST]set [KeyColumns] = 'EBELN,EBELP' where [TableName] = 'L0_S4HANA_2LIS_02_HDR'
