CREATE TABLE [TEST].[L0_S4HANA_2LIS_02_ITM_FULL]
(
	[ROCANCEL] [nvarchar](1) NULL,
	[BEDAT] [date] NULL,
	[BSART] [nvarchar](4) NULL,
	[BSTYP] [nvarchar](1) NULL,
	[BUDAT] [date] NULL,
	[EBELN] [nvarchar](10) NOT NULL,
	[EKGRP] [nvarchar](3) NULL,
	[EKORG] [nvarchar](4) NULL,
	[HWAER] [nvarchar](5) NULL,
	[KDATB] [date] NULL,
	[KDATE] [date] NULL,
	[LBLIF] [nvarchar](10) NULL,
	[LIFNR] [nvarchar](10) NULL,
	[LIFRE] [nvarchar](10) NULL,
	[LLIEF] [nvarchar](10) NULL,
	[LOGSY] [nvarchar](10) NULL,
	[ORGLOGSY] [nvarchar](10) NULL,
	[RESWK] [nvarchar](4) NULL,
	[STATU] [nvarchar](1) NULL,
	[SYDAT] [date] NULL,
	[WAERS] [nvarchar](5) NULL,
	[WKURS] [numeric](9, 5) NULL,
	[BRESWK] [nvarchar](4) NULL,
	[BSAKZ] [nvarchar](1) NULL,
	[BUKRS] [nvarchar](4) NULL,
	[KALSM] [nvarchar](6) NULL,
	[KNUMV] [nvarchar](10) NULL,
	[KTWRT] [numeric](15, 2) NULL,
	[SUBMI] [nvarchar](10) NULL,
	[AFNAM] [nvarchar](12) NULL,
	[AKTNR] [nvarchar](10) NULL,
	[AKTWE] [numeric](13, 3) NULL,
	[ALAV] [numeric](3, 0) NULL,
	[ALIEF] [numeric](9, 0) NULL,
	[BSGRU] [nvarchar](3) NULL,
	[BWAPPLNM] [nvarchar](30) NULL,
	[BWVORG] [char](3) NULL,
	[EBELP] [char](5) NOT NULL,
	[ELIKZ] [nvarchar](1) NULL,
	[EMATN] [nvarchar](40) NULL,
	[EREKZ] [nvarchar](1) NULL,
	[KONNR] [nvarchar](10) NULL,
	[KTMNG] [numeric](13, 3) NULL,
	[KTPNR] [char](5) NULL,
	[KZMAB] [nvarchar](1) NULL,
	[KZPOS] [nvarchar](1) NULL,
	[KZTAB] [nvarchar](1) NULL,
	[LAVI] [numeric](3, 0) NULL,
	[LFZTA] [numeric](13, 0) NULL,
	[LGORT] [nvarchar](4) NULL,
	[LMEIN] [nvarchar](3) NULL,
	[MABW] [numeric](6, 2) NULL,
	[MATKL] [nvarchar](9) NULL,
	[MATNR] [nvarchar](40) NULL,
	[MEINS] [nvarchar](3) NULL,
	[MENGE] [numeric](13, 3) NULL,
	[NETPR] [numeric](11, 2) NULL,
	[NETWR] [numeric](13, 2) NULL,
	[PEINH] [numeric](5, 0) NULL,
	[PSTYP] [nvarchar](1) NULL,
	[PWEV] [numeric](3, 0) NULL,
	[PWFR] [numeric](3, 0) NULL,
	[PWMT] [numeric](3, 0) NULL,
	[PWTT] [numeric](3, 0) NULL,
	[PWWE] [numeric](3, 0) NULL,
	[REPOS] [nvarchar](1) NULL,
	[TABW] [numeric](3, 0) NULL,
	[TXZ01] [nvarchar](40) NULL,
	[UMREN] [numeric](5, 0) NULL,
	[UMREZ] [numeric](5, 0) NULL,
	[WEBRE] [nvarchar](1) NULL,
	[WEPOS] [nvarchar](1) NULL,
	[WERKS] [nvarchar](4) NULL,
	[XERSY] [nvarchar](1) NULL,
	[ZWERT] [numeric](13, 2) NULL,
	[BANFN] [nvarchar](10) NULL,
	[BNFPO] [char](5) NULL,
	[BRGEW] [numeric](13, 3) NULL,
	[BRTWR] [numeric](13, 2) NULL,
	[BRTWR_R] [numeric](15, 2) NULL,
	[BSTAE] [nvarchar](4) NULL,
	[CHARG] [nvarchar](10) NULL,
	[CNFM_QTY] [numeric](13, 3) NULL,
	[CON_ID] [nvarchar](5) NULL,
	[EFFWR] [numeric](13, 2) NULL,
	[EFFWR_R] [numeric](15, 2) NULL,
	[EGLKZ] [nvarchar](1) NULL,
	[ESOKZ] [nvarchar](1) NULL,
	[GEWEI] [nvarchar](3) NULL,
	[IDNLF] [nvarchar](35) NULL,
	[INFNR] [nvarchar](10) NULL,
	[KNTTP] [nvarchar](1) NULL,
	[KZAVI] [nvarchar](1) NULL,
	[KZKPO] [nvarchar](1) NULL,
	[KZWEV] [nvarchar](1) NULL,
	[KZWI1] [numeric](13, 2) NULL,
	[KZWI2] [numeric](13, 2) NULL,
	[KZWI3] [numeric](13, 2) NULL,
	[KZWI4] [numeric](13, 2) NULL,
	[KZWI5] [numeric](13, 2) NULL,
	[KZWI6] [numeric](13, 2) NULL,
	[LOEKZ] [nvarchar](1) NULL,
	[LTSNR] [nvarchar](6) NULL,
	[MEPRF] [nvarchar](1) NULL,
	[MFRNR] [nvarchar](10) NULL,
	[MFRPN] [nvarchar](40) NULL,
	[MPO_MATNR] [nvarchar](40) NULL,
	[MPROF] [nvarchar](4) NULL,
	[MWSKZ] [nvarchar](2) NULL,
	[NAVNW] [numeric](13, 2) NULL,
	[NETWR_R] [numeric](15, 2) NULL,
	[NTGEW] [numeric](13, 3) NULL,
	[OBJID] [char](8) NULL,
	[OBJID_COM] [char](8) NULL,
	[PLANNING_GUID] [nvarchar](32) NULL,
	[PRDAT] [date] NULL,
	[PUNEI] [nvarchar](3) NULL,
	[RELOC_ID] [nvarchar](10) NULL,
	[RELOC_SEQ_ID] [nvarchar](4) NULL,
	[RESLO] [nvarchar](4) NULL,
	[RETPO] [nvarchar](1) NULL,
	[SATNR] [nvarchar](40) NULL,
	[SGT_RCAT] [nvarchar](40) NULL,
	[SGT_SCAT] [nvarchar](40) NULL,
	[STAFO] [nvarchar](6) NULL,
	[STAPO] [nvarchar](1) NULL,
	[TWRKZ] [nvarchar](1) NULL,
	[VOLEH] [nvarchar](3) NULL,
	[VOLUM] [numeric](13, 3) NULL,
	[VRTKZ] [nvarchar](1) NULL,
	[WEBAZ] [numeric](3, 0) NULL,
	[WEUNB] [nvarchar](1) NULL,
	[ZZ_AEDAT] [date] NULL,
	[ZZ_INCO2_L] [nvarchar](70) NULL,
	[ZZ_INCO3_L] [nvarchar](70) NULL,
	[ZZ_INFNR] [nvarchar](10) NULL,
	[ZZ_KO_PRCTR] [nvarchar](10) NULL,
	[ZZ_MTART] [nvarchar](4) NULL,
	[ZZ_STAWN] [nvarchar](17) NULL,
	[ZZ_UNIQUEID] [nvarchar](15) NULL,
	[PERIV] [nvarchar](2) NULL,
	[QUAN_INT] [numeric](3, 0) NULL,
	[TIME_INT] [numeric](3, 0) NULL,
	[NOTIME] [numeric](3, 0) NULL,
	[NOQUAN] [numeric](3, 0) NULL,
	[NOPOS] [numeric](3, 0) NULL,
	[PWLIF] [nvarchar](10) NULL,
	[PREST] [nvarchar](10) NULL,
	[PLIWK] [nvarchar](10) NULL,
	[PLIEF] [nvarchar](10) NULL,
	[PBEST] [nvarchar](10) NULL,
	[MGABW] [numeric](3, 2) NULL,
	[LFABW] [numeric](3, 2) NULL,
	[MAXBW] [numeric](3, 0) NULL,
	[VVABW] [numeric](3, 2) NULL,
	[UZEIT] [char](6) NULL,
	[MCEX_UEBTO] [numeric](3, 1) NULL,
	[MCEX_UEBTK] [nvarchar](1) NULL,
	[MCEX_UNTTO] [numeric](3, 1) NULL,
	[ZMM_IM_READY_DATE] [date] NULL,
	[ZMM_MRD] [date] NULL,
	[ZMM_QC_DATE] [date] NULL,
	[ZMM_ETD] [date] NULL,
	[ZZ_ZTERM] [nvarchar](4) NULL,
	[ZZ_INCO1] [nvarchar](3) NULL,
	[ZZ_INCO2] [nvarchar](3) NULL,
	[ZZ_DPTYP] [nvarchar](4) NULL,
	[ZZ_DPPCT] [numeric](5, 2) NULL,
	[ZZ_DPAMT] [numeric](11, 2) NULL,
	[ZZ_DPDAT] [date] NULL,
	[ZZ_NETPR] [numeric](11, 2) NULL,
	[ZZ_NETPR_TC_UNROUNDED] [numeric](25, 9) NULL,
	[ZZ_NETPR_HC_UNROUNDED] [numeric](25, 9) NULL,
	[ZREFBS] [nvarchar](10) NULL,
	[ZREFPS] [char](5) NULL,
	[ZCONTRACT_REFERENCE] [nvarchar](40) NULL,
	[LOAD_TIMESTAMP] [datetime2](7) NOT NULL
)
WITH
(
	DISTRIBUTION = HASH ( [EBELN] ),
	CLUSTERED COLUMNSTORE INDEX
)


INSERT INTO [MD].[MD_L0_LOAD_LIST]
           ([TableName]
           ,[SchemaName]
           ,[FolderPath]
           ,[Is_Active]
           ,[EntityName]
           ,[KeyColumns]
           ,[PipelineLastRun])
     VALUES
           ('L0_S4HANA_2LIS_02_ITM_FULL'
           ,'TEST'
           ,'curated/s4hana_theobald/cbp/2lis_02_itm_temp'
           ,0
           ,'SAP'
           ,'ROCANCEL,EBELN,EBELP'
           ,'2024-01-01')

update [MD].[MD_L0_LOAD_LIST]set [KeyColumns] = 'EBELN,EBELP' where [TableName] = 'L0_S4HANA_2LIS_02_ITM_FULL'

---- select * INTO [TEST].[L0_S4HANA_2LIS_02_ITM] from [L0].[L0_S4HANA_2LIS_02_ITM]

select * from [MD].[MD_L0_LOAD_LIST] where [TableName] like '%03_BF%'


