
CREATE TABLE [TEST].[L1_FACT_A_STOCK_DEVELOPMENT]
(
	D_SNAPSHOT date,
	[D_CALENDAR_DATE] [date] NULL,
	[NUM_ITEM] [int] NULL,
	[VL_FORECAST_TOTAL_STOCK] decimal(19,4) NULL,
	[VL_INTIAL_STOCK_QTY] decimal(19,4) NOT NULL,
	[VL_FC_QUANTITY] decimal(19,4) NOT NULL,
	[VL_OPEN_QUANTITY] decimal(19,4) NULL,
	DT_DWH_CREATED smalldatetime NOT NULL,
	DT_DWH_UPDATED smalldatetime NOT NULL
)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO


