/******************************
** Name: Gets the SAP purchasing data 
** Auth: [Helder Barbosa]
** Date: 01/03/2025
**************************
** Change History
**************************
** PR   Date		 Author			Description 
** --   --------	 -------		------------------------------------
** 1	01/03/2025	Hbarbosa	     Initial Script
*/
 


CREATE PROCEDURE TEST.WR_TX_L0_S4HANA_02_ITM_L1_FACT_A_PURCHASING_TRANSACTIONS @NUM_LOAD_DAYS INT
AS
BEGIN

/****************************************************************
** Load Date
** calculate for how many days we process transactions
*****************************************************************/
DECLARE @LOAD_START_DATE AS date 

IF(ISNULL(@NUM_LOAD_DAYS,0) > 0 )
    SET @LOAD_START_DATE = CAST(GETDATE () - @NUM_LOAD_DAYS as date)


DELETE FROM TEST.L1_FACT_A_PURCHASIG_TRANSACTIONS WHERE DT_DWH_CREATED>=@LOAD_START_DATE



    INSERT INTO TEST.L1_FACT_A_PURCHASIG_TRANSACTIONS (
        CD_DOCUMENT_NO,
        CD_DOCUMENT_TYPE,
        T_DOCUMENT_TYPE, 
        CD_PURCHASING_CATEGORY, 
        CD_COMPANY_CODE,
        D_CREATED,
        D_POSTING, 
        CD_OUTLINE_AGREEMENT, 
        CD_PRICING_DOCUMENT_NO, 
        CD_GR_MESSAGE,
        CD_PAYMENT_IN_DISCOUNT_DAYS,
        CD_PAYMENT_TERM,
        D_DOWN_PAYMENT,
        PERC_DOWN_PAYMENT, 
        AMT_FIXED_DOWN_PAYMENT_FC,
        D_LAST_CHANGED,
        D_VALIDITY_START,
        D_VALIDITY_END,
        FL_DOCUMENT_DELETION,
        CD_FORWARDER_REFERENCE, 
        CD_SUPPLIER_REFERENCE, 
        D_ETA_PORT,
        D_ETD, 
        CD_TRANSPORT_MODE,
        CD_PORT_OF_LOADING, 
        CD_PORT_OF_DISCHARGE, 
        CD_DOCUMENT_LINE,
        CD_ITEM, 
        CD_PLANT,
        CD_STORAGE_LOCATION, 
        VL_ITEM_ORDER_QTY, 
        CD_ITEM_ORDER_UNIT, 
        CD_CURRENCY,
        VL_EXCHANGE_RATE, 
        AMT_NET_PRICE_EUR,
        NUM_PRICE_UNIT,
        AMT_NET_PRICE_FC, 
        CD_VENDOR, 
        CD_COMPANY_CODE,
        CD_PURCHASING_GROUP,
        CD_PURCHASING_ORG,
        CD_EFFECTIVE_VALUE, 
        VL_ITEM_COMMITTED_QTY,
        CD_INCOTERMS,
        CD_INCOTERMS_L1,
        CD_INCOTERMS_L2, 
        AMT_GROSS_PRICE_FC, 
        FL_DOCUMENT_LINE_DELETION,
        CD_CONTRACT_REFERENCE,
        D_ITEM_READY_DATE, 
        CD_DOWN_PAYMENT_CATEGORY,
        D_LINE_DOWN_PAYMENT,
        PERC_LINE_DOWN_PAYMENT, 
        AMT_LINE_FIXED_DOWN_PAYMENT_FC,
        CD_CONTRACT_NUMBER,
        D_IM_READY,
        CD_CONFIRMATION_CONTROL_TYPE,
        CD_GOODS_SUPPLIER,
        D_LINE_LAST_CHANGED,
        D_QUALITY_CONTROL,
        CD_INFO_RECORD,
        D_LINE_ETD,

    )
    SELECT 
        HDR.EBELN, HDR.BSTYP, TYP.TRANSACTIONTYPE, HDR.BSART, HDR.BUKRS,
        HDR.BEDAT, HDR.BUDAT, HDR.ZZKONNR, HDR.KNUMV, HDR.ZZ_WEAKT,
        HDR.ZZ_ZBD1T, HDR.ZZ_ZTERM, HDR.ZZDPDAT, HDR.ZZDPPER, 
        HDR.ZZDPFIX, HDR.ZZ_AEDAT, HDR.KDATB, HDR.KDATE, HDR.LOEKZ,
        HDR.ZZFORWARDER_REF, HDR.ZZSUPPLIER_REF, HDR.ZZETA, HDR.ZZETD, HDR.ZZTRANSPORT_MODE,
        HDR.ZZPORT_OF_LOADING, HDR.ZZPORT_OF_DISCHARG, ITM.EBELP, ITM.MATNR, ITM.WERKS,
        ITM.LGORT, ITM.MENGE, ITM.MEINS, ITM.WAERS, 
        CASE 
            WHEN ITM.WKURS < 0 THEN (1 / ABS(ITM.WKURS))
            ELSE ABS(ITM.WKURS)
        END AS VL_EXCHANGE_RATE, 
        ITM.NETPR, ITM.PEINH, ITM.NETWR, ITM.LIFNR, ITM.BUKRS,
        ITM.EKGRP, ITM.EKORG, ITM.EFFWR, ITM.KTMNG, 
        ITM.ZZ_INCO1, ITM.ZZ_INCO2_L, ITM.ZZ_INCO3_L, ITM.BRTWR, ITM.LOEKZ,
        ITM.ZCONTRACT_REFERENCE, ITM.ZMM_MRD, ITM.ZZ_DPTYP, ITM.ZZ_DPDAT,
        ITM.ZZ_DPPCT, ITM.ZZ_DPAMT, ITM.KONNR, ITM.ZMM_IM_READY_DATE,
        ITM.BSAKZ, ITM.LLIEF, ITM.ZZ_AEDAT, ITM.ZMM_QC_DATE,
        ITM.INFNR, ITM.ZMM_ETD
    FROM TEST.L0_S4HANA_2LIS_02_HDR HDR
    INNER JOIN TEST.L0_S4HANA_2LIS_02_ITM ITM
        ON HDR.EBELN = ITM.EBELN
    LEFT JOIN TEST.L0_MI_TRANSACTION_TYPE TYP 
        ON TYP.TRANSACTIONTYPESHORT = HDR.BSTYP
        AND TYP.SOURCETYPE = 'BSTYP'
    
    WHERE 
		(  
            @LOAD_START_DATE IS NULL
            OR
            LEAST(ITM.ZZ_AEDAT,ITM.BEDAT,HDR.BEDAT,HDR.ZZ_AEDAT) >= @LOAD_START_DATE

        )





END;
