--select * from [L0].[L0_MI_BUSINESS_PLAN_MARKETING_RATES] mkt where month = '2025-10-01'
	SELECT distinct
	   ItemNo= ISNULL(it.NUM_ITEM,itsb.NUM_ITEM)
	  ,ChannelGroup3= kpi.[CD_CHANNEL_GROUP_3]               
	  ,PlanPrice= kpi.[AMT_PLAN_PRICE_EUR]               
	  ,Quantity= kpi.VL_ITEM_QUANTITY                 
	  ,Mekhedging= kpi.[AMT_MEK_HEDGING_EUR]              
	  ,GtsMarkup = kpi.[AMT_GTS_MARKUP_EUR]               
	  ,StorageLocation = kpi.T_REVISED_LOCATION
	  ,Country = kpi.CD_COUNTRY_GROUP
	  ,ShippingCostEst = kpi.AMT_SHIPPING_COST_EST_EUR
	---kpi--QTY
	,NetOrderQuantityEst = VL_NET_ORDER_QUANTITY
	,RefundedQuantityEst = VL_REFUNDED_QUANTITY_EST
	,ReturnedQuantityEst = VL_RETURNED_QUANTITY_EST
	,ReplacedQuantityEst = VL_REPLACEMENT_ORDER_QUANTITY_EST
	--KPI's Amount
	,NetOrderValueEst = AMT_NET_ORDER_VALUE_EST_EUR
	,RefundedOrderValueEst = AMT_REFUNDED_ORDER_VALUE_EST_EUR	
	,RevenueEst = AMT_REVENUE_EST_EUR
	,NetProductCostEst = AMT_NET_PRODUCT_COST_EST_EUR
	,PC0Est = AMT_PC0_EST_EUR
	,COGSOperationsEst = AMT_COGS_OPERATIONS_EST
	,PC1Est = AMT_PC1_EST_EUR
	,HandlingInboundEst = AMT_HANDLING_INBOUND_EST_EUR
	,HandlingTransShippmentEst = AMT_HANDLING_TRANS_SHIPPMENT_EST_EUR
	,HandlingReturnsEst = AMT_HANDLING_RETURNS_EST_EUR
	,TruckingTransShipmentEst = AMT_TRUCKING_TRANS_SHIPMENT_EST_EUR
	,FulfillmentOutboundEst = AMT_FULFILLMENT_OUTBOUND_EST_EUR
	,CommissionsMarketplacesEst = AMT_COMMISSIONS_MARKETPLACES_EUR
	,CommissionsMarketplacesRefundsEst = AMT_COMMISSIONS_MARKETPLACES_REFUNDS_EUR
	,CommissionsAmazonEst = AMT_COMMISSIONS_AMAZON_EUR
	,CommissionsAmazonRefundsEst = AMT_COMMISSIONS_AMAZON_REFUNDS_EUR
	,MarketingShops = AMT_SHOP_MARKETING_EUR
	,MarketingAmazon = AMT_AMAZON_MARKETING_COSTS_EUR
	,MarketingMarketplacesEst = AMT_MARKETING_MARKETPLACES_EST_EUR
	,CustomerServiceHandlingEst = AMT_CS_HANDLING_CLAIMS_EUR
	,PackagingEst = AMT_PACKAGING_EUR
	,HandlingShipmentsEst = AMT_HANDLING_ORDERS_EST_EUR
	,PaymentsFeesEst = AMT_PAYMENTS_EUR
	,EnviroLicenseCostEst = [AMT_ENVIRO_AND_LICENSE_COST_EST_EUR]		
	,PC2Est = AMT_PC2_EST_EUR
	,WarehousingRentEst = AMT_WAREHOUSING_RENT_EST_EUR
	,WarehousingOPEXEst = AMT_WAREHOUSING_OPEX_EST_EUR
	,MarketingFixedCostEst = AMT_NET_ORDER_VALUE_EST_EUR * (CASE WHEN kpi.[CD_CHANNEL_GROUP_3]= 'MarketplacesWE' THEN 0.000719 WHEN kpi.[CD_CHANNEL_GROUP_3]= 'ShopWE' THEN 0.007668 WHEN kpi.[CD_CHANNEL_GROUP_3]= 'AMAZON' THEN 0.000266 ELSE  0 END )
	,CustomerServiceOPEXEst = AMT_CS_MANAGEMENT_EST_EUR
	,PC3Est = AMT_PC3_EST_EUR
	,RefundRate = [VL_REFUND_RATE]
    ,ReturnRate = [VL_RETURN_RATE]
    ,ReplacementRate = [VL_REPLACEMENT_RATE]
	,MarketingFixedCostsRate = CASE WHEN kpi.[CD_CHANNEL_GROUP_3]= 'MarketplacesWE' THEN 0.000719 WHEN kpi.[CD_CHANNEL_GROUP_3]= 'ShopWE' THEN 0.007668 WHEN kpi.[CD_CHANNEL_GROUP_3]= 'AMAZON' THEN 0.000266 ELSE  0 END
	,EOL = CASE WHEN ISNULL(itsb.CD_ITEM_STATUS_BUSINESS_PLAN,'') = 'EOL'
								OR ISNULL(it.CD_STATUS_PLANT,'') = 'Z5'
								OR ISNULL(it.[T_MI_ITEM_STATUS],'') = '-1'
								THEN 'Y' ELSE 'N' END
	FROM TEST.[L1_FACT_F_BUSINESS_PLAN_KPI_ELMO] kpi
	LEFT JOIN L1.L1_DIM_A_ITEM it on it.ID_ITEM = kpi.ID_ITEM
	LEFT JOIN L1.L1_DIM_A_ITEM_BUSINESS_PLAN itsb on itsb.ID_ITEM_BUSINESS_PLAN = kpi.ID_ITEM_BUSINESS_PLAN
	LEFT JOIN TEST.[L1_FACT_F_BUSINESS_PLAN_ELMO] bs 
		on ISNULL(kpi.ID_ITEM,kpi.ID_ITEM_BUSINESS_PLAN) = ISNULL(bs.ID_ITEM,bs.ID_ITEM_BUSINESS_PLAN)
		AND bs.CD_CHANNEL_GROUP_3 = kpi.CD_CHANNEL_GROUP_3
		AND bs.T_REVISED_LOCATION = kpi.T_REVISED_LOCATION
		AND bs.CD_COUNTRY_GROUP = kpi.CD_COUNTRY_GROUP
	WHERE
		kpi.CD_COUNTRY_GROUP = 'IT'




