UPDATE STATISTICS [L1].[L1_DIM_A_CS_COMMISSIONS_AMAZON_REFUND] WITH FULLSCAN
--UPDATE STATISTICS [L1].[L1_DIM_A_SALES_TRAN_KPI_MATRIX] WITH FULLSCAN
--UPDATE STATISTICS [L1].[L1_DIM_A_COMPANY] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_WAREHOUSING_FBA] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_PL_SWEDISH_CHEMICAL_TAX] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_MARKETING_FIXED_COST] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_PL_ENVIRO_PACKAGING] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_SALES_TRANSACTION_TYPE] WITH FULLSCAN
--UPDATE STATISTICS [L1].[L1_DIM_A_OTTO_ITEM_MAPPING] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_CS_COMMISSIONS_AMAZON] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_CS_PAYMENTS] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_TRUCKING_TRANS_SHIPMENTS] WITH SAMPLE 20 PERCENT
--UPDATE STATISTICS [L1].[L1_DIM_A_ACCOUNT_NAMES] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_ENVIRO_CLASSIFICATION] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_PL_ENVIRO_REST] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_COMMODITY_VALUES] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_FULFILLMENT_SHIPPING_FACTOR] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_ITEM_BUSINESS_PLAN] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_ITEM] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_MARKETING_MARKETPLACES] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_CS_HANDLING_CLAIMS] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_CS_MANAGEMENT] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_ORDER_CANCELLATION_VALUES] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_WAREHOUSE_RENT] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_HANDLING_SHIPMENTS] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_PACKAGING_COST] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_WAREHOUSING_OPEX] WITH FULLSCAN
--UPDATE STATISTICS [L1].[L1_DIM_A_ITEM_BOM] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_HANDLING_TRANSSHIP] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_CS_COMMISSIONS_MARKETPLACES] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_HANDLING_RETURNS] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_DEPRECIATION_VALUES] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_PL_ENVIRO_LICENSES] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_SALES_REPLACEMENT_VALUES] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_SALES_REFUND_VALUES] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_SALES_RETURN_VALUES] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_HANDLING_INBOUND] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_STORAGE_LOCATION] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_SM_PIPELINE_LOOKUP] WITH FULLSCAN
UPDATE STATISTICS [L1].[L1_DIM_A_SALES_CHANNEL] WITH FULLSCAN
---UPDATE STATISTICS [L1].[L1_DIM_A_SALES_ACCOUNTING_MATRIX] WITH FULLSCAN
--UPDATE STATISTICS [L1].[L1_DIM_A_ACCOUNT_ATTRIBUTES] WITH FULLSCAN
--UPDATE STATISTICS [L1].[L1_DIM_A_FINANCE_TRAN_KPI_MATRIX] WITH FULLSCAN
--UPDATE STATISTICS [L1].[L1_DIM_A_COUNTRY] WITH FULLSCAN

[PL].[PL_M_SALES_PERFORMANCE]
UPDATE STATISTICS [PL].[PL_M_SALES_PERFORMANCE] WITH FULLSCAN

UPDATE STATISTICS [L1].[L1_FACT_F_BUSINESS_PLAN] WITH SAMPLE 76 PERCENT
----refunds  L0.L0_MI_REFUND_PROXY_VALUES
--[WR].[WR_TX_L0_MI_REFUND_PROXY_VALUES_L1_DIM_A_SALES_REFUND_VALUES]
--WR.WR_SP_SRG_L1_DIM_A_SALES_REFUND_VALUES
-- [WR].[WR_DQ_WR_L1_DIM_A_SALES_REFUND_VALUES]
--  [WR].[WR_HIST_FULL_L1_DIM_A_SALES_REFUND_VALUES]

-----returns  L0.L0_MI_RETURN_PROXY_VALUES
--[WR].[WR_TX_L0_MI_RETURN_PROXY_VALUES_L1_DIM_A_SALES_RETURN_VALUES]
--WR.WR_SP_SRG_L1_DIM_A_SALES_RETURN_VALUES
-- [WR].[WR_HIST_FULL_L1_DIM_A_SALES_RETURN_VALUES]


-- ---replacement  L0.L0_MI_REPLACEMENT_PROXY_VALUES
-- WR.WR_TX_L0_MI_REPLACEMENT_PROXY_VALUES_L1_DIM_A_SALES_REPLACEMENT_VALUES
-- WR.WR_SP_SRG_L1_DIM_A_SALES_REPLACEMENT_VALUES
-- [WR].[WR_HIST_FULL_L1_DIM_A_SALES_REPLACEMENT_VALUES]