CREATE VIEW  L1.L1_FACT_F_SHIPPING_TRACKING_CONTAINER 
(
	[MONTH]   DATE,
    [CHANNELGROUP3]    VARCHAR(50),
	[MARKETINGRATE]     DECIMAL(19,4),
    [LOAD_TIMESTAMP]      datetime2
)
WITH (
    DISTRIBUTION = REPLICATE,
    HEAP
)