CREATE TABLE [TEST].[L1_FACT_A_STOCK_MOVEMENT]
(
	[ID_STOCK_MOVEMENT] [int] NULL,
	[CD_STOCK_MOVEMENT] [varchar](50) NULL,
	[CD_SOURCE_SYSTEM] [varchar](5) NULL,
	[CD_DOCUMENT_NO] [varchar](10) NULL,
	[CD_DOCUMENT_LINE] [varchar](10) NULL,
	[ID_ITEM] [int] NULL,
	[CD_STORAGE_LOCATION] [varchar](10) NULL,
	[CD_STOCK_MOVEMENT_TYPE] [varchar](10) NULL,
	[CD_STOCK_CATEGORY] [varchar](10) NULL,
	[D_CREATED] [date] NULL,
	[NUM_POSTING_YEAR] [int] NULL,
	[D_FI_POSTING] [date] NULL,
	[CD_BATCH] [nvarchar](50) NULL,
	[CD_BATCH_DEVALUATION] [nvarchar](50) NULL,
	[AMT_AMOUNT_DEVALUATION_TRANSACTION] [decimal](19, 6) NULL,
	[CD_CURRENCY_DEVALUATION_TRANSACTION] [varchar](10) NULL,
	[AMT_AMOUNT_DEVALUATION_EUR] [decimal](19, 6) NULL,
	[AMT_SALES_MEK_HEDGING_EUR] [decimal](19, 6) NULL,
	[VL_ITEM_QUANTITY] [decimal](19, 6) NULL,
	[VL_ITEM_QUANTITY_DEVALUATION] [decimal](19, 6) NULL,
	[D_EFF_FROM] [date] NULL,
	[D_EFF_TO] [date] NOT NULL,
	[D_EFF_DELETED] [date] NOT NULL,
	[DT_DWH_CREATED] [smalldatetime] NOT NULL,
	[DT_DWH_UPDATED] [smalldatetime] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH ( [CD_STOCK_MOVEMENT] ),
	CLUSTERED COLUMNSTORE INDEX
)
GO


