    
    SELECT MANDT,EBELN,EBELP
    FROM [tSAP_EKET_FULL]
    GROUP BY MANDT,EBELN,EBELP
    HAVING COUNT(*) > 1
/***************************************
***It stores Purchase Order (PO) Header, 
***************************************/
CREATE PROCEDURE usp_Load_tSAPEKET
AS

with cte_eket as
(
    SELECT DISTINCT MANDT,EBELN,EBELP,ETENR
    FROM [dbo].tSAP_EKET with(nolock)

)
DELETE FROM hist
FROM [tSAP_EKET_FULL] hist 
INNER JOIN cte_eket eket
    on eket.MANDT = hist.MANDT
    AND eket.EBELN = hist.EBELN
    AND eket.EBELP = hist.EBELP
    AND eket.ETENR = hist.ETENR

    
INSERT INTO [dbo].[tSAP_EKET_FULL]
           ([MANDT]
           ,[EBELN]
           ,[EBELP]
           ,[ETENR]
           ,[UNIQUEID]
           ,[EINDT]
           ,[SLFDT]
           ,[LPEIN]
           ,[MENGE]
           ,[AMENG]
           ,[WEMNG]
           ,[WAMNG]
           ,[UZEIT]
           ,[BANFN]
           ,[BNFPO]
           ,[ESTKZ]
           ,[QUNUM]
           ,[QUPOS]
           ,[MAHNZ]
           ,[BEDAT]
           ,[RSNUM]
           ,[SERNR]
           ,[FIXKZ]
           ,[GLMNG]
           ,[DABMG]
           ,[CHARG]
           ,[LICHA]
           ,[CHKOM]
           ,[VERID]
           ,[ABART]
           ,[MNG02]
           ,[DAT01]
           ,[ALTDT]
           ,[AULWE]
           ,[MBDAT]
           ,[MBUHR]
           ,[LDDAT]
           ,[LDUHR]
           ,[TDDAT]
           ,[TDUHR]
           ,[WADAT]
           ,[WAUHR]
           ,[ELDAT]
           ,[ELUHR]
           ,[ANZSN]
           ,[NODISP]
           ,[GEO_ROUTE]
           ,[ROUTE_GTS]
           ,[GTS_IND]
           ,[TSP]
           ,[CD_LOCNO]
           ,[CD_LOCTYPE]
           ,[HANDOVERDATE]
           ,[HANDOVERTIME]
           ,[WESBB]
           ,[STARTDATE]
           ,[ENDDATE]
           ,[_DATAAGING]
           ,[/CWM/MENGE]
           ,[/CWM/DABMG]
           ,[/CWM/WEMNG]
           ,[TMS_REF_UUID]
           ,[ARUN_REQ_DLVDATE]
           ,[FSH_RALLOC_QTY]
           ,[FSH_SALLOC_QTY]
           ,[FSH_OS_ID]
           ,[KEY_ID]
           ,[OTB_VALUE]
           ,[OTB_CURR]
           ,[OTB_RES_VALUE]
           ,[OTB_SPEC_VALUE]
           ,[SPR_RSN_PROFILE]
           ,[BUDG_TYPE]
           ,[OTB_STATUS]
           ,[OTB_REASON]
           ,[CHECK_TYPE]
           ,[DL_ID]
           ,[HANDOVER_DATE]
           ,[NO_SCEM]
           ,[DNG_DATE]
           ,[DNG_TIME]
           ,[CNCL_ANCMNT_DONE]
           ,[DATESHIFT_NUMBER])
SELECT
DISTINCT

[MANDT]
           ,[EBELN]
           ,[EBELP]
           ,[ETENR]
           ,[UNIQUEID]
           ,[EINDT]
           ,[SLFDT]
           ,[LPEIN]
           ,[MENGE]
           ,[AMENG]
           ,[WEMNG]
           ,[WAMNG]
           ,[UZEIT]
           ,[BANFN]
           ,[BNFPO]
           ,[ESTKZ]
           ,[QUNUM]
           ,[QUPOS]
           ,[MAHNZ]
           ,[BEDAT]
           ,[RSNUM]
           ,[SERNR]
           ,[FIXKZ]
           ,[GLMNG]
           ,[DABMG]
           ,[CHARG]
           ,[LICHA]
           ,[CHKOM]
           ,[VERID]
           ,[ABART]
           ,[MNG02]
           ,[DAT01]
           ,[ALTDT]
           ,[AULWE]
           ,[MBDAT]
           ,[MBUHR]
           ,[LDDAT]
           ,[LDUHR]
           ,[TDDAT]
           ,[TDUHR]
           ,[WADAT]
           ,[WAUHR]
           ,[ELDAT]
           ,[ELUHR]
           ,[ANZSN]
           ,[NODISP]
           ,[GEO_ROUTE]
           ,[ROUTE_GTS]
           ,[GTS_IND]
           ,[TSP]
           ,[CD_LOCNO]
           ,[CD_LOCTYPE]
           ,[HANDOVERDATE]
           ,[HANDOVERTIME]
           ,[WESBB]
           ,[STARTDATE]
           ,[ENDDATE]
           ,[_DATAAGING]
           ,[/CWM/MENGE]
           ,[/CWM/DABMG]
           ,[/CWM/WEMNG]
           ,[TMS_REF_UUID]
           ,[ARUN_REQ_DLVDATE]
           ,[FSH_RALLOC_QTY]
           ,[FSH_SALLOC_QTY]
           ,[FSH_OS_ID]
           ,[KEY_ID]
           ,[OTB_VALUE]
           ,[OTB_CURR]
           ,[OTB_RES_VALUE]
           ,[OTB_SPEC_VALUE]
           ,[SPR_RSN_PROFILE]
           ,[BUDG_TYPE]
           ,[OTB_STATUS]
           ,[OTB_REASON]
           ,[CHECK_TYPE]
           ,[DL_ID]
           ,[HANDOVER_DATE]
           ,[NO_SCEM]
           ,[DNG_DATE]
           ,[DNG_TIME]
           ,[CNCL_ANCMNT_DONE]
           ,[DATESHIFT_NUMBER]
    FROM [tSAP_EKET]
    