/****** Object:  StoredProcedure [WR].[WR_TX_L1_FACT_A_SALES_TRANSACTIONS_L1_FACT_A_SALES_TRANSACTION_KPI_SM]    Script Date: 13/10/2025 11:36:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROC [WR].[WR_TX_L1_FACT_A_SALES_TRANSACTIONS_L1_FACT_A_SALES_TRANSACTION_KPI_SM] @NUM_DAYS [INT] AS
BEGIN


	DECLARE @LOAD_START_DATE AS date 

	IF (ISNULL(@NUM_DAYS,0) = 0)
	BEGIN
		SET @LOAD_START_DATE = '2024-01-01'
	END
	ELSE
		SET @LOAD_START_DATE = CAST(GETDATE () - @NUM_DAYS as date)

	TRUNCATE TABLE [WR].[WR_L1_FACT_A_SALES_TRANSACTION_KPI_SM] 



;WITH CTE_ENVIRO as 
    (
	        SELECT 
				ID_ITEM,
				CD_COUNTRY_DELIVERY,
				NUM_YEAR,
				CD_CURRENCY,
				AMT_FEE_PER_UNIT = sum(AMT_FEE_PER_UNIT) 
			FROM [L1].[L1_DIM_A_ENVIRO_REST_UNIT_FEES]
            GROUP BY ID_ITEM,CD_COUNTRY_DELIVERY,NUM_YEAR,CD_CURRENCY
    ),
	CTE_SERVICES_COSTS_DEDUP AS
	(
	SELECT 
		id,
		item_code,
		warehouse,
		country,
		cost_type_id,
		cost = MAX(ISNULL(cost,0))
	FROM [L0].[L0_MERCURY_LOGISTIC_BUDGET_CAPO_SERVICE]
	GROUP BY 
		id,
		item_code,
		warehouse,
		country,
		cost_type_id	
	)
,CTE_CAPO_SERVICES AS
(

	SELECT
  	    cost.item_code,
	    CASE WHEN cost.warehouse=1 THEN 'Kamp-Lintfort'
	         WHEN cost.warehouse=2 THEN 'Hoppegarten'
	         WHEN cost.warehouse=3 THEN 'Bratislava'
	         WHEN cost.warehouse=4 THEN 'Werne'
             WHEN cost.warehouse=6 THEN 'Bucharest'
             WHEN cost.warehouse=7 THEN 'Lager UK'
	    END warehouse,
        warehouse as warehouse_id,
	    cost.country,
		ctypes.cost_type_name as Fulfillment,
	    SUM(ISNULL(cost,0)) as cost
	FROM CTE_SERVICES_COSTS_DEDUP cost 
	LEFT JOIN [L0].[L0_MERCURY_LOGISTIC_BUDGET_COST_TYPES] ctypes
	ON cost.cost_type_id = ctypes.id
	WHERE 0=0
	    --AND cost.warehouse IN (1, 3, 4)
		and warehouse is not null
	GROUP BY 
	    cost.item_code,
	    cost.warehouse,
	    cost.country,
		ctypes.cost_type_name
	HAVING 
	SUM(ISNULL(cost,0)) > 0

)
,CTE_SALES_L1 AS
	(
			SELECT 
				ID_SALES_TRANSACTION								= fact.ID_SALES_TRANSACTION				
				,CD_SALES_TRANSACTION								= fact.CD_SALES_TRANSACTION										
				,CD_SOURCE_SYSTEM									= fact.CD_SOURCE_SYSTEM											
				,CD_SALES_PROCESS_ID																	
				,CD_SALES_PROCESS_LINE								= fact.CD_SALES_PROCESS_LINE										
				,CD_DOCUMENT_NO													
				,CD_DOCUMENT_LINE												
				,CD_DOCUMENT_ID_REFERENCE										
				,ID_COMPANY											= fact.ID_COMPANY												
				,D_CREATED											= fact.D_CREATED													
				,D_SALES_PROCESS									= fact.D_SALES_PROCESS											
				,D_DOCUMENT_CREATED									= fact.D_DOCUMENT_CREATED										
				,T_CANCELLATION_REASON								= fact.T_CANCELLATION_REASON										
				,FL_INCIDENT										= fact.FL_INCIDENT												
				,DT_CREATED														
				,CD_TYPE														
				,[ID_SALES_TRANSACTION_TYPE]						= fact.[ID_SALES_TRANSACTION_TYPE]								
				,ID_ITEM											= fact.ID_ITEM													
				,ID_ITEM_PARENT										= fact.ID_ITEM_PARENT											
				,CD_ITEM_TYPE										= fact.CD_ITEM_TYPE												
				,ID_SALES_CHANNEL									= fact.ID_SALES_CHANNEL											
				,CD_FULFILLMENT										= fact.CD_FULFILLMENT											
				,CD_CUSTOMER													
				,CD_CUSTOMER_SERVICE_AGENT                                      
				,T_CREATION_USERNAME                                            
				,CD_MARKET_ORDER_ID												
				,CD_PAYMENT_METHOD												
				,CD_STORAGE_LOCATION								= fact.CD_STORAGE_LOCATION										
				,T_STORAGE_LOCATION									= ISNULL(fact.T_REVISED_LOCATION,fact.T_STORAGE_LOCATION)		
				,CD_COUNTRY_INVOICE									= fact.CD_COUNTRY_INVOICE			
				,CD_COUNTRY_GROUP_INVOICE							= cmi.COUNTRYGROUP						
				,CD_ZIP_INVOICE													
				,T_CITY_INVOICE													
				,CD_COUNTRY_DELIVERY								= fact.CD_COUNTRY_DELIVERY	
				,CD_COUNTRY_GROUP_DELIVERY							= cmd.COUNTRYGROUP
				,CD_ZIP_DELIVERY									= fact.CD_ZIP_DELIVERY			
				,T_CITY_DELIVERY									= fact.T_CITY_DELIVERY		
				,CD_COUNTRY_ORDER									= fact.CD_COUNTRY_ORDER			
				,CD_ZIP_ORDER										= fact.CD_ZIP_ORDER			
				,T_CITY_ORDER										= fact.T_CITY_ORDER			
				,VL_ITEM_QUANTITY									= fact.VL_ITEM_QUANTITY			
				,VL_ITEM_PARENT_QUANTITY                            = fact.VL_ITEM_PARENT_QUANTITY            
				,AMT_NET_SHIPPING_REVENUE_EUR						= fact.AMT_NET_SHIPPING_REVENUE_EUR			
				,AMT_NET_PRICE_EUR									= fact.AMT_NET_PRICE_EUR			
				,AMT_NET_PRICE_FC									= fact.AMT_NET_PRICE_FC 			
				,AMT_SHIPPING_COST_EST_EUR							= ISNULL(fact.AMT_SHIPPING_COST_EST_EUR,0) + ISNULL(capo.cost,0)
				,AMT_SHIPPING_COST_SERVICES_EST_EUR					= ISNULL(capo.cost,0)
				,CD_SHIPMENT_COSTS_SOURCE                           = fact.CD_SHIPMENT_COSTS_SOURCE             
				,AMT_GROSS_SHIPPING_REVENUE_EUR						= fact.AMT_GROSS_SHIPPING_REVENUE_EUR			
				,AMT_GROSS_SHIPPING_REVENUE_FC						= fact.AMT_GROSS_SHIPPING_REVENUE_FC			
				,AMT_GROSS_PRICE_EUR								= fact.AMT_GROSS_PRICE_EUR			
				,AMT_GROSS_PRICE_FC									= fact.AMT_GROSS_PRICE_FC			
				,AMT_TAX_PRICE_EUR									= fact.AMT_TAX_PRICE_EUR			
				,AMT_TAX_DISCOUNTS_EUR								= fact.AMT_TAX_DISCOUNTS_EUR			
				,AMT_TAX_FREIGHT_EUR								= fact.AMT_TAX_FREIGHT_EUR			
				,AMT_TAX_TOTAL_EUR									= fact.AMT_TAX_TOTAL_EUR			
				,AMT_TAX_TOTAL_PAYABLE_EUR                          = fact.AMT_TAX_TOTAL_PAYABLE_EUR            
				,AMT_TAX_TOTAL_PAYABLE_FC                           = fact.AMT_TAX_TOTAL_PAYABLE_FC            
				,AMT_TAX_OUTPUT_EUR                                 = fact.AMT_TAX_OUTPUT_EUR           
				,AMT_TAX_OUTPUT_FC                                  = fact.AMT_TAX_OUTPUT_FC            
				,AMT_MEK_HEDGING_EUR								= fact.AMT_MEK_HEDGING_EUR			
				,AMT_GTS_MARKUP										= fact.AMT_GTS_MARKUP			
				,AMT_NET_DISCOUNT_EUR								= fact.AMT_NET_DISCOUNT_EUR		
				,AMT_NET_DISCOUNT_FC                                = fact.AMT_NET_DISCOUNT_FC       
				,CD_CURRENCY										= fact.CD_CURRENCY	
				,NUM_ITEM											= item.NUM_ITEM
				,VL_ITEM_GROSS_WEIGHT								= item.VL_GROSS_WEIGHT
				,T_PRODUCT_HIERARCHY_2								= fact.T_PRODUCT_HIERARCHY_2
				,CD_BILLING_CATEGORY								= fact.CD_BILLING_CATEGORY	
				,D_BILLING_DATE										= fact.D_BILLING_DATE					
				,CD_BILLING_POSTING_STATUS							= fact.CD_BILLING_POSTING_STATUS		
				,CD_PAYER											= fact.CD_PAYER						
				,VL_BILLING_QUANTITY								= fact.VL_BILLING_QUANTITY			
				,VL_EXCHANGE_RATE									= fact.VL_EXCHANGE_RATE				
				,CD_SALES_DOCUMENT_NO								= fact.CD_SALES_DOCUMENT_NO           
				,D_UPDATED											= fact.D_UPDATED						
				,CD_REJECTION_STATUS								= fact.CD_REJECTION_STATUS			
				,D_CANCELLATION										= fact.D_CANCELLATION	
				,[CD_RETURN_REASON]									= fact.[CD_RETURN_REASON]         
				,[T_RETURN_REASON]									= fact.[T_RETURN_REASON] 
				,AMT_TOTAL_NET_PRICE_EUR							= fact.AMT_TOTAL_NET_PRICE_EUR
				,AMT_TOTAL_NET_PRICE_FC								= fact.AMT_TOTAL_NET_PRICE_FC
				,AMT_TAX_REVERSED_EUR								= fact.AMT_TAX_REVERSED_EUR
				,AMT_TAX_REVERSED_FC								= fact.AMT_TAX_REVERSED_FC
				,AMT_TOTAL_PRICE_EUR								= fact.AMT_TOTAL_PRICE_EUR
				,AMT_TOTAL_PRICE_FC									= fact.AMT_TOTAL_PRICE_FC
				,CD_PRECEDING_DOCUMENT_NO							= fact.CD_PRECEDING_DOCUMENT_NO 
				,CD_LINKED_DOCUMENT_NO								= fact.CD_LINKED_DOCUMENT_NO 
				,AMT_NET_SHIPPING_REVENUE_FC						= fact.AMT_NET_SHIPPING_REVENUE_FC
				,CD_CARRIER											= fact.CD_CARRIER
				,VL_REFUND_RATE										= fact.VL_REFUND_RATE 					
				,VL_RETURN_RATE										= fact.VL_RETURN_RATE					
        		,VL_REPLACEMENT_RATE								= fact.VL_REPLACEMENT_RATE 	
				,VL_DEPRETIATION_RATE								= dep.VL_RATE
				,CD_REFUND_RATE_SOURCE								= fact.CD_REFUND_RATE_SOURCE 
				,CD_RETURN_RATE_SOURCE								= fact.CD_RETURN_RATE_SOURCE 
				,CD_REPLACEMENT_RATE_SOURCE							= fact.CD_REPLACEMENT_RATE_SOURCE 
				-- channel
				,CD_CHANNEL_GROUP_1									= REPLACE(dimchannel.CD_CHANNEL_GROUP_1,' ','')
				,CD_CHANNEL_GROUP_3									= REPLACE(dimchannel.CD_CHANNEL_GROUP_3,' ','')

				--kpi parameters
				,VL_GROSS_ORDER_VALUE_PARAM							= kpi.VL_GROSS_ORDER_VALUE_PARAM
				,VL_CANCELLED_ORDERS_QUANTITY_EST_PARAM				= kpi.VL_CANCELLED_ORDERS_QUANTITY_EST_PARAM
				,VL_CANCELLED_ORDER_VALUE_EST_PARAM					= kpi.VL_CANCELLED_ORDER_VALUE_EST_PARAM
				,VL_NET_ORDER_QUANTITY_EST_PARAM					= kpi.VL_NET_ORDER_QUANTITY_EST_PARAM
				,VL_REFUNDED_ORDER_VALUE_EST_PARAM					= kpi.VL_REFUNDED_ORDER_VALUE_EST_PARAM
				,VL_RETURN_ORDER_VALUE_EST_PARAM					= kpi.VL_RETURN_ORDER_VALUE_EST_PARAM
				,VL_NET_ORDER_VALUE_EST_PARAM						= kpi.VL_NET_ORDER_VALUE_EST_PARAM
				,VL_RETURNED_QUANTITY_EST_PARAM						= kpi.VL_RETURNED_QUANTITY_EST_PARAM
				,VL_REFUNDED_QUANTITY_EST_PARAM						= kpi.VL_REFUNDED_QUANTITY_EST_PARAM
				,VL_NET_QUANTITY_EST_PARAM							= kpi.VL_NET_QUANTITY_EST_PARAM
				,VL_REVENUE_EST_PARAM								= kpi.VL_REVENUE_EST_PARAM
				,VL_PC0_PARAM										= kpi.VL_PC0_PARAM
				,VL_CANCELLED_ORDER_VALUE_PARAM						= kpi.VL_CANCELLED_ORDER_VALUE_PARAM
				,VL_CANCELLED_ORDER_QUANTITY_PARAM					= kpi.VL_CANCELLED_ORDER_QUANTITY_PARAM	
				,VL_NET_ORDER_VALUE_FULL_PRICE_PARAM				= kpi.VL_NET_ORDER_VALUE_FULL_PRICE_PARAM	
				,VL_NETORDER_QUANTITY_PARAM							= kpi.VL_NETORDER_QUANTITY_PARAM    
				,VL_NET_ORDER_VALUE_PARAM							= kpi.VL_NET_ORDER_VALUE_PARAM
				,VL_NET_PRODUCT_COSTS_THEREOF_RETURN_MEK_PARAM		= kpi.VL_NET_PRODUCT_COSTS_THEREOF_RETURN_MEK_PARAM

				--KPI's
				,AMT_COMMERCIAL_TURNOVER_EUR							= (ISNULL(VL_ITEM_QUANTITY,0) *1000) * VL_COMMERCIAL_TURNOVER_PARAM		
				,AMT_TURNOVER_EUR										= (ISNULL(AMT_GROSS_PRICE_EUR,0)) * VL_TURNOVER_PARAM	
				,VL_ORDER_QUANTITY										= (ISNULL(VL_ITEM_QUANTITY,0)   )* VL_ORDER_QUANTITY_PARAM				
				,AMT_VALUE_ADDED_TAX_EUR								= (ABS(ISNULL(AMT_TAX_PRICE_EUR,0))   )* VL_VALUE_ADDED_TAX_PARAM		
				,AMT_ORDER_DISCOUNTS_EUR								= (ABS(ISNULL(AMT_NET_DISCOUNT_EUR,0))   )* VL_ORDER_DISCOUNTS_PARAM
				,AMT_ORDER_CHARGES_EUR									= (ISNULL(AMT_NET_SHIPPING_REVENUE_EUR,0)   )* VL_ORDER_CHARGES_PARAM
				,VL_CANCELLED_RATE										= ISNULL(cll.VL_RATE,0)
				,PCT_MARKETING											= ISNULL(marketplaces.[PCT_MARKETING],0)		
				,PCT_COMMISSIONS_MARKETPLACES							= ISNULL(CM.PCT_COMMISSIONS_ORDER,0)
				,PCT_COMMISSIONS_MARKETPLACES_RETURN					= ISNULL(CM.PCT_COMMISSIONS_RETURN,0)
				,PCT_PAYMENTS_ORDER										= ISNULL(PAY.PCT_PAYMENTS_ORDER, 0)
				,VL_AMAZON_COMMISSIONS_ORDER_RATE						= c_amaz.[VL_COMMISSIONS_ORDER_RATE]
				--,[AMT_SHIP_CORRECTION_FACTOR_ORDER]					= factor.[AMT_CORRECTION_FACTOR_ORDER]
				--,[AMT_SHIP_CORRECTION_FACTOR_RETURN]					= factor.[AMT_CORRECTION_FACTOR_RETURN]
				--,[AMT_SHIP_CORRECTION_FACTOR_REPLACEMENT]				= factor.[AMT_CORRECTION_FACTOR_REPLACEMENT]
				,AMT_ENVIRO_REST_UNIT_FEE_CALC_EUR						= env.AMT_FEE_PER_UNIT * COALESCE(enviro_rate.VL_FX_RATE, 1)* kpi.VL_ENVIRO_EST_PARAM
				,AMT_REPACKING_FEE_PER_UNIT_CALC_EUR					= repack.AMT_FEE_PER_UNIT * COALESCE(enviro_rate.VL_FX_RATE, 1) * 0.025 * kpi.VL_ENVIRO_EST_PARAM

				,LOAD_TIMESTAMP											= GREATEST(fact.[D_EFF_FROM],kpi.[D_EFF_FROM],c_amaz.[D_EFF_FROM]) 
				,D_EFF_TO												= fact.[D_EFF_TO] 
				,D_EFF_DELETED											= fact.[D_EFF_DELETED]
				,FL_DELETED												= fact.FL_DELETED

				FROM [L1].[L1_FACT_A_SALES_TRANSACTION] fact 
		LEFT JOIN [L1].[L1_DIM_A_SALES_TRAN_KPI_MATRIX] kpi
			ON kpi.ID_SALES_TRANSACTION_TYPE = fact.ID_SALES_TRANSACTION_TYPE
		LEFT JOIN [L1].[L1_DIM_A_ITEM] item 
			ON item.[ID_ITEM]=fact.ID_ITEM
		LEFT JOIN [L1].[L1_DIM_A_COMPANY] dimcomp
			 on dimcomp.ID_COMPANY=fact.ID_COMPANY
		LEFT JOIN [L0].[L0_MI_COUNTRY_GROUP] cmi
			ON fact.CD_COUNTRY_INVOICE = cmi.COUNTRY
		LEFT JOIN L1.L1_DIM_A_ORDER_CANCELLATION_VALUES cll  
			on fact.D_CREATED BETWEEN cll.D_VALID_FROM AND cll.D_VALID_TO
			and cmi.CANCELLATION_RATE_COUNTRY_GROUP=cll.CD_COUNTRY_INVOICE_GROUP
			and fact.T_PRODUCT_HIERARCHY_2 =cll.[T_PRODUCT_HIERARCHY_2]
		LEFT JOIN [L1].[L1_DIM_A_SALES_CHANNEL] dimchannel
			ON fact.ID_SALES_CHANNEL = dimchannel.ID_SALES_CHANNEL
	    LEFT JOIN [L1].[L1_DIM_A_MARKETING_MARKETPLACES] marketplaces
			ON fact.ID_SALES_CHANNEL = marketplaces.ID_SALES_CHANNEL
			AND fact.[T_PRODUCT_HIERARCHY_1] = marketplaces.[T_PRODUCT_HIERARCHY_1]
			AND fact.[T_PRODUCT_HIERARCHY_2] = marketplaces.[T_PRODUCT_HIERARCHY_2]
			AND fact.D_CREATED BETWEEN marketplaces.D_VALID_FROM AND marketplaces.D_VALID_TO
		LEFT JOIN [L1].[L1_DIM_A_CS_COMMISSIONS_MARKETPLACES]			AS CM
			ON dimchannel.CD_CHANNEL_GROUP_2 = CM.CD_CHANNEL_GROUP_2
			AND dimchannel.CD_CHANNEL_GROUP_1 = CM.CD_CHANNEL_GROUP_1
			AND fact.T_PRODUCT_HIERARCHY_1 = CM.T_PRODUCT_HIERARCHY_1
			AND fact.T_PRODUCT_HIERARCHY_2 = CM.T_PRODUCT_HIERARCHY_2
			AND fact.D_CREATED BETWEEN CM.D_VALID_FROM AND CM.D_VALID_TO
		LEFT JOIN [L1].[L1_DIM_A_CS_PAYMENTS]							AS PAY
			ON fact.[ID_SALES_CHANNEL] = PAY.[ID_SALES_CHANNEL]
			AND fact.D_CREATED BETWEEN PAY.D_VALID_FROM AND PAY.D_VALID_TO
		LEFT JOIN [L1].[L1_DIM_A_CS_COMMISSIONS_AMAZON] c_amaz
	        ON fact.T_PRODUCT_HIERARCHY_1 = c_amaz.T_PRODUCT_HIERARCHY_1
	        AND fact.T_PRODUCT_HIERARCHY_2 = c_amaz.T_PRODUCT_HIERARCHY_2
			AND dimchannel.CD_CHANNEL_COUNTRY = c_amaz.CD_CHANNEL_COUNTRY
	        AND fact.D_CREATED BETWEEN c_amaz.D_VALID_FROM AND c_amaz.D_VALID_TO
	    LEFT JOIN [L0].[L0_MI_COUNTRY_GROUP] cmd
			ON fact.CD_COUNTRY_DELIVERY = cmd.COUNTRY
			--join fulfillment shipping factor
		--LEFT JOIN L1.L1_DIM_A_FULFILLMENT_SHIPPING_FACTOR factor
		--	ON fact.CD_SIZE_BRACKET = factor.CD_SIZE_BRACKET
		--		AND fact.CD_FULFILLMENT = factor.CD_FULFILLMENT
		--		AND ISNULL(fact.T_REVISED_LOCATION,fact.T_STORAGE_LOCATION) = factor.T_STORAGE_LOCATION
		--		AND cmd.COUNTRYGROUP = factor.[CD_COUNTRY_DELIVERY_GROUP]
		--		AND fact.D_CREATED BETWEEN factor.D_VALID_FROM AND factor.D_VALID_TO 
		--join enviro
		LEFT JOIN  CTE_ENVIRO env
			ON fact.ID_ITEM = env.ID_ITEM
			AND fact.CD_COUNTRY_DELIVERY = env.CD_COUNTRY_DELIVERY
		--join enviro for repackacing
		LEFT JOIN [L1].[L1_DIM_A_ENVIRO_REST_UNIT_FEES] repack
			ON fact.ID_ITEM = repack.ID_ITEM
			AND fact.CD_COUNTRY_DELIVERY = repack.CD_COUNTRY_DELIVERY
			AND repack.CD_ENVIRO_CATEGORY = 'Packaging'
		--join fx rate for enviro
		LEFT JOIN [L1].[L1_FACT_F_FX_RATE] enviro_rate
			ON env.cd_currency=enviro_rate.cd_currency
			AND Year(fact.D_CREATED)=Year(enviro_rate.D_EFFECTIVE)
			AND Month(fact.D_CREATED)=Month(enviro_rate.D_EFFECTIVE)
		LEFT JOIN [L1].[L1_DIM_A_DEPRECIATION_VALUES] dep
			on fact.D_CREATED between dep.D_VALID_FROM and dep.D_VALID_TO
				AND dep.T_PRODUCT_HIERARCHY_2 = fact.T_PRODUCT_HIERARCHY_2
				and dep.T_STORAGE_LOCATION = fact.T_STORAGE_LOCATION
		LEFT JOIN CTE_CAPO_SERVICES capo
			ON capo.item_code = item.NUM_ITEM
				AND
				capo.warehouse = CASE WHEN ISNULL(fact.T_REVISED_LOCATION,fact.T_STORAGE_LOCATION)	 = 'Alicante' THEN 'Kamp-Lintfort' ELSE ISNULL(fact.T_REVISED_LOCATION,fact.T_STORAGE_LOCATION)	 END
				AND capo.Fulfillment = fact.CD_FULFILLMENT
				AND capo.Country = fact.CD_COUNTRY_DELIVERY


		WHERE 
			(item.NUM_ITEM NOT LIKE '7%' OR ID_ITEM_PARENT IS NOT NULL )
			AND item.NUM_ITEM NOT LIKE '6%'
			AND (fact.D_CREATED>=@LOAD_START_DATE OR fact.[DT_DWH_UPDATED]>=@LOAD_START_DATE)
			--AND fact.CD_TYPE IN ('ZAA','ZKE','ZAZ')
			and kpi.VL_GROSS_ORDER_VALUE_PARAM = 1
			and isnull (FL_INCIDENT,'N') = 'N'
			and dimchannel.CD_CHANNEL_GROUP_1 not in ('Intercompany', 'Mandanten')
			and dimchannel.CD_CHANNEL_GROUP_1 is not null
		 
	),
	CTE_SALES_L2 AS 
	(
		SELECT sales.*
			,AMT_COMMISSIONS_MARKETPLACES_EST_EUR																	= AMT_TURNOVER_EUR * [PCT_COMMISSIONS_MARKETPLACES]
			,AMT_GROSS_ORDER_VALUE_EUR																			= (ISNULL(AMT_TURNOVER_EUR,0) - ISNULL(AMT_VALUE_ADDED_TAX_EUR,0) - ISNULL(AMT_ORDER_DISCOUNTS_EUR,0) + ISNULL(AMT_ORDER_CHARGES_EUR,0))			
			,VL_CANCELLED_ORDERS_QUANTITY_EST																	= (VL_ORDER_QUANTITY * VL_CANCELLED_RATE)* VL_CANCELLED_ORDERS_QUANTITY_EST_PARAM
	        ,AMT_COMMISSIONS_AMAZON_EST_EUR = CASE WHEN CD_CHANNEL_GROUP_1 = 'Amazon' then AMT_TURNOVER_EUR*VL_AMAZON_COMMISSIONS_ORDER_RATE ELSE NULL END		
			,AMT_TURNOVER_WITH_DISCOUNTS_EUR = (ISNULL(AMT_TURNOVER_EUR,0) - ISNULL(AMT_ORDER_DISCOUNTS_EUR,0) + ISNULL(AMT_ORDER_CHARGES_EUR,0))  
		FROM CTE_SALES_L1 sales
	)
	,
	CTE_SALES_L3 AS 
	(
		SELECT sales.*
				,AMT_CANCELLED_ORDER_VALUE_EST_EUR				= (AMT_GROSS_ORDER_VALUE_EUR * VL_CANCELLED_RATE)* VL_CANCELLED_ORDER_VALUE_EST_PARAM					
				,VL_NET_ORDER_QUANTITY_EST						= (VL_ORDER_QUANTITY - VL_CANCELLED_ORDERS_QUANTITY_EST) * VL_NET_ORDER_QUANTITY_EST_PARAM	
				,AMT_REFUNDED_ORDER_VALUE_EST_EUR				=  (AMT_GROSS_ORDER_VALUE_EUR * VL_REFUND_RATE) * VL_REFUNDED_ORDER_VALUE_EST_PARAM	
				,AMT_RETURNED_ORDER_VALUE_EST_EUR				=  (AMT_GROSS_ORDER_VALUE_EUR * VL_RETURN_RATE) * VL_RETURN_ORDER_VALUE_EST_PARAM	
				,AMT_MARKETING_MARKETPLACES_EST_EUR				= (PCT_MARKETING * AMT_GROSS_ORDER_VALUE_EUR)
				,AMT_COMMISSIONS_AMAZON_REFUNDS_EST_EUR			= CASE WHEN AMT_COMMISSIONS_AMAZON_EST_EUR BETWEEN c_amaz_ref.[VL_VALUE_FROM] and c_amaz_ref.[VL_VALUE_TO] 
																			THEN CASE WHEN c_amaz_ref.[VL_COMMISSIONS_REFUND_ABOVE_THRESHOLD] <> 0 
																						THEN (AMT_COMMISSIONS_AMAZON_EST_EUR - c_amaz_ref.[VL_COMMISSIONS_REFUND_ABOVE_THRESHOLD])*sales.VL_REFUND_RATE 
																						ELSE (AMT_COMMISSIONS_AMAZON_EST_EUR * c_amaz_ref.[VL_COMMISSIONS_REFUND_BELOW_THRESHOLD_RATE])*sales.VL_REFUND_RATE 
																				END
																ELSE NULL END 
				,[AMT_CANCELLED_ORDER_VALUE_EUR]			= CASE  
																	WHEN isnull(T_CANCELLATION_REASON,'')  NOT IN ('Wrongly created','')OR sales.CD_SOURCE_SYSTEM = 'SGE'
																	THEN (AMT_GROSS_ORDER_VALUE_EUR) * VL_CANCELLED_ORDER_VALUE_PARAM ELSE 0 END	 
				,[VL_CANCELLED_ORDER_QUANTITY]				= CASE 
																	WHEN isnull(T_CANCELLATION_REASON,'')  NOT IN ('Wrongly created','')OR sales.CD_SOURCE_SYSTEM = 'SGE'
																	 THEN ISNULL(VL_ORDER_QUANTITY,0) * VL_CANCELLED_ORDER_QUANTITY_PARAM ELSE 0 END	
	    FROM CTE_SALES_L2 sales
	    LEFT JOIN [L1].[L1_DIM_A_CS_COMMISSIONS_AMAZON_REFUND] c_amaz_ref
	         ON sales.D_CREATED BETWEEN c_amaz_ref.[D_VALID_FROM] AND c_amaz_ref.[D_VALID_TO]
	         AND AMT_COMMISSIONS_AMAZON_EST_EUR > c_amaz_ref.VL_VALUE_FROM 
	         AND AMT_COMMISSIONS_AMAZON_EST_EUR <= c_amaz_ref.VL_VALUE_TO 
	)
	,
	CTE_SALES_L4 AS 
	(
		SELECT sales.*
				 ,AMT_COMMISSIONS_MARKETPLACES_REFUNDS_EST_EUR								= (AMT_REFUNDED_ORDER_VALUE_EST_EUR * [PCT_COMMISSIONS_MARKETPLACES_RETURN])	
				 ,AMT_NET_ORDER_VALUE_EST_EUR												= (AMT_GROSS_ORDER_VALUE_EUR - AMT_CANCELLED_ORDER_VALUE_EST_EUR)*VL_NET_ORDER_VALUE_EST_PARAM
				 ,VL_REFUNDED_QUANTITY_EST													= (VL_NET_ORDER_QUANTITY_EST * VL_REFUND_RATE) *  VL_REFUNDED_QUANTITY_EST_PARAM						
				 ,VL_RETURNED_QUANTITY_EST													= (VL_NET_ORDER_QUANTITY_EST * VL_RETURN_RATE) * VL_RETURNED_QUANTITY_EST_PARAM				
				 ,VL_REPLACEMENT_QUANTITY_EST												= (VL_NET_ORDER_QUANTITY_EST * VL_REPLACEMENT_RATE)* VL_RETURNED_QUANTITY_EST_PARAM	
				 ,[AMT_NET_ORDER_VALUE_EUR]													= (AMT_GROSS_ORDER_VALUE_EUR - [AMT_CANCELLED_ORDER_VALUE_EUR])		
				 ,[AMT_NET_ORDER_VALUE_FULL_PRICE_EUR]										= ((AMT_GROSS_ORDER_VALUE_EUR+AMT_ORDER_DISCOUNTS_EUR) - [AMT_CANCELLED_ORDER_VALUE_EUR]) *VL_NET_ORDER_VALUE_FULL_PRICE_PARAM
				 ,[VL_NET_ORDER_QUANTITY]													= (VL_ORDER_QUANTITY - [VL_CANCELLED_ORDER_QUANTITY]) * VL_CANCELLED_ORDER_QUANTITY_PARAM
		FROM CTE_SALES_L3 sales
	)
	,
	CTE_SALES_L5 AS 
	(
		SELECT sales.*
				,AMT_REVENUE_EST_EUR								= (ISNULL(AMT_NET_ORDER_VALUE_EST_EUR,0) - ISNULL(AMT_REFUNDED_ORDER_VALUE_EST_EUR,0)) * [VL_REVENUE_EST_PARAM]
				,VL_NET_QUANTITY_EST								= (ISNULL(VL_NET_ORDER_QUANTITY_EST,0) - ISNULL(VL_REFUNDED_QUANTITY_EST,0)) * [VL_NET_QUANTITY_EST_PARAM] 
				,AMT_NET_PRODUCT_COSTS_THEREOF_RETURN_MEK_EUR		= ISNULL(AMT_MEK_HEDGING_EUR,0)	* VL_NET_PRODUCT_COSTS_THEREOF_RETURN_MEK_PARAM		
				,AMT_SHIPPING_COST_INVOICED_EST_EUR 					= (VL_NET_ORDER_QUANTITY_EST * AMT_SHIPPING_COST_EST_EUR) --* ISNULL(AMT_SHIP_CORRECTION_FACTOR_ORDER,1))
				,AMT_SHIPPING_COST_RETURNED_EST_EUR 					= (VL_RETURNED_QUANTITY_EST * AMT_SHIPPING_COST_EST_EUR) --* ISNULL(AMT_SHIP_CORRECTION_FACTOR_RETURN,1))
				,AMT_SHIPPING_COST_REPLACED_EST_EUR 					= (VL_REPLACEMENT_QUANTITY_EST * AMT_SHIPPING_COST_EST_EUR) --* ISNULL(AMT_SHIP_CORRECTION_FACTOR_REPLACEMENT,1))
				,AMT_NET_ORDER_CONTRIBUTION_EST_EUR					= AMT_NET_ORDER_VALUE_EST_EUR - (CASE WHEN VL_NET_ORDER_QUANTITY_EST <> 0 THEN (((VL_NET_ORDER_QUANTITY_EST) * (ISNULL(AMT_MEK_HEDGING_EUR,0)-ISNULL(AMT_GTS_MARKUP,0)) )/ISNULL(VL_NET_ORDER_QUANTITY_EST,1)) * [VL_NET_QUANTITY_EST_PARAM]  ELSE 0 END)
				,AMT_ENVIRO_REST_UNIT_FEE_EUR						= (VL_NET_ORDER_QUANTITY_EST - VL_RETURNED_QUANTITY_EST+VL_REPLACEMENT_QUANTITY_EST)*AMT_ENVIRO_REST_UNIT_FEE_CALC_EUR 
				,AMT_REPACKING_FEE_UNIT_EUR							= (VL_NET_ORDER_QUANTITY_EST - VL_RETURNED_QUANTITY_EST+VL_REPLACEMENT_QUANTITY_EST)*AMT_REPACKING_FEE_PER_UNIT_CALC_EUR

				,AMT_MEK_TO_CUSTOMER_EST_EUR						= CASE WHEN VL_NET_ORDER_QUANTITY_EST <> 0 
																			THEN (((VL_NET_ORDER_QUANTITY_EST) * (ISNULL(AMT_MEK_HEDGING_EUR,0)-ISNULL(AMT_GTS_MARKUP,0)) )/ISNULL(VL_NET_ORDER_QUANTITY_EST,1)) * [VL_NET_QUANTITY_EST_PARAM]  
																		ELSE 0 END	
				,AMT_MEK_FROM_CUSTOMER_EST_EUR						= CASE WHEN VL_NET_ORDER_QUANTITY_EST <> 0 
																			THEN (((VL_RETURNED_QUANTITY_EST) * (ISNULL(AMT_MEK_HEDGING_EUR,0)-ISNULL(AMT_GTS_MARKUP,0)) )/ISNULL(VL_NET_ORDER_QUANTITY_EST,1)) * [VL_NET_QUANTITY_EST_PARAM]  
																		ELSE 0 END	
				,AMT_MEK_REPLACEMENT_EST_EUR						= CASE WHEN VL_NET_ORDER_QUANTITY_EST <> 0 
																			THEN (((VL_REPLACEMENT_QUANTITY_EST) * (ISNULL(AMT_MEK_HEDGING_EUR,0)-ISNULL(AMT_GTS_MARKUP,0)) )/ISNULL(VL_NET_ORDER_QUANTITY_EST,1)) * [VL_NET_QUANTITY_EST_PARAM]  
																		ELSE 0 END
				,AMT_MEK_DEPRECIATION_EST_EUR 						= CASE WHEN VL_NET_ORDER_QUANTITY_EST <> 0 
																			THEN (((VL_RETURNED_QUANTITY_EST * VL_DEPRETIATION_RATE) * (ISNULL(AMT_MEK_HEDGING_EUR,0)-ISNULL(AMT_GTS_MARKUP,0)) )/ISNULL(VL_NET_ORDER_QUANTITY_EST,1)) * [VL_NET_QUANTITY_EST_PARAM]  
																		ELSE 0 END

		FROM CTE_SALES_L4 sales
	)
	,
	CTE_SALES_L6 AS 
	(
		SELECT sales.*
				 ,AMT_PAYMENTS_FEES_EST_EUR							= (AMT_REVENUE_EST_EUR * [PCT_PAYMENTS_ORDER])	
				 ,AMT_SHIPPING_OUTBOUND_EST_EUR						= (ISNULL(AMT_SHIPPING_COST_INVOICED_EST_EUR,0)+ISNULL(AMT_SHIPPING_COST_RETURNED_EST_EUR,0)+ISNULL(AMT_SHIPPING_COST_REPLACED_EST_EUR,0))	
				 ,AMT_ELECTRONIC_WASTE_EST_EUR						= ISNULL(AMT_ENVIRO_REST_UNIT_FEE_EUR,0)+ISNULL(AMT_REPACKING_FEE_UNIT_EUR,0)                                                                       
				 ,AMT_FULL_NET_PRODUCT_COST_EST_EUR					= ISNULL(AMT_MEK_TO_CUSTOMER_EST_EUR,0) - ISNULL(AMT_MEK_FROM_CUSTOMER_EST_EUR,0) + ISNULL(AMT_MEK_REPLACEMENT_EST_EUR,0) +ISNULL(AMT_MEK_DEPRECIATION_EST_EUR,0) 
				 ,AMT_COMMISSIONS_SALE_EST_EUR						= ISNULL(AMT_COMMISSIONS_MARKETPLACES_EST_EUR,0) + ISNULL(AMT_COMMISSIONS_AMAZON_EST_EUR,0)
				 ,AMT_COMMISSIONS_REFUNDS_EST_EUR					= ISNULL(AMT_COMMISSIONS_AMAZON_REFUNDS_EST_EUR,0)+ISNULL(AMT_COMMISSIONS_MARKETPLACES_REFUNDS_EST_EUR,0)
				 ,AMT_COMMISSIONS_EST_EUR							= (ISNULL(AMT_COMMISSIONS_MARKETPLACES_EST_EUR,0)-ISNULL(AMT_COMMISSIONS_MARKETPLACES_REFUNDS_EST_EUR,0)+ISNULL(AMT_COMMISSIONS_AMAZON_EST_EUR,0)-ISNULL(AMT_COMMISSIONS_AMAZON_REFUNDS_EST_EUR,0))
		FROM CTE_SALES_L5 sales
	)
	,
	CTE_SALES_L7 AS 
	(
		SELECT sales.*
				,AMT_PC0_EST_EUR									= (AMT_REVENUE_EST_EUR - AMT_FULL_NET_PRODUCT_COST_EST_EUR ) * VL_PC0_PARAM
				,AMT_STEERING_MARGIN_EST_EUR						=  ISNULL(AMT_REVENUE_EST_EUR,0) - ISNULL(AMT_FULL_NET_PRODUCT_COST_EST_EUR,0)
																		- ISNULL(AMT_COMMISSIONS_EST_EUR,0) - ISNULL(AMT_PAYMENTS_FEES_EST_EUR,0) 
																		- ISNULL(AMT_ELECTRONIC_WASTE_EST_EUR,0)
																		- ISNULL(AMT_SHIPPING_OUTBOUND_EST_EUR,0)
				,[AMT_GROSS_MARGIN_EST_EUR]							= ISNULL(AMT_REVENUE_EST_EUR,0) - ISNULL(AMT_FULL_NET_PRODUCT_COST_EST_EUR,0)
		FROM CTE_SALES_L6 sales
	)
	INSERT INTO  [WR].[WR_L1_FACT_A_SALES_TRANSACTION_KPI_SM]
		(
		 ID_SALES_TRANSACTION
		,CD_SALES_TRANSACTION
		,CD_SOURCE_SYSTEM
		,CD_SALES_PROCESS_ID
		,CD_SALES_PROCESS_LINE
		,CD_DOCUMENT_NO
		,CD_DOCUMENT_LINE
		,CD_DOCUMENT_ID_REFERENCE
		,ID_COMPANY
		,D_CREATED
		,D_SALES_PROCESS
		,D_DOCUMENT_CREATED
		,T_CANCELLATION_REASON
		,FL_INCIDENT
		,DT_CREATED
		,CD_TYPE
		,ID_SALES_TRANSACTION_TYPE
		,ID_ITEM
		,ID_ITEM_PARENT 
		,CD_ITEM_TYPE
		,ID_SALES_CHANNEL
		,CD_FULFILLMENT
		,CD_CUSTOMER
		,CD_CUSTOMER_SERVICE_AGENT                                         
		,T_CREATION_USERNAME
		,CD_MARKET_ORDER_ID
		,CD_PAYMENT_METHOD
		,CD_STORAGE_LOCATION
		,T_STORAGE_LOCATION
		,CD_COUNTRY_INVOICE
		,CD_ZIP_INVOICE
		,T_CITY_INVOICE
		,CD_COUNTRY_DELIVERY
		,CD_ZIP_DELIVERY
		,T_CITY_DELIVERY
		,CD_COUNTRY_ORDER
		,CD_ZIP_ORDER
		,T_CITY_ORDER
		,CD_BILLING_CATEGORY	
		,D_BILLING_DATE					
		,CD_BILLING_POSTING_STATUS		
		,CD_PAYER						
		,VL_BILLING_QUANTITY			
		,VL_EXCHANGE_RATE				
		,CD_SALES_DOCUMENT_NO           
		,D_UPDATED						
		,CD_REJECTION_STATUS			
		,D_CANCELLATION
		,[CD_RETURN_REASON]         
        ,[T_RETURN_REASON] 
		,VL_ITEM_QUANTITY
		,VL_ITEM_PARENT_QUANTITY
		,AMT_NET_SHIPPING_REVENUE_EUR
		,AMT_NET_PRICE_EUR
		,AMT_NET_PRICE_FC
		,AMT_SHIPPING_COST_EST_EUR
		,AMT_SHIPPING_COST_SERVICES_EST_EUR
		,CD_SHIPMENT_COSTS_SOURCE
		,AMT_GROSS_SHIPPING_REVENUE_EUR
		,AMT_GROSS_SHIPPING_REVENUE_FC
		,AMT_GROSS_PRICE_EUR
		,AMT_GROSS_PRICE_FC
		,AMT_TAX_PRICE_EUR
		,AMT_TAX_DISCOUNTS_EUR
		,AMT_TAX_FREIGHT_EUR
		,AMT_TAX_TOTAL_EUR
		,AMT_TAX_TOTAL_PAYABLE_EUR
		,AMT_TAX_TOTAL_PAYABLE_FC
        ,AMT_TAX_OUTPUT_EUR
		,AMT_TAX_OUTPUT_FC
		,AMT_MEK_HEDGING_EUR
		,AMT_GTS_MARKUP
		,AMT_NET_DISCOUNT_EUR
		,AMT_NET_DISCOUNT_FC                                     
		,CD_CURRENCY
		,AMT_COMMERCIAL_TURNOVER_EUR
		,AMT_TURNOVER_EUR
		,VL_ORDER_QUANTITY
		,AMT_VALUE_ADDED_TAX_EUR
		,AMT_ORDER_DISCOUNTS_EUR
		,AMT_ORDER_CHARGES_EUR
		,AMT_GROSS_ORDER_VALUE_EUR
		,VL_CANCELLED_ORDERS_QUANTITY_EST
		,VL_RETURNED_QUANTITY_EST
		,AMT_CANCELLED_ORDER_VALUE_EST_EUR
		,VL_NET_ORDER_QUANTITY_EST
		,AMT_REFUNDED_ORDER_VALUE_EST_EUR
		,AMT_RETURNED_ORDER_VALUE_EST_EUR
		,AMT_NET_ORDER_VALUE_EST_EUR
		,VL_REFUNDED_QUANTITY_EST
		,AMT_REVENUE_EST_EUR
		,VL_NET_QUANTITY_EST
		,AMT_NET_ORDER_CONTRIBUTION_EST_EUR
		,AMT_PC0_EST_EUR
		,AMT_MARKETING_MARKETPLACES_EST_EUR
		,AMT_COMMISSIONS_MARKETPLACES_EST_EUR
		,AMT_COMMISSIONS_MARKETPLACES_REFUNDS_EST_EUR
		,AMT_PAYMENTS_FEES_EST_EUR
		,VL_REPLACEMENT_QUANTITY_EST
		,AMT_COMMISSIONS_AMAZON_EST_EUR
		,AMT_COMMISSIONS_AMAZON_REFUNDS_EST_EUR
		,AMT_SHIPPING_OUTBOUND_EST_EUR
		,CD_COUNTRY_GROUP_INVOICE
		,CD_COUNTRY_GROUP_DELIVERY
		,AMT_ENVIRO_REST_UNIT_FEE_EUR
	    ,AMT_REPACKING_FEE_UNIT_EUR
		,[AMT_CANCELLED_ORDER_VALUE_EUR]
		,[VL_CANCELLED_ORDER_QUANTITY]            
		,[AMT_NET_ORDER_VALUE_EUR]                
		,[AMT_NET_ORDER_VALUE_FULL_PRICE_EUR]     
		,[VL_NET_ORDER_QUANTITY]          
		,AMT_NET_PRODUCT_COSTS_THEREOF_RETURN_MEK_EUR
		--,LOAD_TIMESTAMP
	    ,[D_EFF_TO]
	    ,[D_EFF_DELETED]
		,FL_DELETED
		,AMT_TOTAL_NET_PRICE_EUR
		,AMT_TOTAL_NET_PRICE_FC
		,AMT_TAX_REVERSED_EUR
		,AMT_TAX_REVERSED_FC
		,AMT_TOTAL_PRICE_EUR
		,AMT_TOTAL_PRICE_FC
		,CD_PRECEDING_DOCUMENT_NO 
        ,CD_LINKED_DOCUMENT_NO 
		,AMT_ELECTRONIC_WASTE_EST_EUR
		,AMT_NET_SHIPPING_REVENUE_FC
        ,CD_CARRIER
		,VL_REFUND_RATE 					
	    ,VL_RETURN_RATE					
	    ,VL_REPLACEMENT_RATE 	
		,VL_DEPRETIATION_RATE
		,CD_REFUND_RATE_SOURCE 
        ,CD_RETURN_RATE_SOURCE 
        ,CD_REPLACEMENT_RATE_SOURCE 
		,AMT_MEK_TO_CUSTOMER_EST_EUR 
		,AMT_MEK_FROM_CUSTOMER_EST_EUR
		,AMT_MEK_REPLACEMENT_EST_EUR 
		,AMT_MEK_DEPRECIATION_EST_EUR 
		,AMT_COMMISSIONS_EST_EUR
		,AMT_COMMISSIONS_SALE_EST_EUR
		,AMT_COMMISSIONS_REFUNDS_EST_EUR
		,AMT_STEERING_MARGIN_EST_EUR
		,AMT_FULL_NET_PRODUCT_COST_EST_EUR
		,AMT_SHIPPING_COST_INVOICED_EST_EUR 
		,AMT_SHIPPING_COST_RETURNED_EST_EUR  
		,AMT_SHIPPING_COST_REPLACED_EST_EUR  
		,AMT_GROSS_MARGIN_EST_EUR
		)

		SELECT 
			 ID_SALES_TRANSACTION
		,CD_SALES_TRANSACTION
		,CD_SOURCE_SYSTEM
		,CD_SALES_PROCESS_ID
		,CD_SALES_PROCESS_LINE
		,CD_DOCUMENT_NO
		,CD_DOCUMENT_LINE
		,CD_DOCUMENT_ID_REFERENCE
		,ID_COMPANY
		,D_CREATED
		,D_SALES_PROCESS
		,D_DOCUMENT_CREATED
		,T_CANCELLATION_REASON
		,FL_INCIDENT
		,DT_CREATED
		,CD_TYPE
		,ID_SALES_TRANSACTION_TYPE
		,ID_ITEM
		,ID_ITEM_PARENT 
		,CD_ITEM_TYPE
		,ID_SALES_CHANNEL
		,CD_FULFILLMENT
		,CD_CUSTOMER
		,CD_CUSTOMER_SERVICE_AGENT                                         
		,T_CREATION_USERNAME
		,CD_MARKET_ORDER_ID
		,CD_PAYMENT_METHOD
		,CD_STORAGE_LOCATION
		,T_STORAGE_LOCATION
		,CD_COUNTRY_INVOICE
		,CD_ZIP_INVOICE
		,T_CITY_INVOICE
		,CD_COUNTRY_DELIVERY
		,CD_ZIP_DELIVERY
		,T_CITY_DELIVERY
		,CD_COUNTRY_ORDER
		,CD_ZIP_ORDER
		,T_CITY_ORDER
		,CD_BILLING_CATEGORY	
		,D_BILLING_DATE					
		,CD_BILLING_POSTING_STATUS		
		,CD_PAYER						
		,VL_BILLING_QUANTITY			
		,VL_EXCHANGE_RATE				
		,CD_SALES_DOCUMENT_NO           
		,D_UPDATED						
		,CD_REJECTION_STATUS			
		,D_CANCELLATION
		,[CD_RETURN_REASON]         
        ,[T_RETURN_REASON] 
		,VL_ITEM_QUANTITY
		,VL_ITEM_PARENT_QUANTITY
		,AMT_NET_SHIPPING_REVENUE_EUR
		,AMT_NET_PRICE_EUR
		,AMT_NET_PRICE_FC
		,ISNULL(AMT_SHIPPING_COST_EST_EUR,0) - ISNULL(AMT_SHIPPING_COST_SERVICES_EST_EUR,0)
		,AMT_SHIPPING_COST_SERVICES_EST_EUR
		,CD_SHIPMENT_COSTS_SOURCE
		,AMT_GROSS_SHIPPING_REVENUE_EUR
		,AMT_GROSS_SHIPPING_REVENUE_FC
		,AMT_GROSS_PRICE_EUR
		,AMT_GROSS_PRICE_FC
		,AMT_TAX_PRICE_EUR
		,AMT_TAX_DISCOUNTS_EUR
		,AMT_TAX_FREIGHT_EUR
		,AMT_TAX_TOTAL_EUR
		,AMT_TAX_TOTAL_PAYABLE_EUR
		,AMT_TAX_TOTAL_PAYABLE_FC
        ,AMT_TAX_OUTPUT_EUR
		,AMT_TAX_OUTPUT_FC
		,AMT_MEK_HEDGING_EUR
		,AMT_GTS_MARKUP
		,AMT_NET_DISCOUNT_EUR
		,AMT_NET_DISCOUNT_FC                                     
		,CD_CURRENCY
		,AMT_COMMERCIAL_TURNOVER_EUR
		,AMT_TURNOVER_EUR
		,VL_ORDER_QUANTITY
		,AMT_VALUE_ADDED_TAX_EUR
		,AMT_ORDER_DISCOUNTS_EUR
		,AMT_ORDER_CHARGES_EUR
		,AMT_GROSS_ORDER_VALUE_EUR
		,VL_CANCELLED_ORDERS_QUANTITY_EST
		,VL_RETURNED_QUANTITY_EST
		,AMT_CANCELLED_ORDER_VALUE_EST_EUR
		,VL_NET_ORDER_QUANTITY_EST
		,AMT_REFUNDED_ORDER_VALUE_EST_EUR
		,AMT_RETURNED_ORDER_VALUE_EST_EUR
		,AMT_NET_ORDER_VALUE_EST_EUR
		,VL_REFUNDED_QUANTITY_EST
		,AMT_REVENUE_EST_EUR
		,VL_NET_QUANTITY_EST
		,AMT_NET_ORDER_CONTRIBUTION_EST_EUR
		,[AMT_PC0_EST_EUR]
		,AMT_MARKETING_MARKETPLACES_EST_EUR
		,AMT_COMMISSIONS_MARKETPLACES_EST_EUR
		,AMT_COMMISSIONS_MARKETPLACES_REFUNDS_EST_EUR
		,AMT_PAYMENTS_FEES_EST_EUR
		,VL_REPLACEMENT_QUANTITY_EST
		,AMT_COMMISSIONS_AMAZON_EST_EUR
		,AMT_COMMISSIONS_AMAZON_REFUNDS_EST_EUR
		,AMT_SHIPPING_OUTBOUND_EST_EUR
		,CD_COUNTRY_GROUP_INVOICE
		,CD_COUNTRY_GROUP_DELIVERY
		,AMT_ENVIRO_REST_UNIT_FEE_EUR
	    ,AMT_REPACKING_FEE_UNIT_EUR
		,[AMT_CANCELLED_ORDER_VALUE_EUR]
		,[VL_CANCELLED_ORDER_QUANTITY]            
		,[AMT_NET_ORDER_VALUE_EUR]                
		,[AMT_NET_ORDER_VALUE_FULL_PRICE_EUR]     
		,[VL_NET_ORDER_QUANTITY]          
		,AMT_NET_PRODUCT_COSTS_THEREOF_RETURN_MEK_EUR
		--,LOAD_TIMESTAMP
	    ,[D_EFF_TO]
	    ,[D_EFF_DELETED]
		,FL_DELETED
		,AMT_TOTAL_NET_PRICE_EUR
		,AMT_TOTAL_NET_PRICE_FC
		,AMT_TAX_REVERSED_EUR
		,AMT_TAX_REVERSED_FC
		,AMT_TOTAL_PRICE_EUR
		,AMT_TOTAL_PRICE_FC
		,CD_PRECEDING_DOCUMENT_NO 
        ,CD_LINKED_DOCUMENT_NO 
		,AMT_ELECTRONIC_WASTE_EST_EUR
		,AMT_NET_SHIPPING_REVENUE_FC
        ,CD_CARRIER
		,VL_REFUND_RATE 					
	    ,VL_RETURN_RATE					
	    ,VL_REPLACEMENT_RATE 	
		,VL_DEPRETIATION_RATE
		,CD_REFUND_RATE_SOURCE 
        ,CD_RETURN_RATE_SOURCE 
        ,CD_REPLACEMENT_RATE_SOURCE 
		,AMT_MEK_TO_CUSTOMER_EST_EUR 
		,AMT_MEK_FROM_CUSTOMER_EST_EUR
		,AMT_MEK_REPLACEMENT_EST_EUR 
		,AMT_MEK_DEPRECIATION_EST_EUR 
		,AMT_COMMISSIONS_EST_EUR
		,AMT_COMMISSIONS_SALE_EST_EUR
		,AMT_COMMISSIONS_REFUNDS_EST_EUR
		,AMT_STEERING_MARGIN_EST_EUR
		,AMT_FULL_NET_PRODUCT_COST_EST_EUR
		,AMT_SHIPPING_COST_INVOICED_EST_EUR  
		,AMT_SHIPPING_COST_RETURNED_EST_EUR  
		,AMT_SHIPPING_COST_REPLACED_EST_EUR  
		,AMT_GROSS_MARGIN_EST_EUR
FROM CTE_SALES_L7


END

GO


