--- FBM

SELECT  
	 ItemNo = it.NUM_ITEM,
	 ParentItem = it2.NUM_ITEM ,
	 Fullfillment = CD_FULFILLMENT, 
	 DeliveryCountry = CD_COUNTRY_DELIVERY,
	 StorageLocation = T_STORAGE_LOCATION,
	 NetOrderValueEst23 = SUM(CASE WHEN YEAR(fact.D_CREATED) >= 2023  THEN AMT_NET_ORDER_VALUE_EST_EUR ELSE 0 END ),
	 NetOrderValueEst = SUM(AMT_NET_ORDER_VALUE_EST_EUR )
FROM L1.L1_FACT_A_SALES_TRANSACTION_KPI fact
INNER JOIN [L1].[L1_DIM_A_SALES_CHANNEL] channel
	ON channel.ID_SALES_CHANNEL = fact.ID_SALES_CHANNEL
INNER JOIN [L1].[L1_DIM_A_SALES_TRANSACTION_TYPE] ttype
	ON ttype.ID_SALES_TRANSACTION_TYPE = fact.ID_SALES_TRANSACTION_TYPE
INNER JOIN [L1].[L1_DIM_A_ITEM] it
	ON it.ID_ITEM = fact.ID_ITEM
LEFT JOIN  [L1].[L1_DIM_A_ITEM] it2
	ON it2.ID_ITEM = fact.ID_ITEM_PARENT
WHERE 
	[CD_SALES_TRANSACTION_CATEGORY] in ('Order','OrderInvoice')
	AND
		isnull(AMT_SHIPPING_COST_EST_EUR,0) = 0 
	AND CD_FULFILLMENT NOT IN('FBA','B2B')
	AND ISNULL(T_CANCELLATION_REASON,'') = ''
	AND fact.D_CREATED>='2023-11-01'
	AND CD_CHANNEL_GROUP_1 not in ('B2B')
GROUP BY it.NUM_ITEM,it2.NUM_ITEM,CD_FULFILLMENT,T_STORAGE_LOCATION,CD_COUNTRY_DELIVERY



----- FBM

--SELECT 
--	Distinct 
--	 ItemNo = it.NUM_ITEM,
--	 ParentItem = it2.NUM_ITEM ,
--	 Fullfillment = CD_FULFILLMENT, 
--	 DeliveryCountry = CD_COUNTRY_DELIVERY,
--	 StorageLocation = T_STORAGE_LOCATION
--FROM L1.L1_FACT_A_SALES_TRANSACTION_KPI fact
--INNER JOIN [L1].[L1_DIM_A_SALES_CHANNEL] channel
--	ON channel.ID_SALES_CHANNEL = fact.ID_SALES_CHANNEL
--INNER JOIN [L1].[L1_DIM_A_SALES_TRANSACTION_TYPE] ttype
--	ON ttype.ID_SALES_TRANSACTION_TYPE = fact.ID_SALES_TRANSACTION_TYPE
--INNER JOIN [L1].[L1_DIM_A_ITEM] it
--	ON it.ID_ITEM = fact.ID_ITEM
--LEFT JOIN  [L1].[L1_DIM_A_ITEM] it2
--	ON it2.ID_ITEM = fact.ID_ITEM_PARENT
--WHERE 
--	[CD_SALES_TRANSACTION_CATEGORY] in ('Order','OrderInvoice')
--	AND
--		isnull(AMT_SHIPPING_COST_EST_EUR,0) = 0 
--	AND CD_FULFILLMENT IN('PBM')
--	AND ISNULL(T_CANCELLATION_REASON,'') = ''

--- FBA - NON UK
--- IF the channel group is not GB the match is done by country of mercury = channelgroup country. Warehouse is always  Amazon FBA DE (number 2)

SELECT 
	 
	 ItemNo = it.NUM_ITEM,
	 ParentItem = it2.NUM_ITEM ,
	 Fullfillment = CD_FULFILLMENT, 
	 DeliveryCountry = CD_COUNTRY_DELIVERY,
	 Warehouse = 'Amazon FBA DE',
	 ChannelCountry = [CD_CHANNEL_COUNTRY],
	 NetOrderValueEst23 = SUM(CASE WHEN YEAR(fact.D_CREATED) >= 2023  THEN AMT_NET_ORDER_VALUE_EST_EUR ELSE 0 END ),
	 NetOrderValueEst = SUM(AMT_NET_ORDER_VALUE_EST_EUR )
FROM L1.L1_FACT_A_SALES_TRANSACTION_KPI fact
INNER JOIN [L1].[L1_DIM_A_SALES_CHANNEL] channel
	ON channel.ID_SALES_CHANNEL = fact.ID_SALES_CHANNEL
INNER JOIN [L1].[L1_DIM_A_SALES_TRANSACTION_TYPE] ttype
	ON ttype.ID_SALES_TRANSACTION_TYPE = fact.ID_SALES_TRANSACTION_TYPE
INNER JOIN [L1].[L1_DIM_A_ITEM] it
	ON it.ID_ITEM = fact.ID_ITEM
LEFT JOIN  [L1].[L1_DIM_A_ITEM] it2
	ON it2.ID_ITEM = fact.ID_ITEM_PARENT
WHERE 
	[CD_SALES_TRANSACTION_CATEGORY] in ('Order','OrderInvoice')
	AND
		isnull(AMT_SHIPPING_COST_EST_EUR,0) = 0 
	AND CD_FULFILLMENT IN('FBA')
	AND [CD_CHANNEL_COUNTRY] <> 'GB'
	AND ISNULL(T_CANCELLATION_REASON,'') = ''
	AND fact.D_CREATED>='2023-11-01'

GROUP BY it.NUM_ITEM,it2.NUM_ITEM,CD_FULFILLMENT,CD_COUNTRY_DELIVERY,[CD_CHANNEL_COUNTRY]

--- FBA -  UK
--- IF the channel group is  GB the match is done by country of mercury = delivery country. Warehouse is always  Amazon FBA GB (number 1)

SELECT 
	 
	 ItemNo = it.NUM_ITEM,
	 ParentItem = it2.NUM_ITEM ,
	 Fullfillment = CD_FULFILLMENT, 
	 DeliveryCountry = CD_COUNTRY_DELIVERY,
	 Warehouse = 'Amazon FBA GB',
	 ChannelCountry = [CD_CHANNEL_COUNTRY],
	 NetOrderValueEst23 = SUM(CASE WHEN YEAR(fact.D_CREATED) >= 2023  THEN AMT_NET_ORDER_VALUE_EST_EUR ELSE 0 END ),
	 NetOrderValueEst = SUM(AMT_NET_ORDER_VALUE_EST_EUR )
FROM L1.L1_FACT_A_SALES_TRANSACTION_KPI fact
INNER JOIN [L1].[L1_DIM_A_SALES_CHANNEL] channel
	ON channel.ID_SALES_CHANNEL = fact.ID_SALES_CHANNEL
INNER JOIN [L1].[L1_DIM_A_SALES_TRANSACTION_TYPE] ttype
	ON ttype.ID_SALES_TRANSACTION_TYPE = fact.ID_SALES_TRANSACTION_TYPE
INNER JOIN [L1].[L1_DIM_A_ITEM] it
	ON it.ID_ITEM = fact.ID_ITEM
LEFT JOIN  [L1].[L1_DIM_A_ITEM] it2
	ON it2.ID_ITEM = fact.ID_ITEM_PARENT
WHERE 
	[CD_SALES_TRANSACTION_CATEGORY] in ('Order','OrderInvoice')
	AND
		isnull(AMT_SHIPPING_COST_EST_EUR,0) = 0 
	AND CD_FULFILLMENT IN('FBA')
	AND [CD_CHANNEL_COUNTRY] = 'GB'
	AND ISNULL(T_CANCELLATION_REASON,'') = ''
	AND fact.D_CREATED>='2023-11-01'
GROUP BY it.NUM_ITEM,it2.NUM_ITEM,CD_FULFILLMENT,CD_COUNTRY_DELIVERY,[CD_CHANNEL_COUNTRY]


Select 
	  ItemNo = it.NUM_ITEM,
	 ParentItem = it2.NUM_ITEM ,
	 Fullfillment = CD_FULFILLMENT, 
	 DeliveryCountry = CD_COUNTRY_DELIVERY,
	 StorageLocation = T_STORAGE_LOCATION,
	 fact.*,channel.*
FROM L1.L1_FACT_A_SALES_TRANSACTION_KPI fact
INNER JOIN [L1].[L1_DIM_A_SALES_CHANNEL] channel
	ON channel.ID_SALES_CHANNEL = fact.ID_SALES_CHANNEL
INNER JOIN [L1].[L1_DIM_A_SALES_TRANSACTION_TYPE] ttype
	ON ttype.ID_SALES_TRANSACTION_TYPE = fact.ID_SALES_TRANSACTION_TYPE
INNER JOIN [L1].[L1_DIM_A_ITEM] it
	ON it.ID_ITEM = fact.ID_ITEM
LEFT JOIN  [L1].[L1_DIM_A_ITEM] it2
	ON it2.ID_ITEM = fact.ID_ITEM_PARENT
WHERE 
	[CD_SALES_TRANSACTION_CATEGORY] in ('Order','OrderInvoice')
	AND
		isnull(AMT_SHIPPING_COST_EST_EUR,0) = 0 
	AND CD_FULFILLMENT NOT IN('FBA','B2B')
	AND ISNULL(T_CANCELLATION_REASON,'') = ''
	AND fact.D_CREATED>='2023-11-01'
	and it.NUM_ITEM = '10000109'
	and T_STORAGE_LOCATION = 'Bratislava'
	and CD_COUNTRY_DELIVERY = 'DE'