/****** Object:  Table [L1].[L1_FACT_F_PRICE_TOOL_SM]    Script Date: 10/11/2025 11:09:26 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
--DROP TABLE [L1].[L1_FACT_F_PRICE_TOOL_SM]
CREATE TABLE [L1].[L1_FACT_F_PRICE_TOOL_SM]
(
	[D_PRICE] [date] NULL,
	[CD_ITEM] [varchar](150)  NULL,
	[T_L1] [varchar](150) NULL,
	[T_L2] [varchar](150) NULL,
	[T_L3] [varchar](150) NULL,
	[T_L4] [varchar](150) NULL,
	[CD_FULFILLMENT] [varchar](5) NULL,
	[T_STORAGE_LOCATION] [varchar](150) NULL,
	[CD_COUNTRY_GROUP] [varchar](50) NULL,
	[CD_CHANNEL_GROUP_3] [varchar](50) NULL,
	[VL_ITEM_QUANTITY] [decimal](38, 6) NULL,
	[AMT_PLAN_PRICE_EUR] [decimal](38, 6) NULL,
	[AMT_SHIPPING_COST_EST_EUR] [float] NULL,
	[AMT_SHIPPING_COST_SERVICES_EST_EUR] [float] NULL,
	[AMT_MEK_HEDGING_EUR] [decimal](23, 6) NULL,
	[AMT_GTS_MARKUP_EUR] [decimal](38, 6) NULL,
	[AMT_TARGET_NET_ORDER_VALUE_EUR] [decimal](38, 6) NULL,
	[CD_CURRENCY] [varchar](5) NULL,
	[VL_REFUND_RATE] [decimal](23, 6) NULL,
	[VL_RETURN_RATE] [decimal](23, 6) NULL,
	[VL_REPLACEMENT_RATE] [decimal](23, 6) NULL,
	[CD_REFUND_RATE_SOURCE] [varchar](150) NULL,
	[CD_RETURN_RATE_SOURCE] [varchar](150) NULL,
	[CD_REPLACEMENT_RATE_SOURCE] [varchar](150) NULL,
	[AMT_COMMISSIONS_MARKETPLACES_FC_EUR] [decimal](38, 6) NULL,
	[AMT_GROSS_ORDER_VALUE_EUR] [decimal](38, 6) NULL,
	[AMT_COMMISSIONS_AMAZON_FC_EUR] [decimal](38, 6) NULL,
	[VL_NET_ORDER_QUANTITY] [decimal](38, 6) NULL,
	[AMT_REFUNDED_ORDER_VALUE_FC_EUR] [decimal](38, 6) NULL,
	[AMT_COMMISSIONS_AMAZON_REFUNDS_FC_EUR] [decimal](38, 6) NULL,
	[AMT_COMMISSIONS_MARKETPLACES_REFUNDS_FC_EUR] [decimal](38, 6) NULL,
	[AMT_NET_ORDER_VALUE_FC_EUR] [decimal](38, 6) NULL,
	[VL_REFUNDED_QUANTITY_FC] [decimal](38, 6) NULL,
	[VL_RETURNED_QUANTITY_FC] [decimal](38, 6) NULL,
	[VL_REPLACEMENT_QUANTITY_FC] [decimal](38, 6) NULL,
	[AMT_REVENUE_FC_EUR] [decimal](38, 6) NULL,
	[AMT_SHIPPING_COSTS_INVOICED_FC_EUR] [float] NULL,
	[AMT_SHIPPING_COSTS_RETURNED_FC_EUR] [float] NULL,
	[AMT_SHIPPING_COSTS_REPLACED_FC_EUR] [float] NULL,
	[AMT_ENVIRO_REST_UNIT_FEE_EUR] [decimal](38, 6) NULL,
	[AMT_REPACKAGING_FC_EUR] [numeric](38, 6) NULL,
	[AMT_PAYMENTS_FEES_FC_EUR] [numeric](38, 6) NULL,
	[AMT_MARKETING_COST_EUR] [decimal](38, 6) NULL,
	[AMT_SHIPPING_OUTBOUND_FC_EUR] [float] NOT NULL,
	[AMT_ENVIRO_AND_LICENSE_COST_FC_EUR] [numeric](38, 6) NULL,
	[AMT_MEK_TO_CUSTOMER_FC_EUR] [decimal](38, 6) NULL,
	[AMT_MEK_FROM_CUSTOMER_FC_EUR] [decimal](38, 6) NULL,
	[AMT_MEK_REPLACEMENT_FC_EUR] [decimal](38, 6) NULL,
	[AMT_MEK_DEPRECIATION_FC_EUR] [decimal](38, 6) NULL,
	[AMT_COMMISSIONS_SALE_FC_EUR] [decimal](38, 6) NULL,
	[AMT_COMMISSIONS_REFUNDS_FC_EUR] [decimal](38, 6) NULL,
	[AMT_COMMISSIONS_FC_EUR] [decimal](38, 6) NULL,
	[AMT_FULL_NET_PRODUCT_COST_FC_EUR] [decimal](38, 6) NULL,
	[AMT_GROSS_MARGIN_FC_EUR] [decimal](19, 2) NULL,
	[AMT_STEERING_MARGIN_FC_EUR] [float] NULL,
	[PCT_SM_TARGET] [decimal](19, 2) NULL,
	[AMT_SM_TARGET_PLAN_PRICE_EUR] [decimal](38, 6) NULL,
	[PCT_SM_ORIGINAL] [decimal](19, 2) NULL,
	[VL_MARKETING_RATE] [decimal](23, 6) NULL,
	[VL_ITEM_QUANTITY_FIRST_YEAR] [decimal](38, 6) NULL,
	[VL_ITEM_QUANTITY_6M] [decimal](38, 6) NULL,
	[VL_ITEM_QUANTITY_12M] [decimal](38, 6) NULL,

	[AMT_NET_ORDER_VALUE_FIRST_YEAR_FC_EUR]  [decimal](38, 6) NULL,
	[AMT_NET_ORDER_VALUE_6M_FC_EUR]  [decimal](38, 6) NULL,
	[AMT_NET_ORDER_VALUE_12M_FC_EUR]  [decimal](38, 6) NULL,

	[AMT_REVENUE_FIRST_YEAR_FC_EUR] [decimal](38, 6) NULL,
	[AMT_REVENUE_6M_FC_EUR] [decimal](38, 6) NULL,
	[AMT_REVENUE_12M_FC_EUR] [decimal](38, 6) NULL,

	[AMT_STEERING_MARGIN_FIRST_YEAR_FC_EUR] [float] NULL,
	[AMT_STEERING_MARGIN_6M_FC_EUR] [float] NULL,
	[AMT_STEERING_MARGIN_12M_FC_EUR] [float] NULL,
	[DT_DWH_CREATED]  datetime2(7) NULL

)
WITH
(
	DISTRIBUTION = ROUND_ROBIN,
	CLUSTERED COLUMNSTORE INDEX
)
GO


