ALTER PROC WR.WR_TX_L1_FACT_F_PRICE_TOOL_SM  
-- =============================================  
-- Author:      Helder Barbosa
-- Create Date: 2025-09-14
-- Description: Populates WR_TX_L1_FACT_F_PRICE_TOOL_SM
-- 2025-09-14   v1:HBarbosa      :  initial version
-- ============================================= 
AS
BEGIN

	--select distinct storagelocation from PL.[PL_V_BUSINESS_PLAN_KPI_SM]
	DECLARE @OTHER_DELIVER_COSTS_RATE DECIMAL(19,4) = 0.16
	DECLARE @GTS_RATE DECIMAL(19,4) = 0.13
	DECLARE @DEFAULT_REFUND_RATE DECIMAL(19,4) = 0.12
	DECLARE @DEFAULT_RETURN_RATE DECIMAL(19,4) = 0.10
	DECLARE @DEFAULT_REPLACEMENT_RATE DECIMAL(19,4) = 0.01
	DECLARE @DEFAULT_PAYMENTS_RATE DECIMAL(19,4) = 0.006

	DECLARE @DEFAULT_FULLFILMENT AS VARCHAR(10) = 'FBM'
	DECLARE @DEFAULT_STORAGE_LOCATION AS VARCHAR(50) = 'Kamp-Lintfort'

	DECLARE @DateCalc as date 
	SET @DateCalc = CAST(getdate() as date)

		DECLARE @MAXLOAD_DATE as datetime2(7)

	SELECT @MAXLOAD_DATE = ISNULL(MAX([DT_DWH_CREATED]),'2025-01-01') FROM [L1].[L1_FACT_F_PRICE_TOOL_SM]

;WITH CTE_ENVIRO as 
    (
	        SELECT 
				T_PRODUCT_HIERARCHY_3,
				CD_ENVIRO_CATEGORY,
				CD_COUNTRY_DELIVERY,
				NUM_YEAR,
				CD_CURRENCY,
				AMT_FEE_PER_UNIT = sum(AMT_FEE_PER_UNIT) / COUNT(DISTINCT env.ID_ITEM) 
			FROM [L1].[L1_DIM_A_ENVIRO_REST_UNIT_FEES] env
			INNER JOIN L1.L1_DIM_A_ITEM it on it.ID_ITEM = env.ID_ITEM
            GROUP BY it.T_PRODUCT_HIERARCHY_3,CD_COUNTRY_DELIVERY,NUM_YEAR,CD_CURRENCY,CD_ENVIRO_CATEGORY
    ),
	cte_enviro_agg	AS
	(
		SELECT
				T_PRODUCT_HIERARCHY_3,
				CD_COUNTRY_DELIVERY,
				NUM_YEAR,
				CD_CURRENCY,
				AMT_FEE_PER_UNIT = SUM(ISNULL(AMT_FEE_PER_UNIT,0))
		FROM CTE_ENVIRO
		GROUP BY T_PRODUCT_HIERARCHY_3,CD_COUNTRY_DELIVERY,NUM_YEAR,CD_CURRENCY
	
	)
, cte_rrr_item_L3_rates as (
SELECT 
		T_PRODUCT_HIERARCHY_3,
		REPLACE(ch.CD_CHANNEL_GROUP_3,' ','') as CD_CHANNEL_GROUP_3,
		CD_COUNTRY_DELIVERY,
		ReturnRate					= ROUND((SUM([VL_RETURN_QUANTITY])/SUM([VL_ORDER_QUANTITY])),4),
		RefundRate					= ROUND((SUM(AMT_REFUNDS_EUR)/SUM(AMT_GROSS_ORDER_VALUE_EUR)),4),
		ReplacementRate				= ROUND((SUM(VL_REPLACEMENT_QUANTITY)/SUM(AMT_GROSS_ORDER_VALUE_EUR)),4) 
  FROM [L1].[L1_FACT_A_CLAIM_RATES] c
  INNER JOIN L1.L1_DIM_A_SALES_CHANNEL ch on ch.ID_SALES_CHANNEL = c.ID_SALES_CHANNEL
  INNER JOIN L1.L1_DIM_A_ITEM it on it.ID_ITEM = c.ID_ITEM



  WHERE 
   [D_SALES_PROCESS] between DATEADD(MONTH,-12,DATEADD(week,-8,@DateCalc)) and DATEADD(week,-8,@DateCalc)
	and c.num_item like '1%' 
  GROUP BY 
   T_PRODUCT_HIERARCHY_3,REPLACE(ch.CD_CHANNEL_GROUP_3,' ',''),CD_COUNTRY_DELIVERY
   HAVING  
	SUM(AMT_GROSS_ORDER_VALUE_EUR) > 0
	AND
	SUM([VL_ORDER_QUANTITY]) > 20
) ,cte_rrr_item_family_rates as (
SELECT 
		T_PRODUCT_HIERARCHY_4,
		REPLACE(ch.CD_CHANNEL_GROUP_3,' ','') as CD_CHANNEL_GROUP_3,
		CD_COUNTRY_DELIVERY,
		ReturnRate					= ROUND((SUM([VL_RETURN_QUANTITY])/SUM([VL_ORDER_QUANTITY])),4),
		RefundRate					= ROUND((SUM(AMT_REFUNDS_EUR)/SUM(AMT_GROSS_ORDER_VALUE_EUR)),4),
		ReplacementRate				= ROUND((SUM(VL_REPLACEMENT_QUANTITY)/SUM(AMT_GROSS_ORDER_VALUE_EUR)),4) 
  FROM [L1].[L1_FACT_A_CLAIM_RATES] c
  INNER JOIN L1.L1_DIM_A_SALES_CHANNEL ch on ch.ID_SALES_CHANNEL = c.ID_SALES_CHANNEL
  INNER JOIN L1.L1_DIM_A_ITEM it on it.ID_ITEM = c.ID_ITEM

  WHERE 
   [D_SALES_PROCESS] between DATEADD(MONTH,-12,DATEADD(week,-8,@DateCalc)) and DATEADD(week,-8,@DateCalc)
	and c.num_item like '1%' 
  GROUP BY 
   T_PRODUCT_HIERARCHY_4,REPLACE(ch.CD_CHANNEL_GROUP_3,' ',''),CD_COUNTRY_DELIVERY
   HAVING  
	SUM(AMT_GROSS_ORDER_VALUE_EUR) > 0
	AND
	SUM([VL_ORDER_QUANTITY]) > 20
)


,CTE_SALES_L1 AS
	(
		SELECT 
			 [D_PRICE]						= ISNULL(fact.MONTHCALCULATION,cast(fact.LOAD_TIMESTAMP as date))											
			,[CD_ITEM]						= fact.ItemNo																				
			,CD_FULFILLMENT					= @DEFAULT_FULLFILMENT										
			,[T_STORAGE_LOCATION]			= @DEFAULT_STORAGE_LOCATION
			,T_L1							= fact.L1
			,T_L2							= fact.L2
			,T_L3							= fact.L3
			,T_L4							= fact.L4
			,[CD_COUNTRY_GROUP]				= Country						
			,[CD_CHANNEL_GROUP_3]			= fact.ChannelGroup3
			,VL_ITEM_QUANTITY				= 1 
			,VL_ITEM_QUANTITY_FIRST_YEAR	= fact.QtyFirstYear
			,VL_ITEM_QUANTITY_6M			= fact.QtyFC6Months
			,VL_ITEM_QUANTITY_12M			= fact.QtyFC12Months
			,AMT_PLAN_PRICE_EUR				= PlanPrice							
			,AMT_SHIPPING_COST_EST_EUR		= ShippingCost
			,AMT_SHIPPING_COST_SERVICES_EST_EUR		= 0 
			,AMT_MEK_HEDGING_EUR			= MEK
			,AMT_GTS_MARKUP_EUR				= 		0									
			,AMT_TARGET_NET_ORDER_VALUE_EUR = PlanPrice
			,CD_CURRENCY				  = 'EUR'								
            ,VL_REFUND_RATE 			  = CASE 
												WHEN ISNULL(fact.RefundRate,0) > 0 THEN fact.RefundRate
												WHEN ISNULL(family_rates.RefundRate,0) > 0 THEN family_rates.RefundRate
												WHEN ISNULL(l3_rates.RefundRate,0) > 0 THEN l3_rates.RefundRate
												ELSE @DEFAULT_REFUND_RATE END	
	        ,VL_RETURN_RATE				  = CASE 
												WHEN ISNULL(fact.[ReturnRate],0) > 0 THEN fact.[ReturnRate]
												WHEN ISNULL(family_rates.[ReturnRate],0) > 0 THEN family_rates.[ReturnRate]
												WHEN ISNULL(l3_rates.[ReturnRate],0) > 0 THEN l3_rates.[ReturnRate]
												ELSE @DEFAULT_RETURN_RATE END	
        	,VL_REPLACEMENT_RATE 		  =CASE 
												WHEN ISNULL(fact.ReplacementRate,0) > 0 THEN fact.ReplacementRate
												WHEN ISNULL(family_rates.ReplacementRate,0) > 0 THEN family_rates.ReplacementRate
												WHEN ISNULL(l3_rates.ReplacementRate,0) > 0 THEN l3_rates.ReplacementRate
												ELSE @DEFAULT_REPLACEMENT_RATE END	
			,CD_REFUND_RATE_SOURCE 		  = CASE 
												WHEN ISNULL(fact.RefundRate,0) > 0 THEN 'Override'
												WHEN ISNULL(family_rates.RefundRate,0) > 0 THEN 'family_rates'
												WHEN ISNULL(l3_rates.RefundRate,0) > 0 THEN 'l3_rates'
												ELSE 'Default' END	
            ,CD_RETURN_RATE_SOURCE 		  = CASE 
												WHEN ISNULL(fact.[ReturnRate],0) > 0 THEN 'Override'
												WHEN ISNULL(family_rates.[ReturnRate],0) > 0 THEN'family_rates'
												WHEN ISNULL(l3_rates.[ReturnRate],0) > 0 THEN 'l3_rates'
												ELSE 'Default' END	
            ,CD_REPLACEMENT_RATE_SOURCE	  = CASE 
												WHEN ISNULL(fact.ReplacementRate,0) > 0 THEN 'Override'
												WHEN ISNULL(family_rates.ReplacementRate,0) > 0 THEN 'family_rates'
												WHEN ISNULL(l3_rates.ReplacementRate,0) > 0 THEN 'l3_rates'
												ELSE 'Default' END										

			,[PCT_COMMISSIONS_MARKETPLACES] = ISNULL(com_mkt_bs.[MARKETPLACERATE],0)				
			,[PCT_COMMISSIONS_MARKETPLACES_RETURN] = ISNULL(com_mkt_bs.[MARKETPLACERATE],0)
			
			,[PCT_PAYMENTS_ORDER] = CASE WHEN fact.ChannelGroup3 = 'Amazon' THEN 0 ELSE @DEFAULT_PAYMENTS_RATE END

	        ,VL_COMMISSIONS_ORDER_RATE = c_amaz.[VL_COMMISSIONS_ORDER_RATE]			

			,AMT_PRECALC_ENVIRO_REST_UNIT_FEE_EUR = env.AMT_FEE_PER_UNIT * COALESCE(enviro_rate.VL_FX_RATE, 1) 
            ,AMT_PRECALC_REPACKAGING_EUR = repack.AMT_FEE_PER_UNIT * COALESCE(enviro_rate.VL_FX_RATE, 1) * 0.025 							

			,PCT_MKT_RATE = CASE WHEN ISNULL(fact.MarketingRate,0) = 0 THEN mkt.MARKETINGRATE ELSE fact.MarketingRate END
			,PCT_VAT_VALUE = CASE WHEN ISNULL(vat.PCT_VALUE,0) = 0 THEN 0 ELSE vat.PCT_VALUE / 100 END
			,VL_DEPRETIATION_RATE = ISNULL(dep.VL_RATE,0)
			,PCT_SM_TARGET = fact.SMTARGET
			,DT_DWH_CREATED = fact.LOAD_TIMESTAMP
			FROM L0.L0_MI_PRICE_TOOL_SM fact
			LEFT JOIN [L1].[L1_DIM_A_CS_COMMISSIONS_AMAZON] c_amaz
				ON fact.L1 = c_amaz.T_PRODUCT_HIERARCHY_1
					AND fact.L2 = c_amaz.T_PRODUCT_HIERARCHY_2
					AND ISNULL(fact.MONTHCALCULATION,fact.LOAD_TIMESTAMP) BETWEEN c_amaz.D_VALID_FROM AND c_amaz.D_VALID_TO
					AND CASE WHEN fact.Country = 'INT' THEN 'ES' ELSE fact.Country END = c_amaz.CD_CHANNEL_COUNTRY
			--join enviro
			LEFT JOIN  cte_enviro_agg env
				ON fact.L3 = env.T_PRODUCT_HIERARCHY_3
				AND fact.Country = env.CD_COUNTRY_DELIVERY
				AND YEAR(ISNULL(fact.MONTHCALCULATION,fact.LOAD_TIMESTAMP)) = env.NUM_YEAR
			--join enviro for repackacing
			LEFT JOIN CTE_ENVIRO repack
				ON fact.L3 = repack.T_PRODUCT_HIERARCHY_3
				AND fact.Country   = repack.CD_COUNTRY_DELIVERY
				AND YEAR(ISNULL(fact.MONTHCALCULATION,fact.LOAD_TIMESTAMP)) = repack.NUM_YEAR
				AND repack.CD_ENVIRO_CATEGORY = 'Packaging'
			--join fx rate for enviro
			LEFT JOIN [L1].[L1_FACT_F_FX_RATE] enviro_rate
				ON env.cd_currency=enviro_rate.cd_currency
				AND Year(ISNULL(fact.MONTHCALCULATION,fact.LOAD_TIMESTAMP))=Year(enviro_rate.D_EFFECTIVE)
				AND Month(ISNULL(fact.MONTHCALCULATION,fact.LOAD_TIMESTAMP))=Month(enviro_rate.D_EFFECTIVE)	
			LEFT JOIN [L0].[L0_MI_BUSINESS_PLAN_MARKETING_RATES] mkt
				on REPLACE(mkt.[CHANNELGROUP3],' ','') = fact.ChannelGroup3
				and YEAR(ISNULL(fact.MONTHCALCULATION,fact.LOAD_TIMESTAMP)) = YEAR(mkt.[MONTH])
				and MONTH(ISNULL(fact.MONTHCALCULATION,fact.LOAD_TIMESTAMP)) = MONTH(mkt.[MONTH])
			LEFT JOIN [L0].L0_MI_BUSINESS_PLAN_COMMISSIONS_MARKETPLACES com_mkt_bs
				on	1=1
				AND com_mkt_bs.[CHANNELGROUP3] = fact.ChannelGroup3
				and YEAR(ISNULL(fact.MONTHCALCULATION,fact.LOAD_TIMESTAMP)) = YEAR(com_mkt_bs.[MONTH])
				and MONTH(ISNULL(fact.MONTHCALCULATION,fact.LOAD_TIMESTAMP)) = MONTH(com_mkt_bs.[MONTH])
			LEFT JOIN [L1].[L1_FACT_A_COUNTRY_VAT] vat
				on vat.[CD_COUNTRY] = CASE WHEN fact.Country = 'INT'THEN 'SI' ELSE fact.Country END 
				and vat.[D_VALID_TO]  = '9999-12-31'
			LEFT JOIN [L1].[L1_DIM_A_DEPRECIATION_VALUES] dep
				on ISNULL(fact.MONTHCALCULATION,fact.LOAD_TIMESTAMP) between dep.D_VALID_FROM and dep.D_VALID_TO
				AND dep.T_PRODUCT_HIERARCHY_2 = fact.L2
				and dep.T_STORAGE_LOCATION = @DEFAULT_STORAGE_LOCATION
			LEFT JOIN cte_rrr_item_L3_rates l3_rates 
				on l3_rates.T_PRODUCT_HIERARCHY_3 = fact.L3
				AND REPLACE(l3_rates.CD_CHANNEL_GROUP_3,' ','') = REPLACE(fact.ChannelGroup3,' ','')
				AND l3_rates.CD_COUNTRY_DELIVERY = fact.Country
			LEFT JOIN cte_rrr_item_family_rates family_rates 
				on REPLACE(family_rates.CD_CHANNEL_GROUP_3,' ','') = REPLACE(fact.ChannelGroup3,' ','')
				AND family_rates.CD_COUNTRY_DELIVERY = fact.Country
				AND family_rates.T_PRODUCT_HIERARCHY_4 = fact.L4
			WHERE
				fact.LOAD_TIMESTAMP > @MAXLOAD_DATE
	),
	CTE_SALES_L2 AS 
	(
		SELECT sales.*
			,AMT_COMMISSIONS_MARKETPLACES_FC_EUR  = CASE WHEN CD_CHANNEL_GROUP_3 = 'CEE' then 0 ELSE ([AMT_TARGET_NET_ORDER_VALUE_EUR]*(1+PCT_VAT_VALUE) * [PCT_COMMISSIONS_MARKETPLACES]) END
			,AMT_GROSS_ORDER_VALUE_EUR = [AMT_TARGET_NET_ORDER_VALUE_EUR]
	        ,AMT_COMMISSIONS_AMAZON_FC_EUR = CASE WHEN CD_CHANNEL_GROUP_3 = 'Amazon' then [AMT_TARGET_NET_ORDER_VALUE_EUR]*(1+PCT_VAT_VALUE)*VL_COMMISSIONS_ORDER_RATE ELSE NULL END
			,VL_NET_ORDER_QUANTITY = [VL_ITEM_QUANTITY]
		FROM CTE_SALES_L1 sales
	)
,
	CTE_SALES_L3 AS 
	(
		SELECT sales.*
				,AMT_REFUNDED_ORDER_VALUE_FC_EUR = (AMT_GROSS_ORDER_VALUE_EUR * ISNULL(VL_REFUND_RATE,0)) 		

				,AMT_COMMISSIONS_AMAZON_REFUNDS_FC_EUR = CASE WHEN AMT_COMMISSIONS_AMAZON_FC_EUR between c_amaz_ref.[VL_VALUE_FROM] and c_amaz_ref.[VL_VALUE_TO] 
				      THEN CASE WHEN c_amaz_ref.[VL_COMMISSIONS_REFUND_ABOVE_THRESHOLD] <> 0 
				                THEN (AMT_COMMISSIONS_AMAZON_FC_EUR - c_amaz_ref.[VL_COMMISSIONS_REFUND_ABOVE_THRESHOLD])*sales.VL_REFUND_RATE 
				                ELSE (AMT_COMMISSIONS_AMAZON_FC_EUR * c_amaz_ref.[VL_COMMISSIONS_REFUND_BELOW_THRESHOLD_RATE])*sales.VL_REFUND_RATE 
				           END
				      ELSE NULL
				END
	    FROM CTE_SALES_L2 sales
	    LEFT JOIN [L1].[L1_DIM_A_CS_COMMISSIONS_AMAZON_REFUND] c_amaz_ref
	         ON [D_PRICE] BETWEEN c_amaz_ref.[D_VALID_FROM] AND c_amaz_ref.[D_VALID_TO]
	         AND AMT_COMMISSIONS_AMAZON_FC_EUR > c_amaz_ref.VL_VALUE_FROM 
	         AND AMT_COMMISSIONS_AMAZON_FC_EUR <= c_amaz_ref.VL_VALUE_TO 
	)
	,
	CTE_SALES_L4 AS 
	(
		SELECT sales.*
				,AMT_COMMISSIONS_MARKETPLACES_REFUNDS_FC_EUR = CASE WHEN CD_CHANNEL_GROUP_3 = 'CEE' then 0 ELSE  (AMT_REFUNDED_ORDER_VALUE_FC_EUR*(1+PCT_VAT_VALUE) * [PCT_COMMISSIONS_MARKETPLACES_RETURN]) END		

				 ,AMT_NET_ORDER_VALUE_FC_EUR = AMT_GROSS_ORDER_VALUE_EUR
				 ,VL_REFUNDED_QUANTITY_FC = (VL_NET_ORDER_QUANTITY * VL_REFUND_RATE) 			
				 ,VL_RETURNED_QUANTITY_FC = (VL_NET_ORDER_QUANTITY * VL_RETURN_RATE)				
				 ,VL_REPLACEMENT_QUANTITY_FC = (VL_NET_ORDER_QUANTITY *VL_REPLACEMENT_RATE )				
		FROM CTE_SALES_L3 sales
	)
	,
	CTE_SALES_L5 AS 
	(
		SELECT sales.*
				,AMT_REVENUE_FC_EUR = (AMT_NET_ORDER_VALUE_FC_EUR - AMT_REFUNDED_ORDER_VALUE_FC_EUR)																	
				,AMT_SHIPPING_COSTS_INVOICED_FC_EUR = (VL_NET_ORDER_QUANTITY * [AMT_SHIPPING_COST_EST_EUR])				
				,AMT_SHIPPING_COSTS_RETURNED_FC_EUR = (VL_RETURNED_QUANTITY_FC * [AMT_SHIPPING_COST_EST_EUR])	    		
				,AMT_SHIPPING_COSTS_REPLACED_FC_EUR = (VL_REPLACEMENT_QUANTITY_FC * [AMT_SHIPPING_COST_EST_EUR] )	
				,AMT_ENVIRO_REST_UNIT_FEE_EUR = (VL_NET_ORDER_QUANTITY - VL_RETURNED_QUANTITY_FC+VL_REPLACEMENT_QUANTITY_FC) * AMT_PRECALC_ENVIRO_REST_UNIT_FEE_EUR
				,[AMT_REPACKAGING_FC_EUR] = (VL_NET_ORDER_QUANTITY - VL_RETURNED_QUANTITY_FC+VL_REPLACEMENT_QUANTITY_FC) * AMT_PRECALC_REPACKAGING_EUR 


		FROM CTE_SALES_L4 sales
	)
	,CTE_SALES_L6 AS 
	(
		SELECT sales.*
				  ,AMT_PAYMENTS_FEES_FC_EUR = (AMT_REVENUE_FC_EUR * [PCT_PAYMENTS_ORDER])	
				 ,[AMT_MARKETING_COST_EUR] =  ISNULL(AMT_NET_ORDER_VALUE_FC_EUR,0) * ISNULL(PCT_MKT_RATE,0)
				 ,[AMT_SHIPPING_OUTBOUND_FC_EUR] = (isnull(AMT_SHIPPING_COSTS_INVOICED_FC_EUR,0)+isnull(AMT_SHIPPING_COSTS_RETURNED_FC_EUR,0)+isnull(AMT_SHIPPING_COSTS_REPLACED_FC_EUR,0))										        
				, [AMT_ENVIRO_AND_LICENSE_COST_FC_EUR] = ISNULL(AMT_ENVIRO_REST_UNIT_FEE_EUR,0)+ISNULL([AMT_REPACKAGING_FC_EUR],0)                                                                         

		FROM CTE_SALES_L5 sales
	)
	,
	CTE_SALES_L7 AS 
	(
		SELECT 	sales.*
		,[AMT_MEK_TO_CUSTOMER_FC_EUR]			= CASE WHEN [VL_ITEM_QUANTITY] <> 0 
													THEN (VL_NET_ORDER_QUANTITY) * (ISNULL([AMT_MEK_HEDGING_EUR],0)-ISNULL([AMT_GTS_MARKUP_EUR],0))  
													ELSE 0 END	
		,[AMT_MEK_FROM_CUSTOMER_FC_EUR]			= CASE WHEN [VL_ITEM_QUANTITY] <> 0 
													THEN (VL_RETURNED_QUANTITY_FC) * (ISNULL([AMT_MEK_HEDGING_EUR],0)-ISNULL([AMT_GTS_MARKUP_EUR],0))  
													ELSE 0 END	
		,[AMT_MEK_REPLACEMENT_FC_EUR]			= CASE WHEN [VL_ITEM_QUANTITY] <> 0 
													THEN (VL_REPLACEMENT_QUANTITY_FC) * (ISNULL([AMT_MEK_HEDGING_EUR],0)-ISNULL([AMT_GTS_MARKUP_EUR],0))  
													ELSE 0 END	
		,[AMT_MEK_DEPRECIATION_FC_EUR] 			= CASE WHEN [VL_ITEM_QUANTITY] <> 0 
													THEN (VL_RETURNED_QUANTITY_FC*VL_DEPRETIATION_RATE) * (ISNULL([AMT_MEK_HEDGING_EUR],0)-ISNULL([AMT_GTS_MARKUP_EUR],0))  
													ELSE 0 END	
		,[AMT_COMMISSIONS_SALE_FC_EUR]			= ISNULL(AMT_COMMISSIONS_MARKETPLACES_FC_EUR,0) + ISNULL(AMT_COMMISSIONS_AMAZON_FC_EUR,0)
		,[AMT_COMMISSIONS_REFUNDS_FC_EUR]		= ISNULL(AMT_COMMISSIONS_AMAZON_REFUNDS_FC_EUR,0)+ISNULL(AMT_COMMISSIONS_MARKETPLACES_REFUNDS_FC_EUR,0)
		,[AMT_COMMISSIONS_FC_EUR]				= (ISNULL(AMT_COMMISSIONS_MARKETPLACES_FC_EUR,0)-ISNULL(AMT_COMMISSIONS_MARKETPLACES_REFUNDS_FC_EUR,0)+ISNULL(AMT_COMMISSIONS_AMAZON_FC_EUR,0)-ISNULL(AMT_COMMISSIONS_AMAZON_REFUNDS_FC_EUR,0))

		FROM CTE_SALES_L6 sales


	),
	CTE_SALES_L8 AS 
	(
		SELECT sales.*,

		[AMT_FULL_NET_PRODUCT_COST_FC_EUR] =  ISNULL([AMT_MEK_TO_CUSTOMER_FC_EUR],0) - ISNULL([AMT_MEK_FROM_CUSTOMER_FC_EUR],0) + ISNULL([AMT_MEK_REPLACEMENT_FC_EUR],0) +ISNULL([AMT_MEK_DEPRECIATION_FC_EUR],0) ,
		[AMT_GROSS_MARGIN_FC_EUR] = ISNULL(AMT_REVENUE_FC_EUR,0) - (ISNULL([AMT_MEK_TO_CUSTOMER_FC_EUR],0) - ISNULL([AMT_MEK_FROM_CUSTOMER_FC_EUR],0) + ISNULL([AMT_MEK_REPLACEMENT_FC_EUR],0) +ISNULL([AMT_MEK_DEPRECIATION_FC_EUR],0)) ,
		[AMT_STEERING_MARGIN_FC_EUR] =  ISNULL(AMT_REVENUE_FC_EUR,0)
					- (ISNULL([AMT_MEK_TO_CUSTOMER_FC_EUR],0) - ISNULL([AMT_MEK_FROM_CUSTOMER_FC_EUR],0) + ISNULL([AMT_MEK_REPLACEMENT_FC_EUR],0) +ISNULL([AMT_MEK_DEPRECIATION_FC_EUR],0)) -- Net product Costs
					- ISNULL([AMT_MARKETING_COST_EUR],0) 
					- ISNULL([AMT_COMMISSIONS_FC_EUR],0) 
					- ISNULL(AMT_PAYMENTS_FEES_FC_EUR,0) 
					- ISNULL([AMT_ENVIRO_AND_LICENSE_COST_FC_EUR],0)
					- ISNULL([AMT_SHIPPING_OUTBOUND_FC_EUR],0)   ----(ShippingCostsInvoicedEst+ShippingCostsReturnedEst+ShippingCostsReplacedEst)
		FROM CTE_SALES_L7 sales 
	
	
	), CTE_SALES_L9 AS
	(
	
			SELECT sales.*,
			AMT_SM_TARGET_PLAN_PRICE_EUR =         CASE 
														WHEN sales.AMT_TARGET_NET_ORDER_VALUE_EUR > 0
															 AND (
																	AMT_REVENUE_FC_EUR
																	- AMT_MARKETING_COST_EUR
																	- AMT_COMMISSIONS_FC_EUR
																	- AMT_PAYMENTS_FEES_FC_EUR
																	- 0.30 * AMT_TARGET_NET_ORDER_VALUE_EUR
																 ) <> 0
            THEN ROUND(
                    (   AMT_FULL_NET_PRODUCT_COST_FC_EUR
                      + AMT_ENVIRO_AND_LICENSE_COST_FC_EUR
                      + AMT_SHIPPING_OUTBOUND_FC_EUR
                    )
                    * AMT_TARGET_NET_ORDER_VALUE_EUR
                    /
                    (   AMT_REVENUE_FC_EUR
                      - AMT_MARKETING_COST_EUR
                      - AMT_COMMISSIONS_FC_EUR
                      - AMT_PAYMENTS_FEES_FC_EUR
                      - 0.30 * AMT_TARGET_NET_ORDER_VALUE_EUR
                    )
                  , 2)
            ELSE NULL END,
			PCT_SM_ORIGINAL = [AMT_STEERING_MARGIN_FC_EUR] / AMT_TARGET_NET_ORDER_VALUE_EUR
			 
			,AMT_NET_ORDER_VALUE_FIRST_YEAR_FC_EUR = AMT_NET_ORDER_VALUE_FC_EUR * VL_ITEM_QUANTITY_FIRST_YEAR
			,AMT_NET_ORDER_VALUE_6M_FC_EUR = AMT_NET_ORDER_VALUE_FC_EUR * VL_ITEM_QUANTITY_6M
			,AMT_NET_ORDER_VALUE_12M_FC_EUR = AMT_NET_ORDER_VALUE_FC_EUR * VL_ITEM_QUANTITY_12M

			,AMT_REVENUE_FIRST_YEAR_FC_EUR = AMT_REVENUE_FC_EUR * VL_ITEM_QUANTITY_FIRST_YEAR
			,AMT_REVENUE_6M_FC_EUR = AMT_REVENUE_FC_EUR * VL_ITEM_QUANTITY_6M
			,AMT_REVENUE_12M_FC_EUR = AMT_REVENUE_FC_EUR * VL_ITEM_QUANTITY_12M

			,AMT_STEERING_MARGIN_FIRST_YEAR_FC_EUR = AMT_STEERING_MARGIN_FC_EUR * VL_ITEM_QUANTITY_FIRST_YEAR
			,AMT_STEERING_MARGIN_6M_FC_EUR = AMT_STEERING_MARGIN_FC_EUR * VL_ITEM_QUANTITY_6M
			,AMT_STEERING_MARGIN_12M_FC_EUR = AMT_STEERING_MARGIN_FC_EUR * VL_ITEM_QUANTITY_12M

		FROM CTE_SALES_L8 sales 
	
	
	)
	INSERT INTO [L1].[L1_FACT_F_PRICE_TOOL_SM] (
            [D_PRICE]
           ,[CD_ITEM]
		   ,T_L1
		   ,T_L2
		   ,T_L3
		   ,T_L4
           ,[CD_FULFILLMENT]
           ,[T_STORAGE_LOCATION]
           ,[CD_COUNTRY_GROUP]
           ,[CD_CHANNEL_GROUP_3]
           ,[VL_ITEM_QUANTITY]
           ,[AMT_PLAN_PRICE_EUR]
           ,[AMT_SHIPPING_COST_EST_EUR]
		   ,[AMT_SHIPPING_COST_SERVICES_EST_EUR]
           ,[AMT_MEK_HEDGING_EUR]
           ,[AMT_GTS_MARKUP_EUR]
           ,[AMT_TARGET_NET_ORDER_VALUE_EUR]
           ,[CD_CURRENCY]
           ,[VL_REFUND_RATE]
           ,[VL_RETURN_RATE]
           ,[VL_REPLACEMENT_RATE]
           ,[CD_REFUND_RATE_SOURCE]
           ,[CD_RETURN_RATE_SOURCE]
           ,[CD_REPLACEMENT_RATE_SOURCE]
           ,[AMT_COMMISSIONS_MARKETPLACES_FC_EUR]
           ,[AMT_GROSS_ORDER_VALUE_EUR]
           ,[AMT_COMMISSIONS_AMAZON_FC_EUR]
           ,[VL_NET_ORDER_QUANTITY]
           ,[AMT_REFUNDED_ORDER_VALUE_FC_EUR]
           ,[AMT_COMMISSIONS_AMAZON_REFUNDS_FC_EUR]
           ,[AMT_COMMISSIONS_MARKETPLACES_REFUNDS_FC_EUR]
           ,[AMT_NET_ORDER_VALUE_FC_EUR]
           ,[VL_REFUNDED_QUANTITY_FC]
           ,[VL_RETURNED_QUANTITY_FC]
           ,[VL_REPLACEMENT_QUANTITY_FC]
           ,[AMT_REVENUE_FC_EUR]
           ,[AMT_SHIPPING_COSTS_INVOICED_FC_EUR]
           ,[AMT_SHIPPING_COSTS_RETURNED_FC_EUR]
           ,[AMT_SHIPPING_COSTS_REPLACED_FC_EUR]
           ,[AMT_ENVIRO_REST_UNIT_FEE_EUR]
           ,[AMT_REPACKAGING_FC_EUR]
           ,[AMT_PAYMENTS_FEES_FC_EUR]
           ,[AMT_MARKETING_COST_EUR]
           ,[AMT_SHIPPING_OUTBOUND_FC_EUR]
           ,[AMT_ENVIRO_AND_LICENSE_COST_FC_EUR]
           ,[AMT_MEK_TO_CUSTOMER_FC_EUR]
           ,[AMT_MEK_FROM_CUSTOMER_FC_EUR]
           ,[AMT_MEK_REPLACEMENT_FC_EUR]
           ,[AMT_MEK_DEPRECIATION_FC_EUR]
           ,[AMT_COMMISSIONS_SALE_FC_EUR]
           ,[AMT_COMMISSIONS_REFUNDS_FC_EUR]
           ,[AMT_COMMISSIONS_FC_EUR]
           ,[AMT_FULL_NET_PRODUCT_COST_FC_EUR]
		   ,[AMT_GROSS_MARGIN_FC_EUR]
           ,[AMT_STEERING_MARGIN_FC_EUR]
		   ,PCT_SM_TARGET
		   ,AMT_SM_TARGET_PLAN_PRICE_EUR
		   ,PCT_SM_ORIGINAL
		   ,VL_ITEM_QUANTITY_FIRST_YEAR
		   ,VL_ITEM_QUANTITY_6M
		   ,VL_ITEM_QUANTITY_12M
		   ,[AMT_NET_ORDER_VALUE_FIRST_YEAR_FC_EUR] 
		   ,[AMT_NET_ORDER_VALUE_6M_FC_EUR]
		   ,[AMT_NET_ORDER_VALUE_12M_FC_EUR] 
		   ,[AMT_REVENUE_FIRST_YEAR_FC_EUR] 
		   ,[AMT_REVENUE_6M_FC_EUR] 
		   ,[AMT_REVENUE_12M_FC_EUR]
		   ,[AMT_STEERING_MARGIN_FIRST_YEAR_FC_EUR] 
		   ,[AMT_STEERING_MARGIN_6M_FC_EUR]
		   ,[AMT_STEERING_MARGIN_12M_FC_EUR]
		   ,DT_DWH_CREATED
		   )
	SELECT
         [D_PRICE]
           ,[CD_ITEM]
			,T_L1
		   ,T_L2
		   ,T_L3
		   ,T_L4
           ,[CD_FULFILLMENT]
           ,[T_STORAGE_LOCATION]
           ,[CD_COUNTRY_GROUP]
           ,[CD_CHANNEL_GROUP_3]
		   ,[VL_ITEM_QUANTITY]
           ,[AMT_PLAN_PRICE_EUR]
           ,[AMT_SHIPPING_COST_EST_EUR]
		   ,[AMT_SHIPPING_COST_SERVICES_EST_EUR]
           ,[AMT_MEK_HEDGING_EUR]
           ,[AMT_GTS_MARKUP_EUR]
           ,[AMT_TARGET_NET_ORDER_VALUE_EUR]
           ,[CD_CURRENCY]
           ,[VL_REFUND_RATE]
           ,[VL_RETURN_RATE]
           ,[VL_REPLACEMENT_RATE]
           ,[CD_REFUND_RATE_SOURCE]
           ,[CD_RETURN_RATE_SOURCE]
           ,[CD_REPLACEMENT_RATE_SOURCE]
           ,[AMT_COMMISSIONS_MARKETPLACES_FC_EUR]
           ,[AMT_GROSS_ORDER_VALUE_EUR]
           ,[AMT_COMMISSIONS_AMAZON_FC_EUR]
           ,[VL_NET_ORDER_QUANTITY]
           ,[AMT_REFUNDED_ORDER_VALUE_FC_EUR]
           ,[AMT_COMMISSIONS_AMAZON_REFUNDS_FC_EUR]
           ,[AMT_COMMISSIONS_MARKETPLACES_REFUNDS_FC_EUR]
           ,[AMT_NET_ORDER_VALUE_FC_EUR]
           ,[VL_REFUNDED_QUANTITY_FC]
           ,[VL_RETURNED_QUANTITY_FC]
           ,[VL_REPLACEMENT_QUANTITY_FC]
           ,[AMT_REVENUE_FC_EUR]
           ,[AMT_SHIPPING_COSTS_INVOICED_FC_EUR]
           ,[AMT_SHIPPING_COSTS_RETURNED_FC_EUR]
           ,[AMT_SHIPPING_COSTS_REPLACED_FC_EUR]
           ,[AMT_ENVIRO_REST_UNIT_FEE_EUR]
           ,[AMT_REPACKAGING_FC_EUR]
           ,[AMT_PAYMENTS_FEES_FC_EUR]
		   ,[AMT_MARKETING_COST_EUR]
           ,[AMT_SHIPPING_OUTBOUND_FC_EUR]
           ,[AMT_ENVIRO_AND_LICENSE_COST_FC_EUR]
           ,[AMT_MEK_TO_CUSTOMER_FC_EUR]
           ,[AMT_MEK_FROM_CUSTOMER_FC_EUR]
           ,[AMT_MEK_REPLACEMENT_FC_EUR]
           ,[AMT_MEK_DEPRECIATION_FC_EUR]
           ,[AMT_COMMISSIONS_SALE_FC_EUR]
           ,[AMT_COMMISSIONS_REFUNDS_FC_EUR]
           ,[AMT_COMMISSIONS_FC_EUR]
           ,[AMT_FULL_NET_PRODUCT_COST_FC_EUR]
		   ,[AMT_GROSS_MARGIN_FC_EUR]
           ,[AMT_STEERING_MARGIN_FC_EUR]
		   ,PCT_SM_TARGET
		   ,AMT_SM_TARGET_PLAN_PRICE_EUR
		   ,PCT_SM_ORIGINAL
		   ,VL_ITEM_QUANTITY_FIRST_YEAR
		   ,VL_ITEM_QUANTITY_6M
		   ,VL_ITEM_QUANTITY_12M
		   ,[AMT_NET_ORDER_VALUE_FIRST_YEAR_FC_EUR] 
		   ,[AMT_NET_ORDER_VALUE_6M_FC_EUR]
		   ,[AMT_NET_ORDER_VALUE_12M_FC_EUR] 
		   ,[AMT_REVENUE_FIRST_YEAR_FC_EUR] 
		   ,[AMT_REVENUE_6M_FC_EUR] 
		   ,[AMT_REVENUE_12M_FC_EUR]
		   ,[AMT_STEERING_MARGIN_FIRST_YEAR_FC_EUR] 
		   ,[AMT_STEERING_MARGIN_6M_FC_EUR]
		   ,[AMT_STEERING_MARGIN_12M_FC_EUR]
		   ,DT_DWH_CREATED
	FROM CTE_SALES_L9


END




--SELECT * FROM  [L1].[L1_FACT_F_PRICE_TOOL_SM]



