ALTER PROCEDURE [WR].[WR_TX_L0_MI_PRICE_TOOL_SM]
    @ItemNo VARCHAR(150),
    @PlanPrice VARCHAR(150),
    @MEK VARCHAR(150),
    @ShippingCost VARCHAR(150),
    @Country VARCHAR(150),
    @ChannelGroup3 VARCHAR(150),
    @L1 VARCHAR(150),
    @L2 VARCHAR(150),
    @L3 VARCHAR(150),
    @L4 VARCHAR(150),
    @SMTARGET VARCHAR(150),
    @QTY_FIRST_YEAR VARCHAR(150),
    @QTY_FC6_MONTHS VARCHAR(150),
    @QTY_FC12_MONTHS VARCHAR(150),
    @MONTH_CALCULATION VARCHAR(150),
    @REFUNDRATE VARCHAR(150),
    @REPLACEMENTRATE VARCHAR(150),
    @RETURNRATE VARCHAR(150),
    @MARKETINGRATE VARCHAR(150)

AS
BEGIN

    DECLARE @LOAD_TIMESTAMP as datetime
    SET @LOAD_TIMESTAMP = getdate()

    SET @REFUNDRATE = CASE WHEN ISNULL(@REFUNDRATE,'')= '' THEN '0' ELSE @REFUNDRATE END
    SET @REPLACEMENTRATE = CASE WHEN ISNULL(@REPLACEMENTRATE,'')= '' THEN '0' ELSE @REPLACEMENTRATE END
    SET @RETURNRATE = CASE WHEN ISNULL(@RETURNRATE,'')= '' THEN '0' ELSE @RETURNRATE END
    SET @MARKETINGRATE = CASE WHEN ISNULL(@MARKETINGRATE,'')= '' THEN '0' ELSE @MARKETINGRATE END



    INSERT INTO [L0].[L0_MI_PRICE_TOOL_SM]
    (ItemNo, PlanPrice, MEK, ShippingCost, Country, ChannelGroup3, L1, L2, L3, L4, SMTARGET,
    [QtyFirstYear],[QtyFC6Months],[QtyFC12Months],
    [MONTHCALCULATION],[REFUNDRATE],[REPLACEMENTRATE],[RETURNRATE],[MARKETINGRATE],
    LOAD_TIMESTAMP)
    VALUES (@ItemNo, @PlanPrice, @MEK, @ShippingCost, @Country, @ChannelGroup3, @L1, @L2, @L3, @L4, @SMTARGET,
           @QTY_FIRST_YEAR,@QTY_FC6_MONTHS,@QTY_FC12_MONTHS,
           @MONTH_CALCULATION,@REFUNDRATE,@REPLACEMENTRATE,@RETURNRATE,@MARKETINGRATE,

    @LOAD_TIMESTAMP)
END;




EXEC [WR].[WR_TX_L0_MI_PRICE_TOOL_SM]
    @ItemNo = '10000164',
    @PlanPrice = '128.95',
    @MEK = '75.01',
    @ShippingCost= '4.1',
    @Country ='DE',
    @ChannelGroup3 = 'ShopWE',
    @L1 ='Small Appliances & Kitchen',
    @L2 = 'Watches / Wristwatch',
    @L3 = 'Watches Winder',
    @L4 = 'Old Marshall',
    @SMTARGET = '0.3',
    @QTY_FIRST_YEAR = '5',
    @QTY_FC6_MONTHS = '45',
    @QTY_FC12_MONTHS = '100',
    @MONTH_CALCULATION = '2026-01-01' ,
    @REFUNDRATE = NULL,
    @REPLACEMENTRATE = NULL,
    @RETURNRATE = NULL,
    @MARKETINGRATE = NULL



    