/****** Object:  View [PL].[PL_V_SM_FIXED_COSTS_ESTIMATE]    Script Date: 13/10/2025 11:49:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [PL].[PL_V_SM_FIXED_COSTS_ESTIMATE]
AS SELECT [DATE] 
      ,[POSITION]
      ,[SUBITEM]
      ,[STORAGELOCATIONCODE]
      ,[COMMEMNT]
      ,[VALUE]
      ,[ADDEDON]
  FROM [L0].[L0_MI_SM_FIX_COST_ESTIMATE];
GO


