--[WR].[WR_TX_L0_SAGE_KHKBuchungsjournal_L1_FACT_A_SALES_ACCOUNTING_VALUE] 
--[WR].WR_TX_L0_LUCANET_READ_FACTS_L1_FACT_A_SALES_ACCOUNTING_VALUE
--WR.WR_TX_L0_S4HANA_ACDOCA_L1_FACT_A_SALES_ACCOUNTING_VALUE
-- [WR].[WR_SP_SRG_L1_FACT_A_SALES_ACCOUNTING_VALUE]
-- WR.WR_HIST_FULL_L1_FACT_SALES_ACCOUNTING_VALUE

-- WR.WR_HIST_FULL_L1_FACT_F_SALES_FINANCE_RECONCILIATION
--select count(*) from WR.[WR_L1_FACT_F_SALES_FINANCE_RECONCILIATION]
-- TRUNCATE TABLE WR.[WR_L1_FACT_F_SALES_FINANCE_RECONCILIATION]
-- TRUNCATE TABLE L1.[L1_FACT_F_SALES_FINANCE_RECONCILIATION]
-- TRUNCATE TABLE WR.[WR_L1_FACT_A_SALES_ACCOUNTING_VALUE]
-- TRUNCATE TABLE L1.[L1_FACT_A_SALES_ACCOUNTING_VALUE]

DECLARE @nMonth as int  = 1

WHILE (@nMonth <= 12)
BEGIN
	print 'start month['+cast(@nMonth as nvarchar(50))+']'
	--EXEC WR.WR_TX_L1_FACT_SALES_ACCOUNTING_SAP_L1_FACT_F_SALES_FINANCE_RECONCILIATION @NUM_POSTING_YEAR =2023,@NUM_POSTING_PERIOD = @nMonth
	--EXEC WR.[WR_TX_L1_FACT_SALES_ACCOUNTING_SAGE_L1_FACT_F_SALES_FINANCE_RECONCILIATION] @NUM_POSTING_YEAR =2023,@NUM_POSTING_PERIOD = @nMonth
	EXEC WR_FIN.[WR_TX_L1_FACT_SALES_ACCOUNTING_LUCANET_L1_FACT_F_SALES_FINANCE_RECONCILIATION] @NUM_POSTING_YEAR =2023,@NUM_POSTING_PERIOD =@nMonth

	print 'end month['+cast(@nMonth as nvarchar(50))+']'

	SET @nMonth = @nMonth+1
END


--select * from WR.[WR_L1_FACT_F_SALES_FINANCE_RECONCILIATION] where cd_source_system = 'LCN' and num_posting_period = 1



--select * from WR.WR_L1_FACT_F_SALES_FINANCE_RECONCILIATION where num_posting_period = 9 and cd_source_system ='LCN'


--SELECT * FROM  PL.PL_V_FINANCIAL_RECONCILIATION WHERE posting_month = 10 and source = 'sap'


--select num_posting_period
--	,SUM([AMT_REFUNDED_ORDER_VALUE_FI_EUR]								)[AMT_REFUNDED_ORDER_VALUE_FI_EUR]
--	,SUM([AMT_REFUND_INVOICE_CANCELLATION_FI_EUR])[AMT_REFUND_INVOICE_CANCELLATION_FI_EUR]
--	,SUM([AMT_REFUNDED_ORDER_VALUE_ACT_EUR_INVOICED_IN_PERIOD]			)[AMT_REFUNDED_ORDER_VALUE_ACT_EUR_INVOICED_IN_PERIOD]
--	,SUM([AMT_REFUNDED_ORDER_VALUE_ACT_EUR_PRIOR_PERIODS]				)[AMT_REFUNDED_ORDER_VALUE_ACT_EUR_PRIOR_PERIODS]
--	,SUM([AMT_REFUNDED_ORDER_VALUE_ACT_EUR_NOT_INVOICED]					)[AMT_REFUNDED_ORDER_VALUE_ACT_EUR_NOT_INVOICED]
--	,SUM([AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR_INVOICED_IN_PERIOD])[AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR_INVOICED_IN_PERIOD]
--	,SUM([AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR_PRIOR_PERIODS])	[AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR_PRIOR_PERIODS]
--	,SUM([AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR_NOT_INVOICED])[AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR_NOT_INVOICED]
--	,SUM([AMT_REFUNDED_MANUAL_POSTING_FI_EUR])[AMT_REFUNDED_MANUAL_POSTING_FI_EUR]
--	,SUM([AMT_REFUNDED_MANUAL_POSTING_INTERCOMPANY_FI_EUR])[AMT_REFUNDED_MANUAL_POSTING_INTERCOMPANY_FI_EUR]
--	,SUM([AMT_REFUNDED_ORDER_VALUE_EST_EUR])[AMT_REFUNDED_ORDER_VALUE_EST_EUR]
--	,SUM(AMT_REFUNDED_ORDER_VALUE_INTERCOMPANY_FI_EUR)AMT_REFUNDED_ORDER_VALUE_INTERCOMPANY_FI_EUR

--from L1.L1_FACT_F_SALES_FINANCE_RECONCILIATION 
--where num_posting_period = 1 --and cd_source_system ='SAP'
--Group by num_posting_period