CREATE TABLE [TEST].[L0_FINANCE_MARCH_ORDERS] (
[Mandant] INT,
[Jahr] INT,
[Monat] INT,
[Tag] nvarchar(255),
[Zahlungsart] nvarchar(255),
[Flag_IC] nvarchar(255),
[Vertriebsweg] nvarchar(255),
[Kundengruppe] nvarchar(255),
[Verkaufsbüro Nr#] nvarchar(255),
[Verkaufsbüro] nvarchar(255),
[Lieferland] nvarchar(255),
[Verkaufsbeleg] nvarchar(255),
[Faktura] nvarchar(255),
[Fakturaposition] nvarchar(255),
[Fakturaart] nvarchar(255),
[Faktura storniert] nvarchar(255),
[Geändert am] nvarchar(255),
[Buchungsbeleg] nvarchar(255),
[Produkthierarchie 1] nvarchar(255),
[Artikelgruppe] nvarchar(255),
[Produkthierarchie 2] nvarchar(255),
[Produkthierarchiebezeichnung 2] nvarchar(255),
[Produkthierarchie 3] nvarchar(255),
[Produkthierarchiebezeichnung 3] nvarchar(255),
[Charge] nvarchar(255),
[Artikelnummer] nvarchar(255),
[Artikelbezeichnung] nvarchar(255),
[Materialart] nvarchar(255),
[Steuerklassifi#-Kd] nvarchar(255),
[Exchange rate]  nvarchar(255),
[Umsatz v# Stornos]  nvarchar(255),
[Storno]  nvarchar(255),
[Umsatz v# Ret# inkl# BF (Finance View)]  nvarchar(255),
[Ret# Umsatz inkl# BF]  nvarchar(255),
[Nettovertriebskosten]  nvarchar(255),
[Deckungsbeitrag]  nvarchar(255),
[Gutschriftsdeckungsbeitrag]  nvarchar(255),
[Menge v# Ret#]  nvarchar(255),
[Ret# Menge]  nvarchar(255),
[Belegfuß v# Ret#]  nvarchar(255),
[Ret# Belegfuß]  nvarchar(255),
[Interner Preis (MEK)]  nvarchar(255),
[Kulanzen (aus Kondition)]  nvarchar(255),
[Voucher]  nvarchar(255),
[Artikelart] nvarchar(255),
[Country] nvarchar(255),
[Channel] nvarchar(255),
[Channel_Planung] nvarchar(255),
[Flag_SalesView]  nvarchar(255),
[Flag_FBA]  nvarchar(255),
[Flag_PBM]  nvarchar(255),
[Flag_B2B]  nvarchar(255),
[Flag_M&A]  nvarchar(255),
[Flag_EOL]  nvarchar(255),
[Flag_Kitting]  nvarchar(255),
[Flag_Retoure]  nvarchar(255),
[Flag_0EUR_Rechnung]  nvarchar(255),
[Flag_Kein_MEK]  nvarchar(255),
[Flag_Liquidation]  nvarchar(255),
[Flag_Incident]  nvarchar(255),
[Gutschriftenart] nvarchar(255),
[Artikelnummernkreis]  nvarchar(255),
[M&A Brand] nvarchar(255),
[Steuersatz]  nvarchar(255),
[Umsatz v# Ret# inkl# BF (Sales View)]  nvarchar(255),
[Umsatz n# Ret# inkl# BF]  nvarchar(255),
[Belegfuß n# Ret#]  nvarchar(255),
[Kundengutschriften]  nvarchar(255),
[Kulanzen]  nvarchar(255),
[Korrekturen]  nvarchar(255),
[Menge n# Ret#]  nvarchar(255),
[Wareneinsatz MEK Hedging v# Ret#]  nvarchar(255),
[Ret# Wareneinsatz MEK Hedging]  nvarchar(255),
[Wareneinsatz MEK Hedging n# Ret#]  nvarchar(255),
[Wareneinsatz MEK Hedging v# Ret# ohne Aufschlag]  nvarchar(255),
[Ret# Wareneinsatz MEK Hedging ohne Aufschlag]  nvarchar(255),
[Wareneinsatz MEK Hedging n# Ret# ohne Aufschlag]  nvarchar(255),
[Sales WEQ]  nvarchar(255),
[Finance WEQ]  nvarchar(255),
[F80]  nvarchar(255),
[Zahlungsart1]  nvarchar(255),
[F82] nvarchar(255),
[F83] nvarchar(255),
[Kundengruppe1] nvarchar(255),
[Channel1] nvarchar(255)
)