/****** Script for SelectTopNRows command from SSMS  ******/

;with CTE_ACDOCA as(
SELECT 
	 acdoca.[KDAUF]						
	,acdoca.[GJAHR]					
	,acdoca.[POPER]					
	--,[AWREF]
	--,mov.[MBLNR]
	--,acdoca.AWITEM
	--,mov.ZEILE
	,STRING_AGG(CAST(RACCT as varchar(max)),'#')RACCT
	,STRING_AGG(CAST(AWREF as varchar(max)),'#')AWREF
FROM L0.L0_S4HANA_0FI_ACDOCA_10 acdoca 
INNER JOIN L0.L0_MI_SALESACCOUNTINGMATRIX kpi
	ON CAST(kpi.AccountNumber AS BIGINT) =CAST(acdoca.RACCT AS BIGINT)
LEFT JOIN L0.L0_S4HANA_2LIS_03_BF mov
			ON	mov.[MBLNR] = acdoca.[AWREF] 
				AND cast(mov.ZEILE as int)  = cast(acdoca.AWITEM  as int)
				AND mov.[MJAHR] = acdoca.GJAHR 
				and acdoca.RACCT = '0051600000'
LEFT JOIN L0.L0_S4HANA_BKPF accountHeader
				ON 	accountHeader.[BELNR] = acdoca.[BELNR]
					AND accountHeader.BUKRS = acdoca.RBUKRS 
					AND accountHeader.[GJAHR] = acdoca.GJAHR 
WHERE 1 = 1
	AND acdoca.RBUKRS = '1000'
	AND acdoca.RLDNR = '0L'
--	AND acdoca.KDAUF = '0402902572'
	and acdoca.poper = 5
	and acdoca.gjahr = 2023
GROUP BY 
	acdoca.[KDAUF],acdoca.[GJAHR],acdoca.[POPER]


)

SELECT 
       re.[NUM_POSTING_YEAR]
      ,re.[NUM_POSTING_PERIOD]
      ,re.[CD_DOCUMENT_NO]
	  ,vahdr.AUART AS  SALES_DOCUMENT_TYPE
      ,[AMT_NET_ORDER_VALUE_FI_EUR]
      ,[AMT_NET_ORDER_VALUE_ACT_EUR_INVOICED_IN_PERIOD]
      ,[AMT_NET_ORDER_VALUE_ACT_EUR_PRIOR_PERIODS]
      ,[AMT_NET_ORDER_VALUE_ACT_EUR_NOT_INVOICED]
      ,[AMT_NET_ORDER_VALUE_EST_EUR]
      ,[AMT_REFUNDED_ORDER_VALUE_FI_EUR]
      ,[AMT_REFUNDED_ORDER_VALUE_EST_EUR]
      ,[AMT_REFUNDED_ORDER_VALUE_ACT_EUR_INVOICED_IN_PERIOD]
      ,[AMT_REFUNDED_ORDER_VALUE_ACT_EUR_PRIOR_PERIODS]
      ,[AMT_REFUNDED_ORDER_VALUE_ACT_EUR_NOT_INVOICED]
      ,[AMT_REVENUE_MANUAL_POSTING_FI_EUR]
	  ,[AMT_NET_PRODUCT_COST_FI_EUR]
      ,[AMT_NET_PRODUCT_COST_ACT_EUR_NOT_INVOICED]
      ,[AMT_NET_PRODUCT_COST_ACT_EUR_INVOICED_IN_PERIOD]
      ,[AMT_NET_PRODUCT_COST_ACT_EUR_PRIOR_PERIODS]
      ,[AMT_NET_PRODUCT_COST_EST_EUR]
      ,[AMT_NET_PRODUCT_COST_GTS_ACT_NOT_INVOICED]
      ,[AMT_NET_PRODUCT_COST_GTS_ACT_INVOICED_IN_PERIOD]
      ,[AMT_NET_PRODUCT_COST_GTS_ACT_PRIOR_PERIODS]
      ,[AMT_FX_HEDGING_IMPACT_FI_EUR]
      ,[AMT_STOCK_ADJUSTMENTS_FI_EUR]
      ,[AMT_DEMURRAGE_DETENTION_FI_EUR]
      ,[AMT_DEADFREIGHT_FI_EUR]
      ,[AMT_KICKBACKS_FI_EUR]
      ,[AMT_3RD_PARTY_SERVICES_FI_EUR]
      ,[AMT_RMA_FI_EUR]
      ,[AMT_SAMPLES_FI_EUR]
      ,[AMT_DROPSHIPMENT_CEOTRA9ER_ARTIKEL_FI_EUR]
      ,[AMT_INBOUND_FREIGHT_COST_FI_EUR]
      ,[AMT_PO_CANCELLATION_FI_EUR]
      ,[AMT_FX_HEDGING_IMPACT_EST_EUR]
      ,[AMT_STOCK_ADJUSTMENTS_EST_EUR]
      ,[AMT_DEMURRAGE_DETENTION_EST_EUR]
      ,[AMT_DEADFREIGHT_EST_EUR]
      ,[AMT_KICKBACKS_EST_EUR]
      ,[AMT_3RD_PARTY_SERVICES_EST_EUR]
      ,[AMT_RMA_EST_EUR]
      ,[AMT_SAMPLES_EST_EUR]
      ,[AMT_DROPSHIPMENT_CEOTRA9ER_ARTIKEL_EST_EUR]
      ,[AMT_INBOUND_FREIGHT_COST_EST_EUR]
      ,[AMT_PO_CANCELLATION_EST_EUR]
      ,[AMT_TURNOVER_EUR]
      ,[VL_ORDER_QUANTITY]
      ,[AMT_VALUE_ADDED_TAX_EUR]
      ,[AMT_NET_DISCOUNT_EUR]
      ,[AMT_ORDER_CHARGES_EUR]
      ,[AMT_GROSS_ORDER_VALUE_EUR]
      ,[VL_CANCELLED_ORDERS_QUANTITY_ACT]
      ,[VL_CANCELLED_ORDERS_QUANTITY_EST]
      ,[AMT_CANCELLED_ORDER_VALUE_ACT_EUR]
      ,[AMT_CANCELLED_ORDER_VALUE_EST_EUR]
      ,[VL_NET_ORDER_QUANTITY_ACT]
      ,[VL_NET_ORDER_QUANTITY_EST]
	  ,AccountNumbers = RACCT
	  ,ReferenceNumbes = AWREF
  FROM [L1].[L1_FACT_F_SALES_FINANCE_RECONCILIATION] re
   LEFT JOIN CTE_ACDOCA  ac
	on ac.KDAUF = re.CD_DOCUMENT_NO 
	LEFT JOIN L0.L0_S4HANA_2LIS_11_VAHDR vahdr
		on vahdr.VBELN = re.CD_DOCUMENT_NO