SELECT top 10 
CD_LEDGER =  acdoca.RLDNR
,CD_COMPANY =  acdoca.RBUKRS
,NUM_FISCAL_YEAR =  acdoca.GJAHR
,CD_FI_DOCUMENT_NO =  acdoca.BELNR
,CD_FI_DOCUMENT_LINE =  acdoca.DOCLN
,CD_FI_TYPE =  acdoca.RMVCT
,CD_REFERENCE_PROCEDURE =  acdoca.AWTYP
,CD_REFERENCE_ORG_UNIT =  acdoca.AWORG
,CD_REFERENCE_DOCUMENT_NO =  acdoca.AWREF
,CD_REFERENCE_DOCUMENT_LINE =  acdoca.AWITEM
,FL_IS_REVERSING_ANOTHER_ITEM =  acdoca.XREVERSING
,FL_IS_REVERSED =  acdoca.XREVERSED
,CD_REVERSAL_ORGANIZATION =  acdoca.AWORG_REV
,CD_REVERSAL_REFERENCE_NO =  acdoca.AWREF_REV
,CD_CURRENCY =  acdoca.RWCUR
,CD_COMPANY_CURRENCY =  acdoca.RHCUR
,CD_GLOBAL_CURRENCY =  acdoca.RKCUR
,CD_UNIT_OF_MEASURE =  acdoca.RUNIT
,CD_ACCOUNT_NUMBER =  acdoca.RACCT
,CD_PROFIT_CENTER =  acdoca.PRCTR
,CD_CONTROLLING_AREA =  acdoca.KOKRS
,CD_SEGMENT =  acdoca.SEGMENT
,CD_PARTNER_PROFIT_CTR =  acdoca.PPRCTR
,CD_TRADING_PARTNER =  acdoca.RASSC
,AMT_AMOUNT_IN_BALANCE_TRANSACTION_CURRENCY =  acdoca.TSL
,AMT_AMOUNT_IN_TRANSACTION_CURRENCY =  acdoca.WSL
,AMT_AMOUNT_IN_COMPANY_CURRENCY =  acdoca.HSL
,AMT_AMOUNT_IN_GLOBAL_CURRENCY =  acdoca.KSL
,VL_QUANTITY =  acdoca.MSL
,VL_INVENTORY_QUANTITY =  acdoca.LBKUM
,NUM_POSTING_PERIOD =  acdoca.POPER
,CD_FISCAL_YEAR_VARIANT =  acdoca.PERIV
,D_FI_POSTING =  acdoca.BUDAT
,D_FI_CREATED =  acdoca.BLDAT
,CD_FI_TYPE =  acdoca.BLART
,CD_POSTING_KEY =  acdoca.BSCHL
,CD_ITEM_CATEGORY =  acdoca.LINETYPE
,CD_TRANSACTION_KEY =  acdoca.KTOSL
,DT_FI_TIMESTAMP =  acdoca.TIMESTAMP
,NUM_ORIGIN_OBJECT =  acdoca.RHOART
,CD_GL_ACCOUNT_TYPE =  acdoca.GLACCOUNT_TYPE
,CD_CHART_OF_ACCOUNTS =  acdoca.KTOPL
,CD_ALTERNATIVE_ACCOUNT_NO =  acdoca.LOKKT
,CD_COUNTRY_CHART_ACCTS =  acdoca.KTOP2
,CD_PURCHASING_DOCUMENT =  acdoca.EBELN
,CD_SALES_ORDER_NO =  acdoca.KDAUF
,CD_SALES_ORDER_LINE =  acdoca.KDPOS
,CD_ITEM_NO =  acdoca.MATNR
,CD_PLANT =  acdoca.WERKS
,CD_VENDOR =  acdoca.LIFNR
,CD_CUSTOMER =  acdoca.KUNNR
,CD_ACCOUNT_TYPE =  acdoca.KOART
,CD_SPECIAL_GL_IND =  acdoca.UMSKZ
,CD_TAX_CODE =  acdoca.MWSKZ
,D_CLEARING_DATE =  acdoca.AUGDT
,CD_CLEARING_DOCUMENT =  acdoca.AUGBL
,CD_VALUATION_TYPE =  acdoca.BWTAR
,CD_VALUATION_AREA =  acdoca.BWKEY
,CD_ORIGIN_PROCESS_CATEGORY =  acdoca.MLPTYP
,CD_OBJECT_NUMBER =  acdoca.OBJNR
,CD_OFFSETTING_ACCOUNT =  acdoca.GKONT
,CD_OFFSETTING_ACCOUNT_TYPE =  acdoca.GKOAR
,CD_OBJECT_CLASS =  acdoca.SCOPE
,CD_ACCOUNT_ASSIGNMENT =  acdoca.ACCAS
,CD_OBJECT_TYPE =  acdoca.ACCASTY
,CD_OPERATING_CONCERN =  acdoca.ERKRS
,CD_CO_DOCUMENT_NUMBER =  acdoca.CO_BELNR
,CD_BILLING_TYPE =  acdoca.FKART
,CD_COMPANY_ID =  acdoca.VKORG
,CD_DISTRIBUTION_CHANNEL =  acdoca.VTWEG
,CD_DIVISION =  acdoca.SPART
,CD_SUPPLIER =  acdoca.MATKL
,CD_CUSTOMER_GROUP =  acdoca.KDGRP
,CD_BILLING_DOCUMENT_NO =  vdhdr.VBELN
,CD_BILLING_CATEGORY =  vdhdr.FKTYP
,D_BILLING_DATE =  vdhdr.FKDAT
--,CD_INCOTERMS =  vdhdr.INCO1
--,CD_INCOTERMS_2 =  vdhdr.INCO2
,CD_BILLING_DOCUMENT_POSTING_STATUS =  vdhdr.ZZ_RFBSK
,CD_PAYMENT_METHOD =  vdhdr.ZTERM
,DT_BILLING_DOCUMENT_CREATED_ON =  vdhdr.ERDAT
,CD_PAYER =  vdhdr.KUNRG
--,CD_DUNNING_AREA =  vdhdr.MABER
--,DT_BILLING_DOCUMENT_CHANGED_ON =  vdhdr.AEDAT
--,CD_CANCELED_BILLING_DOCUMENT =  vdhdr.SFAKN
--,CD_INVOICE_LIST_TYPE =  vdhdr.FKART_RL
--,CD_TAX_DEPARTURE_COUNTRY =  vdhdr.LANDTX
--,CD_ORIGIN_SLS_TAX_NO =  vdhdr.STCEG_H
--,CD_COUNTRY_SLS_TAX_NO =  vdhdr.STCEG_L
--,CD_INCOTERMS_LOCATION_1 =  vdhdr.INCO2_L
,CD_BILLING_DOCUMENT_NO =  vditm.VBELN
,CD_BILLING_DOCUMENT_LINE =  vditm.POSNR
,CD_BILLED_QUANTITY =  vditm.FKIMG
,CD_UNIT_WEIGHT =  vditm.GEWEI
,VL_VOLUME =  vditm.VOLUM
,VL_EXCHANGE_RATE =  vditm.KURSK
,CD_SALES_DOCUMENT =  vditm.AUBEL
,CD_ITEM_GROUP =  vditm.MATKL
--,CD_REGION_OF_DLV_PLANT =  vditm.WKREG
,CD_TAX_CLASS_MATERIAL =  vditm.TAXM1
,CD_BILLING_DOCUMENT_CREATED_ON =  vditm.ERDAT
,CD_STORAGE_LOCATION =  vditm.LGORT
,CD_DELIVERY_COUNTRY_OF_ORDER =  vditm.LLAND_AUFT
,CD_COMPANY_OF_ORDER =  vditm.VKORG_AUFT
,CD_DISTRIBUTION_CHANNEL_ORDER =  vditm.VTWEG_AUFT
,CD_RETURN_REASON =  vditm.MSR_RET_REASON
,CD_BILLING_DOCUMENT_REJECTION_STATUS =  vditm.ABSTA
,D_SD_CREATED =  vahdr.ERDAT
,CD_SD_TYPE =  vahdr.AUART
,CD_CUSTOMER_REFERENCE =  vaitm.BSTKD
,D_SALES_DOCUMENT_CHANGED_ON =  vaitm.AEDAT
,CD_CANCELATION_REASON =  vaitm.ABGRU
,D_SD_LINE_CREATED =  vaitm.ERDAT
,CD_SD_ITEM_REJECTION_STATUS =  vaitm.ABSTA
,CD_MATERIAL_DOCUMENT =  bf.MBLNR
,NUM_MATERIAL_DOCUMENT_YEAR =  bf.MJAHR
,CD_MATERIAL_DOCUMENT_LINE =  bf.ZEILE
,CD_MOVEMENT_TYPE =  bf.BWART
,CD_COMPANY =  bkpf.BUKRS
,CD_FI_DOCUMENT_NO =  bkpf.BELNR
,CD_TRANSACTION_CODE =  bkpf.TCODE
,T_DOCUMENT_HEADER_TEXT =  bkpf.BKTXT

FROM L0.L0_S4HANA_0FI_ACDOCA_10 acdoca
INNER JOIN L0.L0_S4HANA_Z_FI_BKPF bkpf
	on		
		bkpf.BUKRS = acdoca.RBUKRS
		AND bkpf.GJAHR = acdoca.GJAHR
		AND bkpf.BELNR = acdoca.BELNR

LEFT JOIN L0.L0_S4HANA_2LIS_03_BF bf
	on 
		acdoca.AWREF = bf.MBLNR
		AND acdoca.AWORG = bf.MJAHR
		AND cast(acdoca.AWITEM as int) = cast(bf.ZEILE as int)
LEFT JOIN L0.L0_S4HANA_2LIS_11_VAHDR vahdr
	on 
		acdoca.KDAUF = vahdr.VBELN
LEFT JOIN L0.L0_S4HANA_2LIS_11_VAITM vaitm
	on 
		acdoca.KDAUF = vahdr.VBELN

LEFT JOIN L0.L0_S4HANA_2LIS_13_VDHDR vdhdr
	on 
		acdoca.AWREF = vdhdr.VBELN
LEFT JOIN L0.L0_S4HANA_2LIS_13_VDITM vditm
	on 
		acdoca.AWREF = vditm.VBELN
		and 
		acdoca.AWITEM = vditm.POSNR


		--select top 10 KSCHL,* FROM L0.L0_S4HANA_0FI_ACDOCA_10 
		-- select top 10 RBUKRS,* FROM L0.L0_S4HANA_Z_FI_BKPF 
		---- select top 10 INCO1,INCO2,* FROM L0.L0_S4HANA_2LIS_13_VDHDR 
		--select top 10 INCO1,INCO2,* FROM L0.L0_S4HANA_2LIS_13_VDITM