DECLARE @PROCESS_ID nvarchar(50)= '0404172204'

SELECT 1
	---only ledger
	,ID_GENERAL_LEDGER					 = fact.ID_GENERAL_LEDGER
	,CD_ACCOUNT_NUMBER                   = fact.CD_ACCOUNT_NUMBER
    ,CD_FI_TYPE                          = fact.CD_FI_TYPE
	,CD_FI_DOCUMENT_NO                   = fact.CD_FI_DOCUMENT_NO
    ,CD_FI_DOCUMENT_LINE                 = fact.CD_FI_DOCUMENT_LINE
	,CD_BILLING_TYPE					 = fkart.[CD_SALES_TRANSACTION_TYPE]
	,CD_LEDGER                           = fact.CD_LEDGER
	,CD_REFERENCE_PROCEDURE              = fact.CD_REFERENCE_PROCEDURE
	,CD_REFERENCE_ORG_UNIT               = fact.CD_REFERENCE_ORG_UNIT
	,CD_REFERENCE_DOCUMENT_NO            = fact.CD_REFERENCE_DOCUMENT_NO
	,CD_REFERENCE_DOCUMENT_LINE          = fact.CD_REFERENCE_DOCUMENT_LINE
	,FL_IS_REVERSING_ANOTHER_ITEM        = fact.FL_IS_REVERSING_ANOTHER_ITEM
	,FL_IS_REVERSED                      = fact.FL_IS_REVERSED
	,ID_COMPANY_FI_REVERSAL              = fact.ID_COMPANY_FI_REVERSAL
	,CD_REVERSAL_FI_DOCUMENT_NO          = fact.CD_REVERSAL_FI_DOCUMENT_NO
	,CD_CURRENCY_COMPANY                 = fact.CD_CURRENCY_COMPANY
	,CD_CURRENCY_GLOBAL                  = fact.CD_CURRENCY_GLOBAL
	,CD_CURRENCY_BALANCE                 = fact.CD_CURRENCY_BALANCE
    ,CD_UNIT                             = fact.CD_UNIT
    ,CD_PROFIT_CENTER                    = fact.CD_PROFIT_CENTER
    ,CD_CONTROLLING_AREA                 = fact.CD_CONTROLLING_AREA
    ,CD_DOCUMENT_TYPE_FI                 = fact.CD_DOCUMENT_TYPE_FI
    ,CD_SEGMENT                          = fact.CD_SEGMENT
    ,CD_PROFIT_CENTER_PARTNER            = fact.CD_PROFIT_CENTER_PARTNER
    ,CD_TRADING_PARTNER                  = fact.CD_TRADING_PARTNER
    ,CD_FISCAL_YEAR_VARIANT              = fact.CD_FISCAL_YEAR_VARIANT
    ,D_FI_POSTING                        = fact.D_FI_POSTING
    ,D_FI_CREATED                        = fact.D_FI_CREATED
    ,DT_FI_TIMESTAMP                     = fact.DT_FI_TIMESTAMP
    ,CD_POSTING_KEY                      = fact.CD_POSTING_KEY
    ,CD_FI_DOCUMENT_LINE_CATEGORY        = fact.CD_FI_DOCUMENT_LINE_CATEGORY
    ,CD_TRANSACTION_KEY                  = fact.CD_TRANSACTION_KEY
    ,CD_OBJECT_ORIGIN                    = fact.CD_OBJECT_ORIGIN
    ,CD_GL_ACCOUNT_TYPE                  = fact.CD_GL_ACCOUNT_TYPE
    ,CD_CHART_OF_ACCOUNTS                = fact.CD_CHART_OF_ACCOUNTS
    ,CD_ACCOUNT_NUMBER_ALTERNATIVE       = fact.CD_ACCOUNT_NUMBER_ALTERNATIVE
    ,CD_CHART_OF_ACCOUNTS_ALTERNATIVE    = fact.CD_CHART_OF_ACCOUNTS_ALTERNATIVE
    ,CD_PURCHASING_DOCUMENT_NO           = fact.CD_PURCHASING_DOCUMENT_NO
    ,CD_SUPPLIER                         = fact.CD_SUPPLIER
    ,CD_ACCOUNT_TYPE                     = fact.CD_ACCOUNT_TYPE
    ,CD_SPECIAL_GL_INDICATOR             = fact.CD_SPECIAL_GL_INDICATOR
    ,CD_TAX_CODE                         = fact.CD_TAX_CODE
    ,D_CLEARING_DATE                     = fact.D_CLEARING_DATE
    ,CD_CLEARING_DOCUMENT_NO             = fact.CD_CLEARING_DOCUMENT_NO
    ,CD_ITEM_VALUATION_TYPE              = fact.CD_ITEM_VALUATION_TYPE
    ,ID_STORAGE_LOCATION_VALUATION       = fact.ID_STORAGE_LOCATION_VALUATION
    ,CD_ORIGIN_PROCESS_CATEGORY          = fact.CD_ORIGIN_PROCESS_CATEGORY
    ,CD_OBJECT_NUMBER                    = fact.CD_OBJECT_NUMBER
    ,CD_ACCOUNT_NUMBER_OFFSETTING        = fact.CD_ACCOUNT_NUMBER_OFFSETTING
    ,CD_ACCOUNT_TYPE_OFFSETTING          = fact.CD_ACCOUNT_TYPE_OFFSETTING
    ,CD_OBJECT_CLASS                     = fact.CD_OBJECT_CLASS
    ,CD_ACCOUNT_NUMBER_ASSIGMENT         = fact.CD_ACCOUNT_NUMBER_ASSIGMENT
    ,CD_OBJECT_TYPE                      = fact.CD_OBJECT_TYPE
    ,CD_OPERATING_CONCERN                = fact.CD_OPERATING_CONCERN
    ,CD_CONTROLLING_DOCUMENT_NO          = fact.CD_CONTROLLING_DOCUMENT_NO
    ,ID_SALES_TRANSACTION_TYPE           = fact.ID_SALES_TRANSACTION_TYPE
    ,ID_COMPANY_SALES                    = fact.ID_COMPANY_SALES
    ,CD_DIVISION                         = fact.CD_DIVISION
    ,CD_ITEM_GROUP                       = fact.CD_ITEM_GROUP
    ,CD_CUSTOMER_GROUP                   = fact.CD_CUSTOMER_GROUP
    ,ID_SALES_CHANNEL                    = fact.ID_SALES_CHANNEL
    ,CD_TRANSACTION_CODE                 = fact.CD_TRANSACTION_CODE
    ,CD_CONDITION_TYPE                   = fact.CD_CONDITION_TYPE
    ,T_DOCUMENT_HEADER_TEXT              = fact.T_DOCUMENT_HEADER_TEXT
    ,CD_STOCK_MOVEMENT_TYPE              = fact.CD_STOCK_MOVEMENT_TYPE
    ,AMT_AMOUNT_BALANCE                  = fact.AMT_AMOUNT_BALANCE
    ,AMT_AMOUNT_TRANSACTION              = fact.AMT_AMOUNT_TRANSACTION
    ,AMT_AMOUNT_COMPANY                  = fact.AMT_AMOUNT_COMPANY
    ,AMT_AMOUNT_GLOBAL                   = fact.AMT_AMOUNT_GLOBAL
    ,VL_QUANTITY_INVENTORY               = fact.VL_QUANTITY_INVENTORY


	--only sales
	,CD_SALES_TYPE						 = NULL

	-- ledger / sales
	,CD_SOURCE_SYSTEM					 = 'SAP'
    ,ID_ITEM                             = fact.ID_ITEM
	,ID_STORAGE_LOCATION				 = fact.ID_STORAGE_LOCATION
    ,ID_COMPANY                          = fact.ID_COMPANY
	,NUM_POSTING_YEAR                    = fact.NUM_POSTING_YEAR
    ,NUM_POSTING_PERIOD                  = fact.NUM_POSTING_PERIOD
	,CD_CURRENCY_TRANSACTION             = fact.CD_CURRENCY_TRANSACTION
    ,VL_QUANTITY                         = fact.VL_QUANTITY
    ,ID_SALES_TRANSACTION                = fact.ID_SALES_TRANSACTION
    ,CD_CUSTOMER                         = fact.CD_CUSTOMER
    ,CD_SALES_PROCESS_ID				 = sales.CD_SALES_PROCESS_ID
    ,CD_SALES_PROCESS_LINE				 = sales.CD_SALES_PROCESS_LINE
    ,CD_SALES_ORDER_NO					 = sales.CD_DOCUMENT_NO
    ,CD_SALES_ORDER_LINE				 = sales.CD_DOCUMENT_LINE
    ,ID_COMPANY_SALES_ORDER				 = sales.ID_COMPANY
    ,ID_SALES_TRANSACTION_TYPE			 = sales.ID_SALES_TRANSACTION_TYPE
    ,CD_TYPE_SALES						 = sales.CD_TYPE
    ,D_SALES_ORDER_CREATED				 = sales.D_CREATED
    ,D_SALES_PROCESS					 = sales.D_SALES_PROCESS
    ,DT_CREATED							 = sales.DT_CREATED
    ,T_CANCELLATION_REASON				 = sales.T_CANCELLATION_REASON
    ,FL_INCIDENT						 = sales.FL_INCIDENT
    ,CD_ITEM_TYPE						 = sales.CD_ITEM_TYPE
	,CD_FULFILLMENT						 = sales.CD_FULFILLMENT
    ,CD_MARKET_ORDER_ID					 = sales.CD_MARKET_ORDER_ID
    ,CD_PAYMENT_METHOD					 = sales.CD_PAYMENT_METHOD
    ,CD_COUNTRY_INVOICE					 = sales.CD_COUNTRY_INVOICE
    ,CD_ZIP_INVOICE						 = sales.CD_ZIP_INVOICE
    ,T_CITY_INVOICE						 = sales.T_CITY_INVOICE
    ,CD_COUNTRY_DELIVERY				 = sales.CD_COUNTRY_DELIVERY
    ,CD_ZIP_DELIVERY					 = sales.CD_ZIP_DELIVERY
    ,T_CITY_DELIVERY					 = sales.T_CITY_DELIVERY
    ,CD_COUNTRY_ORDER					 = sales.CD_COUNTRY_ORDER
    ,CD_ZIP_ORDER						 = sales.CD_ZIP_ORDER
    ,T_CITY_ORDER						 = sales.T_CITY_ORDER
  	,[AMT_TURNOVER_EUR]						=0
	,[VL_ORDER_QUANTITY]					=0
	,[AMT_VALUE_ADDED_TAX_EUR]				=0
	,[AMT_ORDER_DISCOUNTS_EUR]				=0
	,[AMT_ORDER_CHARGES_EUR]				=0
	,[AMT_GROSS_ORDER_VALUE_EUR]			=0
	,[AMT_CANCELLED_ORDER_VALUE_EUR]        =0
	,[VL_CANCELLED_ORDER_QUANTITY]          =0
	,[AMT_NET_ORDER_VALUE_EUR]              =0
	,[AMT_NET_ORDER_VALUE_FULL_PRICE_EUR]   =0
	,[VL_NET_ORDER_QUANTITY]                =0
	,[AMT_INVOICED_ORDER_VALUE_FULL_PRICE_EUR]										= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_INVOICED_ORDER_VALUE_FULL_PRICE_PARAM],0)) 
	,[AMT_INVOICED_DISCOUNTS_VOUCHERS_EUR]											= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_INVOICED_DISCOUNTS_VOUCHERS_PARAM],0))
	,[AMT_INVOICED_ORDER_VALUE_EUR]													= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_INVOICED_ORDER_VALUE_PARAM],0))
	,[AMT_REFUNDS_EUR]																= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_REFUNDS_PARAM],0))
	,[AMT_REFUNDS_THEREOF_RETURN_AVOIDANCE_CREDITS_EUR]								= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_REFUNDS_THEREOF_RETURN_AVOIDANCE_CREDITS_PARAM],0))
	,[AMT_REFUNDS_THEREOF_CREDIT_NOTES_RETURNS_EUR]									= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_REFUNDS_THEREOF_CREDIT_NOTES_RETURNS_PARAM],0))
	,[AMT_REVENUE_EUR]																= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_REVENUE_PARAM],0))
	,[AMT_REVENUE_THEREOF_REVENUE_SD_EUR]											= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_REVENUE_THEREOF_REVENUE_SD_PARAM],0))
	,[AMT_REVENUE_THEREOF_WARRANTY_PROVISION_EUR]									= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_REVENUE_THEREOF_WARRANTY_PROVISION_PARAM],0))
	,[AMT_REVENUE_THEREOF_OTHER_REVENUE_ON_CHARGED_IS_COUNTS_SPECIAL_EFFECTS_EUR]	= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_REVENUE_THEREOF_OTHER_REVENUE_ON_CHARGED_IS_COUNTS_SPECIAL_EFFECTS_PARAM],0))
	,[AMT_NET_PRODUCT_COST_EUR]														= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_NET_PRODUCT_COST_PARAM],0))
	,[AMT_COGS_FX_HEDGING_IMPACT_EUR]												= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_COGS_FX_HEDGING_IMPACT_PARAM],0))
	,[AMT_COGS_STOCK_VALUE_ADJUSTMENT_EUR]											= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_COGS_STOCK_VALUE_ADJUSTMENT_PARAM],0))
	,[AMT_DEMMURAGE_AND_DETENTION_EUR]												= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_DEMMURAGE_AND_DETENTION_PARAM],0))
	,[AMT_DEADFREIGHT_EUR]															= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_DEADFREIGHT_PARAM],0))
	,[AMT_KICKBACKS_EUR]															= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_KICKBACKS_PARAM],0))
	,[AMT_3RDPARTYSERVICES_EUR]														= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_3RDPARTYSERVICES_PARAM],0))
	,[AMT_RMA_EUR]																	= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_RMA_PARAM],0))
	,[AMT_SAMPLES_EUR]																= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_SAMPLES_PARAM],0))
	,[AMT_DROPSHIPMENT_CEOTRA9ER_ARTIKEL_EUR]										= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_DROPSHIPMENT_CEOTRA9ER_ARTIKEL_PARAM],0))
	,[AMT_INBOUND_FREIGHT_COSTS_EST_EUR]											= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_INBOUND_FREIGHT_COSTS_EST_PARAM],0))
	,[AMT_PO_CANCELLATION_EUR]														= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_PO_CANCELLATION_PARAM],0))
	,[AMT_STOCK_ADJUSTMENT_EUR]														= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_STOCK_ADJUSTMENT_PARAM],0))
	,[AMT_OTHER_COGS_EFFECTS_EUR]													= (fact.AMT_AMOUNT_COMPANY * isnull(matrix.[VL_OTHER_COGS_EFFECTS_PARAM],0))

FROM L1.L1_FACT_A_GENERAL_LEDGER fact
LEFT JOIN [L1].[L1_DIM_A_SALES_TRANSACTION_TYPE] fkart
	ON fkart.ID_SALES_TRANSACTION_TYPE = fact.ID_SALES_TRANSACTION_TYPE
LEFT JOIN L1.L1_FACT_A_SALES_TRANSACTION sales on sales.[ID_SALES_TRANSACTION] =  fact.[ID_SALES_TRANSACTION]
LEFT JOIN [L1].[L1_FACT_A_STOCK_MOVEMENT] stock
	ON stock.CD_DOCUMENT_NO = fact.CD_REFERENCE_DOCUMENT_NO
		AND cast(stock.CD_DOCUMENT_LINE as int) = CAST(fact.CD_REFERENCE_DOCUMENT_LINE as int)
		AND cast(stock.NUM_POSTING_YEAR as nvarchar(10))= fact.CD_REFERENCE_ORG_UNIT
INNER JOIN [L1].[L1_DIM_A_FINANCE_TRAN_KPI_MATRIX] matrix
	ON matrix.CD_ACCOUNT_NUMBER = fact.CD_ACCOUNT_NUMBER
		AND (CONCAT(matrix.CD_TRANSACTION_TYPE_FI ,'#FKART')  =fkart.[CD_SALES_TRANSACTION_TYPE]  OR (matrix.CD_TRANSACTION_TYPE_FI IS NULL ))
		AND (ISNULL(matrix.CD_DOCUMENT_TYPE_FI,'') = ISNULL(fact.CD_DOCUMENT_TYPE_FI,'') OR matrix.CD_DOCUMENT_TYPE_FI IS NULL)
		AND (ISNULL(matrix.CD_STOCK_MOVEMENT_TYPE,'') = isnull(stock.CD_STOCK_MOVEMENT_TYPE,'') OR matrix.CD_STOCK_MOVEMENT_TYPE IS NULL)
		AND (
				(matrix.FL_HAS_TCODE = 'Y' AND isnull(CD_TRANSACTION_CODE,'')<> '') 
				OR  
				(matrix.FL_HAS_TCODE = 'N' AND isnull(CD_TRANSACTION_CODE,'')= '')
				
				OR matrix.FL_HAS_TCODE IS NULL
			)

WHERE 1=1
	--YEAR(D_FI_CREATED) = 2023-- and ID_SALES_TRANSACTION = 88098979
	--AND
	--MONTH(D_FI_CREATED) =  5
	--AND sales.CD_SALES_PROCESS_ID = @PROCESS_ID

