DECLARE  @NUM_POSTING_YEAR [int]=2023,@NUM_POSTING_PERIOD [int] = 10
	DECLARE @PROCESSID nvarchar(50)='' 

IF OBJECT_ID('tempdb..#Intercompany') IS NOT NULL
	DROP TABLE #Intercompany

CREATE TABLE #Intercompany
(
	Mandant int,
	Kundennummer int

)
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 101000094,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 101000095,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 101000426,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 101000456,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 101000602,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 101000789,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 101170609,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 101502400,2
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 101633002,2
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 101923004,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 101925412,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 101926092,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 101926466,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 101929286,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 101930952,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 101930953,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 101933394,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 102823359,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 102852810,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 102858006,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 103899691,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 103991514,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 103992516,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 103993080,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 103993776,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 103995190,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 103995383,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 104000000,2
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 104000001,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 104000002,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 104000003,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 104028600,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 104130000,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 104695552,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 104999000,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 104999027,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 104999033,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 104999949,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 104999950,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 104999951,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 105097372,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 106000000,3
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 106100010,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 107022500,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 110547729,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 111006943,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 114412984,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 119000135,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 119005641,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 170001618,1
INSERT INTO #Intercompany (Kundennummer,Mandant) SELECT 170001746,1

/*****************************************************************************
** CTE responsible for calculate for the given period the values from SAGE based transactions
** according to the kpi accounting matrix
*****************************************************************************/

; WITH  CTE_BUCHUNGSJOURNAL AS (
	SELECT 
		   [CD_DOCUMENT_NO]                                                     AS [CD_DOCUMENT_NO]
		  ,vorid                                                                AS [CD_SALES_PROCESS_ID]
		  ,max([NUM_POSTING_YEAR])                                              AS NUM_POSTING_YEAR
		  ,max([NUM_POSTING_PERIOD])                                            AS NUM_POSTING_PERIOD
		  ,accounting.[CD_SOURCE_SYSTEM]                                        AS CD_SOURCE_SYSTEM
		  ,[CD_COMPANY]                                                         AS CD_COMPANY 
		  --,CASE WHEN inc.Kundennummer IS NOT NULL THEN 'Intercompany'
				--ELSE ch.CD_CHANNEL_GROUP_1	END									AS CD_CHANNEL_GROUP_1
		  ,MAX(CD_DOCUMENT_TYPE_FI)												AS CD_DOCUMENT_TYPE_FI
		  ,SUM(ISNULL(AMT_NET_ORDER_VALUE_FI_EUR,0) )							AS AMT_NET_ORDER_VALUE_FI_EUR
		  ,CH.ID_SALES_CHANNEL
		  ,SUM(CASE WHEN inc.Kundennummer IS NOT NULL OR
							CD_CHANNEL_GROUP_1 ='Intercompany' 
							OR CD_CHANNEL_GROUP_1 ='Mandanten'
							THEN ISNULL(AMT_NET_ORDER_VALUE_FI_EUR,0) ELSE 0 END)	AS AMT_NET_ORDER_VALUE_INTERCOMPANY_FI_EUR
		  ,SUM(ISNULL(AMT_REFUNDED_ORDER_VALUE_FI_EUR,0))						AS AMT_REFUNDED_ORDER_VALUE_FI_EUR	
		  ,SUM(ISNULL(AMT_REFUNDED_MANUAL_POSTING_FI_EUR,0))					AS AMT_REFUNDED_MANUAL_POSTING_FI_EUR	
		  ,SUM(ISNULL(AMT_STOCK_VALUE_ADJUSTMENTS_FI_EUR,0))                    AS AMT_STOCK_VALUE_ADJUSTMENTS_FI_EUR

		
	 FROM L1.L1_FACT_A_SALES_ACCOUNTING_VALUE		accounting
	  LEFT JOIN L0.L0_SAGE_KHKVKBELEGE belege
			ON CAST(belege.Belegnummer as nvarchar(50)) = accounting.CD_DOCUMENT_NO
			AND year(belege.Belegdatum) = accounting.NUM_POSTING_YEAR
			AND belege.mandant = accounting.CD_COMPANY
	  LEFT JOIN #Intercompany inc on inc.mandant = belege.mandant and inc.Kundennummer = belege.A0Empfaenger
	  LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL ch on ch.CD_SALES_CHANNEL = belege.Kundengruppe and ch.CD_SOURCE_SYSTEM='SGE'

	  WHERE 
		[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR
		AND [NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD	
		AND accounting.CD_SOURCE_SYSTEM = 'SGE'
		AND (vorid = @PROCESSID or @PROCESSID = '')
	 GROUP BY [CD_DOCUMENT_NO],vorid,[NUM_POSTING_YEAR],[NUM_POSTING_PERIOD],accounting.[CD_SOURCE_SYSTEM],[CD_COMPANY],inc.Kundennummer,ch.ID_SALES_CHANNEL

)

/*****************************************************************************
** CTE responsible for calculate the PL line based on sales orders data. It's not 
** limited by period, as we may have sales values recognize this period but not invoiced
** or invoiced but sales recognized in previous periods
*****************************************************************************/
 ,CTE_SALES_ORDERS AS 
(

SELECT 
		  
		 FACT.CD_DOCUMENT_NO 		
		,FACT.CD_SALES_PROCESS_ID 
		,CD_SALES_TRANSACTION_CATEGORY																																			    AS CD_TYPE
		,MONTH(FACT.[D_CREATED])																																				    AS [NUM_POSTING_PERIOD]
		,YEAR(FACT.[D_CREATED])	 																																			        AS [NUM_POSTING_YEAR]
		,FACT.[CD_SOURCE_SYSTEM]
		,[CD_COMPANY]
		,CH.ID_SALES_CHANNEL
	--	,CD_CHANNEL_GROUP_1																																							as CD_CHANNEL_GROUP_1
		--NOV
		 ,CASE WHEN CD_SALES_TRANSACTION_CATEGORY in ('Order','OrderInvoice') 
		THEN SUM(ISNULL(FACT.AMT_GROSS_PRICE_EUR,0)+ISNULL(FACT.AMT_NET_SHIPPING_REVENUE_EUR,0)-ISNULL(FACT.AMT_TAX_PRICE_EUR,0)-ABS(ISNULL(FACT.AMT_NET_DISCOUNT_EUR,0)))
		WHEN CD_SALES_TRANSACTION_CATEGORY = 'OrderCancellation' THEN -1*SUM(ISNULL(FACT.AMT_GROSS_PRICE_EUR,0)+ISNULL(FACT.AMT_NET_SHIPPING_REVENUE_EUR,0)-ISNULL(FACT.AMT_TAX_PRICE_EUR,0)-ABS(ISNULL(FACT.AMT_NET_DISCOUNT_EUR,0)))
		ELSE 0 END  AS AMT_NET_ORDER_VALUE_ACT_EUR
	    ,SUM(CASE WHEN (CD_CHANNEL_GROUP_1 ='Intercompany' OR CD_CHANNEL_GROUP_1 ='Mandanten') AND CD_SALES_TRANSACTION_CATEGORY in ('Order','OrderInvoice','Invoice') 
		THEN ISNULL(FACT.AMT_GROSS_PRICE_EUR,0)+ISNULL(FACT.AMT_NET_SHIPPING_REVENUE_EUR,0)-ISNULL(FACT.AMT_TAX_PRICE_EUR,0)-ABS(ISNULL(FACT.AMT_NET_DISCOUNT_EUR,0))	ELSE 0 END)  AS [AMT_NET_ORDER_VALUE_INTERCOMPANY_ACT_EUR]
		----REFUNDS
		,CASE WHEN CD_SALES_TRANSACTION_CATEGORY ='Refund' THEN  sum(ISNULL(FACT.AMT_GROSS_PRICE_EUR,0)-ISNULL(FACT.AMT_TAX_PRICE_EUR,0)+ISNULL(FACT.AMT_NET_SHIPPING_REVENUE_EUR,0)-ABS(ISNULL(FACT.AMT_NET_DISCOUNT_EUR,0))) ELSE 0 END                          AS [AMT_REFUNDED_ORDER_VALUE_ACT_EUR]
		,SUM(CASE WHEN (CD_CHANNEL_GROUP_1 ='Intercompany' OR CD_CHANNEL_GROUP_1 ='Mandanten') AND CD_SALES_TRANSACTION_CATEGORY ='Refund' THEN
		ISNULL(FACT.AMT_GROSS_PRICE_EUR,0)-ISNULL(FACT.AMT_TAX_PRICE_EUR,0)+ISNULL(FACT.AMT_NET_SHIPPING_REVENUE_EUR,0)-ABS(ISNULL(FACT.AMT_NET_DISCOUNT_EUR,0)) ELSE 0 END)   AS [AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR]
		,sum(ISNULL(AMT_REFUNDED_ORDER_VALUE_EST_EUR,0))																														AS [AMT_REFUNDED_ORDER_VALUE_EST_EUR]
		,sum(AMT_RETURN_ORDER_VALUE_EST_EUR)																														            AS [AMT_RETURN_ORDER_VALUE_EST_EUR]
		----PRODUCT COST
		,sum( FACT.AMT_MEK_HEDGING_EUR -  FACT.AMT_GTS_MARKUP)																			                                        AS [AMT_NET_PRODUCT_COST_ACT_EUR]
		,sum(CASE WHEN  (CD_CHANNEL_GROUP_1 ='Intercompany' OR CD_CHANNEL_GROUP_1 ='Mandanten') THEN  FACT.AMT_MEK_HEDGING_EUR -  FACT.[AMT_GTS_MARKUP] ELSE 0 END)	                AS [AMT_NET_PRODUCT_COST_INTERCOMPANY_ACT_EUR]
		,sum(AMT_NET_PRODUCT_COST_EST_EUR)																						                                                AS [AMT_NET_PRODUCT_COST_EST_EUR]
		,sum( FACT.[AMT_GTS_MARKUP])																									                                        AS [AMT_NET_PRODUCT_COST_GTS_ACT]
		,sum(CASE WHEN(CD_CHANNEL_GROUP_1 ='Intercompany' OR CD_CHANNEL_GROUP_1 ='Mandanten')  THEN  FACT.[AMT_GTS_MARKUP] ELSE 0 END)		                                        AS [AMT_NET_PRODUCT_COST_INTERCOMPANY_GTS_ACT]
		---- PC1 Lines																																	
		,SUM(AMT_FX_HEDGING_IMPACT_EST_EUR)																														                AS [AMT_FX_HEDGING_IMPACT_EST_EUR]
		,SUM(AMT_COGS_STOCK_VALUE_ADJUSTMENT_EST_EUR)																											                AS AMT_COGS_STOCK_VALUE_ADJUSTMENT_EST_EUR
		,SUM(AMT_DEMURRAGE_DETENTION_EUR)																														                AS [AMT_DEMURRAGE_DETENTION_EST_EUR]
		,SUM(AMT_DEADFREIGHT_EUR)																																                AS [AMT_DEADFREIGHT_EST_EUR]
		,SUM(AMT_KICKBACKS_EUR)																																	                AS [AMT_KICKBACKS_EST_EUR]
		,SUM(AMT_3RD_PARTY_SERVICES_EUR)																														                AS [AMT_3RD_PARTY_SERVICES_EST_EUR]
		,SUM(AMT_RMA_EUR)																																		                AS [AMT_RMA_EST_EUR]
		,SUM(AMT_SAMPLES_EUR)																																	                AS [AMT_SAMPLES_EST_EUR]
		,SUM([AMT_DROPSHIPMENT_CEOTRA9ER_ARTIKEL_EST_EUR])																											            AS [AMT_DROPSHIPMENT_CEOTRA9ER_ARTIKEL_EST_EUR]
		,SUM([AMT_INBOUND_FREIGHT_COST_EST_EUR])																													            AS [AMT_INBOUND_FREIGHT_COST_EST_EUR]
		,SUM(AMT_PO_CANCELLATION_EUR)																															                AS [AMT_PO_CANCELLATION_EST_EUR]
		,SUM(AMT_OTHER_COGS_EFFECTS_EST_EUR)																														            AS [AMT_OTHER_COSTS_EFFECTS_EST_EUR]
		----- first pl LINES							  
		,SUM(AMT_TURNOVER_EUR)																																            AS [AMT_TURNOVER_EUR]
		,SUM(VL_ORDER_QUANTITY)														                                                                                        AS [VL_ORDER_QUANTITY]
		,SUM(AMT_VALUE_ADDED_TAX_EUR)																																            AS [AMT_VALUE_ADDED_TAX_EUR]
		,SUM(AMT_NET_DISCOUNT_EUR)																															                AS [AMT_NET_DISCOUNT_EUR]
		,SUM(AMT_ORDER_CHARGES_EUR)																																    AS [AMT_ORDER_CHARGES_EUR]
		,SUM(AMT_GROSS_ORDER_VALUE_EUR)                                                                                                                             AS [AMT_GROSS_ORDER_VALUE_EUR]
		,SUM(FACT.VL_ITEM_QUANTITY)			                                                                                                                                   AS [VL_CANCELLED_ORDERS_QUANTITY_ACT] 
		,SUM(VL_CANCELLED_ORDERS_QUANTITY_EST)																												                    AS [VL_CANCELLED_ORDERS_QUANTITY_EST]	
		,CASE WHEN CD_SALES_TRANSACTION_CATEGORY = 'OrderCancellation' THEN -1*SUM(ISNULL(FACT.AMT_GROSS_PRICE_EUR,0)+ISNULL(FACT.AMT_NET_SHIPPING_REVENUE_EUR,0)-ISNULL(FACT.AMT_TAX_PRICE_EUR,0)-ABS(ISNULL(FACT.AMT_NET_DISCOUNT_EUR,0)))
		ELSE 0 END		                                                                                                                            AS [AMT_CANCELLED_ORDER_VALUE_ACT_EUR]
		,SUM(AMT_CANCELLED_ORDER_VALUE_EST_EUR)	                                                                                                                                AS [AMT_CANCELLED_ORDER_VALUE_EST_EUR]
		,SUM(FACT.VL_ITEM_QUANTITY)														                                                                                        AS [VL_NET_ORDER_QUANTITY_ACT]
		,SUM(VL_NET_ORDER_QUANTITY_EST)																			    AS [VL_NET_ORDER_QUANTITY_EST]
		,SUM(AMT_REPLACEMENT_PRODUCT_COST_EST_EUR)																														        AS AMT_REPLACEMENT_PRODUCT_COST_EST
		,SUM(VL_RETURNED_QUANTITY_EST)																															                AS AMT_RETURNED_QUANTITY_EST
		,SUM(AMT_REPLACEMENT_ORDER_QUANTITY_EST_EUR)																													        AS AMT_REPLACEMENT_ORDER_QUANTITY_EST
		,SUM(VL_REFUNDED_QUANTITY_EST)																															                AS AMT_REFUNDED_QUANTITY_EST
        ,SUM(CASE WHEN VL_ITEM_QUANTITY <> 0 
		THEN (((VL_NET_ORDER_QUANTITY_EST) * (ISNULL(FACT.AMT_MEK_HEDGING_EUR,0)-ISNULL(FACT.AMT_GTS_MARKUP,0)) )/ISNULL(FACT.VL_ITEM_QUANTITY,1)) 
		ELSE 0 END	)				                                                                                                                                            AS [AMT_NET_ORDER_QTY_PRODUCT_COST_EST_EUR]
		,SUM(CASE WHEN VL_ITEM_QUANTITY <> 0 
		THEN (((VL_REFUNDED_QUANTITY_EST) * (ISNULL(FACT.AMT_MEK_HEDGING_EUR,0)-ISNULL(FACT.AMT_GTS_MARKUP,0)) )/ISNULL(FACT.VL_ITEM_QUANTITY,1)) 
		ELSE 0 END	)                                                                                                                                           				AS [AMT_NET_REFUNDED_QTY_PRODUCT_COST_EST_EUR]
		----I/C First lines
		----I/C
		,SUM(CASE WHEN  (CD_CHANNEL_GROUP_1 ='Intercompany' OR CD_CHANNEL_GROUP_1 ='Mandanten') THEN AMT_TURNOVER_EUR ELSE 0 END)									                    AS [AMT_TURNOVER_INTERCOMPANY_EUR]
		,SUM( CASE WHEN (CD_CHANNEL_GROUP_1 ='Intercompany' OR CD_CHANNEL_GROUP_1 ='Mandanten') THEN VL_ORDER_QUANTITY  ELSE 0 END)														AS [VL_ORDER_QUANTITY_INTERCOMPANY]
		,SUM(CASE WHEN  (CD_CHANNEL_GROUP_1 ='Intercompany' OR CD_CHANNEL_GROUP_1 ='Mandanten') THEN AMT_VALUE_ADDED_TAX_EUR ELSE 0 END)							                    AS [AMT_VALUE_ADDED_TAX_INTERCOMPANY_EUR]
		,SUM(CASE WHEN  (CD_CHANNEL_GROUP_1 ='Intercompany' OR CD_CHANNEL_GROUP_1 ='Mandanten') THEN AMT_NET_DISCOUNT_EUR ELSE 0 END)							                    AS [AMT_NET_DISCOUNT_INTERCOMPANY_EUR]
		,SUM(CASE WHEN  (CD_CHANNEL_GROUP_1 ='Intercompany' OR CD_CHANNEL_GROUP_1 ='Mandanten') THEN AMT_ORDER_CHARGES_EUR ELSE 0 END)							                    AS [AMT_ORDER_CHARGES_INTERCOMPANY_EUR]
		,SUM(CASE WHEN  (CD_CHANNEL_GROUP_1 ='Intercompany' OR CD_CHANNEL_GROUP_1 ='Mandanten') THEN AMT_GROSS_ORDER_VALUE_EUR ELSE 0 END)						                    AS [AMT_GROSS_ORDER_VALUE_INTERCOMPANY_EUR]
		,SUM( CASE WHEN (CD_CHANNEL_GROUP_1 ='Intercompany' OR CD_CHANNEL_GROUP_1 ='Mandanten') THEN VL_ORDER_QUANTITY  ELSE 0 END)						                         AS [VL_CANCELLED_ORDERS_QUANTITY_INTERCOMPANY_ACT]
		,SUM( CASE WHEN  (CD_CHANNEL_GROUP_1 ='Intercompany' OR CD_CHANNEL_GROUP_1 ='Mandanten') THEN AMT_CANCELLED_ORDER_VALUE_EST_EUR  ELSE 0 END)					                 AS [AMT_CANCELLED_ORDER_VALUE_INTERCOMPANY_ACT_EUR]
		,SUM( CASE WHEN  (CD_CHANNEL_GROUP_1 ='Intercompany' OR CD_CHANNEL_GROUP_1 ='Mandanten') THEN FACT.VL_ITEM_QUANTITY  ELSE 0 END)						                        AS [VL_NET_ORDER_QUANTITY_INTERCOMPANY_ACT]
		,sum(AMT_NET_ORDER_VALUE_EST_EUR)			AS [AMT_NET_ORDER_VALUE_EST_EUR]
	
    FROM L1.L1_FACT_A_SALES_TRANSACTION_KPI FACT
	LEFT JOIN  [L1].L1_DIM_A_SALES_CHANNEL ch
    ON ch.ID_SALES_CHANNEL = FACT.ID_SALES_CHANNEL
	LEFT JOIN [L1].[L1_DIM_A_SALES_TRANSACTION_TYPE] type
	ON type.ID_SALES_TRANSACTION_TYPE = FACT.ID_SALES_TRANSACTION_TYPE
	LEFT JOIN [L1].[L1_DIM_A_COMPANY] comp
	ON comp.[ID_COMPANY] = FACT.[ID_COMPANY]
	WHERE FACT.CD_SOURCE_SYSTEM = 'SGE' 
	AND (fact.CD_SALES_PROCESS_ID = @PROCESSID or @PROCESSID ='')
	---add a condition to filter by refunds and orders
	AND [type].CD_SALES_TRANSACTION_CATEGORY in ('Order','OrderInvoice','Refund','OrderCancellation')
	GROUP BY FACT.CD_DOCUMENT_NO,FACT.CD_SALES_PROCESS_ID,MONTH(FACT.D_CREATED),YEAR(FACT.D_CREATED),CD_SALES_TRANSACTION_CATEGORY,FACT.[CD_SOURCE_SYSTEM],[CD_COMPANY],ch.ID_SALES_CHANNEL
		

)
INSERT INTO [WR].[WR_L1_FACT_F_SALES_FINANCE_RECONCILIATION]
 (
	D_EFFECTIVE
	 ,[CD_DOCUMENT_NO]
	,[CD_SALES_PROCESS_ID]
	,[CD_SOURCE_SYSTEM]
	,[NUM_POSTING_YEAR]
    ,[NUM_POSTING_PERIOD]
	,[CD_TYPE]
	,[CD_DOCUMENT_TYPE_FI]
	,[CD_COMPANY] 
	,[ID_SALES_CHANNEL]	
		---FIRST PL LINES
	,[AMT_TURNOVER_EUR]												
	,[VL_ORDER_QUANTITY]												
	,[AMT_VALUE_ADDED_TAX_EUR]										
	,[AMT_NET_DISCOUNT_EUR]											
	,[AMT_ORDER_CHARGES_EUR]											
	,[AMT_GROSS_ORDER_VALUE_EUR]										
	,[VL_CANCELLED_ORDERS_QUANTITY_ACT]								
	,[VL_CANCELLED_ORDERS_QUANTITY_EST]								
	,[AMT_CANCELLED_ORDER_VALUE_ACT_EUR]								
	,[AMT_CANCELLED_ORDER_VALUE_EST_EUR]								
	,[VL_NET_ORDER_QUANTITY_ACT]										
	,[VL_NET_ORDER_QUANTITY_EST]										
	,[AMT_NET_ORDER_VALUE_FI_EUR]	
	,[AMT_NET_ORDER_VALUE_INTERCOMPANY_FI_EUR]
	,[AMT_NET_ORDER_VALUE_ACT_EUR_INVOICED_IN_PERIOD]				
	,[AMT_NET_ORDER_VALUE_ACT_EUR_PRIOR_PERIODS]						
	,[AMT_NET_ORDER_VALUE_ACT_EUR_NOT_INVOICED]						
	,[AMT_NET_ORDER_VALUE_MANUAL_POSTING_FI_EUR]						
	,[AMT_NET_ORDER_VALUE_INTERCOMPANY_ACT_EUR]						
	,[AMT_NET_ORDER_VALUE_EST_EUR]									
	,[AMT_REFUNDED_ORDER_VALUE_FI_EUR]								
	,[AMT_REFUNDED_ORDER_VALUE_ACT_EUR_INVOICED_IN_PERIOD]			
	,[AMT_REFUNDED_ORDER_VALUE_ACT_EUR_PRIOR_PERIODS]				
	,[AMT_REFUNDED_ORDER_VALUE_ACT_EUR_NOT_INVOICED]					
	,[AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR_INVOICED_IN_PERIOD]
	,[AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR_PRIOR_PERIODS]	
	,[AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR_NOT_INVOICED]	
	,[AMT_REFUNDED_MANUAL_POSTING_FI_EUR]							
	,[AMT_REFUNDED_ORDER_VALUE_EST_EUR]								
	,[AMT_RETURN_ORDER_VALUE_EST_EUR]								
	,[AMT_REVENUE_MANUAL_POSTING_FI_EUR]								
	,[AMT_NET_PRODUCT_COST_FI_EUR]									
	,[AMT_NET_PRODUCT_COST_FI_RETURNS]								
	,[AMT_NET_PRODUCT_COST_FI_Z92]									
	,[AMT_NET_PRODUCT_COST_GTS_FI_EUR]								
	,[AMT_NET_PRODUCT_COST_GTS_FI_RETURNS_EUR]						
	,[AMT_NET_PRODUCT_COST_GTS_FI_Z92_EUR]							
	,[AMT_NET_PRODUCT_COST_ACT_EUR_INVOICED_IN_PERIOD]				
	,[AMT_NET_PRODUCT_COST_ACT_EUR_PRIOR_PERIODS]					
	,[AMT_NET_PRODUCT_COST_ACT_EUR_NOT_INVOICED]						
	,[AMT_NET_PRODUCT_COST_EST_EUR]									
	,[AMT_NET_PRODUCT_COST_INTERCOMPANY_ACT_EUR_INVOICED_IN_PERIOD]	
	,[AMT_NET_PRODUCT_COST_INTERCOMPANY_ACT_EUR_PRIOR_PERIODS]		
	,[AMT_NET_PRODUCT_COST_INTERCOMPANY_ACT_EUR_NOT_INVOICED]		
	,[AMT_NET_PRODUCT_COST_GTS_ACT_INVOICED_IN_PERIOD]				
	,[AMT_NET_PRODUCT_COST_GTS_ACT_PRIOR_PERIODS]					
	,[AMT_NET_PRODUCT_COST_GTS_ACT_NOT_INVOICED]						
	,[AMT_NET_PRODUCT_COST_GTS_INTERCOMPANY_ACT_INVOICED_IN_PERIOD]  
	,[AMT_NET_PRODUCT_COST_GTS_INTERCOMPANY_ACT_PRIOR_PERIODS]       
	,[AMT_NET_PRODUCT_COST_GTS_INTERCOMPANY_ACT_NOT_INVOICED]		
	,[AMT_FX_HEDGING_IMPACT_FI_EUR]									
	,[AMT_COGS_STOCK_ADJUSTMENTS_FI_EUR]										
	,[AMT_DEMURRAGE_DETENTION_FI_EUR]									
	,[AMT_DEADFREIGHT_FI_EUR]											
	,[AMT_KICKBACKS_FI_EUR]												
	,[AMT_3RD_PARTY_SERVICES_FI_EUR]										
	,[AMT_RMA_FI_EUR]													
	,[AMT_SAMPLES_FI_EUR]												
	,[AMT_DROPSHIPMENT_CEOTRA9ER_ARTIKEL_FI_EUR]							 
	,[AMT_INBOUND_FREIGHT_COST_FI_EUR]									
	,[AMT_PO_CANCELLATION_FI_EUR]										
	,[AMT_COGS_RECONCILIATION_FI_EUR]									
	,[AMT_OTHER_COSTS_EFFECTS_FI_EUR]									
	,[AMT_STOCK_VALUE_ADJUSTMENTS_FI_EUR]								
	,[AMT_FX_HEDGING_IMPACT_EST_EUR]										
	,[AMT_COGS_STOCK_ADJUSTMENTS_EST_EUR]								
	,[AMT_DEMURRAGE_DETENTION_EST_EUR]									
	,[AMT_DEADFREIGHT_EST_EUR]											
	,[AMT_KICKBACKS_EST_EUR]												
	,[AMT_3RD_PARTY_SERVICES_EST_EUR]									
	,[AMT_RMA_EST_EUR]													
	,[AMT_SAMPLES_EST_EUR]												
	,[AMT_DROPSHIPMENT_CEOTRA9ER_ARTIKEL_EST_EUR]						 
	,[AMT_INBOUND_FREIGHT_COST_EST_EUR]									
	,[AMT_PO_CANCELLATION_EST_EUR]       								
	,[AMT_OTHER_COSTS_EFFECTS_EST_EUR]									
	,[AMT_REPLACEMENT_PRODUCT_COST_EST]									
	,[AMT_RETURNED_QUANTITY_EST]											
	,[AMT_REPLACEMENT_ORDER_QUANTITY_EST]									
	,[AMT_REFUNDED_QUANTITY_EST]											
	,[VL_REFUNDED_QTY_WITHOUT_RETURNS_VALUE_FI]						
	,[VL_REFUNDED_QTY_VALUE_FI]										
	,[VL_REPLACEMENT_QTY_VALUE_FI]									
	,[AMT_NET_REFUNDED_QTY_PRODUCT_COST_EST_EUR]							
	,[AMT_NET_ORDER_QTY_PRODUCT_COST_EST_EUR]		
	,[AMT_TURNOVER_INTERCOMPANY_EUR]
	,[VL_ORDER_QUANTITY_INTERCOMPANY]
	,[AMT_VALUE_ADDED_TAX_INTERCOMPANY_EUR]
	,[AMT_NET_DISCOUNT_INTERCOMPANY_EUR]
	,[AMT_ORDER_CHARGES_INTERCOMPANY_EUR]
	,[AMT_GROSS_ORDER_VALUE_INTERCOMPANY_EUR]
	,[VL_CANCELLED_ORDERS_QUANTITY_INTERCOMPANY_ACT]
	,[AMT_CANCELLED_ORDER_VALUE_INTERCOMPANY_ACT_EUR]
	,[VL_NET_ORDER_QUANTITY_INTERCOMPANY_ACT]
    ,[DT_DWH_CREATED]
    ,[DT_DWH_UPDATED]
) -- end insert


/*****************************************************************************
** FIRST SELECT. It gets all the lines for SAGE FI
*****************************************************************************/

SELECT 
    CONCAT(@NUM_POSTING_YEAR,@NUM_POSTING_PERIOD) as D_EFFECTIVE
    ,[CD_DOCUMENT_NO]
	,CD_SALES_PROCESS_ID
	,[CD_SOURCE_SYSTEM]
	,[NUM_POSTING_YEAR]
	,[NUM_POSTING_PERIOD]
	,NULL as CD_TYPE
	,CD_DOCUMENT_TYPE_FI
	,[CD_COMPANY] 
	,ID_SALES_CHANNEL
	--,CASE WHEN CD_CHANNEL_GROUP_1 = 'Mandanten' THEN 'Intercompany' ELSE CD_CHANNEL_GROUP_1 END AS CD_CHANNEL_GROUP_1
	   ---FIRSL PL LINES
	,0 as [AMT_TURNOVER_EUR] 
	,0 as [VL_ORDER_QUANTITY] 				  
	,0 as [AMT_VALUE_ADDED_TAX_EUR] 			  
	,0 as [AMT_NET_DISCOUNT_EUR] 		  
	,0 as [AMT_ORDER_CHARGES_EUR] 			  
	,0 as [AMT_GROSS_ORDER_VALUE_EUR] 			  
	,0 as [VL_CANCELLED_ORDERS_QUANTITY_ACT] 	  
	,0 as [VL_CANCELLED_ORDERS_QUANTITY_EST] 		  
	,0 as [AMT_CANCELLED_ORDER_VALUE_ACT_EUR] 		  
	,0 as [AMT_CANCELLED_ORDER_VALUE_EST_EUR] 			  
	,0 as [VL_NET_ORDER_QUANTITY_ACT] 			  
	,0 as [VL_NET_ORDER_QUANTITY_EST] 
	---NOV
	,AMT_NET_ORDER_VALUE_FI_EUR
	,AMT_NET_ORDER_VALUE_INTERCOMPANY_FI_EUR
	,0																		AS AMT_NET_ORDER_VALUE_ACT_EUR_INVOICED_IN_PERIOD
	,0																		AS AMT_NET_ORDER_VALUE_ACT_EUR_PRIOR_PERIODS
	,0									                                    AS AMT_NET_ORDER_VALUE_ACT_EUR_NOT_INVOICED
	,0																		AS AMT_NET_ORDER_VALUE_MANUAL_POSTING_FI_EUR
	,0 as [AMT_NET_ORDER_VALUE_INTERCOMPANY_ACT_EUR]
	,0 as AMT_NET_ORDER_VALUE_EST_EUR
	--REFUNDS
	,AMT_REFUNDED_ORDER_VALUE_FI_EUR
	,0																		AS AMT_REFUNDED_ORDER_VALUE_ACT_EUR_INVOICED_IN_PERIOD
	,0																		AS AMT_REFUNDED_ORDER_VALUE_ACT_EUR_PRIOR_PERIODS
	,0  										                            AS AMT_REFUNDED_ORDER_VALUE_ACT_EUR_NOT_INVOICED
	,0																		AS AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR_INVOICED_IN_PERIOD
	,0																		AS AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR_PRIOR_PERIODS					
	,0 AS AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR_NOT_INVOICED
	,AMT_REFUNDED_MANUAL_POSTING_FI_EUR
	,0 as AMT_REFUNDED_ORDER_VALUE_EST_EUR
	--returns
	,0 as [AMT_RETURN_ORDER_VALUE_EST_EUR]
	--REVENUE
	,0 AS [AMT_REVENUE_MANUAL_POSTING_FI_EUR]
	--NET PRODUCT COST WITH GTS
	,0																		AS AMT_NET_PRODUCT_COST_FI_EUR
	,0																		AS AMT_NET_PRODUCT_COST_FI_RETURNS
	,0																		AS AMT_NET_PRODUCT_COST_FI_Z92
	--NET PRODUCT COST FI ONLY GTS
	,0																		AS AMT_NET_PRODUCT_COST_GTS_FI_EUR
	,0																		AS AMT_NET_PRODUCT_COST_GTS_FI_RETURNS_EUR
	,0																		AS AMT_NET_PRODUCT_COST_GTS_FI_Z92_EUR
    --NET PRODUCT COST
	,0																		AS AMT_NET_PRODUCT_COST_ACT_EUR_INVOICED_IN_PERIOD
	,0																		AS AMT_NET_PRODUCT_COST_ACT_EUR_PRIOR_PERIODS
	,0 											AS AMT_NET_PRODUCT_COST_ACT_EUR_NOT_INVOICED
	,0 as [AMT_NET_PRODUCT_COST_EST_EUR]
	 --NET PRODUCT COST I/C
	,0																		AS AMT_NET_PRODUCT_COST_INTERCOMPANY_ACT_EUR_INVOICED_IN_PERIOD
	,0																		AS AMT_NET_PRODUCT_COST_INTERCOMPANY_ACT_EUR_PRIOR_PERIODS
	,0 						AS AMT_NET_PRODUCT_COST_INTERCOMPANY_ACT_EUR_NOT_INVOICED
	 --NET PRODUCT COST ONLY GTS
	,0																		AS AMT_NET_PRODUCT_COST_GTS_ACT_INVOICED_IN_PERIOD
	,0																		AS AMT_NET_PRODUCT_COST_GTS_ACT_PRIOR_PERIODS
	,0 										AS AMT_NET_PRODUCT_COST_GTS_ACT_NOT_INVOICED
	 --NET PRODUCT COST ONLY GTS I/C
	,0																		AS AMT_NET_PRODUCT_COST_GTS_INTERCOMPANY_ACT_INVOICED_IN_PERIOD
	,0																		AS AMT_NET_PRODUCT_COST_GTS_INTERCOMPANY_ACT_PRIOR_PERIODS
	,0 							AS AMT_NET_PRODUCT_COST_GTS_INTERCOMPANY_ACT_NOT_INVOICED
	 --PC1 Lines
	,0																		AS [AMT_FX_HEDGING_IMPACT_FI_EUR]
	,0																		AS [AMT_COGS_STOCK_ADJUSTMENTS_FI_EUR]
	,0																		AS [AMT_DEMURRAGE_DETENTION_FI_EUR]
	,0																		AS [AMT_DEADFREIGHT_FI_EUR]
	,0																		AS [AMT_KICKBACKS_FI_EUR]
	,0																		AS [AMT_3RD_PARTY_SERVICES_FI_EUR]
	,0																		AS [AMT_RMA_FI_EUR]
	,0																		AS [AMT_SAMPLES_FI_EUR]
	,0																		AS [AMT_DROPSHIPMENT_CEOTRA9ER_ARTIKEL_FI_EUR]
	,0																		AS [AMT_INBOUND_FREIGHT_COST_FI_EUR]
	,0																		AS [AMT_PO_CANCELLATION_FI_EUR]
	,0																		AS [AMT_COGS_RECONCILIATION_FI_EUR]
	,0																		AS [AMT_OTHER_COSTS_EFFECTS_FI_EUR]
	,[AMT_STOCK_VALUE_ADJUSTMENTS_FI_EUR]
	,0 as [AMT_FX_HEDGING_IMPACT_EST_EUR]
	,0 as [AMT_COGS_STOCK_VALUE_ADJUSTMENT_EST_EUR]
	,0 as [AMT_DEMURRAGE_DETENTION_EST_EUR]
	,0 as [AMT_DEADFREIGHT_EST_EUR]
	,0 as [AMT_KICKBACKS_EST_EUR]
	,0 as [AMT_3RD_PARTY_SERVICES_EST_EUR]
	,0 as [AMT_RMA_EST_EUR]
	,0 as [AMT_SAMPLES_EST_EUR]
	,0 as [AMT_DROPSHIPMENT_CEOTRA9ER_ARTIKEL_EST_EUR]
	,0 as [AMT_INBOUND_FREIGHT_COST_EST_EUR]
	,0 as [AMT_PO_CANCELLATION_EST_EUR]
	,0 as [AMT_OTHER_COSTS_EFFECTS_EST_EUR]
	,0 as AMT_REPLACEMENT_PRODUCT_COST_EST
	,0 as AMT_RETURNED_QUANTITY_EST
	,0 as AMT_REPLACEMENT_ORDER_QUANTITY_EST
	,0 as AMT_REFUNDED_QUANTITY_EST
	,0                                                                      AS AMT_REFUNDED_QTY_WITHOUT_RETURNS_VALUE_FI_EUR
	,0                                                                      AS AMT_REFUNDED_QTY_VALUE_FI_EUR
	,0                                                                      AS AMT_REPLACEMENT_QTY_VALUE_FI_EUR
	,0 as AMT_NET_REFUNDED_QTY_PRODUCT_COST_EST_EUR
	,0 as AMT_NET_ORDER_QTY_PRODUCT_COST_EST_EUR
	,0 as [AMT_TURNOVER_INTERCOMPANY_EUEffathaR]
	,0 as [VL_ORDER_QUANTITY_INTERCOMPANY]
	,0 as [AMT_VALUE_ADDED_TAX_INTERCOMPANY_EUR]
	,0 as [AMT_NET_DISCOUNT_INTERCOMPANY_EUR]
	,0 as [AMT_ORDER_CHARGES_INTERCOMPANY_EUR]
	,0 as [AMT_GROSS_ORDER_VALUE_INTERCOMPANY_EUR]
	,0                                                                      AS [VL_CANCELLED_ORDERS_QUANTITY_INTERCOMPANY_ACT]
	,0 as [AMT_CANCELLED_ORDER_VALUE_INTERCOMPANY_ACT_EUR]
	,0                                                                      AS [VL_NET_ORDER_QUANTITY_INTERCOMPANY_ACT]
	,sysdatetime()															AS [DT_DWH_CREATED]
	,sysdatetime()															AS [DT_DWH_UPDATED]

from  CTE_BUCHUNGSJOURNAL

UNION

--/*****************************************************************************
--** SECOND SELECT. It gets all the PL lines from sales data  
--** which have a match in FI
--*****************************************************************************/
SELECT 
     
	CONCAT(@NUM_POSTING_YEAR,@NUM_POSTING_PERIOD) as D_EFFECTIVE
    ,sales.[CD_DOCUMENT_NO]
	,sales.CD_SALES_PROCESS_ID
	,sales.[CD_SOURCE_SYSTEM]
	,@NUM_POSTING_YEAR  as [NUM_POSTING_YEAR]
	,@NUM_POSTING_PERIOD as [NUM_POSTING_PERIOD]
	,CD_TYPE
	,NULL AS FI_DOCUMENT_TYPE
	,sales.[CD_COMPANY] 
	,sales.ID_SALES_CHANNEL
	--,CASE WHEN sales.CD_CHANNEL_GROUP_1 = 'Mandanten' THEN 'Intercompany' ELSE sales.CD_CHANNEL_GROUP_1 END AS CD_CHANNEL_GROUP_1
	   ---FIRSL PL LINES
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_TURNOVER_EUR] 		                          ELSE 0 END AS	AMT_TURNOVER_EUR			  
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[VL_ORDER_QUANTITY] 				              ELSE 0 END AS VL_ORDER_QUANTITY
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_VALUE_ADDED_TAX_EUR] 			  			  ELSE 0 END AS AMT_VALUE_ADDED_TAX_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_NET_DISCOUNT_EUR] 		  					  ELSE 0 END AS AMT_NET_DISCOUNT_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_ORDER_CHARGES_EUR] 			  			  ELSE 0 END AS AMT_ORDER_CHARGES_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_GROSS_ORDER_VALUE_EUR] 			  		  ELSE 0 END AS AMT_GROSS_ORDER_VALUE_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[VL_CANCELLED_ORDERS_QUANTITY_ACT] 	  			  ELSE 0 END AS VL_CANCELLED_ORDERS_QUANTITY_ACT
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[VL_CANCELLED_ORDERS_QUANTITY_EST] 		  		  ELSE 0 END AS VL_CANCELLED_ORDERS_QUANTITY_EST
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_CANCELLED_ORDER_VALUE_ACT_EUR] 		  	  ELSE 0 END AS AMT_CANCELLED_ORDER_VALUE_ACT_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_CANCELLED_ORDER_VALUE_EST_EUR] 			  ELSE 0 END AS AMT_CANCELLED_ORDER_VALUE_EST_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[VL_NET_ORDER_QUANTITY_ACT] 			  		  ELSE 0 END AS VL_NET_ORDER_QUANTITY_ACT
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[VL_NET_ORDER_QUANTITY_EST] 					  ELSE 0 END AS VL_NET_ORDER_QUANTITY_EST
	---NOV
	,0																		AS AMT_NET_ORDER_VALUE_FI_EUR
	,0																		AS AMT_NET_ORDER_VALUE_INTERCOMPANY_FI_EUR
	,CASE 	WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD and isnull(fi_values.AMT_NET_ORDER_VALUE_FI_EUR,0) <> 0 THEN	sales.[AMT_NET_ORDER_VALUE_ACT_EUR]		
			ELSE 0 END																																						AS AMT_NET_ORDER_VALUE_ACT_EUR_INVOICED_IN_PERIOD


	,CASE WHEN ((sales.NUM_POSTING_YEAR<@NUM_POSTING_YEAR) OR (sales.NUM_POSTING_YEAR = @NUM_POSTING_YEAR 	      
					and sales.NUM_POSTING_PERIOD < @NUM_POSTING_PERIOD)) and isnull(fi_values.AMT_NET_ORDER_VALUE_FI_EUR,0) <> 0 THEN sales.[AMT_NET_ORDER_VALUE_ACT_EUR] ELSE 0 END	 AS AMT_NET_ORDER_VALUE_ACT_EUR_PRIOR_PERIODS



	,0									AS AMT_NET_ORDER_VALUE_ACT_EUR_NOT_INVOICED
	,0									AS AMT_NET_ORDER_VALUE_MANUAL_POSTING_FI_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD and fi_values.AMT_NET_ORDER_VALUE_FI_EUR <> 0    THEN sales.[AMT_NET_ORDER_VALUE_INTERCOMPANY_ACT_EUR] ELSE 0 END AS [AMT_NET_ORDER_VALUE_INTERCOMPANY_ACT_EUR]
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD and fi_values.AMT_NET_ORDER_VALUE_FI_EUR <> 0   THEN AMT_NET_ORDER_VALUE_EST_EUR ELSE 0 END AS AMT_NET_ORDER_VALUE_EST_EUR
	--REFUNDS
	,0 as AMT_REFUNDED_ORDER_VALUE_FI_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN	sales.[AMT_REFUNDED_ORDER_VALUE_ACT_EUR]		ELSE 0 END		AS AMT_REFUNDED_ORDER_VALUE_ACT_EUR_INVOICED_IN_PERIOD
	,CASE WHEN (sales.NUM_POSTING_YEAR<@NUM_POSTING_YEAR) OR (sales.NUM_POSTING_YEAR = @NUM_POSTING_YEAR	      
					and sales.NUM_POSTING_PERIOD <@NUM_POSTING_PERIOD) THEN sales.[AMT_REFUNDED_ORDER_VALUE_ACT_EUR] ELSE 0 END			 							AS AMT_REFUNDED_ORDER_VALUE_ACT_EUR_PRIOR_PERIODS
	,0  										                            AS AMT_REFUNDED_ORDER_VALUE_ACT_EUR_NOT_INVOICED
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN	sales.AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR	ELSE 0 END	AS AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR_INVOICED_IN_PERIOD
	,CASE WHEN (sales.NUM_POSTING_YEAR<@NUM_POSTING_YEAR) OR (sales.NUM_POSTING_YEAR = @NUM_POSTING_YEAR	      
					and sales.NUM_POSTING_PERIOD <@NUM_POSTING_PERIOD) THEN sales.AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR	ELSE 0 END								AS AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR_PRIOR_PERIODS
	,0                                              						AS AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR_NOT_INVOICED
	,0 AS AMT_REFUNDED_MANUAL_POSTING_FI_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.AMT_REFUNDED_ORDER_VALUE_EST_EUR ELSE 0 END AS AMT_REFUNDED_ORDER_VALUE_EST_EUR
	--returns
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_RETURN_ORDER_VALUE_EST_EUR] ELSE 0 END AS AMT_RETURN_ORDER_VALUE_EST_EUR
	--REVENUE
	,0 AS [AMT_REVENUE_MANUAL_POSTING_FI_EUR]
	--NET PRODUCT COST WITH GTS
	,0																		AS AMT_NET_PRODUCT_COST_FI_EUR
	,0																		AS AMT_NET_PRODUCT_COST_FI_RETURNS
	,0																		AS AMT_NET_PRODUCT_COST_FI_Z92
	--NET PRODUCT COST FI ONLY GTS
	,0																		AS AMT_NET_PRODUCT_COST_GTS_FI_EUR
	,0																		AS AMT_NET_PRODUCT_COST_GTS_FI_RETURNS_EUR
	,0																		AS AMT_NET_PRODUCT_COST_GTS_FI_Z92_EUR
    --NET PRODUCT COST
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.AMT_NET_PRODUCT_COST_ACT_EUR ELSE 0 END AS AMT_NET_PRODUCT_COST_ACT_EUR_INVOICED_IN_PERIOD
	,CASE WHEN (sales.NUM_POSTING_YEAR<@NUM_POSTING_YEAR) OR (sales.NUM_POSTING_YEAR = @NUM_POSTING_YEAR	      
					and sales.NUM_POSTING_PERIOD <@NUM_POSTING_PERIOD) THEN sales.AMT_NET_PRODUCT_COST_ACT_EUR	ELSE 0 END																	AS AMT_NET_PRODUCT_COST_ACT_EUR_PRIOR_PERIODS
	,0										                                AS AMT_NET_PRODUCT_COST_ACT_EUR_NOT_INVOICED
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_NET_PRODUCT_COST_EST_EUR] ELSE 0 END AS MT_NET_PRODUCT_COST_EST_EUR
	 --NET PRODUCT COST I/C
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.AMT_NET_PRODUCT_COST_INTERCOMPANY_ACT_EUR ELSE 0 END	AS AMT_NET_PRODUCT_COST_INTERCOMPANY_ACT_EUR_INVOICED_IN_PERIOD
	,CASE WHEN (sales.NUM_POSTING_YEAR<@NUM_POSTING_YEAR) OR (sales.NUM_POSTING_YEAR = @NUM_POSTING_YEAR	      
					and sales.NUM_POSTING_PERIOD <@NUM_POSTING_PERIOD) THEN sales.AMT_NET_PRODUCT_COST_INTERCOMPANY_ACT_EUR		 ELSE 0 END							AS AMT_NET_PRODUCT_COST_INTERCOMPANY_ACT_EUR_PRIOR_PERIODS
	,0								AS AMT_NET_PRODUCT_COST_INTERCOMPANY_ACT_EUR_NOT_INVOICED
	 --NET PRODUCT COST ONLY GTS
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.AMT_NET_PRODUCT_COST_GTS_ACT ELSE 0 END			AS AMT_NET_PRODUCT_COST_GTS_ACT_INVOICED_IN_PERIOD
	,CASE WHEN (sales.NUM_POSTING_YEAR<@NUM_POSTING_YEAR) OR (sales.NUM_POSTING_YEAR = @NUM_POSTING_YEAR	      
					and sales.NUM_POSTING_PERIOD <@NUM_POSTING_PERIOD) THEN sales.AMT_NET_PRODUCT_COST_GTS_ACT 		ELSE 0 END											 AS AMT_NET_PRODUCT_COST_GTS_ACT_PRIOR_PERIODS
	,0										                                                                                                                    AS AMT_NET_PRODUCT_COST_GTS_ACT_NOT_INVOICED
	 --NET PRODUCT COST ONLY GTS I/C
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.AMT_NET_PRODUCT_COST_INTERCOMPANY_GTS_ACT ELSE 0 END	AS AMT_NET_PRODUCT_COST_GTS_INTERCOMPANY_ACT_INVOICED_IN_PERIOD
	,CASE WHEN (sales.NUM_POSTING_YEAR<@NUM_POSTING_YEAR) OR (sales.NUM_POSTING_YEAR = @NUM_POSTING_YEAR	      
					and sales.NUM_POSTING_PERIOD <@NUM_POSTING_PERIOD) THEN sales.AMT_NET_PRODUCT_COST_INTERCOMPANY_GTS_ACT		 ELSE 0 END														AS AMT_NET_PRODUCT_COST_GTS_INTERCOMPANY_ACT_PRIOR_PERIODS
	,0							AS AMT_NET_PRODUCT_COST_GTS_INTERCOMPANY_ACT_NOT_INVOICED
	 --PC1 Lines
	,0  																    AS [AMT_FX_HEDGING_IMPACT_FI_EUR]
	,0																		AS [AMT_COGS_STOCK_ADJUSTMENTS_FI_EUR]
	,0																		AS [AMT_DEMURRAGE_DETENTION_FI_EUR]
	,0																		AS [AMT_DEADFREIGHT_FI_EUR]
	,0																		AS [AMT_KICKBACKS_FI_EUR]
	,0																		AS [AMT_3RD_PARTY_SERVICES_FI_EUR]
	,0																		AS [AMT_RMA_FI_EUR]
	,0																		AS [AMT_SAMPLES_FI_EUR]
	,0																		AS [AMT_DROPSHIPMENT_CEOTRA9ER_ARTIKEL_FI_EUR]
	,0																		AS [AMT_INBOUND_FREIGHT_COST_FI_EUR]
	,0																		AS [AMT_PO_CANCELLATION_FI_EUR]
	,0																		AS [AMT_COGS_RECONCILIATION_FI_EUR]
	,0																		AS [AMT_OTHER_COSTS_EFFECTS_FI_EUR]
	,0																		AS [AMT_STOCK_VALUE_ADJUSTMENTS_FI_EUR]
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_FX_HEDGING_IMPACT_EST_EUR]                ELSE 0 END AS AMT_FX_HEDGING_IMPACT_EST_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_COGS_STOCK_VALUE_ADJUSTMENT_EST_EUR]	       ELSE 0 END AS AMT_COGS_STOCK_ADJUSTMENTS_EST_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_DEMURRAGE_DETENTION_EST_EUR]			   ELSE 0 END AS AMT_DEMURRAGE_DETENTION_EST_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_DEADFREIGHT_EST_EUR]					   ELSE 0 END AS AMT_DEADFREIGHT_EST_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_KICKBACKS_EST_EUR]						   ELSE 0 END AS AMT_KICKBACKS_EST_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_3RD_PARTY_SERVICES_EST_EUR]			   ELSE 0 END AS AMT_3RD_PARTY_SERVICES_EST_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_RMA_EST_EUR]							   ELSE 0 END AS AMT_RMA_EST_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_SAMPLES_EST_EUR]						   ELSE 0 END AS AMT_SAMPLES_EST_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_DROPSHIPMENT_CEOTRA9ER_ARTIKEL_EST_EUR]   ELSE 0 END AS AMT_DROPSHIPMENT_CEOTRA9ER_ARTIKEL_EST_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_INBOUND_FREIGHT_COST_EST_EUR]			   ELSE 0 END AS AMT_INBOUND_FREIGHT_COST_EST_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_PO_CANCELLATION_EST_EUR]				   ELSE 0 END AS AMT_PO_CANCELLATION_EST_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_OTHER_COSTS_EFFECTS_EST_EUR]			   ELSE 0 END AS AMT_OTHER_COSTS_EFFECTS_EST_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.AMT_REPLACEMENT_PRODUCT_COST_EST			   ELSE 0 END AS AMT_REPLACEMENT_PRODUCT_COST_EST
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.AMT_RETURNED_QUANTITY_EST					   ELSE 0 END AS AMT_RETURNED_QUANTITY_EST
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.AMT_REPLACEMENT_ORDER_QUANTITY_EST			   ELSE 0 END AS AMT_REPLACEMENT_ORDER_QUANTITY_EST	
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.AMT_REFUNDED_QUANTITY_EST       			   ELSE 0 END AS AMT_REFUNDED_QUANTITY_EST
	,0                                                                      AS AMT_REFUNDED_QTY_WITHOUT_RETURNS_VALUE_FI_EUR											   
	,0                                                                      AS AMT_REFUNDED_QTY_VALUE_FI_EUR
	,0                                                                      AS AMT_REPLACEMENT_QTY_VALUE_FI_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.AMT_NET_REFUNDED_QTY_PRODUCT_COST_EST_EUR             ELSE 0 END AS AMT_NET_REFUNDED_QTY_PRODUCT_COST_EST_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.AMT_NET_ORDER_QTY_PRODUCT_COST_EST_EUR				  ELSE 0 END AS AMT_NET_ORDER_QTY_PRODUCT_COST_EST_EUR	
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_TURNOVER_INTERCOMPANY_EUR]						  ELSE 0 END AS AMT_TURNOVER_INTERCOMPANY_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[VL_ORDER_QUANTITY_INTERCOMPANY]					  ELSE 0 END AS VL_ORDER_QUANTITY_INTERCOMPANY
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_VALUE_ADDED_TAX_INTERCOMPANY_EUR]				  ELSE 0 END AS AMT_VALUE_ADDED_TAX_INTERCOMPANY_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_NET_DISCOUNT_INTERCOMPANY_EUR]					  ELSE 0 END AS AMT_NET_DISCOUNT_INTERCOMPANY_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_ORDER_CHARGES_INTERCOMPANY_EUR]				  ELSE 0 END AS AMT_ORDER_CHARGES_INTERCOMPANY_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_GROSS_ORDER_VALUE_INTERCOMPANY_EUR]			  ELSE 0 END AS AMT_GROSS_ORDER_VALUE_INTERCOMPANY_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[VL_CANCELLED_ORDERS_QUANTITY_INTERCOMPANY_ACT]		  ELSE 0 END AS VL_CANCELLED_ORDERS_QUANTITY_INTERCOMPANY_ACT
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[AMT_CANCELLED_ORDER_VALUE_INTERCOMPANY_ACT_EUR]	  ELSE 0 END AS AMT_CANCELLED_ORDER_VALUE_INTERCOMPANY_ACT_EUR
	,CASE WHEN sales.[NUM_POSTING_YEAR] = @NUM_POSTING_YEAR and sales.[NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD THEN sales.[VL_NET_ORDER_QUANTITY_INTERCOMPANY_ACT]			  ELSE 0 END AS VL_NET_ORDER_QUANTITY_INTERCOMPANY_ACT
	,sysdatetime()															AS [DT_DWH_CREATED]
	,sysdatetime()															AS [DT_DWH_UPDATED]

FROM CTE_SALES_ORDERS sales
INNER JOIN 
		(
			SELECT CD_Sales_process_id,sum(AMT_NET_ORDER_VALUE_FI_EUR)AMT_NET_ORDER_VALUE_FI_EUR ,sum(AMT_REFUNDED_ORDER_VALUE_FI_EUR) AMT_REFUNDED_ORDER_VALUE_FI_EUR  FROM CTE_BUCHUNGSJOURNAL GROUP BY CD_Sales_process_id
		) fi_values
		on sales.CD_Sales_process_id = fi_values.CD_Sales_process_id
WHERE --sales.CD_Sales_process_id  in (SELECT DISTINCT CD_Sales_process_id FROM CTE_BUCHUNGSJOURNAL)
1=1
AND sales.[NUM_POSTING_YEAR] <= @NUM_POSTING_YEAR 
AND ((sales.NUM_POSTING_YEAR<@NUM_POSTING_YEAR) OR (sales.NUM_POSTING_YEAR =@NUM_POSTING_YEAR	 and sales.NUM_POSTING_PERIOD <=@NUM_POSTING_PERIOD))

UNION
--/*****************************************************************************
--** THIRD SELECT. It gets all the PL lines from sales data  
--** which do not have a match in FI
--*****************************************************************************/
SELECT 
     
	CONCAT(@NUM_POSTING_YEAR,@NUM_POSTING_PERIOD) as D_EFFECTIVE
    ,sales.[CD_DOCUMENT_NO]
	,CD_SALES_PROCESS_ID
	,sales.[CD_SOURCE_SYSTEM]
    ,@NUM_POSTING_YEAR  as [NUM_POSTING_YEAR]
	,@NUM_POSTING_PERIOD as [NUM_POSTING_PERIOD]
	,CD_TYPE
	,NULL AS FI_DOCUMENT_TYPE
	,sales.[CD_COMPANY] 
	,sales.ID_SALES_CHANNEL

	--,CASE WHEN sales.CD_CHANNEL_GROUP_1 = 'Mandanten' THEN 'Intercompany' ELSE sales.CD_CHANNEL_GROUP_1 END AS CD_CHANNEL_GROUP_1
	   ---FIRSL PL LINES
	,sales.[AMT_TURNOVER_EUR] 					  
	,sales.[VL_ORDER_QUANTITY] 				  
	,sales.[AMT_VALUE_ADDED_TAX_EUR] 			  
	,sales.[AMT_NET_DISCOUNT_EUR] 		  
	,sales.[AMT_ORDER_CHARGES_EUR] 			  
	,sales.[AMT_GROSS_ORDER_VALUE_EUR] 			  
	,sales.[VL_CANCELLED_ORDERS_QUANTITY_ACT] 	  
	,sales.[VL_CANCELLED_ORDERS_QUANTITY_EST] 		  
	,sales.[AMT_CANCELLED_ORDER_VALUE_ACT_EUR] 		  
	,sales.[AMT_CANCELLED_ORDER_VALUE_EST_EUR] 			  
	,sales.[VL_NET_ORDER_QUANTITY_ACT] 			  
	,sales.[VL_NET_ORDER_QUANTITY_EST] 
	---NOV
	,0																		AS AMT_NET_ORDER_VALUE_FI_EUR
	,0																		AS AMT_NET_ORDER_VALUE_INTERCOMPANY_FI_EUR
	,0	AS AMT_NET_ORDER_VALUE_ACT_EUR_INVOICED_IN_PERIOD
	,0	AS AMT_NET_ORDER_VALUE_ACT_EUR_PRIOR_PERIODS
	,AMT_NET_ORDER_VALUE_ACT_EUR									AS AMT_NET_ORDER_VALUE_ACT_EUR_NOT_INVOICED
	,0																		AS AMT_NET_ORDER_VALUE_MANUAL_POSTING_FI_EUR
	,[AMT_NET_ORDER_VALUE_INTERCOMPANY_ACT_EUR]
	,AMT_NET_ORDER_VALUE_EST_EUR
	--REFUNDS
	,0 as AMT_REFUNDED_ORDER_VALUE_FI_EUR
	,0	AS AMT_REFUNDED_ORDER_VALUE_ACT_EUR_INVOICED_IN_PERIOD
	,0	AS AMT_REFUNDED_ORDER_VALUE_ACT_EUR_PRIOR_PERIODS
	,sales.[AMT_REFUNDED_ORDER_VALUE_ACT_EUR]  AS AMT_REFUNDED_ORDER_VALUE_ACT_EUR_NOT_INVOICED
	,0																		AS AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR_INVOICED_IN_PERIOD
	,0																		AS AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR_PRIOR_PERIODS
	,[AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR]						AS AMT_REFUNDED_INTERCOMPANY_ORDER_VALUE_ACT_EUR_NOT_INVOICED
	,0 AS AMT_REFUNDED_MANUAL_POSTING_FI_EUR
	,AMT_REFUNDED_ORDER_VALUE_EST_EUR
	--returns
	,[AMT_RETURN_ORDER_VALUE_EST_EUR]
	--REVENUE
	,0 AS [AMT_REVENUE_MANUAL_POSTING_FI_EUR]
	--NET PRODUCT COST WITH GTS
	,0																		AS AMT_NET_PRODUCT_COST_FI_EUR
	,0																		AS AMT_NET_PRODUCT_COST_FI_RETURNS
	,0																		AS AMT_NET_PRODUCT_COST_FI_Z92
	--NET PRODUCT COST FI ONLY GTS
	,0																		AS AMT_NET_PRODUCT_COST_GTS_FI_EUR
	,0																		AS AMT_NET_PRODUCT_COST_GTS_FI_RETURNS_EUR
	,0																		AS AMT_NET_PRODUCT_COST_GTS_FI_Z92_EUR
    --NET PRODUCT COST
	,0																		AS AMT_NET_PRODUCT_COST_ACT_EUR_INVOICED_IN_PERIOD
	,0																		AS AMT_NET_PRODUCT_COST_ACT_EUR_PRIOR_PERIODS
	,[AMT_NET_PRODUCT_COST_ACT_EUR]											AS AMT_NET_PRODUCT_COST_ACT_EUR_NOT_INVOICED
	,[AMT_NET_PRODUCT_COST_EST_EUR]
	 --NET PRODUCT COST I/C
	,0																		AS AMT_NET_PRODUCT_COST_INTERCOMPANY_ACT_EUR_INVOICED_IN_PERIOD
	,0																		AS AMT_NET_PRODUCT_COST_INTERCOMPANY_ACT_EUR_PRIOR_PERIODS
	,AMT_NET_PRODUCT_COST_INTERCOMPANY_ACT_EUR								AS AMT_NET_PRODUCT_COST_INTERCOMPANY_ACT_EUR_NOT_INVOICED
	 --NET PRODUCT COST ONLY GTS
	,0																		AS AMT_NET_PRODUCT_COST_GTS_ACT_INVOICED_IN_PERIOD
	,0																		AS AMT_NET_PRODUCT_COST_GTS_ACT_PRIOR_PERIODS
	,[AMT_NET_PRODUCT_COST_GTS_ACT]											AS AMT_NET_PRODUCT_COST_GTS_ACT_NOT_INVOICED
	 --NET PRODUCT COST ONLY GTS I/C
	,0																		AS AMT_NET_PRODUCT_COST_GTS_INTERCOMPANY_ACT_INVOICED_IN_PERIOD
	,0																		AS AMT_NET_PRODUCT_COST_GTS_INTERCOMPANY_ACT_PRIOR_PERIODS
	,AMT_NET_PRODUCT_COST_INTERCOMPANY_ACT_EUR								AS AMT_NET_PRODUCT_COST_GTS_INTERCOMPANY_ACT_NOT_INVOICED
	 --PC1 Lines
	,0																		AS [AMT_FX_HEDGING_IMPACT_FI_EUR]
	,0																		AS [AMT_COGS_STOCK_ADJUSTMENTS_FI_EUR]
	,0																		AS [AMT_DEMURRAGE_DETENTION_FI_EUR]
	,0																		AS [AMT_DEADFREIGHT_FI_EUR]
	,0																		AS [AMT_KICKBACKS_FI_EUR]
	,0																		AS [AMT_3RD_PARTY_SERVICES_FI_EUR]
	,0																		AS [AMT_RMA_FI_EUR]
	,0																		AS [AMT_SAMPLES_FI_EUR]
	,0																		AS [AMT_DROPSHIPMENT_CEOTRA9ER_ARTIKEL_FI_EUR]
	,0																		AS [AMT_INBOUND_FREIGHT_COST_FI_EUR]
	,0																		AS [AMT_PO_CANCELLATION_FI_EUR]
	,0																		AS [AMT_COGS_RECONCILIATION_FI_EUR]
	,0																		AS [AMT_OTHER_COSTS_EFFECTS_FI_EUR]
	,0																		AS [AMT_STOCK_VALUE_ADJUSTMENTS_FI_EUR]
	,[AMT_FX_HEDGING_IMPACT_EST_EUR]
	,[AMT_COGS_STOCK_VALUE_ADJUSTMENT_EST_EUR]
	,[AMT_DEMURRAGE_DETENTION_EST_EUR]
	,[AMT_DEADFREIGHT_EST_EUR]
	,[AMT_KICKBACKS_EST_EUR]
	,[AMT_3RD_PARTY_SERVICES_EST_EUR]
	,[AMT_RMA_EST_EUR]
	,[AMT_SAMPLES_EST_EUR]
	,[AMT_DROPSHIPMENT_CEOTRA9ER_ARTIKEL_EST_EUR]
	,[AMT_INBOUND_FREIGHT_COST_EST_EUR]
	,[AMT_PO_CANCELLATION_EST_EUR]
	,[AMT_OTHER_COSTS_EFFECTS_EST_EUR]
	,AMT_REPLACEMENT_PRODUCT_COST_EST
	,AMT_RETURNED_QUANTITY_EST
	,AMT_REPLACEMENT_ORDER_QUANTITY_EST
	,AMT_REFUNDED_QUANTITY_EST
	,0                                                                      AS AMT_REFUNDED_QTY_WITHOUT_RETURNS_VALUE_FI_EUR
	,0                                                                      AS AMT_REFUNDED_QTY_VALUE_FI_EUR
	,0                                                                      AS AMT_REPLACEMENT_QTY_VALUE_FI_EUR
	,AMT_NET_REFUNDED_QTY_PRODUCT_COST_EST_EUR
	,AMT_NET_ORDER_QTY_PRODUCT_COST_EST_EUR
	,[AMT_TURNOVER_INTERCOMPANY_EUR]
	,[VL_ORDER_QUANTITY_INTERCOMPANY]
	,[AMT_VALUE_ADDED_TAX_INTERCOMPANY_EUR]
	,[AMT_NET_DISCOUNT_INTERCOMPANY_EUR]
	,[AMT_ORDER_CHARGES_INTERCOMPANY_EUR]
	,[AMT_GROSS_ORDER_VALUE_INTERCOMPANY_EUR]
	,[VL_CANCELLED_ORDERS_QUANTITY_INTERCOMPANY_ACT]
	,[AMT_CANCELLED_ORDER_VALUE_INTERCOMPANY_ACT_EUR]
	,[VL_NET_ORDER_QUANTITY_INTERCOMPANY_ACT]
	,sysdatetime()															AS [DT_DWH_CREATED]
	,sysdatetime()															AS [DT_DWH_UPDATED]

FROM CTE_SALES_ORDERS sales
WHERE sales.CD_Sales_process_id NOT IN (SELECT DISTINCT ISNULL(CD_Sales_process_id,0) FROM  CTE_BUCHUNGSJOURNAL)
AND [NUM_POSTING_YEAR] = @NUM_POSTING_YEAR
AND [NUM_POSTING_PERIOD] = @NUM_POSTING_PERIOD	
