with cte_fc_shares as 
(
	SELECT 
		NUM_ITEM,
		CD_CHANNEL_GROUP_3,
		CD_COUNTRY_GROUP,
		VL_ITEM_QUANTITY = SUM(VL_ITEM_QUANTITY),
		AMT_TOTAL_QUANTITY = SUM(SUM(VL_ITEM_QUANTITY)) over(partition by NUM_ITEM),
		ChannelShare = SUM(VL_ITEM_QUANTITY) / SUM(SUM(VL_ITEM_QUANTITY)) over(partition by NUM_ITEM)
	FROM L1.L1_FACT_F_BOTTOM_LINE_FORECAST
	where 
	NUM_ITEM = '10000164'
	and YEAR(D_TARGET) = 2025
	and MONTH(D_TARGET) = 9
	GROUP BY CD_CHANNEL_GROUP_3,NUM_ITEM,CD_COUNTRY_GROUP

)
SELECT
		NUM_ITEM,
		CD_CHANNEL_GROUP_3,
		CD_COUNTRY_GROUP,
		fc.REALIZABLEFCQTYSEP25,
		VL_ITEM_QUANTITY = REALIZABLEFCQTYSEP25 *ChannelShare ,
		AMT_NET_ORDER_VALUE_EUR = (REALIZABLEFCQTYSEP25 *ChannelShare) * PLANPRICE,
		AMT_PLAN_PRICE_EUR = PLANPRICE
FROM L0.L0_MI_REALIZABLE_FC_25 fc
INNER JOIN cte_fc_shares sh
	on fc.ItemNo = sh.NUM_ITEM





	

;with cte_fc_shares as 
(
	SELECT 
		ID_ITEM,
		NUM_ITEM,
		CD_CHANNEL_GROUP_3,
		CD_CHANNEL_GROUP_1,
		CD_COUNTRY_GROUP,
		VL_ITEM_QUANTITY = SUM(VL_ITEM_QUANTITY),
		AMT_TOTAL_QUANTITY = SUM(SUM(VL_ITEM_QUANTITY)) over(partition by NUM_ITEM),
		ChannelShare = SUM(VL_ITEM_QUANTITY) / SUM(SUM(VL_ITEM_QUANTITY)) over(partition by NUM_ITEM)
	FROM L1.L1_FACT_F_BOTTOM_LINE_FORECAST
	where 1=1
	--NUM_ITEM = '10000164'
	and YEAR(D_TARGET) = 2025
	and MONTH(D_TARGET) = 9
	GROUP BY CD_CHANNEL_GROUP_3,NUM_ITEM,CD_COUNTRY_GROUP,CD_CHANNEL_GROUP_1,ID_ITEM

), cte_fc as 
(
	SELECT
			NUM_ITEM,ID_ITEM,
			CD_CHANNEL_GROUP_3,CD_CHANNEL_GROUP_1,
			CD_COUNTRY_GROUP,
			fc.REALIZABLEFCQTYSEP25,
			VL_ITEM_QUANTITY = REALIZABLEFCQTYSEP25 *ChannelShare ,
			AMT_NET_ORDER_VALUE_EUR = (REALIZABLEFCQTYSEP25 *ChannelShare) * PLANPRICE,
			[AMT_PLAN_PRICE_EUR] = PLANPRICE
	FROM L0.L0_MI_REALIZABLE_FC_25 fc
	INNER JOIN cte_fc_shares sh
		on fc.ItemNo = sh.NUM_ITEM

)
INSERT INTO [L1].L1_FACT_F_BOTTOM_LINE__REALIZABLE_FORECAST_25
(
	
	    [D_TARGET], 
	    [ID_ITEM],
		[NUM_ITEM],
        [CD_CHANNEL_GROUP_3],
		[CD_CHANNEL_GROUP_1],
	    [CD_COUNTRY_GROUP],
        [AMT_PLAN_PRICE_EUR],
        [VL_ITEM_QUANTITY],
        [AMT_TARGET_NET_ORDER_VALUE_EUR],
        [DT_DWH_CREATED],
        [DT_DWH_UPDATED] 
)

SELECT                                    
       D_TARGET = run_rates.DATE_ADJUSTED 
	  ,b_plan.[ID_ITEM]
	  ,b_plan.[NUM_ITEM]
      ,b_plan.[CD_CHANNEL_GROUP_3]
	  ,b_plan.[CD_CHANNEL_GROUP_1]
	  ,b_plan.[CD_COUNTRY_GROUP]
      ,b_plan.[AMT_PLAN_PRICE_EUR]
      ,[VL_ITEM_QUANTITY] = [VL_ITEM_QUANTITY] *  ISNULL(CAST(run_rates.rr as decimal(19,9)) ,1)
      ,[AMT_TARGET_NET_ORDER_VALUE_EUR] = AMT_NET_ORDER_VALUE_EUR *  ISNULL(CAST(run_rates.rr as decimal(19,9)) ,1)
      ,sysdatetime() as [DT_DWH_CREATED]
      ,sysdatetime() as [DT_DWH_UPDATED]
	
	from cte_fc b_plan
	LEFT JOIN L1.L1_DIM_A_ITEM item
		on item.[ID_ITEM] = b_plan.[ID_ITEM]
	INNER JOIN [L0].[L0_MI_FC_BL_RUN_RATES] run_rates
		on run_rates.[CategoryL1] = item.T_PRODUCT_HIERARCHY_1
	AND	run_rates.[CategoryL2] = item.T_PRODUCT_HIERARCHY_2
	AND	run_rates.[CategoryL3] = item.T_PRODUCT_HIERARCHY_3
	AND	REPLACE(run_rates.[CHANNELGROUP3],' ','') = REPLACE(b_plan.[CD_CHANNEL_GROUP_3],' ','')
	AND run_rates.[month] = 9



	SELECT cd_Channel_group_3, sum([VL_ITEM_QUANTITY])[VL_ITEM_QUANTITY],sum([AMT_TARGET_NET_ORDER_VALUE_EUR])[AMT_TARGET_NET_ORDER_VALUE_EUR]
	FROM L1.L1_FACT_F_BOTTOM_LINE__REALIZABLE_FORECAST_25
	GROUP BY rollup(cd_Channel_group_3)



	SELECT NUM_ITEM, sum([VL_ITEM_QUANTITY])[VL_ITEM_QUANTITY],sum([AMT_TARGET_NET_ORDER_VALUE_EUR])[AMT_TARGET_NET_ORDER_VALUE_EUR]
	FROM L1.L1_FACT_F_BOTTOM_LINE__REALIZABLE_FORECAST_25
	GROUP BY NUM_ITEM



