EXEC  WR.[WR_TX_L1_FACT_A_SALES_TRANSACTIONS_L1_FACT_A_SALES_TRANSACTION_KPI_SM]  @NUM_DAYS = 0
EXEC  WR.[WR_HIST_FULL_L1_FACT_A_SALES_TRANSACTIONS_KPI_SM]  
EXEC  WR.[WR_TX_L1_FACT_A_AMAZON_ITEM_ATTRIBUTION_L1_FACT_A_SALES_TRANSACTION_MKT_KPI] @NUM_DAYS =  631
EXEC  WR.WR_TX_L1_FACT_A_D2C_PERFORMANCE_ITEM_L1_FACT_A_SALES_TRANSACTION_MKT_KPI_SM @NUM_DAYS =  631
EXEC  WR.[WR_TX_L1_FACT_A_GOOGLE_ADS_PERFORMANCE_CAMPAIGN_L1_FACT_A_SALES_TRANSACTION_MKT_KPI_SM] @NUM_DAYS =  631
EXEC  WR.WR_TX_PL_V_SALES_TRANSACTIONS_SM_PL_M_SALES_TRANSACTIONS_SM  

SELECT YEAR(D_CREATED),count(*)
FROM L1.L1_FACT_A_SALES_TRANSACTION_KPI_SM
GROUP BY YEAR(D_CREATED)

--DELETE FROM WR.WR_L1_FACT_A_SALES_TRANSACTION_KPI_SM WHERE YEAR(D_CREATED) < 2024