EXEC  WR.[WR_TX_L1_FACT_A_SALES_TRANSACTIONS_L1_FACT_A_SALES_TRANSACTION_KPI_SM]  @NUM_DAYS = 0
EXEC  WR.[WR_HIST_FULL_L1_FACT_A_SALES_TRANSACTIONS_KPI_SM]  
EXEC  WR.[WR_TX_L1_FACT_A_AMAZON_ITEM_ATTRIBUTION_L1_FACT_A_SALES_TRANSACTION_MKT_KPI] @NUM_DAYS =  650
EXEC  WR.WR_TX_L1_FACT_A_D2C_PERFORMANCE_ITEM_L1_FACT_A_SALES_TRANSACTION_MKT_KPI_SM @NUM_DAYS =  650
EXEC  WR.[WR_TX_L1_FACT_A_GOOGLE_ADS_PERFORMANCE_CAMPAIGN_L1_FACT_A_SALES_TRANSACTION_MKT_KPI_SM] @NUM_DAYS =  650
EXEC  WR.WR_TX_PL_V_SALES_TRANSACTIONS_SM_PL_M_SALES_TRANSACTIONS_SM  


SELECT * INTO  [L1].[L1_FACT_A_SALES_TRANSACTION_KPI_SM_BCK20251009] FROM  [L1].[L1_FACT_A_SALES_TRANSACTION_KPI_SM]

SELECT YEAR(D_CREATED),count(*)
FROM L1.L1_FACT_A_SALES_TRANSACTION_KPI_SM
GROUP BY YEAR(D_CREATED)

--DELETE FROM WR.WR_L1_FACT_A_SALES_TRANSACTION_KPI_SM WHERE YEAR(D_CREATED) < 2024

--SELECT * INTO PL.PL_V_SALES_TRANSACTIONS_SM_bck20250925 from PL.PL_V_SALES_TRANSACTIONS_SM

SELECT  [DeliveryCountryGroup],SUM([ShippingOutboundEst])
FROM PL.PL_M_SALES_TRANSACTIONS_SM
WHERE 
	Year(TransactionDate) = 2025
	AND MONTH(TransactionDate) < 9 
Group by [DeliveryCountryGroup]
order by 1


SELECT  CD_COUNTRY_GROUP_DELIVERY,SUM(AMT_SHIPPING_OUTBOUND_EST_EUR)
FROM L1.L1_FACT_A_SALES_TRANSACTION_KPI_SM
WHERE 
	Year(D_CREATED) = 2025
	AND MONTH(D_CREATED) < 9 
Group by CD_COUNTRY_GROUP_DELIVERY
order by 1






with cte_ship_factor as 
(
	SELECT  ProcessId,SUM([ShippingOutboundEst])[ShippingOutboundEst]
	FROM PL.PL_M_SALES_TRANSACTIONS_SM
	WHERE 
		Year(TransactionDate) = 2025
		AND MONTH(TransactionDate) < 9 
		AND [DeliveryCountryGroup] = 'CEE'
	Group by ProcessId
),
CTE_services as 
(
	SELECT  CD_SALES_PROCESS_ID,SUM(AMT_SHIPPING_OUTBOUND_EST_EUR)AMT_SHIPPING_OUTBOUND_EST_EUR
	FROM L1.L1_FACT_A_SALES_TRANSACTION_KPI_SM
	WHERE 
		Year(D_CREATED) = 2025
		AND MONTH(D_CREATED) < 9 
		AND CD_COUNTRY_GROUP_DELIVERY = 'CEE'
	Group by CD_SALES_PROCESS_ID
)

SELECT 
	f.ProcessID, f.[ShippingOutboundEst] as ShippingCostWithFactor, AMT_SHIPPING_OUTBOUND_EST_EUR ShippingCostWithServices,
	Diff = ISNULL([ShippingOutboundEst],0) + ISNULL(AMT_SHIPPING_OUTBOUND_EST_EUR,0)
FROM cte_ship_factor f
LEFT JOIN CTE_services s
on f.Processid = s.CD_SALES_PROCESS_ID
order by 4 DESC




select * from  L1.L1_FACT_A_SALES_TRANSACTION_KPI_SM where CD_SALES_PROCESS_ID = '0407271620'
select * from  WR.WR_L1_FACT_A_SALES_TRANSACTION_KPI_SM where CD_SALES_PROCESS_ID = '0407129067'

select * from  L1.L1_DIM_A_ITEM where ID_ITEM = '86'
DELETE from  L1.L1_FACT_A_SALES_TRANSACTION_KPI_SM where CD_SALES_PROCESS_ID = '0407129067'

select distinct cd_item from L1.L1_DIM_A_ITEM_BOM where cd_bom_usage = 3

select top 1 * from Pl.PL_M_SALES_TRANSACTIONS_SM  

UPDATE  L1.L1_FACT_A_SALES_TRANSACTION_KPI SET FL_INCIDENT = 'Y' WHERE CD_SALES_PROCESS_ID = '0407129067'

---- 
 
SELECT TOP 10 * 
FROM PL_M_SALES_TRANSACTIONS_SM where 