--CREATE PROC WR.WR_TX_L1_FACT_F_BUSINESS_PLAN_L1_FACT_F_BUSINESS_PLAN_KPI_SM  @MONTH_DATE DATETIME
---- =============================================  
---- Author:      Helder Barbosa
---- Create Date: 2025-09-14
---- Description: Populates L1_FACT_F_BUSINESS_PLAN_L1_FACT_F_BUSINESS_PLAN_KPI_SM
---- 2025-09-14   v1:HBarbosa      :  initial version

---- ============================================= 
--AS
--BEGIN

DECLARE @MONTH_DATE date = '2025-01-01'

	--TRUNCATE TABLE [WR].[WR_L1_FACT_F_BUSINESS_PLAN_KPI_SM] 

	DECLARE @OTHER_DELIVER_COSTS_RATE DECIMAL(19,4) = 0.16
	DECLARE @GTS_RATE DECIMAL(19,4) = 0.13

;WITH CTE_ENVIRO as 
    (
	        SELECT 
				ID_ITEM,
				CD_COUNTRY_DELIVERY,
				NUM_YEAR,
				CD_CURRENCY,
				AMT_FEE_PER_UNIT = sum(AMT_FEE_PER_UNIT) 
			FROM [L1].[L1_DIM_A_ENVIRO_REST_UNIT_FEES]
            GROUP BY ID_ITEM,CD_COUNTRY_DELIVERY,NUM_YEAR,CD_CURRENCY
    ),
 cte_mek as (
		SELECT 
		 [ItemNo] as MATNR
		,[MekHedging] as MEK
		,[LastValueDate] as LOAD_TIMESTAMP 
		,1 AS LastVersion
	FROM  [PL].[PL_V_LAST_MEK]
 
    UNION
 
		SELECT 
		 ov.[ItemNo] as MATNR
		,ov.[MEK] as MEK
		,ov.LOAD_TIMESTAMP 
		,1 AS LastVersion
	FROM  [L0].L0_MI_BUSINESS_PLAN_MEK_OVERRIDE ov
    LEFT JOIN [PL].[PL_V_LAST_MEK]  mek on mek. itemno = ov.itemno
    Where 
        mek.ItemNo is null

	
)
,
CTE_SHIPP_COSTS as
(SELECT 
	cast(cost.item_code as nvarchar(50))item_code,
	CASE WHEN cost.warehouse=1 THEN 'Kamp-Lintfort'
	        WHEN cost.warehouse=2 THEN 'Hoppegarten'
	        WHEN cost.warehouse=3 THEN 'Bratislava'
	        WHEN cost.warehouse=4 THEN 'Werne'
	END warehouse,
    warehouse as warehouse_id,
	cost.country,
	ctypes.cost_type_name as Fulfillment,
	SUM(cost.parcel_total_cost) as main_shipping_cost
FROM [L0].[L0_MERCURY_LOGISTIC_BUDGET_CAPO_COST] cost 
LEFT JOIN [L0].[L0_MERCURY_LOGISTIC_BUDGET_COST_TYPES] ctypes
ON cost.cost_type_id = ctypes.id
WHERE 0=0
	--AND cost.warehouse IN (1, 3, 4)
	AND cost.item_code in  (SELECT cast(ItemNo as nvarchar(50)) from  WR.WR_V_L0_MI_BUSINESS_PLAN)
GROUP BY 
	cost.item_code,
	cost.warehouse,
	cost.country,
	ctypes.cost_type_name
)
,CTE_BASE_DATA AS
	(
		SELECT 
			 ID_COMPANY						= 	cp.ID_COMPANY							
			,fact.D_TARGET 												
			,D_TARGET_LOOKUP 				= 	fact.D_TARGET						
			,fact.ID_ITEM												
			,ID_ITEM_BUSINESS_PLAN			= 	itemBS.ID_ITEM_BUSINESS_PLAN					
			,CD_FULFILLMENT					= CASE WHEN fact.[CD_CHANNEL_GROUP_3] = 'B2B' THEN 'B2B' ELSE 'FBM' END					
			,T_REVISED_LOCATION				= CASE WHEN fact.[CD_CHANNEL_GROUP_3] = 'B2B' THEN 'Alicante' 
													WHEN fact.[CD_CHANNEL_GROUP_3] = 'CEE' THEN 'Bratislava' ELSE 'Kamp-Lintfort' END							
			,fact.[CD_COUNTRY_GROUP]									
			,fact.[CD_CHANNEL_GROUP_3]
			,VL_ITEM_QUANTITY					= SUM(ISNULL(fact.VL_ITEM_QUANTITY,0))									
			,AMT_PLAN_PRICE_EUR					= SUM(ISNULL(fact.AMT_PLAN_PRICE_EUR,0))							
			,AMT_SHIPPING_COST_EST_EUR			= MAX(ISNULL(ship_cost_fbm.main_shipping_cost,0))
			,AMT_MEK_HEDGING_EUR				= MAX(ISNULL(mek.MEK,0))
			,AMT_GTS_MARKUP_EUR					= MAX(ISNULL(mek.MEK,0) / (1+ ISNULL(@OTHER_DELIVER_COSTS_RATE,0)) /(1+ CASE WHEN GTS.ItemNo is not null THEN @GTS_RATE ELSE 0 END) * CASE WHEN GTS.ItemNo is not null THEN @GTS_RATE ELSE 0 END)
			,[AMT_TARGET_NET_ORDER_VALUE_EUR]	= SUM(ISNULL([AMT_TARGET_NET_ORDER_VALUE_EUR],0))
			,CD_CURRENCY					= 'EUR'		
			,VL_REFUND_RATE 				= MAX(ISNULL(VL_REFUND_RATE,0))	
	        ,VL_RETURN_RATE					= MAX(ISNULL(VL_RETURN_RATE,0))
        	,VL_REPLACEMENT_RATE 			= MAX(ISNULL(VL_REPLACEMENT_RATE,0))
			,CD_REFUND_RATE_SOURCE 			= MAX(ISNULL(CD_REFUND_RATE_SOURCE,'default'))
            ,CD_RETURN_RATE_SOURCE 			= MAX(ISNULL(CD_RETURN_RATE_SOURCE,'default'))
            ,CD_REPLACEMENT_RATE_SOURCE 	= MAX(ISNULL(CD_REPLACEMENT_RATE_SOURCE,'default'))	
		FROM L1.L1_FACT_F_BOTTOM_LINE_FORECAST fact
		LEFT JOIN WR.WR_SRG_L1_DIM_A_COMPANY cp
			on CAST(cp.CD_COMPANY as int) = 1000
			and cp.cd_source_system = 'SAP'
		LEFT JOIN WR.WR_SRG_L1_DIM_A_ITEM_BUSINESS_PLAN itemBS
			on itemBS.NUM_ITEM = fact.NUM_ITEM  
		LEFT JOIN cte_mek mek 
			on CAST(mek.MATNR as bigint) = fact.NUM_ITEM  
			and mek.LastVersion = 1
		LEFT JOIN [L0].[L0_MI_GTS_MARKUP_RATES] GTS
			ON fact.NUM_ITEM  = GTS.ITEMNO
			AND D_TARGET between GTS.VALID_FROM and GTS.VALID_TO 
		LEFT JOIN CTE_SHIPP_COSTS ship_cost_fbm
			ON fact.NUM_ITEM  = ship_cost_fbm.Item_code
				AND CASE WHEN fact.[CD_COUNTRY_GROUP] = 'INT'THEN 'ES'ELSE fact.[CD_COUNTRY_GROUP] END =ship_cost_fbm.country
				AND ship_cost_fbm.warehouse = 'Kamp-Lintfort'
				AND ship_cost_fbm.Fulfillment = 'FBM'
		 LEFT JOIN [L1].[L1_FACT_A_NOV_CLAIM_RATES] rrr
				ON rrr.id_item = fact.ID_ITEM
					AND '2025-05-01' BETWEEN rrr.d_valid_from and rrr.d_valid_to
					AND (rrr.CD_COUNTRY_INVOICE_GROUP is null OR rrr.CD_COUNTRY_INVOICE_GROUP = CASE WHEN fact.[CD_COUNTRY_GROUP] = 'INT'THEN 'ES'ELSE fact.[CD_COUNTRY_GROUP] END)
					AND (rrr.CD_COUNTRY_DELIVERY IS null OR rrr.CD_COUNTRY_DELIVERY = CASE WHEN fact.[CD_COUNTRY_GROUP] = 'INT'THEN 'ES'ELSE fact.[CD_COUNTRY_GROUP] END)
					AND (rrr.CD_CHANNEL_GROUP_3 is null OR REPLACE(rrr.CD_CHANNEL_GROUP_3,' ','') = fact.[CD_CHANNEL_GROUP_3]  )
		WHERE
			ISNULL([AMT_TARGET_NET_ORDER_VALUE_EUR],0) > 0
			and
			fact.D_TARGET >= @MONTH_DATE
		GROUP BY 
				cp.ID_COMPANY
				,D_TARGET
				,fact.ID_ITEM
				,itemBS.ID_ITEM_BUSINESS_PLAN
				,CASE WHEN fact.[CD_CHANNEL_GROUP_3] = 'B2B' THEN 'B2B' ELSE 'FBM' END	
				,CASE WHEN fact.[CD_CHANNEL_GROUP_3] = 'B2B' THEN 'Alicante' 
					WHEN fact.[CD_CHANNEL_GROUP_3] = 'CEE' THEN 'Bratislava' ELSE 'Kamp-Lintfort' END
				,[CD_COUNTRY_GROUP]
				,fact.[CD_CHANNEL_GROUP_3]
				

	),
	CTE_BS AS
	(
	
			SELECT 
			 ID_COMPANY						= 	fact.ID_COMPANY							
			,fact.D_TARGET 												
			,D_TARGET_LOOKUP 				= 	fact.D_TARGET_LOOKUP						
			,fact.ID_ITEM												
			,ID_ITEM_BUSINESS_PLAN								
			,CD_FULFILLMENT					= CD_FULFILLMENT				
			,T_REVISED_LOCATION				= T_REVISED_LOCATION							
			,fact.[CD_COUNTRY_GROUP]									
			,fact.[CD_CHANNEL_GROUP_3]
			,VL_ITEM_QUANTITY													
			,AMT_PLAN_PRICE_EUR											
			,AMT_SHIPPING_COST_EST_EUR			
			,AMT_MEK_HEDGING_EUR				
			,AMT_GTS_MARKUP_EUR					
			,[AMT_TARGET_NET_ORDER_VALUE_EUR]	
			,CD_CURRENCY							
			,VL_REFUND_RATE 				
	        ,VL_RETURN_RATE					
        	,VL_REPLACEMENT_RATE 			
			,CD_REFUND_RATE_SOURCE 			
            ,CD_RETURN_RATE_SOURCE 			
            ,CD_REPLACEMENT_RATE_SOURCE 	
		FROM [L1].[L1_FACT_F_BUSINESS_PLAN] fact
		
		WHERE
			ISNULL([AMT_TARGET_NET_ORDER_VALUE_EUR],0) > 0
			--and
			--YEAR(fact.D_TARGET) = YEAR(@MONTH_DATE)
			AND
			MONTH(fact.D_TARGET) >= DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()) + 1, 0)


	
	),
	cte_full_data as (
	
			SELECT 
			 ID_COMPANY						
			,D_TARGET 					
			,D_TARGET_LOOKUP 				
			,ID_ITEM					
			,ID_ITEM_BUSINESS_PLAN			
			,CD_FULFILLMENT					
			,T_REVISED_LOCATION				
			,[CD_COUNTRY_GROUP]		
			,[CD_CHANNEL_GROUP_3]
			,VL_ITEM_QUANTITY													
			,AMT_PLAN_PRICE_EUR											
			,AMT_SHIPPING_COST_EST_EUR			
			,AMT_MEK_HEDGING_EUR				
			,AMT_GTS_MARKUP_EUR					
			,[AMT_TARGET_NET_ORDER_VALUE_EUR]	
			,CD_CURRENCY							
			,VL_REFUND_RATE 				
	        ,VL_RETURN_RATE					
        	,VL_REPLACEMENT_RATE 			
			,CD_REFUND_RATE_SOURCE 			
            ,CD_RETURN_RATE_SOURCE 			
            ,CD_REPLACEMENT_RATE_SOURCE  
		FROM CTE_BASE_DATA
		UNION ALL
			SELECT 
			 ID_COMPANY						
			,D_TARGET 					
			,D_TARGET_LOOKUP 				
			,ID_ITEM					
			,ID_ITEM_BUSINESS_PLAN			
			,CD_FULFILLMENT					
			,T_REVISED_LOCATION				
			,[CD_COUNTRY_GROUP]		
			,[CD_CHANNEL_GROUP_3]
			,VL_ITEM_QUANTITY													
			,AMT_PLAN_PRICE_EUR											
			,AMT_SHIPPING_COST_EST_EUR			
			,AMT_MEK_HEDGING_EUR				
			,AMT_GTS_MARKUP_EUR					
			,[AMT_TARGET_NET_ORDER_VALUE_EUR]	
			,CD_CURRENCY							
			,VL_REFUND_RATE 				
	        ,VL_RETURN_RATE					
        	,VL_REPLACEMENT_RATE 			
			,CD_REFUND_RATE_SOURCE 			
            ,CD_RETURN_RATE_SOURCE 			
            ,CD_REPLACEMENT_RATE_SOURCE  
		FROM CTE_BS
	
	)

,CTE_SALES_L1 AS
	(
		SELECT 
			 fact.ID_COMPANY											
			,fact.D_TARGET 												
			,fact.ID_ITEM												
			,fact.ID_ITEM_BUSINESS_PLAN									
			,fact.CD_FULFILLMENT										
			,fact.T_REVISED_LOCATION									
			,fact.[CD_COUNTRY_GROUP]									
			,fact.[CD_CHANNEL_GROUP_3]
			,fact.VL_ITEM_QUANTITY										
			,AMT_PLAN_PRICE_EUR											
			,AMT_SHIPPING_COST_EST_EUR	
			,AMT_MEK_HEDGING_EUR 
			,AMT_GTS_MARKUP_EUR														
			,[AMT_TARGET_NET_ORDER_VALUE_EUR]
			,fact.CD_CURRENCY													
            ,fact.VL_REFUND_RATE 					
	        ,fact.VL_RETURN_RATE					
        	,fact.VL_REPLACEMENT_RATE 	
			,fact.CD_REFUND_RATE_SOURCE 
            ,fact.CD_RETURN_RATE_SOURCE 
            ,fact.CD_REPLACEMENT_RATE_SOURCE 												

			,[PCT_COMMISSIONS_MARKETPLACES] = ISNULL(com_mkt_bs.[MARKETPLACERATE],0)				
			,[PCT_COMMISSIONS_MARKETPLACES_RETURN] = ISNULL(com_mkt_bs.[MARKETPLACERATE],0)
			
			,[PCT_PAYMENTS_ORDER] = CASE WHEN [CD_CHANNEL_GROUP_3] = 'Amazon' THEN 0 ELSE 0.06 END

	        ,VL_COMMISSIONS_ORDER_RATE = c_amaz.[VL_COMMISSIONS_ORDER_RATE]			

			,AMT_PRECALC_ENVIRO_REST_UNIT_FEE_EUR = env.AMT_FEE_PER_UNIT * COALESCE(enviro_rate.VL_FX_RATE, 1) --AS EnviroRestUnitFee_PreCalc
            ,AMT_PRECALC_REPACKAGING_EUR = repack.AMT_FEE_PER_UNIT * COALESCE(enviro_rate.VL_FX_RATE, 1) * 0.025 --AS Repackaging_PreCalc							

			,[AMT_CORRECTION_FACTOR_ORDER] = ISNULL(factor.[AMT_CORRECTION_FACTOR_ORDER],1) 
            ,[AMT_CORRECTION_FACTOR_RETURN] = ISNULL(factor.[AMT_CORRECTION_FACTOR_RETURN],1)
            ,[AMT_CORRECTION_FACTOR_REPLACEMENT] = ISNULL(factor.[AMT_CORRECTION_FACTOR_REPLACEMENT],1)

			,PCT_MKT_RATE = mkt.MARKETINGRATE
			,PCT_VAT_VALUE = CASE WHEN ISNULL(vat.PCT_VALUE,0) = 0 THEN 0 ELSE vat.PCT_VALUE / 100 END
			,VL_DEPRETIATION_RATE = ISNULL(dep.VL_RATE,0)
			FROM cte_full_data fact
			LEFT JOIN [L1].[L1_DIM_A_ITEM] item 
				ON item.[ID_ITEM]=fact.ID_ITEM
			LEFT JOIN [L1].[L1_DIM_A_CS_COMMISSIONS_AMAZON] c_amaz
				ON item.T_PRODUCT_HIERARCHY_1 = c_amaz.T_PRODUCT_HIERARCHY_1
					AND item.T_PRODUCT_HIERARCHY_2 = c_amaz.T_PRODUCT_HIERARCHY_2
					AND fact.D_TARGET_LOOKUP BETWEEN c_amaz.D_VALID_FROM AND c_amaz.D_VALID_TO
					AND CASE WHEN fact.[CD_COUNTRY_GROUP] = 'INT' THEN 'ES' ELSE fact.[CD_COUNTRY_GROUP] END = c_amaz.CD_CHANNEL_COUNTRY
			--join enviro
			LEFT JOIN  CTE_ENVIRO env
				ON fact.ID_ITEM = env.ID_ITEM
				AND fact.[CD_COUNTRY_GROUP] = env.CD_COUNTRY_DELIVERY
				AND YEAR(fact.D_TARGET_LOOKUP) = env.NUM_YEAR
			--join enviro for repackacing
			LEFT JOIN [L1].[L1_DIM_A_ENVIRO_REST_UNIT_FEES] repack
				ON fact.ID_ITEM = repack.ID_ITEM
				AND fact.[CD_COUNTRY_GROUP]   = repack.CD_COUNTRY_DELIVERY
				AND YEAR(fact.D_TARGET_LOOKUP) = repack.NUM_YEAR
				AND repack.CD_ENVIRO_CATEGORY = 'Packaging'
			--join fx rate for enviro
			LEFT JOIN [L1].[L1_FACT_F_FX_RATE] enviro_rate
				ON env.cd_currency=enviro_rate.cd_currency
				AND Year(fact.D_TARGET_LOOKUP)=Year(enviro_rate.D_EFFECTIVE)
				AND Month(fact.D_TARGET_LOOKUP)=Month(enviro_rate.D_EFFECTIVE)	
			--join fulfillment shipping factor
			LEFT JOIN L1.L1_DIM_A_FULFILLMENT_SHIPPING_FACTOR factor
				ON item.CD_SIZE_BRACKET = factor.CD_SIZE_BRACKET
					AND fact.CD_FULFILLMENT = factor.CD_FULFILLMENT
					AND fact.T_REVISED_LOCATION = factor.T_STORAGE_LOCATION
					AND CASE WHEN fact.[CD_CHANNEL_GROUP_3]='CEE' THEN 'CEE' ELSE fact.CD_COUNTRY_GROUP END = factor.[CD_COUNTRY_DELIVERY_GROUP]
					AND fact.D_TARGET_LOOKUP BETWEEN factor.D_VALID_FROM AND factor.D_VALID_TO 
			LEFT JOIN [L0].[L0_MI_BUSINESS_PLAN_MARKETING_RATES] mkt
				on REPLACE(mkt.[CHANNELGROUP3],' ','') = fact.[CD_CHANNEL_GROUP_3]
				and YEAR(fact.D_TARGET) = YEAR(mkt.[MONTH])
				and MONTH(fact.D_TARGET) = MONTH(mkt.[MONTH])
			LEFT JOIN [L0].L0_MI_BUSINESS_PLAN_COMMISSIONS_MARKETPLACES com_mkt_bs
				on	1=1
				AND com_mkt_bs.[CHANNELGROUP3] = fact.CD_CHANNEL_GROUP_3
				and YEAR(fact.D_TARGET) = YEAR(com_mkt_bs.[MONTH])
				and MONTH(fact.D_TARGET) = MONTH(com_mkt_bs.[MONTH])
			LEFT JOIN [L1].[L1_FACT_A_COUNTRY_VAT] vat
				on vat.[CD_COUNTRY] = CASE WHEN fact.CD_COUNTRY_GROUP = 'INT'THEN 'SI' ELSE fact.CD_COUNTRY_GROUP END 
				and vat.[D_VALID_TO]  = '9999-12-31'
			LEFT JOIN [L1].[L1_DIM_A_DEPRECIATION_VALUES] dep
				on fact.D_TARGET_LOOKUP between dep.D_VALID_FROM and dep.D_VALID_TO
				AND dep.T_PRODUCT_HIERARCHY_2 = item.T_PRODUCT_HIERARCHY_2
				and dep.T_STORAGE_LOCATION = fact.T_REVISED_LOCATION
			 



	),
	CTE_SALES_L2 AS 
	(
		SELECT sales.*
			,AMT_COMMISSIONS_MARKETPLACES_EUR  = CASE WHEN CD_CHANNEL_GROUP_3 = 'CEE' then 0 ELSE ([AMT_TARGET_NET_ORDER_VALUE_EUR]*(1+PCT_VAT_VALUE) * [PCT_COMMISSIONS_MARKETPLACES]) END
			,AMT_GROSS_ORDER_VALUE_EUR = [AMT_TARGET_NET_ORDER_VALUE_EUR]
	        ,AMT_COMMISSIONS_AMAZON_EUR = CASE WHEN CD_CHANNEL_GROUP_3 = 'Amazon' then [AMT_TARGET_NET_ORDER_VALUE_EUR]*(1+PCT_VAT_VALUE)*VL_COMMISSIONS_ORDER_RATE ELSE NULL END
			,VL_NET_ORDER_QUANTITY = [VL_ITEM_QUANTITY]
		FROM CTE_SALES_L1 sales
	)
,
	CTE_SALES_L3 AS 
	(
		SELECT sales.*
				,AMT_REFUNDED_ORDER_VALUE_EST_EUR = (AMT_GROSS_ORDER_VALUE_EUR * ISNULL(VL_REFUND_RATE,0)) 		

				,AMT_COMMISSIONS_AMAZON_REFUNDS_EUR = CASE WHEN AMT_COMMISSIONS_AMAZON_EUR between c_amaz_ref.[VL_VALUE_FROM] and c_amaz_ref.[VL_VALUE_TO] 
				      THEN CASE WHEN c_amaz_ref.[VL_COMMISSIONS_REFUND_ABOVE_THRESHOLD] <> 0 
				                THEN (AMT_COMMISSIONS_AMAZON_EUR - c_amaz_ref.[VL_COMMISSIONS_REFUND_ABOVE_THRESHOLD])*sales.VL_REFUND_RATE 
				                ELSE (AMT_COMMISSIONS_AMAZON_EUR * c_amaz_ref.[VL_COMMISSIONS_REFUND_BELOW_THRESHOLD_RATE])*sales.VL_REFUND_RATE 
				           END
				      ELSE NULL
				END
	    FROM CTE_SALES_L2 sales
	    LEFT JOIN [L1].[L1_DIM_A_CS_COMMISSIONS_AMAZON_REFUND] c_amaz_ref
	         ON DATEADD(YEAR,-1,D_TARGET) BETWEEN c_amaz_ref.[D_VALID_FROM] AND c_amaz_ref.[D_VALID_TO]
	         AND AMT_COMMISSIONS_AMAZON_EUR > c_amaz_ref.VL_VALUE_FROM 
	         AND AMT_COMMISSIONS_AMAZON_EUR <= c_amaz_ref.VL_VALUE_TO 
	)
	,
	CTE_SALES_L4 AS 
	(
		SELECT sales.*
				,AMT_COMMISSIONS_MARKETPLACES_REFUNDS_EUR = CASE WHEN CD_CHANNEL_GROUP_3 = 'CEE' then 0 ELSE  (AMT_REFUNDED_ORDER_VALUE_EST_EUR*(1+PCT_VAT_VALUE) * [PCT_COMMISSIONS_MARKETPLACES_RETURN]) END		

				 ,AMT_NET_ORDER_VALUE_EST_EUR = AMT_GROSS_ORDER_VALUE_EUR
				 ,VL_REFUNDED_QUANTITY_EST = (VL_NET_ORDER_QUANTITY * VL_REFUND_RATE) 			
				 ,VL_RETURNED_QUANTITY_EST = (VL_NET_ORDER_QUANTITY * VL_RETURN_RATE)				
				 ,VL_REPLACEMENT_QUANTITY_EST = (VL_NET_ORDER_QUANTITY *VL_REPLACEMENT_RATE )				
		FROM CTE_SALES_L3 sales
	)
	,
	CTE_SALES_L5 AS 
	(
		SELECT sales.*
				,AMT_REVENUE_EST_EUR = (AMT_NET_ORDER_VALUE_EST_EUR - AMT_REFUNDED_ORDER_VALUE_EST_EUR)																	
				,AMT_SHIPPING_COSTS_INVOICED_EST_EUR = (VL_NET_ORDER_QUANTITY * [AMT_SHIPPING_COST_EST_EUR] * AMT_CORRECTION_FACTOR_ORDER)				
				,AMT_SHIPPING_COSTS_RETURNED_EST_EUR = (VL_RETURNED_QUANTITY_EST * [AMT_SHIPPING_COST_EST_EUR] * AMT_CORRECTION_FACTOR_RETURN )	    		
				,AMT_SHIPPING_COSTS_REPLACED_EST_EUR = (VL_REPLACEMENT_QUANTITY_EST * [AMT_SHIPPING_COST_EST_EUR] * AMT_CORRECTION_FACTOR_REPLACEMENT )	
				,AMT_NET_ORDER_CONTRIBUTION_EST_EUR = AMT_NET_ORDER_VALUE_EST_EUR - (CASE WHEN [VL_ITEM_QUANTITY] <> 0 
														THEN (VL_NET_ORDER_QUANTITY) * (ISNULL([AMT_MEK_HEDGING_EUR],0)) 	ELSE 0 END)																			
				,AMT_ENVIRO_REST_UNIT_FEE_EUR = (VL_NET_ORDER_QUANTITY - VL_RETURNED_QUANTITY_EST+VL_REPLACEMENT_QUANTITY_EST) * AMT_PRECALC_ENVIRO_REST_UNIT_FEE_EUR
				,AMT_REPACKAGING_EUR = (VL_NET_ORDER_QUANTITY - VL_RETURNED_QUANTITY_EST+VL_REPLACEMENT_QUANTITY_EST) * AMT_PRECALC_REPACKAGING_EUR 


		FROM CTE_SALES_L4 sales
	)
	,CTE_SALES_L6 AS 
	(
		SELECT sales.*
					,AMT_PAYMENTS_EUR = (AMT_REVENUE_EST_EUR * [PCT_PAYMENTS_ORDER])	
				 ,AMT_SHOP_MARKETING_EUR =  CASE WHEN [CD_CHANNEL_GROUP_3] <> 'Amazon' THEN AMT_NET_ORDER_VALUE_EST_EUR * PCT_MKT_RATE ELSE 0 END
				 ,AMT_AMAZON_MARKETING_COSTS_EUR = CASE WHEN [CD_CHANNEL_GROUP_3] = 'Amazon' THEN AMT_NET_ORDER_VALUE_EST_EUR * PCT_MKT_RATE ELSE 0 END
				 ,AMT_FULFILLMENT_OUTBOUND_EST_EUR = (isnull(AMT_SHIPPING_COSTS_INVOICED_EST_EUR,0)+isnull(AMT_SHIPPING_COSTS_RETURNED_EST_EUR,0)+isnull(AMT_SHIPPING_COSTS_REPLACED_EST_EUR,0))										        
				,AMT_ENVIRO_AND_LICENSE_COST_EST_EUR = ISNULL(AMT_ENVIRO_REST_UNIT_FEE_EUR,0)+ISNULL(AMT_REPACKAGING_EUR,0)                                                                         

		FROM CTE_SALES_L5 sales
	)
	,
	CTE_SALES_L7 AS 
	(
		SELECT 	sales.*
		,AMT_MEK_TO_CUSTOMER_PLAN_EUR_SM			= CASE WHEN [VL_ITEM_QUANTITY] <> 0 
													THEN (VL_NET_ORDER_QUANTITY) * (ISNULL([AMT_MEK_HEDGING_EUR],0)-ISNULL([AMT_GTS_MARKUP_EUR],0))  
													ELSE 0 END	
		,AMT_MEK_FROM_CUSTOMER_PLAN_EUR_SM			= CASE WHEN [VL_ITEM_QUANTITY] <> 0 
													THEN (VL_RETURNED_QUANTITY_EST) * (ISNULL([AMT_MEK_HEDGING_EUR],0)-ISNULL([AMT_GTS_MARKUP_EUR],0))  
													ELSE 0 END	
		,AMT_MEK_REPLACEMENT_PLAN_EUR_SM			= CASE WHEN [VL_ITEM_QUANTITY] <> 0 
													THEN (VL_REPLACEMENT_QUANTITY_EST) * (ISNULL([AMT_MEK_HEDGING_EUR],0)-ISNULL([AMT_GTS_MARKUP_EUR],0))  
													ELSE 0 END	
		,AMT_MEK_DEPRECIATION_PLAN_EUR_SM 			= CASE WHEN [VL_ITEM_QUANTITY] <> 0 
													THEN (VL_RETURNED_QUANTITY_EST*VL_DEPRETIATION_RATE) * (ISNULL([AMT_MEK_HEDGING_EUR],0)-ISNULL([AMT_GTS_MARKUP_EUR],0))  
													ELSE 0 END	
		,AMT_MARKETING_ATTRIBUTION_PLAN_EUR_SM		= ISNULL(AMT_SHOP_MARKETING_EUR,0)+ISNULL(AMT_AMAZON_MARKETING_COSTS_EUR,0)
		,AMT_COMMISSIONS_SALE_PLAN_EUR_SM			= ISNULL(AMT_COMMISSIONS_MARKETPLACES_EUR,0) + ISNULL(AMT_COMMISSIONS_AMAZON_EUR,0)
		,AMT_COMMISSIONS_REFUNDS_PLAN_EUR_SM		= ISNULL(AMT_COMMISSIONS_AMAZON_REFUNDS_EUR,0)+ISNULL(AMT_COMMISSIONS_MARKETPLACES_REFUNDS_EUR,0)
		,AMT_COMMISSIONS_PLAN_EUR_SM				= (ISNULL(AMT_COMMISSIONS_MARKETPLACES_EUR,0)-ISNULL(AMT_COMMISSIONS_MARKETPLACES_REFUNDS_EUR,0)+ISNULL(AMT_COMMISSIONS_AMAZON_EUR,0)-ISNULL(AMT_COMMISSIONS_AMAZON_REFUNDS_EUR,0))
		,AMT_SHIPPING_COST_INVOICED_PLAN_SM		= AMT_SHIPPING_COSTS_INVOICED_EST_EUR
		,AMT_SHIPPING_COST_RETURNED_PLAN_SM		= AMT_SHIPPING_COSTS_RETURNED_EST_EUR
		,AMT_SHIPPING_COST_REPLACED_PLAN_SM		= AMT_SHIPPING_COSTS_REPLACED_EST_EUR 
		FROM CTE_SALES_L6 sales


	),
	CTE_SALES_L8 AS 
	(
		SELECT sales.*,

		AMT_FULL_NET_PRODUCT_COST_PLAN_EUR_SM =  ISNULL(AMT_MEK_TO_CUSTOMER_PLAN_EUR_SM,0) - ISNULL(AMT_MEK_FROM_CUSTOMER_PLAN_EUR_SM,0) + ISNULL(AMT_MEK_REPLACEMENT_PLAN_EUR_SM,0) +ISNULL(AMT_MEK_DEPRECIATION_PLAN_EUR_SM,0) ,
		AMT_STEERING_MARGIN_PLAN_EUR_SM =  ISNULL(AMT_REVENUE_EST_EUR,0)
					- (ISNULL(AMT_MEK_TO_CUSTOMER_PLAN_EUR_SM,0) - ISNULL(AMT_MEK_FROM_CUSTOMER_PLAN_EUR_SM,0) + ISNULL(AMT_MEK_REPLACEMENT_PLAN_EUR_SM,0) +ISNULL(AMT_MEK_DEPRECIATION_PLAN_EUR_SM,0)) -- Net product Costs
					- ISNULL(AMT_MARKETING_ATTRIBUTION_PLAN_EUR_SM,0) 
					- ISNULL(AMT_COMMISSIONS_PLAN_EUR_SM,0) 
					- ISNULL(AMT_PAYMENTS_EUR,0) 
					- ISNULL(AMT_ENVIRO_AND_LICENSE_COST_EST_EUR,0)
					- ISNULL(AMT_FULFILLMENT_OUTBOUND_EST_EUR,0)   ----(ShippingCostsInvoicedEst+ShippingCostsReturnedEst+ShippingCostsReplacedEst)
		FROM CTE_SALES_L7 sales 
	
	
	)

	
		SELECT * INTO TEST.WR_BS_HB FROM CTE_SALES_L8


--END

