DECLARE @ItemNo  varchar(50) = '10047378'


SELECT 
	Dataset = 'Steering Margin',
	ItemNo	=	NUM_ITEM,
	ItemFamily = T_PRODUCT_HIERARCHY_4,
	ChannelGroup3 = CD_CHANNEL_GROUP_3,
	DeliveryCountryGroup = DeliveryCountryGroup,
	NetOrderValue = SUM(NetOrderValueEst),
	Revenue = SUM(RevenueEst),
	MarketingCost = SUM(ISNULL(MarketingCostAct,0)),
	[Marketing %] = CASE WHEN SUM(ISNULL(RevenueEst,0)) = 0 THEN 0 ELSE  (SUM(ISNULL(MarketingCostAct,0)) / SUM(ISNULL(RevenueEst,0))) *100 END
FROM PL.[PL_V_SALES_TRANSACTIONS_SM] fact
LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL ch
	ON ch.ID_SALES_CHANNEL = fact.ChannelId
LEFT JOIN L1.L1_DIM_A_ITEM it
	ON it.ID_ITEM = fact.ItemID
WHERE
	it.Num_ITEM = @ItemNo
	AND fact.TransactionDate between '2025-09-01' and '2025-09-30'
	AND CD_CHANNEL_GROUP_3= 'Shop WE'
	AND DeliveryCountryGroup = 'DE'
GROUP BY NUM_ITEM,T_PRODUCT_HIERARCHY_4,CD_CHANNEL_GROUP_3,DeliveryCountryGroup


--DECLARE @ItemNo  varchar(50) = '10047378'


SELECT 
	Dataset = 'CPNL',
	ItemNo	=	NUM_ITEM,
	ItemFamily = T_PRODUCT_HIERARCHY_4,
	ChannelGroup3 = CD_CHANNEL_GROUP_3,
	DeliveryCountryGroup = DeliveryCountryGroup,
	NetOrderValue = SUM(NetOrderValueEst),
	Revenue = SUM(RevenueEst),
	MarketingOPe = SUM(ISNULL(MarketingOPEXEst,0)),
	MarketingCost = SUM(ISNULL(MarketingAmazon,0))+SUM(ISNULL(MarketingMarketplacesEst,0))+ SUM(ISNULL(MarketingShops,0)) + SUM(ISNULL(MarketingOPEXEst,0)),
	[Marketing %] = CASE WHEN SUM(ISNULL(RevenueEst,0)) = 0 THEN 0 ELSE  ((SUM(ISNULL(MarketingAmazon,0))+SUM(ISNULL(MarketingMarketplacesEst,0))+ SUM(ISNULL(MarketingShops,0)) + SUM(ISNULL(MarketingOPEXEst,0))) / SUM(ISNULL(RevenueEst,0))) *100 END
FROM PL.[PL_V_SALES_TRANSACTIONS] fact
LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL ch
	ON ch.ID_SALES_CHANNEL = fact.ChannelId
LEFT JOIN L1.L1_DIM_A_ITEM it
	ON it.ID_ITEM = fact.ItemID
WHERE
	it.Num_ITEM = 10047378
	AND fact.TransactionDate between '2025-09-01' and '2025-09-30'
		AND CD_CHANNEL_GROUP_3= 'Shop WE'
	AND DeliveryCountryGroup = 'DE'
GROUP BY NUM_ITEM,T_PRODUCT_HIERARCHY_4,CD_CHANNEL_GROUP_3,DeliveryCountryGroup

GGL= 31.80 + 0.38 D2C + 0 Marketplaces + 

	SELECT ROUND(SUM(isnull(PS.[AMT_COST_EUR_ATT],0)),2)	 MarketingGoogle
	FROM [L1].L1_FACT_A_GOOGLE_ITEM_ATTRIBUTION AS PS
		LEFT JOIN [L1].[L1_DIM_A_MARKETING_ACCOUNT] AS MA
			 ON PS.ID_MARKETING_ACCOUNT = MA.ID_MARKETING_ACCOUNT
		LEFT JOIN l1.[L1_DIM_A_SALES_CHANNEL] AS SC
			 ON MA.CD_SALES_CHANNEL = SC.CD_SALES_CHANNEL
		LEFT JOIN [L0].[L0_MI_COUNTRY_MAPPING] cmid
			ON MA.CD_COUNTRY = cmid.COUNTRY
		LEFT JOIN [L1].[L1_DIM_A_COMPANY] company
		    ON  [CD_COMPANY]= '1000' and company.[CD_SOURCE_SYSTEM] = 'SAP'
		WHERE 
			ps.[D_CAMPAIGN] between '2025-09-01' and '2025-09-30'
			and CD_ITEM = 10047378
			AND CD_CHANNEL_GROUP_3= 'Shop WE'
			AND MA.CD_COUNTRY = 'DE'
		GROUP BY 
			PS.[D_CAMPAIGN],
			ID_ITEM,
			SC.ID_SALES_CHANNEL,
			MA.CD_COUNTRY,
			cmid.INVOICECOUNTRYGROUP,
			cmid.DELIVERYCOUNTRYGROUP,
			SC.T_DEFAULT_STORAGE_LOCATION,
			ID_COMPANY 
			having  SUM(isnull(PS.[AMT_COST_EUR_ATT],0)) <> 0

		SELECT ROUND(SUM(isnull(PS.[AMT_COST_EUR_ATT],0)),2)	 MarketingD2C
		FROM L1.L1_FACT_A_D2C_PERFORMANCE_ITEM AS PS
		LEFT JOIN [L1].[L1_DIM_A_MARKETING_ACCOUNT] AS MA
			 ON PS.ID_MARKETING_ACCOUNT = MA.ID_MARKETING_ACCOUNT
		LEFT JOIN l1.[L1_DIM_A_SALES_CHANNEL] AS SC
			 ON MA.CD_SALES_CHANNEL = SC.CD_SALES_CHANNEL
		LEFT JOIN [L0].[L0_MI_COUNTRY_MAPPING] cmid
			ON MA.CD_COUNTRY = cmid.COUNTRY
		LEFT JOIN [L1].[L1_DIM_A_COMPANY] company
		    ON  [CD_COMPANY]= '1000' and company.[CD_SOURCE_SYSTEM] = 'SAP'
		WHERE 
			ps.[D_CAMPAIGN] between '2025-09-01' and '2025-09-30'
			and CD_ITEM= '10047378'
			AND CD_CHANNEL_GROUP_3= 'Shop WE'
			AND MA.CD_COUNTRY = 'DE'
		GROUP BY 
			PS.[D_CAMPAIGN],
			PS.CD_SOURCE_SYSTEM,
			ID_ITEM,
			SC.ID_SALES_CHANNEL,
			MA.CD_COUNTRY,
			cmid.INVOICECOUNTRYGROUP,
			cmid.DELIVERYCOUNTRYGROUP,
			SC.T_DEFAULT_STORAGE_LOCATION,
			ID_COMPANY
			having  SUM(isnull(PS.[AMT_COST_EUR_ATT],0)) <> 0



			select top 10 * FROM L1.L1_FACT_A_D2C_PERFORMANCE_ITEM AS PS


	--select *
	--from L1.L1_DIM_A_ORDER_CANCELLATION_VALUES cll
	--where
	--CD_COUNTRY_INVOICE_GROUP = 'INT'
	--and '2025-03-17' BETWEEN cll.D_VALID_FROM AND cll.D_VALID_TO
	--and
	--[T_PRODUCT_HIERARCHY_2] = 'Fridges & Freezers'



		SELECT 
			AMT_MKT_COST_EUR = ROUND(SUM(isnull(fact.[AMT_COST_EUR_ATT],0)),2)
		FROM 
		[L1].L1_FACT_A_D2C_PERFORMANCE_ITEM fact
		INNER JOIN L1.L1_DIM_A_ITEM it on it.ID_ITEM = fact.ID_ITEM
		INNER JOIN L1.L1_DIM_A_MARKETING_ACCOUNT acc on acc.[ID_MARKETING_ACCOUNT] = fact.[ID_MARKETING_ACCOUNT]
		LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL channel
				on channel.[CD_SALES_CHANNEL] = acc.[CD_SALES_CHANNEL]
		LEFT JOIN [L0].[L0_MI_COUNTRY_GROUP] cmd
					ON acc.CD_COUNTRY = cmd.COUNTRY
		WHERE 1=1 and
			[D_CAMPAIGN] between '2025-09-01' and '2025-09-30'
			and [T_PRODUCT_HIERARCHY_4]= 'Velaire'
			AND CD_CHANNEL_GROUP_3= 'Shop WE'
			AND acc.CD_COUNTRY = 'DE'
		GROUP BY [T_PRODUCT_HIERARCHY_4],
				channel.CD_CHANNEL_GROUP_3,
				D_CAMPAIGN,
				ISNULL(cmd.CountryGroup,'INT')
		HAVING ROUND(SUM(isnull(fact.[AMT_COST_EUR_ATT],0)),2) >  0

	Velaire: GGL: 10908.130000 + D2C: 179.51 


	SELECT 
		ID_SALES_TRANSACTION,
		CD_SALES_TRANSACTION = cast(CD_SALES_TRANSACTION as varchar(150)),
		s.D_CREATED,
		it.T_PRODUCT_HIERARCHY_4,
		CD_CHANNEL_GROUP_3 = REPLACE(ch.[CD_CHANNEL_GROUP_3],' ',''),
		CD_COUNTRY_GROUP_DELIVERY = CD_COUNTRY_GROUP_DELIVERY,
		it.NUM_ITEM,
		it.ID_ITEM
		,AMT_TOTAL_NOV_FAMILY_EUR	= SUM(ISNULL(AMT_NET_ORDER_VALUE_EST_EUR,0)) 
											OVER(PARTITION BY T_PRODUCT_HIERARCHY_4, s.D_CREATED ,[CD_CHANNEL_GROUP_3],CD_COUNTRY_GROUP_DELIVERY )
		,PERC_NOV_FAMILY_SHARE		= AMT_NET_ORDER_VALUE_EST_EUR / SUM(ISNULL(AMT_NET_ORDER_VALUE_EST_EUR,0)) 
											OVER(PARTITION BY T_PRODUCT_HIERARCHY_4, s.D_CREATED ,[CD_CHANNEL_GROUP_3],CD_COUNTRY_GROUP_DELIVERY )
		,AMT_TOTAL_NOV_ITEM_EUR		= SUM(ISNULL(AMT_NET_ORDER_VALUE_EST_EUR,0)) 
											OVER(PARTITION BY NUM_ITEM, s.D_CREATED,[CD_CHANNEL_GROUP_3],CD_COUNTRY_GROUP_DELIVERY )
		,PERC_NOV_ITEM_SHARE		= AMT_NET_ORDER_VALUE_EST_EUR / SUM(ISNULL(AMT_NET_ORDER_VALUE_EST_EUR,0)) 
														OVER(PARTITION BY NUM_ITEM, s.D_CREATED,[CD_CHANNEL_GROUP_3],CD_COUNTRY_GROUP_DELIVERY )
	FROM L1.L1_FACT_A_SALES_TRANSACTION_KPI_SM s
	INNER JOIN L1.L1_DIM_A_ITEM it on it.ID_ITEM = s.ID_ITEM
	LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL ch on ch.ID_SALES_CHANNEL = s.ID_SALES_CHANNEL
	WHERE 1=1
	AND s.D_CREATED between '2025-09-01' and '2025-09-30'
	and	ch.CD_CHANNEL_GROUP_3 in ('Shop WE')
	AND CD_COUNTRY_GROUP_DELIVERY = 'DE'
	AND ISNULL(AMT_NET_ORDER_VALUE_EST_EUR,0) > 0
	and T_PRODUCT_HIERARCHY_4 = 'Velaire'




	select
		it.NUM_ITEM, SUM(AMT_MKT_COST_EUR)
	FROM 
	L1.L1_FACT_A_SALES_TRANSACTION_MKT_KPI_SM s
	INNER JOIN L1.L1_DIM_A_ITEM it on it.ID_ITEM = s.ID_ITEM

	WHERE 1=1
	AND s.D_CREATED between '2025-09-01' and '2025-09-30'
	and	CD_CHANNEL_GROUP_3 in ('Shop WE')
	AND CD_COUNTRY_GROUP = 'DE'
	and s.T_PRODUCT_HIERARCHY_4 = 'Velaire'
	GROUP BY 
	NUM_ITEM




	SELECT * FROM l1.l1_dim_a_item where T_PRODUCT_HIERARCHY_4 = 'Velaire'




	SELECT 
			CD_SALES_TRANSACTION_MKT = cast(CONCAT('AMZ','#',D_CAMPAIGN,'#',T_PRODUCT_HIERARCHY_4,'#',CD_CHANNEL_GROUP_3,'#',ISNULL(cmd.CountryGroup,'INT')) as varchar(150)),
			D_CAMPAIGN,
			T_PRODUCT_HIERARCHY_4,
			ID_SALES_CHANNEL = MIN(channel.ID_SALES_CHANNEL),
			CD_CHANNEL_GROUP_3 = channel.CD_CHANNEL_GROUP_3,
			CD_COUNTRY_GROUP = ISNULL(cmd.CountryGroup,'INT'),
			AMT_MKT_COST_EUR = SUM((ISNULL([AMT_COST_EUR_ATT],0)+ISNULL([GOOGLE_AMT_COST_EUR_ATT],0)+ISNULL([DSP_AMT_COST_EUR_ATT],0))) 
		FROM 
		[L1].L1_FACT_A_AMAZON_ITEM_ATTRIBUTION amz
		INNER JOIN L1.L1_DIM_A_ITEM it on it.ID_ITEM = amz.ID_ITEM
		INNER JOIN L1.L1_DIM_A_MARKETING_ACCOUNT acc on acc.[ID_MARKETING_ACCOUNT] = amz.[ID_MARKETING_ACCOUNT]
		LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL channel
				on channel.[CD_SALES_CHANNEL] = acc.[CD_SALES_CHANNEL]
		LEFT JOIN [L0].[L0_MI_COUNTRY_GROUP] cmd
					ON acc.CD_COUNTRY = cmd.COUNTRY
		WHERE 1=1
			and D_CAMPAIGN = '2025-10-01' 
			and [T_PRODUCT_HIERARCHY_4]  = 'Velaire'
			and channel.CD_CHANNEL_GROUP_3 = 'Amazon'
			and CountryGroup = 'DE'
		GROUP BY [T_PRODUCT_HIERARCHY_4],
				channel.CD_CHANNEL_GROUP_3,
				D_CAMPAIGN,
				ISNULL(cmd.CountryGroup,'INT')
		HAVING SUM((ISNULL([AMT_COST_EUR_ATT],0)+ISNULL([GOOGLE_AMT_COST_EUR_ATT],0)+ISNULL([DSP_AMT_COST_EUR_ATT],0))) >  0



		601.683699 --- 1/10/2025
		1704 NOV
