DECLARE @ProcessID  varchar(50) = '0407244050'


SELECT 
	Dataset = 'Steering Margin',
	ProcessID = CD_SALES_PROCESS_ID,
	ProcessIDLine = CD_SALES_PROCESS_LINE,
	ProcessIDate = D_SALES_PROCESS,
	ItemNo	=	NUM_ITEM,
	L2	=	T_PRODUCT_HIERARCHY_2,
	IncidentFlag = [FL_INCIDENT],
	ChannelGroup3 = CD_CHANNEL_GROUP_3,
	CountryInvoice = CD_COUNTRY_INVOICE,
	RefundRate = VL_RETURN_RATE,
	RefundRatesource = CD_REFUND_RATE_SOURCE,
	GrossOrderValue = AMT_GROSS_ORDER_VALUE_EUR,
	CancelledOrderValue = AMT_CANCELLED_ORDER_VALUE_EST_EUR,
	NetOrderValue = AMT_NET_ORDER_VALUE_EST_EUR,fact.*
FROM L1.[L1_FACT_A_SALES_TRANSACTION_KPI_SM] fact
LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL ch
	ON ch.ID_SALES_CHANNEL = fact.ID_SALES_CHANNEL
LEFT JOIN L1.L1_DIM_A_ITEM it
	ON it.ID_ITEM = fact.ID_ITEM
WHERE
	CD_SALES_PROCESS_ID = @ProcessID
	AND
	[CD_TYPE] in ('ZAA','ZKE','ZAZ')



SELECT 
	Dataset = 'Steering Margin TEST',
	ProcessID = CD_SALES_PROCESS_ID,
	ProcessIDLine = CD_SALES_PROCESS_LINE,
	ItemNo	=	NUM_ITEM,
	L2	=	T_PRODUCT_HIERARCHY_2,
	IncidentFlag = [FL_INCIDENT],
	ChannelGroup3 = CD_CHANNEL_GROUP_3,
	CountryInvoice = CD_COUNTRY_INVOICE,
	RefundRate = VL_RETURN_RATE,
	RefundRatesource = CD_REFUND_RATE_SOURCE,
	GrossOrderValue = AMT_GROSS_ORDER_VALUE_EUR,
	CancelledOrderValue = AMT_CANCELLED_ORDER_VALUE_EST_EUR,
	NetOrderValue = AMT_NET_ORDER_VALUE_EST_EUR,fact.*
FROM TEST.L1_FACT_A_SALES_TRANSACTION_KPI_SM fact
LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL ch
	ON ch.ID_SALES_CHANNEL = fact.ID_SALES_CHANNEL
LEFT JOIN L1.L1_DIM_A_ITEM it
	ON it.ID_ITEM = fact.ID_ITEM
WHERE
	CD_SALES_PROCESS_ID = @ProcessID
	AND
	[CD_TYPE] in ('ZAA','ZKE','ZAZ')


SELECT 
	Dataset = 'CPNL',
	ProcessID = CD_SALES_PROCESS_ID,
	ProcessIDLine = CD_SALES_PROCESS_LINE,
	ItemId	=	ID_ITEM,
	IncidentFlag = [FL_INCIDENT],
	ChannelGroup3 = CD_CHANNEL_GROUP_3,
	RefundRate = VL_RETURN_RATE,
	RefundRatesource = CD_REFUND_RATE_SOURCE,
	GrossOrderValue = AMT_GROSS_ORDER_VALUE_EUR,
	CancelledOrderValue = AMT_CANCELLED_ORDER_VALUE_EST_EUR,
	NetOrderValue = AMT_NET_ORDER_VALUE_EST_EUR
FROM L1.L1_FACT_A_SALES_TRANSACTION_KPI fact
LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL ch
	ON ch.ID_SALES_CHANNEL = fact.ID_SALES_CHANNEL
WHERE
	CD_SALES_PROCESS_ID = @ProcessID
	AND
	[CD_TYPE] in ('ZAA','ZKE','ZAZ')




SELECT 
	Dataset = 'Main Data',
	ProcessID = CD_SALES_PROCESS_ID,
	ProcessIDLine = CD_SALES_PROCESS_LINE,
	ProcessIDate = D_SALES_PROCESS,
	ItemNo	=	NUM_ITEM,
	L2	=	fact.T_PRODUCT_HIERARCHY_2,
	IncidentFlag = [FL_INCIDENT],
	ChannelGroup3 = CD_CHANNEL_GROUP_3,
	CountryInvoice = CD_COUNTRY_INVOICE,
	RefundRate = VL_RETURN_RATE,
	RefundRatesource = CD_REFUND_RATE_SOURCE,fact.*
	FROM L1.L1_FACT_A_SALES_TRANSACTION fact
LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL ch
	ON ch.ID_SALES_CHANNEL = fact.ID_SALES_CHANNEL
LEFT JOIN L1.L1_DIM_A_ITEM it
	ON it.ID_ITEM = fact.ID_ITEM
WHERE
	CD_SALES_PROCESS_ID = @ProcessID
	AND
	[CD_TYPE] in ('ZAA','ZKE','ZAZ')





	--select *
	--from L1.L1_DIM_A_ORDER_CANCELLATION_VALUES cll
	--where
	--CD_COUNTRY_INVOICE_GROUP = 'INT'
	--and '2025-03-17' BETWEEN cll.D_VALID_FROM AND cll.D_VALID_TO
	--and
	--[T_PRODUCT_HIERARCHY_2] = 'Fridges & Freezers'