  
  
  
  UPDATE b
    SET
	 [VL_REFUND_RATE] 					=	rrr.[VL_REFUND_RATE]
	,[VL_RETURN_RATE]					=	rrr.[VL_RETURN_RATE]
	,[VL_REPLACEMENT_RATE]			   =	rrr.[VL_REPLACEMENT_RATE]
	,[CD_REFUND_RATE_SOURCE] 		   =	rrr.[CD_REFUND_RATE_SOURCE]
    ,[CD_RETURN_RATE_SOURCE] 		   =	rrr.[CD_RETURN_RATE_SOURCE]
    ,[CD_REPLACEMENT_RATE_SOURCE]	   =	rrr.[CD_REPLACEMENT_RATE_SOURCE]
   FROM [L1].[L1_FACT_F_BUSINESS_PLAN] b
   INNER JOIN [L1].[L1_FACT_A_NOV_CLAIM_RATES] rrr
  	ON rrr.id_item = b.ID_ITEM
    AND '2024-01-01' BETWEEN rrr.d_valid_from and rrr.d_valid_to
	AND (rrr.CD_COUNTRY_INVOICE_GROUP is null OR rrr.CD_COUNTRY_INVOICE_GROUP = b.CD_COUNTRY_GROUP)
	AND (rrr.CD_COUNTRY_DELIVERY IS null OR rrr.CD_COUNTRY_DELIVERY = b.CD_COUNTRY_GROUP)
	AND (rrr.CD_CHANNEL_GROUP_3 is null OR REPLACE(rrr.CD_CHANNEL_GROUP_3,' ','') = REPLACE(b.CD_CHANNEL_GROUP_3,' ',''))     
where 
	b.D_TARGET = '2025-01-01'
	and ISNULL(b.[VL_REFUND_RATE],0)  = 0