
CREATE TABLE WayofDistribution
(
	WayofDistributionID VARCHAR(5) NOT NULL,
	[Name]  VARCHAR(50) NOT NULL,
	CreatedOn  datetime2 default(getdate()),
	ModifiedOn datetime2 default(getdate())

)
--INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '00','Direct Sales'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '10','E-Star'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '11','Klarstein'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '12','Auna'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '13','Blumfeldt'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '14','Capital Sports'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '15','Besoa'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '16','hifi-tower'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '17','Steakreaktor'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '18','Numan'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '20','SK E-Star'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '21','SK Klarstein'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '22','Famtastic'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '23','SK Blumfeldt'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '25','Allegro'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '30','Amazon'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '31','ebay'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '32','cdiscount'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '33','Darty'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '34','fnac'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '35','La Redoute'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '36','Boulanger'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '37','Rue du commerce'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '38','Conforama'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '39','Rakuten'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '40','Ricardo'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '41','Backmarket'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '42','Bol'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '43','MediaMarktSaturn'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '44','kaufland'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '45','Wayfair'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '46','Groupon'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '47','ManoMano'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '48','Check24'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '49','Rewe'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '50','Otto'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '51','Netto'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '52','Moebel24'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '53','Metro'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '54','AO'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '55','ePrice'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '56','BUT'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '57','LeroyMerlin'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '59','Obi'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '60','Amazon FBA'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '61','ubaldi'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '70','Sleepwise'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '71','Brunolie'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '72','Superlunary'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '91','B2B'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '93','Free Orders'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '95','SAGE'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '98','mitarbeiter.E-star'
INSERT INTO WayofDistribution(WayofDistributionID,[Name]) SELECT '99','Intercompany'

