with cte_sales as (

	SELECT CD_SALES_PROCESS_ID,CD_MARKET_ORDER_ID, SUM(AMT_TURNOVER_EUR)  AMT_TURNOVER_EUR, SUM(VL_ORDER_QUANTITY)VL_ORDER_QUANTITY, MIN(kpi.CD_FULFILLMENT)CD_FULFILLMENT, MIN(ch.T_SALES_CHANNEL)T_SALES_CHANNEL
	FROM L1.L1_FACT_A_SALES_TRANSACTION_KPI kpi
	LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL ch on ch.ID_SALES_CHANNEL = kpi.ID_SALES_CHANNEL
	where 
		kpi.CD_TYPE IN('ZKE')
	GROUP BY CD_MARKET_ORDER_ID,CD_SALES_PROCESS_ID
)

SELECT 
	PostingYear = NUM_POSTING_YEAR,
	PostingPeriod = NUM_POSTING_PERIOD,
	BillingDocumentNo = CD_FI_DOCUMENT_NO,
	BillingType = CD_DOCUMENT_TYPE_FI,
	ClearingDate = D_CLEARING_DATE,
	ClearingNo = CD_CLEARING_DOCUMENT_NO,
	PositionText = acdoca.SGTXT,
	Amount = AMT_AMOUNT_TRANSACTION,
	Currency = CD_CURRENCY_TRANSACTION,
	CustomerReference = acdoca.ZUONR,
	AmazonAmount = amz.[AMT_ECOMMERCE_ITEM_TURNOVER_FC],
	AmazonQty = amz.CNT_QUANTITY,

	SalesOrder = sales.CD_SALES_PROCESS_ID,
	SalesGrossOrderValue = sales.AMT_TURNOVER_EUR,
	SalesGrossOrderValue = sales.VL_ORDER_QUANTITY,
	SalesOffice = sales.T_SALES_CHANNEL,
	Fulfillment = sales.CD_FULFILLMENT,

	PossibleProblem = CASE 
							WHEN sales.CD_SALES_PROCESS_ID IS NULL THEN 'Invoice missing' 
							WHEN abs(AMT_AMOUNT_TRANSACTION) <> abs(amz.[AMT_ECOMMERCE_ITEM_TURNOVER_FC]) THEN 'Invoice wrong (< payment)' 
							ELSE NULL END,
	--AMT_AMOUNT_BALANCE,
	--CD_CURRENCY_BALANCE,

	fact.*
FROM L1_FIN.L1_FACT_A_GENERAL_LEDGER fact
INNER JOIN L1.L1_DIM_A_COMPANY cp on cp.ID_COMPANY = fact.ID_COMPANY
INNER JOIN L0_FIN.L0_S4HANA_0FI_ACDOCA_10 acdoca
	on 
		acdoca.RLDNR = fact.CD_LEDGER 
		and acdoca.RBUKRS = cp.CD_COMPANY
		and acdoca.GJAHR = fact.NUM_POSTING_YEAR 
		and acdoca.BELNR = fact.CD_FI_DOCUMENT_NO 
		and acdoca.DOCLN = fact.CD_FI_DOCUMENT_LINE 
LEFT JOIN L0_FIN.L0_S4HANA_Z_FI_BKPF bkpf
	on 	 bkpf.BUKRS = acdoca.RBUKRS
	and bkpf.GJAHR = acdoca.GJAHR
    and bkpf.BELNR = acdoca.BELNR	
LEFT JOIN cte_sales sales on REPLACE(sales.CD_MARKET_ORDER_ID,'-','') = acdoca.ZUONR
LEFT JOIN L1.L1_FACT_A_AMAZON_ORDER_DAILY amz on REPLACE(amz.CD_AMAZON_ORDER,'-','') = acdoca.ZUONR
WHERE 1=1
	--AND YEAR(D_FI_CREATED) = 2022
	--AND CD_FI_DOCUMENT_NO = '1404680301'
	and CD_DOCUMENT_TYPE_FI in ('DM','RR')
	and acdoca.ZUONR = '02803261945703578'
	--AND 
	--	ISNULL(D_CLEARING_DATE,'') = ''


	--select * FROM L1.L1_FACT_A_SALES_TRANSACTION_KPI where CD_MARKET_ORDER_ID like'%028-0041859-9631533' 
	--select top 10 * FROM L1.L1_FACT_A_AMAZON_ORDER_DAILY where CD_AMAZON_ORDER ='028-0041859-9631533' 
	--028-0041859-9631533


	--select * from L1.L1_DIM_A_SALES_CHANNEL where id_sales_channel = 29088




	--sL1_FACT_A_AMAZON_SETTLEMENT_REPORT
	--L1_FACT_A_AMAZON_ORDER_DAILY
