CREATE TABLE L1.L1_FACT_A_SALES_TRANSACTION_MKT_KPI_SM
(
	ID_SALES_TRANSACTION	INT NULL,
	CD_SALES_TRANSACTION	VARCHAR(50),
	CD_SOURCE_SYSTEM		VARCHAR(10),
	D_CREATED				DATE,
	ID_ITEM					INT,
	CD_CHANNEL_GROUP_3		VARCHAR(50),
	CD_COUNTRY_GROUP		VARCHAR(10),
	AMT_MKT_COST_EUR		DECIMAL(19),
    [DT_DWH_CREATED]                SMALLDATETIME NOT NULL,
    [DT_DWH_UPDATED]                SMALLDATETIME NOT NULL

)