

;with cte_sm_table as
(
	SELECT s.*,it.T_PRODUCT_HIERARCHY_4,CD_CHANNEL_GROUP_3 = REPLACE(ch.[CD_CHANNEL_GROUP_3],' ',''),
	CD_COUNTRY_GROUP_DELIVERY_SM = CASE WHEN [CD_COUNTRY_DELIVERY] in('PL','FR','CZ','HR','NL','IT','GB','RO','HU','ES','BG','DE','SI','SK') THEN [CD_COUNTRY_DELIVERY]
							  WHEN  right (ch.[CD_CHANNEL_GROUP_1], 3) ='CEE' then 'SK' 
							  ELSE 'INT' END,
							  it.NUM_ITEM
	FROM TEST.L1_FACT_A_SALES_TRANSACTION_KPI_SM s
	INNER JOIN L1.L1_DIM_A_ITEM it on it.ID_ITEM = s.ID_ITEM
	LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL ch on ch.ID_SALES_CHANNEL = s.ID_SALES_CHANNEL
WHERE 1=1
	and s.D_CREATED between '2025-01-01' and '2025-08-30'
	--and 
	--it.T_PRODUCT_HIERARCHY_4 = 'Karaffe'
	and
	ch.CD_CHANNEL_GROUP_3 not in ('Others')
		
),CTE_TOTAL_NOV AS
(
	SELECT *,
		AMT_TOTAL_NOV_FAMILY_EUR = SUM(ISNULL(AMT_NET_ORDER_VALUE_EST_EUR,0)) 
					OVER(PARTITION BY T_PRODUCT_HIERARCHY_4,  DATEPART(WEEK, D_CREATED) ,[CD_CHANNEL_GROUP_3],CD_COUNTRY_GROUP_DELIVERY_SM )
		,PERC_NOV_FAMILY_SHARE = CASE WHEN AMT_NET_ORDER_VALUE_EST_EUR = 0 THEN 0 ELSE AMT_NET_ORDER_VALUE_EST_EUR / SUM(ISNULL(AMT_NET_ORDER_VALUE_EST_EUR,0)) 
					OVER(PARTITION BY T_PRODUCT_HIERARCHY_4, DATEPART(WEEK, D_CREATED) ,[CD_CHANNEL_GROUP_3],CD_COUNTRY_GROUP_DELIVERY_SM )END
		,AMT_TOTAL_NOV_ITEM_EUR = SUM(ISNULL(AMT_NET_ORDER_VALUE_EST_EUR,0)) 
					OVER(PARTITION BY NUM_ITEM, DATEPART(WEEK, D_CREATED) ,[CD_CHANNEL_GROUP_3],CD_COUNTRY_GROUP_DELIVERY_SM )
		,PERC_NOV_ITEM_SHARE = CASE WHEN AMT_NET_ORDER_VALUE_EST_EUR = 0 THEN 0 ELSE AMT_NET_ORDER_VALUE_EST_EUR / SUM(ISNULL(AMT_NET_ORDER_VALUE_EST_EUR,0)) 
					OVER(PARTITION BY NUM_ITEM, DATEPART(WEEK, D_CREATED) ,[CD_CHANNEL_GROUP_3],CD_COUNTRY_GROUP_DELIVERY_SM )END

	FROM cte_sm_table
	 


),cte_agg_mkt_fam as
(
	SELECT
		TransactionPeriod = DATEPART(WEEK, TransactionDate) ,
		ProductFamily,
		ChannelGroup3,
		CountryGroup,
		MarketingAmazon = SUM(ISNULL(MarketingAmazon,0)),
		MarketingGoogle = SUM(ISNULL(MarketingGoogle,0)),
		MarketingD2C = SUM(ISNULL(MarketingD2C,0))

	FROM TEST.PL_V_MARKETING_COST_SM_v2
	GROUP BY 
		DATEPART(WEEK, TransactionDate) ,
		ProductFamily,
		ChannelGroup3,
		CountryGroup
),cte_agg_mkt_item as
(
	SELECT
		TransactionPeriod = DATEPART(WEEK, TransactionDate) ,
		ItemNo,
		ChannelGroup3,
		CountryGroup,
		MarketingAmazon = SUM(ISNULL(MarketingAmazon,0)),
		MarketingGoogle = SUM(ISNULL(MarketingGoogle,0)),
		MarketingD2C = SUM(ISNULL(MarketingD2C,0))

	FROM TEST.PL_V_MARKETING_COST_SM_ITEM
	GROUP BY 
		DATEPART(WEEK, TransactionDate) ,
		ItemNo,
		ChannelGroup3,
		CountryGroup
)
,
CTE_MKT_COST AS
(

	SELECT s.*
		,AMT_MAKETING_AMAZON_COST_EUR = ISNULL(mkt_fam.MarketingAmazon * PERC_NOV_FAMILY_SHARE,0) +  ISNULL(mkt_item.MarketingAmazon * PERC_NOV_ITEM_SHARE,0)
		,AMT_MAKETING_GGL_COST_EUR = ISNULL(mkt_fam.MarketingGoogle * PERC_NOV_FAMILY_SHARE,0)+  ISNULL(mkt_item.MarketingGoogle * PERC_NOV_ITEM_SHARE,0)
		,AMT_MAKETING_D2C_COST_EUR = ISNULL(mkt_fam.MarketingD2C * PERC_NOV_FAMILY_SHARE,0)+  ISNULL(mkt_item.MarketingD2C * PERC_NOV_ITEM_SHARE,0)
	FROM CTE_TOTAL_NOV s
	LEFT JOIN cte_agg_mkt_fam mkt_fam 
			on  
				mkt_fam.TransactionPeriod = DATEPART(WEEK, D_CREATED)
				AND
				mkt_fam.ProductFamily = T_PRODUCT_HIERARCHY_4
				AND
				mkt_fam.ChannelGroup3 = [CD_CHANNEL_GROUP_3]
				AND
				mkt_fam.CountryGroup = CD_COUNTRY_GROUP_DELIVERY_SM
	LEFT JOIN cte_agg_mkt_item mkt_item 
			on  
				mkt_item.TransactionPeriod = DATEPART(WEEK, D_CREATED)
				AND
				mkt_item.ItemNo = s.NUM_ITEM
				AND
				mkt_item.ChannelGroup3 = [CD_CHANNEL_GROUP_3]
				AND
				mkt_item.CountryGroup = CD_COUNTRY_GROUP_DELIVERY_SM


)

SELECT
	--s.*
	TransactionMonth = MONTH(D_CREATED),CD_COUNTRY_GROUP_DELIVERY_SM,
	NOV = SUM(AMT_NET_ORDER_VALUE_EST_EUR),
	MarketingEst = SUM(ISNULL(AMT_MARKETING_ATTRIBUTION_EST_EUR,0)),
	MarketingCostAtributed =  sum(ISNULL(AMT_MAKETING_AMAZON_COST_EUR,0) + ISNULL(AMT_MAKETING_GGL_COST_EUR,0)+ISNULL(AMT_MAKETING_D2C_COST_EUR,0))
	--,AMT_STEERING_MARGIN_WITH_MKT_EST_EUR = ISNULL(AMT_STEERING_MARGIN_EST_EUR,0) + ISNULL(AMT_MARKETING_ATTRIBUTION_EST_EUR,0) -
	--											(ISNULL(AMT_MAKETING_AMAZON_COST_EUR,0) + ISNULL(AMT_MAKETING_GGL_COST_EUR,0)+ISNULL(AMT_MAKETING_D2C_COST_EUR,0))

FROM CTE_MKT_COST s
GROUP BY MONTH(D_CREATED),CD_COUNTRY_GROUP_DELIVERY_SM
order by 1,2

