/****** Object:  Table [TEST].[L1_FACT_F_BUSINESS_PLAN_KPI_SM]    Script Date: 08/07/2025 09:24:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [TEST].[L1_FACT_F_BUSINESS_PLAN_KPI_SM_V2]
(
	[D_SNAPSHOT] [date] NULL,
	[ID_COMPANY] [int] NULL,
	[D_TARGET] [date] NULL,
	[CD_SOURCE] [varchar](50) NULL,
	[ID_ITEM] [int] NULL,
	[ID_ITEM_BUSINESS_PLAN] [int] NULL,
	[CD_FULFILLMENT] [varchar](5) NULL,
	[T_REVISED_LOCATION] [varchar](50) NULL,
	[CD_COUNTRY_GROUP] [varchar](50) NULL,
	[CD_CHANNEL_GROUP_3] [varchar](50) NULL,
	[CD_CURRENCY] [varchar](5) NULL,
	[VL_ITEM_QUANTITY] [decimal](19, 2) NULL,
	[AMT_PLAN_PRICE_EUR] [decimal](19, 2) NULL,
	[AMT_SHIPPING_COST_EST_EUR] [decimal](19, 2) NULL,
	[AMT_MEK_HEDGING_EUR] [decimal](19, 2) NULL,
	[AMT_GTS_MARKUP_EUR] [decimal](19, 2) NULL,
	[AMT_MEK_WITHOUT_GTS_EUR] [decimal](19, 2) NULL,
	[VL_CANCELLED_ORDERS_QUANTITY_EST] [decimal](19, 2) NULL,
	[VL_NET_ORDER_QUANTITY] [decimal](19, 2) NULL,
	[VL_REFUNDED_QUANTITY_EST] [decimal](19, 2) NULL,
	[VL_RETURNED_QUANTITY_EST] [decimal](19, 2) NULL,
	[VL_REPLACEMENT_QUANTITY_EST] [decimal](19, 2) NULL,
	[AMT_GROSS_ORDER_VALUE_EUR] [decimal](19, 2) NULL,
	[AMT_CANCELLED_ORDER_VALUE_EST_EUR] [decimal](19, 2) NULL,
	[AMT_NET_ORDER_VALUE_EST_EUR] [decimal](19, 2) NULL,
	[AMT_REFUNDED_ORDER_VALUE_EST_EUR] [decimal](19, 2) NULL,
	[AMT_REVENUE_EST_EUR] [decimal](19, 2) NULL,
	[AMT_DEPRECIATION_EST_EUR] [decimal](19, 2) NULL,
	[AMT_FULFILLMENT_OUTBOUND_EST_EUR] [decimal](19, 2) NULL,
	[AMT_SHIPPING_COST_INVOICED_PLAN_SM] [decimal](19, 6) NULL,
	[AMT_SHIPPING_COST_RETURNED_PLAN_SM] [decimal](19, 6) NULL,
	[AMT_SHIPPING_COST_REPLACED_PLAN_SM] [decimal](19, 6) NULL,
	[AMT_COMMISSIONS_MARKETPLACES_EUR] [decimal](19, 2) NULL,
	[AMT_COMMISSIONS_MARKETPLACES_REFUNDS_EUR] [decimal](19, 2) NULL,
	
	[AMT_MARKETING_MARKETPLACES_EST_EUR] [decimal](19, 2) NULL,
	
	[AMT_COMMISSIONS_AMAZON_EUR] [decimal](19, 2) NULL,
	[AMT_COMMISSIONS_AMAZON_REFUNDS_EUR] [decimal](19, 2) NULL,
		
	[AMT_PAYMENTS_EUR] [decimal](19, 2) NULL,
	
	[AMT_ENVIRO_AND_LICENSE_COST_EST_EUR] [decimal](19, 2) NULL,
	[AMT_ENVIRO_REST_UNIT_FEE_EUR] [decimal](19, 6) NULL,
	[AMT_REPACKAGING_EUR] [decimal](19, 6) NULL,
	[AMT_NET_ORDER_CONTRIBUTION_EST_EUR] [decimal](19, 2) NULL,

	[AMT_FULL_NET_PRODUCT_COST_PLAN_EUR_SM] [decimal](19, 6) NULL,

	[AMT_MEK_TO_CUSTOMER_PLAN_EUR_SM] [decimal](19, 6) NULL,
	[AMT_MEK_FROM_CUSTOMER_PLAN_EUR_SM] [decimal](19, 6) NULL,
	[AMT_MEK_REPLACEMENT_PLAN_EUR_SM] [decimal](19, 6) NULL,
	[AMT_MEK_DEPRECIATION_PLAN_EUR_SM] [decimal](19, 6) NULL,

	[AMT_MARKETING_ATTRIBUTION_PLAN_EUR_SM] [decimal](19, 6) NULL,

	[AMT_COMMISSIONS_PLAN_EUR_SM] [decimal](19, 6) NULL,
	
	[AMT_COMMISSIONS_SALE_PLAN_EUR_SM] [decimal](19, 6) NULL,
	[AMT_COMMISSIONS_REFUNDS_PLAN_EUR_SM] [decimal](19, 6) NULL,

	[AMT_STEERING_MARGIN_PLAN_EUR_SM] [decimal](19, 6) NULL,

	
	[DT_DWH_CREATED] [smalldatetime] NOT NULL,
	[DT_DWH_UPDATED] [smalldatetime] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH ( [D_SNAPSHOT] ),
	CLUSTERED COLUMNSTORE INDEX
)
GO


