/****** Object:  Table [TEST].[L1_FACT_F_BUSINESS_PLAN_DAILY_SM]    Script Date: 10/07/2025 08:06:24 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [TEST].[L1_FACT_F_BUSINESS_PLAN_SM]
(
	[D_SNAPSHOT] [date] NULL,
	[D_TARGET] [date] NULL,
	[CD_SOURCE] [varchar](50) NULL,
	[D_TARGET_LOOKUP] [date] NULL,
	[ID_ITEM] [int] NULL,
	[ID_ITEM_BUSINESS_PLAN] [int] NULL,
	[ID_COMPANY] [int] NULL,
	[CD_CHANNEL_GROUP_3] [varchar](50) NULL,
	[CD_CHANNEL_GROUP_1] [varchar](50) NULL,
	[CD_COUNTRY_GROUP] [varchar](50) NULL,
	[CD_CURRENCY] [varchar](5) NULL,
	[T_REVISED_LOCATION] [varchar](150) NULL,
	[CD_FULFILLMENT] [varchar](5) NULL,
	[AMT_PLAN_PRICE_EUR] [decimal](19, 2) NULL,
	[VL_ITEM_QUANTITY] [decimal](19, 2) NULL,
	[AMT_MEK_HEDGING_EUR] [decimal](19, 2) NULL,
	[AMT_GTS_MARKUP_EUR] [decimal](19, 2) NULL,
	[AMT_SHIPPING_COST_EST_EUR] [decimal](19, 2) NULL,
	[AMT_TARGET_NET_ORDER_VALUE_EUR] [decimal](19, 2) NULL,
	[VL_REFUND_RATE] [decimal](19, 2) NULL,
	[VL_RETURN_RATE] [decimal](19, 2) NULL,
	[VL_REPLACEMENT_RATE] [decimal](19, 2) NULL,
	[CD_REFUND_RATE_SOURCE] [varchar](50) NULL,
	[CD_RETURN_RATE_SOURCE] [varchar](50) NULL,
	[CD_REPLACEMENT_RATE_SOURCE] [varchar](50) NULL,
	[DT_DWH_CREATED] [smalldatetime] NOT NULL,
	[DT_DWH_UPDATED] [smalldatetime] NOT NULL
)
WITH
(
	DISTRIBUTION = HASH ( [D_SNAPSHOT] ),
	CLUSTERED COLUMNSTORE INDEX
)
GO


