CREATE TEST.PL_V_SM_FIXED_COSTS_ESTIMATE
AS

SELECT [DATE] 
      ,[POSITION]
      ,[SUBITEM]
      ,[STORAGELOCATIONCODE]
      ,[COMMEMNT]
      ,[VALUE]
      ,[ADDEDON]
  FROM [TEST].[L0_MI_SM_FIX_COST_ESTIMATE]
