--L1.L1_FACT_A_SALES_TRANSACTION_KPI_STEERING 
ALTER VIEW TEST.PL_V_MARKETING_COST_SM_v2
AS
with CTE_MKT_AMAZON AS 
(


SELECT 
	D_CAMPAIGN,
	[T_PRODUCT_HIERARCHY_4],
	CD_CHANNEL_GROUP_3 = channel.CD_CHANNEL_GROUP_3,
	CountryGroup = CASE WHEN acc.CD_COUNTRY in('PL','FR','CZ','HR','IT','GB','NL','RO','HU','ES','BG','DE','SI','SK') THEN acc.CD_COUNTRY
							  WHEN  channel.CD_CHANNEL_GROUP_3 ='CEE' then 'SK' 
							  ELSE 'INT' END,
	MKT_AMT = SUM((ISNULL([AMT_COST_EUR_ATT],0)+ISNULL([GOOGLE_AMT_COST_EUR_ATT],0)+ISNULL([DSP_AMT_COST_EUR_ATT],0))) 
FROM 
[L1].L1_FACT_A_AMAZON_ITEM_ATTRIBUTION amz
INNER JOIN L1.L1_DIM_A_ITEM it on it.ID_ITEM = amz.ID_ITEM
INNER JOIN L1.L1_DIM_A_MARKETING_ACCOUNT acc on acc.[ID_MARKETING_ACCOUNT] = amz.[ID_MARKETING_ACCOUNT]
LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL channel
        on channel.[CD_SALES_CHANNEL] = acc.[CD_SALES_CHANNEL]
WHERE
 YEAR(D_CAMPAIGN) >= 2025 and [T_PRODUCT_HIERARCHY_4] is not null
GROUP BY [T_PRODUCT_HIERARCHY_4],channel.CD_CHANNEL_GROUP_3,D_CAMPAIGN,
CASE WHEN acc.CD_COUNTRY in ('PL','FR','CZ','HR','IT','GB','NL','RO','HU','ES','BG','DE','SI','SK') THEN acc.CD_COUNTRY
							  WHEN  channel.CD_CHANNEL_GROUP_3 ='CEE' then 'SK' 
							  ELSE 'INT' END
HAVING SUM((ISNULL([AMT_COST_EUR_ATT],0)+ISNULL([GOOGLE_AMT_COST_EUR_ATT],0)+ISNULL([DSP_AMT_COST_EUR_ATT],0))) >  0
),
CTE_MKT_GOOGLE AS 
(


SELECT 	D_CAMPAIGN,
	[T_PRODUCT_HIERARCHY_4],
	CD_CHANNEL_GROUP_3 = channel.CD_CHANNEL_GROUP_3,
	CountryGroup = CASE WHEN acc.CD_COUNTRY in('PL','FR','CZ','HR','IT','GB','NL','RO','HU','ES','BG','DE','SI','SK') THEN acc.CD_COUNTRY
							  WHEN  channel.CD_CHANNEL_GROUP_3 ='CEE' then 'SK' 
							  ELSE 'INT' END,
	GGL_AMT = SUM(ISNULL([AMT_COST_EUR_ATT],0)) 
FROM 
[L1].L1_FACT_A_GOOGLE_ITEM_ATTRIBUTION amz
INNER JOIN L1.L1_DIM_A_ITEM it on it.ID_ITEM = amz.ID_ITEM
INNER JOIN L1.L1_DIM_A_MARKETING_ACCOUNT acc on acc.[ID_MARKETING_ACCOUNT] = amz.[ID_MARKETING_ACCOUNT]
LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL channel
        on channel.[CD_SALES_CHANNEL] = acc.[CD_SALES_CHANNEL]
WHERE
 YEAR(D_CAMPAIGN) >= 2025 and [T_PRODUCT_HIERARCHY_4] is not null
GROUP BY [T_PRODUCT_HIERARCHY_4],channel.CD_CHANNEL_GROUP_3,D_CAMPAIGN,
CASE WHEN acc.CD_COUNTRY in ('PL','FR','CZ','HR','IT','GB','NL','RO','HU','ES','BG','DE','SI','SK') THEN acc.CD_COUNTRY
							  WHEN  channel.CD_CHANNEL_GROUP_3 ='CEE' then 'SK' 
							  ELSE 'INT' END
HAVING SUM(ISNULL([AMT_COST_EUR_ATT],0)) > 0 
),
CTE_MKT_D2C AS 
(


SELECT 	D_CAMPAIGN,
	[T_PRODUCT_HIERARCHY_4],
	CD_CHANNEL_GROUP_3 = channel.CD_CHANNEL_GROUP_3,
	CountryGroup = CASE WHEN acc.CD_COUNTRY in('PL','FR','CZ','HR','IT','GB','NL','RO','HU','ES','BG','DE','SI','SK') THEN acc.CD_COUNTRY
							  WHEN  channel.CD_CHANNEL_GROUP_3 ='CEE' then 'SK' 
							  ELSE 'INT' END,
	D2C_AMT = SUM(ISNULL([AMT_COST_EUR_ATT],0)) 
FROM 
[L1].L1_FACT_A_D2C_PERFORMANCE_ITEM amz
INNER JOIN L1.L1_DIM_A_ITEM it on it.ID_ITEM = amz.ID_ITEM
INNER JOIN L1.L1_DIM_A_MARKETING_ACCOUNT acc on acc.[ID_MARKETING_ACCOUNT] = amz.[ID_MARKETING_ACCOUNT]
LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL channel
        on channel.[CD_SALES_CHANNEL] = acc.[CD_SALES_CHANNEL]
WHERE
 YEAR(D_CAMPAIGN) >= 2025 and [T_PRODUCT_HIERARCHY_4] is not null
GROUP BY [T_PRODUCT_HIERARCHY_4],channel.CD_CHANNEL_GROUP_3,D_CAMPAIGN,
CASE WHEN acc.CD_COUNTRY in ('PL','FR','CZ','HR','IT','GB','NL','RO','HU','ES','BG','DE','SI','SK') THEN acc.CD_COUNTRY
							  WHEN  channel.CD_CHANNEL_GROUP_3 ='CEE' then 'SK' 
							  ELSE 'INT' END
HAVING SUM(ISNULL([AMT_COST_EUR_ATT],0)) > 0 

)
--SELECT 
--	MarketingSource = 'Amazon',
--	TransactionDate = D_CAMPAIGN,
--	ProductFamily = [T_PRODUCT_HIERARCHY_4],
--	ChannelGroup3 = REPLACE(CD_CHANNEL_GROUP_3,' ',''),
--	CountryGroup = CountryGroup,
--	Marketingcost = MKT_AMT
--FROM CTE_MKT_AMAZON
--UNION
--SELECT 
--	MarketingSource = 'GGL',
--	TransactionDate = D_CAMPAIGN,
--	ProductFamily = [T_PRODUCT_HIERARCHY_4],
--	ChannelGroup3 = REPLACE(CD_CHANNEL_GROUP_3,' ',''),
--	CountryGroup = CountryGroup,
--	Marketingcost = GGL_AMT
--FROM CTE_MKT_GOOGLE
--UNION
--SELECT 
--	MarketingSource = 'D2C',
--	TransactionDate = D_CAMPAIGN,
--	ProductFamily = [T_PRODUCT_HIERARCHY_4],
--	ChannelGroup3 = REPLACE(CD_CHANNEL_GROUP_3,' ',''),
--	CountryGroup = CountryGroup,
--	Marketingcost = D2C_AMT
--FROM CTE_MKT_D2C

SELECT 
	MarketingSource = 'MKT',
	TransactionDate = ISNULL(amz.D_CAMPAIGN,ISNULL(ggl.D_CAMPAIGN,d2c.D_CAMPAIGN)),
	ProductFamily = ISNULL(amz.[T_PRODUCT_HIERARCHY_4],ISNULL(ggl.[T_PRODUCT_HIERARCHY_4],d2c.[T_PRODUCT_HIERARCHY_4])),
	ChannelGroup3 = REPLACE(ISNULL(amz.CD_CHANNEL_GROUP_3,ISNULL(ggl.CD_CHANNEL_GROUP_3,d2c.CD_CHANNEL_GROUP_3)),' ',''),
	CountryGroup = ISNULL(amz.CountryGroup,ISNULL(ggl.CountryGroup,d2c.CountryGroup)),
	MarketingAmazon = ISNULL(MKT_AMT,0), 
	MarketingGoogle = ISNULL(GGL_AMT,0), 
	MarketingD2C	= ISNULL(D2C_AMT,0)
FROM CTE_MKT_AMAZON amz
FULL JOIN CTE_MKT_GOOGLE ggl
	on
		amz.D_CAMPAIGN = ggl.D_CAMPAIGN
		AND 
		amz.[T_PRODUCT_HIERARCHY_4] = ggl.[T_PRODUCT_HIERARCHY_4]
		AND
		REPLACE(amz.CD_CHANNEL_GROUP_3,' ','') = REPLACE(ggl.CD_CHANNEL_GROUP_3,' ','')
		AND
		amz.CountryGroup=  ggl.CountryGroup
FULL JOIN CTE_MKT_D2C d2c
	on
		d2c.D_CAMPAIGN = ggl.D_CAMPAIGN
		AND 
		d2c.[T_PRODUCT_HIERARCHY_4] = ggl.[T_PRODUCT_HIERARCHY_4]
		AND
		REPLACE(d2c.CD_CHANNEL_GROUP_3,' ','') = REPLACE(ggl.CD_CHANNEL_GROUP_3,' ','')
		AND
		d2c.CountryGroup=  ggl.CountryGroup




		--SELECT sum(ISNULL(MarketingAmazon,0)+ISNULL(MarketingGoogle,0)+ISNULL(MarketingD2C,0)) 
		--FROM TEST.PL_V_MARKETING_COST_SM_v2 where TransactionDate between '2025-06-01' and '2025-06-30'




