/****** Object:  StoredProcedure [TEST].[WR_TX_L1_FACT_F_BUSINESS_PLAN_L1_FACT_F_BUSINESS_PLAN_KPI_SM]    Script Date: 07/07/2025 11:03:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROC [TEST].[WR_TX_L1_FACT_F_BUSINESS_PLAN_L1_FACT_F_BUSINESS_PLAN_KPI_SM] @MonthDate datetime AS
BEGIN

--[TEST].[WR_TX_L1_FACT_F_BUSINESS_PLAN_L1_FACT_F_BUSINESS_PLAN_KPI_SM] @MonthDate = '2025-12-01'


DECLARE @LastBPReload as datetime
DECLARE @LastBPSMReload as datetime

SELECT @LastBPReload = MAX(LOAD_TIMESTAMP)
from L0.L0_MI_BUSINESS_PLAN 

SELECT  @LastBPSMReload = MAX([DT_DWH_UPDATED])
from [TEST].L1_FACT_F_BUSINESS_PLAN_SM 
WHERE 
	MONTH(D_TARGET) = 	MONTH(@MonthDate)
	AND
	YEAR(D_TARGET) = 	YEAR(@MonthDate)

IF (@LastBPSMReload < @LastBPReload)
BEGIN

	--UPDATE THE DAILY TABLE
	EXEC [TEST].[WR_TX_L0_MI_BUSINESS_PLAN_L1_FACT_F_BUSINESS_PLAN_SM] @MonthDate = @MonthDate

	---DELETE FROM THE KPI TABLE
	DELETE FROM TEST.[L1_FACT_F_BUSINESS_PLAN_KPI_SM] 
	WHERE 
	MONTH(D_TARGET) = 	MONTH(@MonthDate)
	AND
	YEAR(D_TARGET) = 	YEAR(@MonthDate)

---START KPI

;WITH CTE_ENVIRO as 
    (
	        SELECT ID_ITEM,CD_COUNTRY_DELIVERY,NUM_YEAR,CD_CURRENCY,sum(AMT_FEE_PER_UNIT) AMT_FEE_PER_UNIT 
			from [L1].[L1_DIM_A_ENVIRO_REST_UNIT_FEES]
            GROUP BY ID_ITEM,CD_COUNTRY_DELIVERY,NUM_YEAR,CD_CURRENCY
    ),
 
CTE_CS_PAYMENTS AS (
		select D_VALID_FROM,D_VALID_TO,CD_CHANNEL_GROUP_3, AVG(PCT_PAYMENTS_ORDER)PCT_PAYMENTS_ORDER
		from  [L1].[L1_DIM_A_CS_PAYMENTS] cspayment
		INNER JOIN L1.L1_DIM_A_SALES_CHANNEL ch
			on ch.ID_SALES_CHANNEL = cspayment.ID_SALES_CHANNEL
		GROUP BY
			D_VALID_FROM,D_VALID_TO,CD_CHANNEL_GROUP_3
),
CTE_SALES_L1 AS (
						SELECT 
			 fact.D_SNAPSHOT
			 ,fact.CD_SOURCE
			,fact.ID_COMPANY											
			,fact.D_TARGET 												
			,fact.ID_ITEM												
			,fact.ID_ITEM_BUSINESS_PLAN									
			,fact.CD_FULFILLMENT										
			,fact.T_REVISED_LOCATION									
			,fact.[CD_COUNTRY_GROUP]									
			,fact.[CD_CHANNEL_GROUP_3]
			,fact.VL_ITEM_QUANTITY										
			,AMT_PLAN_PRICE_EUR											
			,AMT_SHIPPING_COST_EST_EUR	
			,AMT_MEK_HEDGING_EUR = CASE WHEN fact.AMT_MEK_HEDGING_EUR = 0 THEN ISNULL(itemdefault.[MEK_HEDGING],0) ELSE	fact.AMT_MEK_HEDGING_EUR END			--AS MEKHedging
			,AMT_GTS_MARKUP_EUR														
			,[AMT_TARGET_NET_ORDER_VALUE_EUR]
			,fact.CD_CURRENCY													
			,item.NUM_ITEM
            ,fact.VL_REFUND_RATE 					
	        ,fact.VL_RETURN_RATE					
        	,fact.VL_REPLACEMENT_RATE 	
			,fact.CD_REFUND_RATE_SOURCE 
            ,fact.CD_RETURN_RATE_SOURCE 
            ,fact.CD_REPLACEMENT_RATE_SOURCE 												

			,[PCT_COMMISSIONS_MARKETPLACES] = ISNULL(com_mkt_bs.[MARKETPLACERATE],0)				
			,[PCT_COMMISSIONS_MARKETPLACES_RETURN] = ISNULL(com_mkt_bs.[MARKETPLACERATE],0)
			
			,[PCT_PAYMENTS_ORDER] = ISNULL(PAY.PCT_PAYMENTS_ORDER, 0)	

	        ,VL_COMMISSIONS_ORDER_RATE = c_amaz.[VL_COMMISSIONS_ORDER_RATE]			
			,LOAD_TIMESTAMP = 	fact.DT_DWH_UPDATED						

			,AMT_PRECALC_ENVIRO_REST_UNIT_FEE_EUR = env.AMT_FEE_PER_UNIT * COALESCE(enviro_rate.VL_FX_RATE, 1) --AS EnviroRestUnitFee_PreCalc
            ,AMT_PRECALC_REPACKAGING_EUR = repack.AMT_FEE_PER_UNIT * COALESCE(enviro_rate.VL_FX_RATE, 1) * 0.025 --AS Repackaging_PreCalc							

			,[AMT_CORRECTION_FACTOR_ORDER] = ISNULL(factor.[AMT_CORRECTION_FACTOR_ORDER],1) 
            ,[AMT_CORRECTION_FACTOR_RETURN] = ISNULL(factor.[AMT_CORRECTION_FACTOR_RETURN],1)
            ,[AMT_CORRECTION_FACTOR_REPLACEMENT] = ISNULL(factor.[AMT_CORRECTION_FACTOR_REPLACEMENT],1)

			,PCT_MKT_RATE = mkt.MARKETINGRATE

			,PCT_VAT_VALUE = CASE WHEN ISNULL(vat.PCT_VALUE,0) = 0 THEN 0 ELSE vat.PCT_VALUE / 100 END
			,item.T_PRODUCT_HIERARCHY_2
			--FROM [L1].[L1_FACT_F_BUSINESS_PLAN] fact 
			FROM [TEST].L1_FACT_F_BUSINESS_PLAN_SM fact
			LEFT JOIN [L1].[L1_DIM_A_ITEM] item 
				ON item.[ID_ITEM]=fact.ID_ITEM
			LEFT JOIN [L1].[L1_DIM_A_ITEM_BUSINESS_PLAN] itemBS
				ON itemBS.[ID_ITEM_BUSINESS_PLAN]=fact.[ID_ITEM_BUSINESS_PLAN]
			LEFT JOIN [L0].L0_MI_BUSINESS_PLAN_ITEM_DEFAULT itemdefault
				ON itemdefault.Itemno=itemBS.NUM_ITEM
			LEFT JOIN [L1].[L1_DIM_A_COMPANY] dimcomp
				 on dimcomp.ID_COMPANY=fact.ID_COMPANY
			LEFT JOIN CTE_CS_PAYMENTS		AS PAY
				ON fact.CD_CHANNEL_GROUP_3 = PAY.CD_CHANNEL_GROUP_3
					AND fact.D_TARGET_LOOKUP BETWEEN PAY.D_VALID_FROM AND PAY.D_VALID_TO
		
			LEFT JOIN [L1].[L1_DIM_A_CS_COMMISSIONS_AMAZON] c_amaz
				ON item.T_PRODUCT_HIERARCHY_1 = c_amaz.T_PRODUCT_HIERARCHY_1
					AND item.T_PRODUCT_HIERARCHY_2 = c_amaz.T_PRODUCT_HIERARCHY_2
					AND fact.D_TARGET_LOOKUP BETWEEN c_amaz.D_VALID_FROM AND c_amaz.D_VALID_TO
					AND CASE WHEN fact.[CD_COUNTRY_GROUP] = 'INT' THEN 'ES' ELSE fact.[CD_COUNTRY_GROUP] END = c_amaz.CD_CHANNEL_COUNTRY
			--join enviro
			LEFT JOIN  CTE_ENVIRO env
				ON fact.ID_ITEM = env.ID_ITEM
				AND fact.CD_COUNTRY_GROUP = env.CD_COUNTRY_DELIVERY
				AND YEAR(fact.D_TARGET_LOOKUP) = env.NUM_YEAR
			--join enviro for repackacing
			LEFT JOIN [L1].[L1_DIM_A_ENVIRO_REST_UNIT_FEES] repack
				ON fact.ID_ITEM = repack.ID_ITEM
				AND fact.CD_COUNTRY_GROUP = repack.CD_COUNTRY_DELIVERY
				AND YEAR(fact.D_TARGET_LOOKUP) = repack.NUM_YEAR
				AND repack.CD_ENVIRO_CATEGORY = 'Packaging'
			--join fx rate for enviro
			LEFT JOIN [L1].[L1_FACT_F_FX_RATE] enviro_rate
				ON env.cd_currency=enviro_rate.cd_currency
				AND Year(fact.D_TARGET_LOOKUP)=Year(enviro_rate.D_EFFECTIVE)
				AND Month(fact.D_TARGET_LOOKUP)=Month(enviro_rate.D_EFFECTIVE)
		
			--join fulfillment shipping factor
			LEFT JOIN L1.L1_DIM_A_FULFILLMENT_SHIPPING_FACTOR factor
				ON item.CD_SIZE_BRACKET = factor.CD_SIZE_BRACKET
					AND fact.CD_FULFILLMENT = factor.CD_FULFILLMENT
					AND fact.T_REVISED_LOCATION = factor.T_STORAGE_LOCATION
					AND CASE WHEN fact.CD_COUNTRY_GROUP = 'INT'THEN 'ES' WHEN fact.[CD_CHANNEL_GROUP_3]='CEE' THEN 'CEE' ELSE fact.CD_COUNTRY_GROUP END = factor.[CD_COUNTRY_DELIVERY_GROUP]
					AND fact.D_TARGET_LOOKUP BETWEEN factor.D_VALID_FROM AND factor.D_VALID_TO 
			LEFT JOIN [L0].[L0_MI_BUSINESS_PLAN_MARKETING_RATES] mkt
				on REPLACE(mkt.[CHANNELGROUP3],' ','') = REPLACE(fact.[CD_CHANNEL_GROUP_3],' ','')
				and YEAR(fact.D_TARGET) = YEAR(mkt.[MONTH])
				and MONTH(fact.D_TARGET) = MONTH(mkt.[MONTH])
			LEFT JOIN [L1].[L1_FACT_A_COUNTRY_VAT] vat
				on vat.[CD_COUNTRY] = CASE WHEN fact.CD_COUNTRY_GROUP = 'INT'THEN 'SI' ELSE fact.CD_COUNTRY_GROUP END 
				and vat.[D_VALID_TO]  = '9999-12-31'
			LEFT JOIN [L0].L0_MI_BUSINESS_PLAN_COMMISSIONS_MARKETPLACES com_mkt_bs
				on	com_mkt_bs.[MONTH] = fact.D_TARGET
				AND com_mkt_bs.[CHANNELGROUP3] = fact.CD_CHANNEL_GROUP_3
			 WHERE
				[AMT_TARGET_NET_ORDER_VALUE_EUR] > 0
				AND 
				YEAR(fact.D_TARGET) = YEAR(@MonthDate)
				AND
				MONTH(fact.D_TARGET) = MONTH(@MonthDate)

)		     
,
	CTE_SALES_L2 AS 
	(
		SELECT sales.*
			,AMT_PAYMENTS_EUR = ([AMT_TARGET_NET_ORDER_VALUE_EUR] * [PCT_PAYMENTS_ORDER])	
			,AMT_COMMISSIONS_MARKETPLACES_EUR  = CASE WHEN CD_CHANNEL_GROUP_3 = 'CEE' then 0 ELSE ([AMT_TARGET_NET_ORDER_VALUE_EUR]*(1+PCT_VAT_VALUE) * [PCT_COMMISSIONS_MARKETPLACES]) END
			,AMT_GROSS_ORDER_VALUE_EUR = [AMT_TARGET_NET_ORDER_VALUE_EUR]
	        ,AMT_COMMISSIONS_AMAZON_EUR = CASE WHEN CD_CHANNEL_GROUP_3 = 'Amazon' then [AMT_TARGET_NET_ORDER_VALUE_EUR]*(1+PCT_VAT_VALUE)*VL_COMMISSIONS_ORDER_RATE ELSE NULL END
			,VL_NET_ORDER_QUANTITY = [VL_ITEM_QUANTITY]
		FROM CTE_SALES_L1 sales
	)
,
	CTE_SALES_L3 AS 
	(
		SELECT sales.*
				,AMT_REFUNDED_ORDER_VALUE_EST_EUR = (AMT_GROSS_ORDER_VALUE_EUR * VL_REFUND_RATE) 		

				,AMT_COMMISSIONS_AMAZON_REFUNDS_EUR = CASE WHEN AMT_COMMISSIONS_AMAZON_EUR between c_amaz_ref.[VL_VALUE_FROM] and c_amaz_ref.[VL_VALUE_TO] 
				      THEN CASE WHEN c_amaz_ref.[VL_COMMISSIONS_REFUND_ABOVE_THRESHOLD] <> 0 
				                THEN (AMT_COMMISSIONS_AMAZON_EUR - c_amaz_ref.[VL_COMMISSIONS_REFUND_ABOVE_THRESHOLD])*sales.VL_REFUND_RATE 
				                ELSE (AMT_COMMISSIONS_AMAZON_EUR * c_amaz_ref.[VL_COMMISSIONS_REFUND_BELOW_THRESHOLD_RATE])*sales.VL_REFUND_RATE 
				           END
				      ELSE NULL
				END
	    FROM CTE_SALES_L2 sales
	    LEFT JOIN [L1].[L1_DIM_A_CS_COMMISSIONS_AMAZON_REFUND] c_amaz_ref
	         ON DATEADD(YEAR,-1,D_TARGET) BETWEEN c_amaz_ref.[D_VALID_FROM] AND c_amaz_ref.[D_VALID_TO]
	         AND AMT_COMMISSIONS_AMAZON_EUR > c_amaz_ref.VL_VALUE_FROM 
	         AND AMT_COMMISSIONS_AMAZON_EUR <= c_amaz_ref.VL_VALUE_TO 
	)
	,
	CTE_SALES_L4 AS 
	(
		SELECT sales.*
						,AMT_COMMISSIONS_MARKETPLACES_REFUNDS_EUR = CASE WHEN CD_CHANNEL_GROUP_3 = 'CEE' then 0 ELSE  (AMT_REFUNDED_ORDER_VALUE_EST_EUR*(1+PCT_VAT_VALUE) * [PCT_COMMISSIONS_MARKETPLACES_RETURN]) END		

				 ,AMT_NET_ORDER_VALUE_EST_EUR = AMT_GROSS_ORDER_VALUE_EUR
				 ,VL_REFUNDED_QUANTITY_EST = (VL_NET_ORDER_QUANTITY * VL_REFUND_RATE) 			
				 ,VL_RETURNED_QUANTITY_EST = (VL_NET_ORDER_QUANTITY * VL_RETURN_RATE)				
				 ,VL_REPLACEMENT_QUANTITY_EST = (VL_NET_ORDER_QUANTITY *VL_REPLACEMENT_RATE )				
		FROM CTE_SALES_L3 sales
	)
	,
	CTE_SALES_L5 AS 
	(
		SELECT sales.*
				,AMT_REVENUE_EST_EUR = (AMT_NET_ORDER_VALUE_EST_EUR - AMT_REFUNDED_ORDER_VALUE_EST_EUR)																	
				,AMT_SHIPPING_COSTS_INVOICED_EST_EUR = (VL_NET_ORDER_QUANTITY * [AMT_SHIPPING_COST_EST_EUR] * AMT_CORRECTION_FACTOR_ORDER)				
				,AMT_SHIPPING_COSTS_RETURNED_EST_EUR = (VL_RETURNED_QUANTITY_EST * [AMT_SHIPPING_COST_EST_EUR] * AMT_CORRECTION_FACTOR_RETURN )	    		
				,AMT_SHIPPING_COSTS_REPLACED_EST_EUR = (VL_REPLACEMENT_QUANTITY_EST * [AMT_SHIPPING_COST_EST_EUR] * AMT_CORRECTION_FACTOR_REPLACEMENT )	
				,AMT_NET_ORDER_CONTRIBUTION_EST_EUR = AMT_NET_ORDER_VALUE_EST_EUR - (CASE WHEN [VL_ITEM_QUANTITY] <> 0 
														THEN (VL_NET_ORDER_QUANTITY) * (ISNULL([AMT_MEK_HEDGING_EUR],0)) 	ELSE 0 END)																			
				,AMT_ENVIRO_REST_UNIT_FEE_EUR = (VL_NET_ORDER_QUANTITY - VL_RETURNED_QUANTITY_EST+VL_REPLACEMENT_QUANTITY_EST) * AMT_PRECALC_ENVIRO_REST_UNIT_FEE_EUR
				,AMT_REPACKAGING_EUR = (VL_NET_ORDER_QUANTITY - VL_RETURNED_QUANTITY_EST+VL_REPLACEMENT_QUANTITY_EST) * AMT_PRECALC_REPACKAGING_EUR 


		FROM CTE_SALES_L4 sales
	)
	,CTE_SALES_L6 AS 
	(
		SELECT sales.*
				 ,AMT_SHOP_MARKETING_EUR =  CASE WHEN [CD_CHANNEL_GROUP_3] <> 'Amazon' THEN AMT_NET_ORDER_VALUE_EST_EUR * PCT_MKT_RATE ELSE 0 END
				 ,AMT_AMAZON_MARKETING_COSTS_EUR = CASE WHEN [CD_CHANNEL_GROUP_3] = 'Amazon' THEN AMT_NET_ORDER_VALUE_EST_EUR * PCT_MKT_RATE ELSE 0 END
				 ,AMT_FULFILLMENT_OUTBOUND_EST_EUR = (isnull(AMT_SHIPPING_COSTS_INVOICED_EST_EUR,0)+isnull(AMT_SHIPPING_COSTS_RETURNED_EST_EUR,0)+isnull(AMT_SHIPPING_COSTS_REPLACED_EST_EUR,0))										        
				,AMT_ENVIRO_AND_LICENSE_COST_EST_EUR = ISNULL(AMT_ENVIRO_REST_UNIT_FEE_EUR,0)+ISNULL(AMT_REPACKAGING_EUR,0)                                                                         

		FROM CTE_SALES_L5 sales
	)
	,
	CTE_SALES_L07 AS 
	(
		SELECT 	sales.*
		,AMT_MEK_TO_CUSTOMER_PLAN_EUR_SM			= CASE WHEN [VL_ITEM_QUANTITY] <> 0 
													THEN (VL_NET_ORDER_QUANTITY) * (ISNULL([AMT_MEK_HEDGING_EUR],0)-ISNULL([AMT_GTS_MARKUP_EUR],0))  
													ELSE 0 END	
		,AMT_MEK_FROM_CUSTOMER_PLAN_EUR_SM			= CASE WHEN [VL_ITEM_QUANTITY] <> 0 
													THEN (VL_RETURNED_QUANTITY_EST) * (ISNULL([AMT_MEK_HEDGING_EUR],0)-ISNULL([AMT_GTS_MARKUP_EUR],0))  
													ELSE 0 END	
		,AMT_MEK_REPLACEMENT_PLAN_EUR_SM			= CASE WHEN [VL_ITEM_QUANTITY] <> 0 
													THEN (VL_REPLACEMENT_QUANTITY_EST) * (ISNULL([AMT_MEK_HEDGING_EUR],0)-ISNULL([AMT_GTS_MARKUP_EUR],0))  
													ELSE 0 END	
		,AMT_MEK_DEPRECIATION_PLAN_EUR_SM 			= CASE WHEN [VL_ITEM_QUANTITY] <> 0 
													THEN (VL_RETURNED_QUANTITY_EST*dep.VL_RATE) * (ISNULL([AMT_MEK_HEDGING_EUR],0)-ISNULL([AMT_GTS_MARKUP_EUR],0))  
													ELSE 0 END	
		,AMT_MARKETING_ATTRIBUTION_PLAN_EUR_SM		= ISNULL(AMT_SHOP_MARKETING_EUR,0)+ISNULL(AMT_AMAZON_MARKETING_COSTS_EUR,0)
		,AMT_COMMISSIONS_SALE_PLAN_EUR_SM			= ISNULL(AMT_COMMISSIONS_MARKETPLACES_EUR,0) + ISNULL(AMT_COMMISSIONS_AMAZON_EUR,0)
		,AMT_COMMISSIONS_REFUNDS_PLAN_EUR_SM		= ISNULL(AMT_COMMISSIONS_AMAZON_REFUNDS_EUR,0)+ISNULL(AMT_COMMISSIONS_MARKETPLACES_REFUNDS_EUR,0)
		,AMT_COMMISSIONS_PLAN_EUR_SM				= (ISNULL(AMT_COMMISSIONS_MARKETPLACES_EUR,0)-ISNULL(AMT_COMMISSIONS_MARKETPLACES_REFUNDS_EUR,0)+ISNULL(AMT_COMMISSIONS_AMAZON_EUR,0)-ISNULL(AMT_COMMISSIONS_AMAZON_REFUNDS_EUR,0))
		,AMT_SHIPPING_COST_INVOICED_PLAN_SM		= AMT_SHIPPING_COSTS_INVOICED_EST_EUR
		,AMT_SHIPPING_COST_RETURNED_PLAN_SM		= AMT_SHIPPING_COSTS_RETURNED_EST_EUR
		,AMT_SHIPPING_COST_REPLACED_PLAN_SM		= AMT_SHIPPING_COSTS_REPLACED_EST_EUR 
		FROM CTE_SALES_L6 sales
		LEFT JOIN [L1].[L1_DIM_A_DEPRECIATION_VALUES] dep
			on sales.D_TARGET between dep.D_VALID_FROM and dep.D_VALID_TO
				AND dep.T_PRODUCT_HIERARCHY_2 = sales.T_PRODUCT_HIERARCHY_2
				and dep.T_STORAGE_LOCATION = sales.T_REVISED_LOCATION

	),
	CTE_SALES_L08 AS 
	(
		SELECT sales.*,

		AMT_FULL_NET_PRODUCT_COST_PLAN_EUR_SM =  ISNULL(AMT_MEK_TO_CUSTOMER_PLAN_EUR_SM,0) - ISNULL(AMT_MEK_FROM_CUSTOMER_PLAN_EUR_SM,0) + ISNULL(AMT_MEK_REPLACEMENT_PLAN_EUR_SM,0) +ISNULL(AMT_MEK_DEPRECIATION_PLAN_EUR_SM,0) ,
		AMT_STEERING_MARGIN_PLAN_EUR_SM =  ISNULL(AMT_REVENUE_EST_EUR,0)
					- (ISNULL(AMT_MEK_TO_CUSTOMER_PLAN_EUR_SM,0) - ISNULL(AMT_MEK_FROM_CUSTOMER_PLAN_EUR_SM,0) + ISNULL(AMT_MEK_REPLACEMENT_PLAN_EUR_SM,0) +ISNULL(AMT_MEK_DEPRECIATION_PLAN_EUR_SM,0)) -- Net product Costs
					- ISNULL(AMT_MARKETING_ATTRIBUTION_PLAN_EUR_SM,0) 
					- ISNULL(AMT_COMMISSIONS_PLAN_EUR_SM,0) 
					- ISNULL(AMT_PAYMENTS_EUR,0) 
					- ISNULL(AMT_ENVIRO_AND_LICENSE_COST_EST_EUR,0)
					- ISNULL(AMT_FULFILLMENT_OUTBOUND_EST_EUR,0)   ----(ShippingCostsInvoicedEst+ShippingCostsReturnedEst+ShippingCostsReplacedEst)
		FROM CTE_SALES_L07 sales 
	
	
	)
INSERT INTO TEST.L1_FACT_F_BUSINESS_PLAN_KPI_SM
(
	 D_SNAPSHOT
	 ,CD_SOURCE
	,ID_COMPANY
	,D_TARGET
	,ID_ITEM
	,ID_ITEM_BUSINESS_PLAN
	,CD_FULFILLMENT
	,T_REVISED_LOCATION
	,CD_COUNTRY_GROUP
	,CD_CHANNEL_GROUP_3
	,CD_CURRENCY
	,VL_ITEM_QUANTITY
	,AMT_PLAN_PRICE_EUR
	,AMT_SHIPPING_COST_EST_EUR
	,AMT_MEK_HEDGING_EUR
	,AMT_GTS_MARKUP_EUR
	---kpi--QTY
	,VL_NET_ORDER_QUANTITY
	,VL_REFUNDED_QUANTITY_EST
	,VL_RETURNED_QUANTITY_EST
	,VL_REPLACEMENT_QUANTITY_EST
	--KPI's Amount
	,AMT_GROSS_ORDER_VALUE_EUR
	,AMT_NET_ORDER_VALUE_EST_EUR
	,AMT_REFUNDED_ORDER_VALUE_EST_EUR	
	,AMT_REVENUE_EST_EUR
	,AMT_FULFILLMENT_OUTBOUND_EST_EUR
	,AMT_PAYMENTS_EUR
	,AMT_ENVIRO_AND_LICENSE_COST_EST_EUR
	,AMT_NET_ORDER_CONTRIBUTION_EST_EUR
	,AMT_MEK_TO_CUSTOMER_PLAN_EUR_SM
	,AMT_MEK_FROM_CUSTOMER_PLAN_EUR_SM
	,AMT_MEK_REPLACEMENT_PLAN_EUR_SM
	,AMT_MEK_DEPRECIATION_PLAN_EUR_SM
	,AMT_MARKETING_ATTRIBUTION_PLAN_EUR_SM
	,AMT_COMMISSIONS_PLAN_EUR_SM
	,AMT_COMMISSIONS_SALE_PLAN_EUR_SM
	,AMT_COMMISSIONS_REFUNDS_PLAN_EUR_SM
	,AMT_STEERING_MARGIN_PLAN_EUR_SM
	,AMT_FULL_NET_PRODUCT_COST_PLAN_EUR_SM
	,AMT_SHIPPING_COST_INVOICED_PLAN_SM 
	,AMT_SHIPPING_COST_RETURNED_PLAN_SM 
	,AMT_SHIPPING_COST_REPLACED_PLAN_SM 
	--- final
	,[DT_DWH_CREATED]
	,[DT_DWH_UPDATED]

)
SELECT
	 D_SNAPSHOT
	,CD_SOURCE
	,ID_COMPANY
	,D_TARGET
	,ID_ITEM
	,ID_ITEM_BUSINESS_PLAN
	,CD_FULFILLMENT
	,T_REVISED_LOCATION
	,CD_COUNTRY_GROUP
	,CD_CHANNEL_GROUP_3
	,CD_CURRENCY
	,VL_ITEM_QUANTITY
	,AMT_PLAN_PRICE_EUR
	,AMT_SHIPPING_COST_EST_EUR
	,AMT_MEK_HEDGING_EUR
	,AMT_GTS_MARKUP_EUR
	---kpi--QTY
	,VL_NET_ORDER_QUANTITY
	,VL_REFUNDED_QUANTITY_EST
	,VL_RETURNED_QUANTITY_EST
	,VL_REPLACEMENT_QUANTITY_EST
	--KPI's Amount
	,AMT_GROSS_ORDER_VALUE_EUR
	,AMT_NET_ORDER_VALUE_EST_EUR
	,AMT_REFUNDED_ORDER_VALUE_EST_EUR	
	,AMT_REVENUE_EST_EUR
	,AMT_FULFILLMENT_OUTBOUND_EST_EUR
	,AMT_PAYMENTS_EUR
	,AMT_ENVIRO_AND_LICENSE_COST_EST_EUR
	,AMT_NET_ORDER_CONTRIBUTION_EST_EUR
	,AMT_MEK_TO_CUSTOMER_PLAN_EUR_SM
	,AMT_MEK_FROM_CUSTOMER_PLAN_EUR_SM
	,AMT_MEK_REPLACEMENT_PLAN_EUR_SM
	,AMT_MEK_DEPRECIATION_PLAN_EUR_SM
	,AMT_MARKETING_ATTRIBUTION_PLAN_EUR_SM
	,AMT_COMMISSIONS_PLAN_EUR_SM
	,AMT_COMMISSIONS_SALE_PLAN_EUR_SM
	,AMT_COMMISSIONS_REFUNDS_PLAN_EUR_SM
	,AMT_STEERING_MARGIN_PLAN_EUR_SM
	,AMT_FULL_NET_PRODUCT_COST_PLAN_EUR_SM
	,AMT_SHIPPING_COST_INVOICED_PLAN_SM 
	,AMT_SHIPPING_COST_RETURNED_PLAN_SM 
	,AMT_SHIPPING_COST_REPLACED_PLAN_SM 
	,GETDATE()
	,GETDATE()
FROM CTE_SALES_L08


END -- IF
END





--SELECT MONTH(D_TARGET),SUM(AMT_NET_ORDER_VALUE_EST_EUR)
--FROM TEST.L1_FACT_F_BUSINESS_PLAN_KPI_SM
			
--GROUP BY MONTH(D_TARGET)
--order by 1 asc

--SELECT MONTH(D_TARGET),SUM(AMT_NET_ORDER_VALUE_EST_EUR)
--FROM TEST.L1_FACT_F_BUSINESS_PLAN_KPI_SM_V2
--GROUP BY MONTH(D_TARGET)
--order by 1 asc