--CREATE PROC WR.[WR_TX_L1_FACT_A_SALES_TRANSACTIONS_L1_FACT_A_SALES_TRANSACTION_KPI_SM]
---- =============================================  
---- Author:      Helder Barbosa
---- Create Date: 2025-09-14
---- Description: Populates L1_FACT_A_SALES_TRANSACTION_KPI
---- 2025-09-14   v1:HBarbosa      :  initial version

---- ============================================= 
--AS
--BEGIN

DECLARE @NUM_DAYS INT
SET @NUM_DAYS = 17

DECLARE @LOAD_DATE as date 
SET @LOAD_DATE = '2024-01-01'--CAST(GETDATE() - @NUM_DAYS as date)

DELETE FROM L1.L1_FACT_A_SALES_TRANSACTION_MKT_KPI_SM
WHERE 
	D_CREATED >= @LOAD_DATE
	AND CD_SOURCE_SYSTEM = 'AMZ'


;WITH CTE_MKT_AMAZON_L4 AS 
(
		SELECT 
			CD_SALES_TRANSACTION_MKT = cast(CONCAT('MKT','#',D_CAMPAIGN,'#',T_PRODUCT_HIERARCHY_4,'#',CD_CHANNEL_GROUP_3,'#',ISNULL(cmd.CountryGroup,'INT')) as varchar(150)),
			D_CAMPAIGN,
			T_PRODUCT_HIERARCHY_4,
			CD_CHANNEL_GROUP_3 = channel.CD_CHANNEL_GROUP_3,
			CD_COUNTRY_GROUP = ISNULL(cmd.CountryGroup,'INT'),
			AMT_MKT_COST_EUR = SUM((ISNULL([AMT_COST_EUR_ATT],0)+ISNULL([GOOGLE_AMT_COST_EUR_ATT],0)+ISNULL([DSP_AMT_COST_EUR_ATT],0))) 
		FROM 
		[L1].L1_FACT_A_AMAZON_ITEM_ATTRIBUTION amz
		INNER JOIN L1.L1_DIM_A_ITEM it on it.ID_ITEM = amz.ID_ITEM
		INNER JOIN L1.L1_DIM_A_MARKETING_ACCOUNT acc on acc.[ID_MARKETING_ACCOUNT] = amz.[ID_MARKETING_ACCOUNT]
		LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL channel
				on channel.[CD_SALES_CHANNEL] = acc.[CD_SALES_CHANNEL]
		LEFT JOIN [L0].[L0_MI_COUNTRY_GROUP] cmd
					ON acc.CD_COUNTRY = cmd.COUNTRY
		WHERE 1=1
			and D_CAMPAIGN >= @LOAD_DATE 
			and [T_PRODUCT_HIERARCHY_4] is not null
		GROUP BY [T_PRODUCT_HIERARCHY_4],
				channel.CD_CHANNEL_GROUP_3,
				D_CAMPAIGN,
				ISNULL(cmd.CountryGroup,'INT')
		HAVING SUM((ISNULL([AMT_COST_EUR_ATT],0)+ISNULL([GOOGLE_AMT_COST_EUR_ATT],0)+ISNULL([DSP_AMT_COST_EUR_ATT],0))) >  0
),
CTE_MKT_AMAZON_ITEM AS 
(
		SELECT 
			CD_SALES_TRANSACTION_MKT = CAst(CONCAT('MKT','#',D_CAMPAIGN,'#',NUM_ITEM,'#',CD_CHANNEL_GROUP_3,'#',ISNULL(cmd.CountryGroup,'INT')) as varchar(150)),
			D_CAMPAIGN,
			it.NUM_ITEM, it.ID_ITEM,
			CD_CHANNEL_GROUP_3 = channel.CD_CHANNEL_GROUP_3,
			CD_COUNTRY_GROUP = ISNULL(cmd.CountryGroup,'INT'),
			AMT_MKT_COST_EUR = SUM((ISNULL([AMT_COST_EUR_ATT],0)+ISNULL([GOOGLE_AMT_COST_EUR_ATT],0)+ISNULL([DSP_AMT_COST_EUR_ATT],0))) 
		FROM 
		[L1].L1_FACT_A_AMAZON_ITEM_ATTRIBUTION amz
		INNER JOIN L1.L1_DIM_A_ITEM it on it.ID_ITEM = amz.ID_ITEM
		INNER JOIN L1.L1_DIM_A_MARKETING_ACCOUNT acc on acc.[ID_MARKETING_ACCOUNT] = amz.[ID_MARKETING_ACCOUNT]
		LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL channel
				on channel.[CD_SALES_CHANNEL] = acc.[CD_SALES_CHANNEL]
		LEFT JOIN [L0].[L0_MI_COUNTRY_GROUP] cmd
					ON acc.CD_COUNTRY = cmd.COUNTRY
		WHERE
			D_CAMPAIGN >= @LOAD_DATE 
			and [T_PRODUCT_HIERARCHY_4] is  null
		GROUP BY it.NUM_ITEM,
				channel.CD_CHANNEL_GROUP_3,
				D_CAMPAIGN,
				ISNULL(cmd.CountryGroup,'INT'),it.ID_ITEM
		HAVING SUM((ISNULL([AMT_COST_EUR_ATT],0)+ISNULL([GOOGLE_AMT_COST_EUR_ATT],0)+ISNULL([DSP_AMT_COST_EUR_ATT],0))) >  0
),
CTE_SALES as
(
	SELECT 
		ID_SALES_TRANSACTION,
		CD_SALES_TRANSACTION = cast(CD_SALES_TRANSACTION as varchar(150)),
		s.D_CREATED,
		it.T_PRODUCT_HIERARCHY_4,
		CD_CHANNEL_GROUP_3 = REPLACE(ch.[CD_CHANNEL_GROUP_3],' ',''),
		CD_COUNTRY_GROUP_DELIVERY = CD_COUNTRY_GROUP_DELIVERY,
		it.NUM_ITEM,
		it.ID_ITEM
		,AMT_TOTAL_NOV_FAMILY_EUR	= SUM(ISNULL(AMT_NET_ORDER_VALUE_EST_EUR,0)) 
											OVER(PARTITION BY T_PRODUCT_HIERARCHY_4, s.D_CREATED ,[CD_CHANNEL_GROUP_3],CD_COUNTRY_GROUP_DELIVERY )
		,PERC_NOV_FAMILY_SHARE		= AMT_NET_ORDER_VALUE_EST_EUR / SUM(ISNULL(AMT_NET_ORDER_VALUE_EST_EUR,0)) 
											OVER(PARTITION BY T_PRODUCT_HIERARCHY_4, s.D_CREATED ,[CD_CHANNEL_GROUP_3],CD_COUNTRY_GROUP_DELIVERY )
		,AMT_TOTAL_NOV_ITEM_EUR		= SUM(ISNULL(AMT_NET_ORDER_VALUE_EST_EUR,0)) 
											OVER(PARTITION BY NUM_ITEM, s.D_CREATED,[CD_CHANNEL_GROUP_3],CD_COUNTRY_GROUP_DELIVERY )
		,PERC_NOV_ITEM_SHARE		= AMT_NET_ORDER_VALUE_EST_EUR / SUM(ISNULL(AMT_NET_ORDER_VALUE_EST_EUR,0)) 
														OVER(PARTITION BY NUM_ITEM, s.D_CREATED,[CD_CHANNEL_GROUP_3],CD_COUNTRY_GROUP_DELIVERY )
	FROM L1.L1_FACT_A_SALES_TRANSACTION_KPI_SM s
	INNER JOIN L1.L1_DIM_A_ITEM it on it.ID_ITEM = s.ID_ITEM
	LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL ch on ch.ID_SALES_CHANNEL = s.ID_SALES_CHANNEL
	WHERE 1=1
	and s.D_CREATED >= @LOAD_DATE
	and	ch.CD_CHANNEL_GROUP_3 in ('Amazon')
	AND ISNULL(AMT_NET_ORDER_VALUE_EST_EUR,0) > 0
		
)
,CTE_SALES_MKT AS
(
	SELECT 
		ID_SALES_TRANSACTION = sales.ID_SALES_TRANSACTION,
		CD_SALES_TRANSACTION = cast(ISNULL(sales.CD_SALES_TRANSACTION,ISNULL(mkt_l4.CD_SALES_TRANSACTION_MKT,mkt_item.CD_SALES_TRANSACTION_MKT)) as varchar(150)),
		CD_SOURCE_SYSTEM = 'AMZ',
		D_CREATED	= ISNULL(sales.D_CREATED,ISNULL(mkt_l4.D_CAMPAIGN,mkt_item.D_CAMPAIGN)),
		ID_ITEM		= ISNULL(sales.ID_ITEM,mkt_item.ID_ITEM),
		T_PRODUCT_HIERARCHY_4 = ISNULL(sales.T_PRODUCT_HIERARCHY_4,mkt_l4.T_PRODUCT_HIERARCHY_4) ,
		CD_CHANNEL_GROUP_3	=	 ISNULL(sales.CD_CHANNEL_GROUP_3,ISNULL(mkt_l4.CD_CHANNEL_GROUP_3,mkt_item.CD_CHANNEL_GROUP_3)),
		CD_COUNTRY_GROUP = ISNULL(sales.CD_COUNTRY_GROUP_DELIVERY,ISNULL(mkt_l4.CD_COUNTRY_GROUP,mkt_item.CD_COUNTRY_GROUP)),
		AMT_MKT_COST_EUR = ISNULL(mkt_l4.AMT_MKT_COST_EUR * ISNULL(PERC_NOV_FAMILY_SHARE,1),0)+  ISNULL(mkt_item.AMT_MKT_COST_EUR * ISNULL(PERC_NOV_ITEM_SHARE,1),0)

FROM CTE_SALES sales --on sales.ID_SALES_TRANSACTION = fact.ID_SALES_TRANSACTION
FULL JOIN CTE_MKT_AMAZON_L4 mkt_l4
	on 
		mkt_l4.D_CAMPAIGN = sales.D_CREATED
		AND
		mkt_l4.T_PRODUCT_HIERARCHY_4 = sales.T_PRODUCT_HIERARCHY_4
		AND
		mkt_l4.CD_CHANNEL_GROUP_3 = sales.[CD_CHANNEL_GROUP_3]
		AND
		mkt_l4.CD_COUNTRY_GROUP = sales.CD_COUNTRY_GROUP_DELIVERY
LEFT JOIN CTE_MKT_AMAZON_ITEM mkt_item
	on 
		mkt_item.D_CAMPAIGN = sales.D_CREATED
		AND
		mkt_item.NUM_ITEM = sales.NUM_ITEM
		AND
		mkt_item.CD_CHANNEL_GROUP_3 = sales.[CD_CHANNEL_GROUP_3]
		AND
		mkt_item.CD_COUNTRY_GROUP = sales.CD_COUNTRY_GROUP_DELIVERY
	)
, cte_family_items as
(
	SELECT T_PRODUCT_HIERARCHY_4, count(*) AS VL_NUMBER_ITEMS
	FROM L1.L1_DIM_A_ITEM
	where T_PRODUCT_HIERARCHY_4 is not null
	GROUP BY T_PRODUCT_HIERARCHY_4

)
INSERT INTO L1.L1_FACT_A_SALES_TRANSACTION_MKT_KPI_SM
(
	ID_SALES_TRANSACTION,
	CD_SALES_TRANSACTION,
	CD_SOURCE_SYSTEM,
	D_CREATED,
	ID_ITEM,
	T_PRODUCT_HIERARCHY_4,
	CD_CHANNEL_GROUP_3,
	CD_COUNTRY_GROUP,
	AMT_MKT_COST_EUR,
	DT_DWH_CREATED,
	DT_DWH_UPDATED
)

SELECT 
		ID_SALES_TRANSACTION ,
		CD_SALES_TRANSACTION = CASE WHEN it.ID_ITEM is NOT null 
									THEN cast(CONCAT(CD_SALES_TRANSACTION,'#',NUM_ITEM) as varchar(150))
									ELSE
									cast( CD_SALES_TRANSACTION as varchar(150))
								END,
		CD_SOURCE_SYSTEM = mkt.CD_SOURCE_SYSTEM,
		D_CREATED	= mkt.D_CREATED,
		ID_ITEM		= ISNULL(mkt.ID_ITEM,it.ID_ITEM),
		T_PRODUCT_HIERARCHY_4 = mkt.T_PRODUCT_HIERARCHY_4  ,
		CD_CHANNEL_GROUP_3	,
		CD_COUNTRY_GROUP ,
		AMT_MKT_COST_EUR = (AMT_MKT_COST_EUR) / CASE WHEN it.ID_ITEM IS NULL THEN 1 ELSE ISNULL(VL_NUMBER_ITEMS,1) END,
		DT_DWH_CREATED = sysdatetime(),
		DT_DWH_UPDATED = sysdatetime()
FROM CTE_SALES_MKT	mkt
LEFT JOIN cte_family_items fam on fam.T_PRODUCT_HIERARCHY_4 = mkt.T_PRODUCT_HIERARCHY_4
LEFT JOIN L1.L1_DIM_A_ITEM it
	on mkt.T_PRODUCT_HIERARCHY_4 IS NOT NULL
		AND ID_SALES_TRANSACTION IS NULL
		AND mkt.ID_ITEM is null
		AND mkt.T_PRODUCT_HIERARCHY_4 = it.T_PRODUCT_HIERARCHY_4

WHERE 1=1
--and T_PRODUCT_HIERARCHY_4 is not null 
and
AMT_MKT_COST_EUR> 0
	
--mkt.D_CREATED>='2025-09-01'



--END


--select sum(AMT_AMAZON_MARKETING_EUR),count(*) FROM L1.L1_FACT_A_SALES_TRANSACTION_KPI_SM fact

	--	SELECT 
	--	AMT_MKT_COST_EUR = SUM((ISNULL([AMT_COST_EUR_ATT],0)+ISNULL([GOOGLE_AMT_COST_EUR_ATT],0)+ISNULL([DSP_AMT_COST_EUR_ATT],0))) 
	--	FROM 
	--	[L1].L1_FACT_A_AMAZON_ITEM_ATTRIBUTION amz
	--			INNER JOIN L1.L1_DIM_A_ITEM it on it.ID_ITEM = amz.ID_ITEM
	--	INNER JOIN L1.L1_DIM_A_MARKETING_ACCOUNT acc on acc.[ID_MARKETING_ACCOUNT] = amz.[ID_MARKETING_ACCOUNT]
	--	LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL channel
	--			on channel.[CD_SALES_CHANNEL] = acc.[CD_SALES_CHANNEL]
	--	LEFT JOIN [L0].[L0_MI_COUNTRY_GROUP] cmd
	--				ON acc.CD_COUNTRY = cmd.COUNTRY
	--	WHERE
	--		D_CAMPAIGN>='2025-09-01'

	--		--232.366

	--		--176.029


	----		8913





	select count(*) from L1.L1_FACT_A_SALES_TRANSACTION_MKT_KPI_SM where ID_SALES_TRANSACTION is null