ALTER VIEW PL.PL_V_MARKETING_COSTS_AMZ_SM
AS

WITH CTE_MKT_AMAZON_L4 AS 
(
		SELECT 
			CD_SALES_TRANSACTION_MKT = cast(CONCAT('AMZ','#',D_CAMPAIGN,'#',ID_SALES_CHANNEL,'#',ISNULL(acc.CD_COUNTRY,'INT'),'#', ISNULL(T_PRODUCT_HIERARCHY_3,'N/A'),'#', ISNULL(T_PRODUCT_HIERARCHY_3,'N/A') ) as varchar(150)),
			D_CAMPAIGN,
			T_PRODUCT_HIERARCHY_4 = ISNULL(T_PRODUCT_HIERARCHY_4,'N/A'),
			T_PRODUCT_HIERARCHY_3 = ISNULL(T_PRODUCT_HIERARCHY_3,'N/A'),
			ID_SALES_CHANNEL = channel.ID_SALES_CHANNEL,
			CD_COUNTRY = ISNULL(acc.CD_COUNTRY,'INT'),
			AMT_MKT_COST_EUR = SUM((ISNULL([AMT_COST_EUR_ATT],0)+ISNULL([GOOGLE_AMT_COST_EUR_ATT],0)+ISNULL([DSP_AMT_COST_EUR_ATT],0))) 
		FROM 
		[L1].L1_FACT_A_AMAZON_ITEM_ATTRIBUTION amz
		INNER JOIN L1.L1_DIM_A_ITEM it on it.ID_ITEM = amz.ID_ITEM
		INNER JOIN L1.L1_DIM_A_MARKETING_ACCOUNT acc on acc.[ID_MARKETING_ACCOUNT] = amz.[ID_MARKETING_ACCOUNT]
		LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL channel
				on channel.[CD_SALES_CHANNEL] = acc.[CD_SALES_CHANNEL]
		WHERE 1=1
			and D_CAMPAIGN >= '2025-01-01' 
			and 
				([T_PRODUCT_HIERARCHY_4] is not null
				OR
				[T_PRODUCT_HIERARCHY_3] IS NOT NULL)
		GROUP BY ISNULL(T_PRODUCT_HIERARCHY_4,'N/A'),
				 ISNULL(T_PRODUCT_HIERARCHY_3,'N/A'),
				channel.ID_SALES_CHANNEL,
				D_CAMPAIGN,
				ISNULL(acc.CD_COUNTRY,'INT')
		HAVING SUM((ISNULL([AMT_COST_EUR_ATT],0)+ISNULL([GOOGLE_AMT_COST_EUR_ATT],0)+ISNULL([DSP_AMT_COST_EUR_ATT],0))) >  0
),
CTE_MKT_AMAZON_ITEM AS 
(
		SELECT 
			CD_SALES_TRANSACTION_MKT = CAst(CONCAT('MKT','#',D_CAMPAIGN,'#',NUM_ITEM,'#',channel.ID_SALES_CHANNEL,'#',ISNULL(acc.CD_COUNTRY,'INT')) as varchar(150)),
			D_CAMPAIGN,
			it.NUM_ITEM, 
			it.ID_ITEM,
			ID_SALES_CHANNEL = channel.ID_SALES_CHANNEL,
			CD_COUNTRY = ISNULL(acc.CD_COUNTRY,'INT'),
			AMT_MKT_COST_EUR = SUM((ISNULL([AMT_COST_EUR_ATT],0)+ISNULL([GOOGLE_AMT_COST_EUR_ATT],0)+ISNULL([DSP_AMT_COST_EUR_ATT],0))) 
		FROM 
		[L1].L1_FACT_A_AMAZON_ITEM_ATTRIBUTION amz
		INNER JOIN L1.L1_DIM_A_ITEM it on it.ID_ITEM = amz.ID_ITEM
		INNER JOIN L1.L1_DIM_A_MARKETING_ACCOUNT acc on acc.[ID_MARKETING_ACCOUNT] = amz.[ID_MARKETING_ACCOUNT]
		LEFT JOIN L1.L1_DIM_A_SALES_CHANNEL channel
				on channel.[CD_SALES_CHANNEL] = acc.[CD_SALES_CHANNEL]
		LEFT JOIN [L0].[L0_MI_COUNTRY_GROUP] cmd
					ON acc.CD_COUNTRY = cmd.COUNTRY
		WHERE 1=1
			and D_CAMPAIGN >= '2025-01-01' 
			and [T_PRODUCT_HIERARCHY_4] is  null
			and [T_PRODUCT_HIERARCHY_3] is  null
		GROUP BY it.NUM_ITEM,
				channel.ID_SALES_CHANNEL,
				D_CAMPAIGN,
				ISNULL(acc.CD_COUNTRY,'INT'),it.ID_ITEM
		HAVING SUM((ISNULL([AMT_COST_EUR_ATT],0)+ISNULL([GOOGLE_AMT_COST_EUR_ATT],0)+ISNULL([DSP_AMT_COST_EUR_ATT],0))) >  0
)
, cte_family_items as
(
	SELECT ISNULL(T_PRODUCT_HIERARCHY_4,'N/A')T_PRODUCT_HIERARCHY_4,ISNULL(T_PRODUCT_HIERARCHY_3,'N/A')T_PRODUCT_HIERARCHY_3, count(*) AS VL_NUMBER_ITEMS
	FROM L1.L1_DIM_A_ITEM
	where T_PRODUCT_HIERARCHY_4 is not null OR T_PRODUCT_HIERARCHY_3 is not null
	GROUP BY ISNULL(T_PRODUCT_HIERARCHY_4,'N/A'),ISNULL(T_PRODUCT_HIERARCHY_3,'N/A')

)



SELECT 
D_CAMPAIGN,
mkt.T_PRODUCT_HIERARCHY_4,
mkt.T_PRODUCT_HIERARCHY_3,
ID_SALES_CHANNEL,
CD_COUNTRY,
NUM_ITEM = it.NUM_ITEM,
ID_ITEM = it.ID_ITEM,
AMT_MKT_COST_EUR = ISNULL(mkt.AMT_MKT_COST_EUR,0) / ISNULL(VL_NUMBER_ITEMS,1)
FROM CTE_MKT_AMAZON_L4 mkt
INNER JOIN cte_family_items fam
ON
		mkt.T_PRODUCT_HIERARCHY_4 = isnull(fam.T_PRODUCT_HIERARCHY_4,'N/A')
		AND mkt.T_PRODUCT_HIERARCHY_3 = isnull(fam.T_PRODUCT_HIERARCHY_3,'N/A')
INNER JOIN L1.L1_DIM_A_ITEM it
	on
		 mkt.T_PRODUCT_HIERARCHY_4 = isnull(it.T_PRODUCT_HIERARCHY_4,'N/A')
		AND mkt.T_PRODUCT_HIERARCHY_3 = isnull(it.T_PRODUCT_HIERARCHY_3,'N/A')

--UNION

--SELECT 
--D_CAMPAIGN,
--T_PRODUCT_HIERARCHY_4,
--T_PRODUCT_HIERARCHY_3,
--ID_SALES_CHANNEL,
--CD_COUNTRY,
--NUM_ITEM = it.NUM_ITEM,
--ID_ITEM = it.ID_ITEM,
--AMT_MKT_COST_EUR = ISNULL(mkt.AMT_MKT_COST_EUR) / ISNULL(VL_NUMBER_ITEMS,1)
--FROM CTE_MKT_AMAZON_L4 mkt
