SELECT TOP (1000) [ItemNo]
      ,[ItemDescription]
      ,[ProductHierarchy1]
      ,[ProductHierarchy2]
      ,[ChannelGroup3]
	  ,[Country]
	  ,[PC0Abs] =[PC0Est]
	  ,[PC0%]
	  ,[SteeringMargin]
	  ,[SteeringMargin %] --= [SteeringMargin]  / [RevenueEst]
      ,[PC3Abs] = [PC3Est]
	  ,[PC3%]--=[PC3Est] / [RevenueEst]
	  ,[RefundRate]
	  ,[ReturnRate] =0.1
	  ,[NetOrderValueEst]
	  ,[NetOrderQuantityEst]
      ,ASP--=[PlanPrice]
 --     ,[Quantity]
     -- ,[StorageLocation]
      ,[RefundedOrderValueEst]
	  ,[RevenueEst]
      ,[GrossMargin]
      ,[Marketing]
      ,[Commissions]
	  ,[Freight&Carrier]

      ,[PaymentsFeesEst]
      ,[Enviro&License]
      ,[Warehouse-var]
      ,[PackagingEst]
      ,[CustomerService-Var]
      ,[NetOrderContributionEst]
	  ,[Mekhedging]
	  ,[ShippingCostEst]

  FROM [PL].[PL_V_MARGIN_STEERING_TOOL]
  WHERE ItemNo  = '10002022'

  order by ChannelGroup3  asc