
--ALTER  TABLE [dbo].[WayofDistribution] ADD ChannelType NVARCHAR(50)

UPDATE [WayofDistribution] SET ChannelType = 'Shop'WHERE [WayofDistributionID] = 10
UPDATE [WayofDistribution] SET ChannelType = 'Shop'WHERE [WayofDistributionID] = 11
UPDATE [WayofDistribution] SET ChannelType = 'Shop'WHERE [WayofDistributionID] = 12
UPDATE [WayofDistribution] SET ChannelType = 'Shop'WHERE [WayofDistributionID] = 13
UPDATE [WayofDistribution] SET ChannelType = 'Shop'WHERE [WayofDistributionID] = 14
UPDATE [WayofDistribution] SET ChannelType = 'Shop'WHERE [WayofDistributionID] = 15
UPDATE [WayofDistribution] SET ChannelType = 'Shop'WHERE [WayofDistributionID] = 16
UPDATE [WayofDistribution] SET ChannelType = 'Shop'WHERE [WayofDistributionID] = 17
UPDATE [WayofDistribution] SET ChannelType = 'Shop'WHERE [WayofDistributionID] = 18
UPDATE [WayofDistribution] SET ChannelType = 'Shop'WHERE [WayofDistributionID] = 20
UPDATE [WayofDistribution] SET ChannelType = 'Shop'WHERE [WayofDistributionID] = 21
UPDATE [WayofDistribution] SET ChannelType = 'Shop'WHERE [WayofDistributionID] = 22
UPDATE [WayofDistribution] SET ChannelType = 'Shop'WHERE [WayofDistributionID] = 23
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 25
UPDATE [WayofDistribution] SET ChannelType = 'Amazon'WHERE [WayofDistributionID] = 30
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 31
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 32
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 33
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 34
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 35
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 36
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 37
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 38
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 39
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 40
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 41
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 42
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 43
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 44
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 45
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 46
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 47
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 48
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 49
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 50
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 51
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 52
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 53
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 54
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 55
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 56
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 57
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 59
UPDATE [WayofDistribution] SET ChannelType = 'Amazon'WHERE [WayofDistributionID] = 60
UPDATE [WayofDistribution] SET ChannelType = 'Marketplace'WHERE [WayofDistributionID] = 61
UPDATE [WayofDistribution] SET ChannelType = 'Shop'WHERE [WayofDistributionID] = 70
UPDATE [WayofDistribution] SET ChannelType = 'Shop'WHERE [WayofDistributionID] = 71
UPDATE [WayofDistribution] SET ChannelType = 'Shop'WHERE [WayofDistributionID] = 72
UPDATE [WayofDistribution] SET ChannelType = 'Shop'WHERE [WayofDistributionID] = 98
